---
title: Data Analytics
date: 07/Nov/2022
listing: 
  type: table
  sort: "order"
  sort-ui: false
  filter-ui: false
  contents: "*/listing.qmd"
  fields: [image, title, date]
  table-striped: true
  table-hover: true
  categories: true
---

## Abstract

This Course takes Business Practitioners on a journey of Business
Analytics: using data to derive insights, make predictions, and decide
on plans of action that can be communicated and actualized in a Business
context.

> "Business analytics, or simply analytics, is the use of data,
> information technology, statistical analysis, quantitative methods,
> and mathematical or computer-based models to help managers gain
> improved insight about their business operations and make better,
> fact-based decisions. Business analytics is"a process of transforming
> data into actions through analysis and insights in the context of
> organizational decision making and problem solving."
>
> ::: {style="text-align: right"}
> -Libertore and Luo, 2010
> :::

<br> The Course starts with **Descriptive Analytics**: Datasets from
various domains of Business enterprise and activity are introduced. The
datasets are motivated from the point of view of the types of
information they contain: students will relate the Data Variables
(Qualitative and Quantitative) to various types of Data/Information
Visualizations.

**Statistical Concepts** such as ***Sampling, Hypothesis Tests,
Simulation / Modelling, and Uncertainty*** will be introduced.

**Predictive Analytics** will take us into looking at Data and training
standard ML algorithms to make predictions with new Data. ***Regression,
Clustering, and Classification*** will be covered.

**Prescriptive Analytics** will deal with coming to terms with the
uncertainty in Predictions, and using tools such as both ***ML,
Linear/non-Linear Programming, and Decision-Making*** to make Business
Decisions, with an assessment of the Risks involved.

The Course will culminate in a full **Business Analytics Workflow** that
includes Data Gathering and Cleaning, Descriptive and Predictive
Analytics, Prescriptive Analytics and Decision Making, and Communication
resulting in a publication-worthy documents.(HTML / PDF/ Word)

## What you will learn

-   **Data Basics**: What does data look like and why should we care?
-   Rapidly and intuitively creating **Graphs and Data Visualizations**
    to explore data for insights
-   Use **Statistical Tests, Procedures, Models, and Simulations** and
    to answer Business Questions
-   Using **ML algorithms** such Regression, Classification, and
    Clustering to develop Business Insights
-   Use **Linear Programming** to make Business Decisions
-   Create crisp and readable **Reports** that can be shared in a
    Business Context

## Texts

1.  James R Evans, *Business Analytics: Methods, Models, and Decisions*,
    Pearson Education, 2021.

## References

### Visualization and R language

1. Hadley Wickham, Mine Cetinkaya-Rundel, and Garett Grolemund. *R for Data Science (2e)*. <https://r4ds.hadley.nz>. The most important reference for data visualization and analysis in R. Available free online. 

1. Robert Kabacoff. *Modern Data Visualization with R*. <u><https://rkabacoff.github.io/datavis/></u>. Available free online.

5.  Jack Dougherty and Ilya Ilyankou, *Hands-On Data Visualization:
    Interactive Storytelling from Spreadsheets to Code*,
    <https://handsondataviz.org/>. Available free online.

6.  Claus O. Wilke, *Fundamentals of Data Visualization*,
    <https://clauswilke.com/dataviz/>. Available free online.

7.  Jonathan Schwabish, *Better Data Visualizations: A Guide for
    Scholars, Researchers, and Wonks*, Columbia University Press, 2021.

8.  Alberto Cairo, *The Functional Art: An introduction to information
    graphics and visualization*, New Riders. 2013. ISBN-9780133041361.

9.  Cole Nussbaumer Knaflic, *Storytelling With Data: A Data
    Visualization Guide for Business Professionals*, Wiley 2015.
    ISBN-9781119002253.

### Analytics

1.  Judd, C.M., McClelland, G.H., & Ryan, C.S. (2017). Data Analysis: A
    Model Comparison Approach To Regression, ANOVA, and Beyond, Third
    Edition (3rd ed.). Routledge.
    <https://doi.org/10.4324/9781315744131>

2.  Thomas Maydon, The 4 Types of Data Analytics,
    <https://www.kdnuggets.com/2017/07/4-types-data-analytics.html>

3.  Dimitris Bertsimas, Robert Freund, *Data, Models, and Decisions: the
    Fundamentals of Management Science*, Dynamic Ideas Press, 2004.

4.  Cliff T. Ragsdale, *Spreadsheet Modeling & Decision Analysis: A
    Practical Introduction to Management Science*, South Western,
    Cengage Learning, Mason, OH, 2012.
    
1. Keith McNulty. *Handbook of Regression Modeling in People Analytics: With Examples in R, Python and Julia* <https://peopleanalytics-regression-book.org>. Available free online.


### Statistics

1. Mine Cetinkaya-Rundel, Johanna Hardin. *Introduction to Modern Statistics*. <https://openintro-ims2.netlify.app>. Available free online.

1. Daniel T. Kaplan. *Statistical Models (second edition)*. <https://dtkaplan.github.io/SM2-bookdown/>. Available free online.

4.  Daniel T. Kaplan, *Compact Introduction to Classical
    Inference*, 2020. <https://dtkaplan.github.io/CompactInference/>. Available free online.

5.  Daniel T. Kaplan and Frank Shaw, *Statistical Modeling:
    Computational Technique*. <https://www.mosaic-web.org/go/SM2-technique/>. Available free online.

6.  Jonas Kristoffer Lindeløv. *Common statistical tests are linear
    models (or: how to teach stats)*. <https://lindeloev.github.io/tests-as-linear/>. Available free online.


## Pedagogical Notes

Why this course is what it is, and why it does what it does! Only if you are interested!!


{{< youtube ScpUmLfZBeA >}}

<br>

{{< youtube aq5SrjXZDy4 >}}

## Our Tools

This is eventually meant to be a three-in-one course, based on the following free and open source tools:

1.  **R** <https://cran.r-project.org/> and **RStudio**
    <https://posit.co/>

    R is a freely available language and environment for statistical
    computing and graphics which provides a wide variety of statistical
    and graphical techniques: *linear and nonlinear modelling,
    statistical tests, time series analysis, classification, clustering*,etc. RStudio is an **integrated development environment (IDE) for R and Python**.

2.  **Orange Data Mining** <https://orangedatamining.com/>

    Orange is also a [FOSS](https://en.wikipedia.org/wiki/Free_and_open-source_software) visual point-and-click software for Data Mining and ML, developed at the University of Slovenia, in Ljubljana, Slovenia.

{{< youtube HXjnDIgGDuI >}}

<br>

2.  **Radiant -- Business analytics using R and Shiny**
    <https://radiant-rstats.github.io/docs/index.html>

    Radiant is a FOSS platform-independent browser-based interface for business analytics in R, developed at the University of San Diego. The application is based on the Shiny package and can be run using R, or in your browser with no installation required. The tool automatically installs a version of R and adds a Shiny-based GUI that removes the need to write R-code. Radiant can also be installed on top of an existing installation of R and invoked from within RStudio.

{{< youtube 7L3hDpLw53I >}}

<br>

And of course, there is this:

<https://openai.com/index/improvements-to-data-analysis-in-chatgpt/>



## Modules
