---
title: "Projects"
author: "Arvind V"
date: 22/July/2024
date-modified: " `r Sys.Date()` "
order: 2024
---

## Introduction

Here are projects that we will contemplate creating at the end of the course. All the techniques, software, packages, theory, hardware...will be pieces aimed the realization of these projects. So we begin this course with the end in mind.

## Project #1: King/Queen of the Mountain

### Description

-   Each participant in the exhibit chooses whether they want to be on a mountain or in a valley, or in a grassland/meadow. More choices if you are up to it..volcano, anyone?

-   Their position within the space will be sensed. And they can move.

-   A terrain map will be projected, either on the ceiling, or the screen, or on the participants themselves, with each individual being located on a specific terrain feature type that they chose at the start.

### Pieces

+---------------------+-----------------------------------------------------------------------------+----------------------------------------------------------------------------+
| Theory              | Tool                                                                        | Wait, but why?                                                             |
+=====================+=============================================================================+============================================================================+
| Terrain Generation  | -   p5.js/ Perlin Noise                                                     | -   Terrain!                                                               |
+---------------------+-----------------------------------------------------------------------------+----------------------------------------------------------------------------+
| Location Sensing    | -   OSC protocol?                                                           | -   Give seed locations to Perlin Noise generator                          |
|                     |                                                                             |                                                                            |
|                     | -   Arduino sensors?                                                        | -   Defines preferences of terrain feature based in identity               |
|                     |                                                                             |                                                                            |
|                     | -   Link p5.js to Arduino, need libraries for interfacing and data transfer |                                                                            |
+---------------------+-----------------------------------------------------------------------------+----------------------------------------------------------------------------+
| Projection          | -   Project terrain map                                                     | -   Watch participants move and terrain follows them                       |
|                     |                                                                             |                                                                            |
|                     | -   Drive Projector using p5.js                                             |                                                                            |
|                     |                                                                             |                                                                            |
|                     | -   Do we need projection mapping libraries?                                |                                                                            |
+---------------------+-----------------------------------------------------------------------------+----------------------------------------------------------------------------+

: Project #1

## Project #2: Sound Relationships

### Description

-   The floor is divided into footprint-sized areas. Each area is mapped to a particular note in a musical scale, that can be selected. Multi-octave.

-   Participants are told of the mapping and given a smartphone. And they can play hopscotch or dance or move, in sync with other participants to create a jam session

-   Can they make music / rhythms?

-   They are given headphones?

### Pieces

+-----------------------------------+---------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+
| Theory                            | Tool                                                                                        | Wait, but why?                                                                                    |
+===================================+=============================================================================================+===================================================================================================+
| Sound Generation                  | -   p5.js with Sound/Music Libraries                                                        | -   Instruments                                                                                   |
|                                   | -   Do any of these SuperCollider? PureData? Strudel? JukeBox AI? have a library for p5.js? | -   Vocals?                                                                                       |
+-----------------------------------+---------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+
| Location Sensing                  | -   OSC protocol?                                                                           | -   Just location sensing                                                                         |
|                                   |                                                                                             |                                                                                                   |
|                                   | -   Arduino sensors?                                                                        |                                                                                                   |
|                                   |                                                                                             |                                                                                                   |
|                                   | -   Link p5.js to Arduino, need libraries for interfacing and data transfer                 |                                                                                                   |
+-----------------------------------+---------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+
| Projection                        | -   Project Network and musical Note?                                                       | -   Network links must decay when participants are too far apart, or are silent...pauses in music |
|                                   |                                                                                             |                                                                                                   |
|                                   | -   Drive Projector using p5.js                                                             |                                                                                                   |
|                                   |                                                                                             |                                                                                                   |
|                                   | -   Do we need projection mapping libraries?                                                |                                                                                                   |
+-----------------------------------+---------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+

: Project #2

## Project #3A and #3B: The 100-Acre Wood with Winnie the Pooh

### Description

-   Create natural shapes / images / illustrations / characters based on kolams/ lu-sona / fractals / L-Systems and graphs.

    -   A: Use grids, smoke, and mirrors to create laser diagrams in a table-top maze.

        -   Pointer laser? Smoke? Agarbatti?

        -   Movable mirrors ( 0/90 degrees only so black paper clips should work.

        -   Single Point of entry for laser.

        -   Look from above through the smoke.

    -   B: Viewers can draw their illustration on a large paper canvas to create a Hundred Acre Wood

        -   Paper and Pencil / Colour / etc

        -   Check with Code and replicate by hand.

    -   Catalogue of Shapes is essential

### Pieces

+-----------------------+-------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------+
| Theory                | Tool                                                              | Wait, but why?                                                                                                    |
+=======================+===================================================================+===================================================================================================================+
| Shape Generation      | -   p5.js                                                         | -   Viewers can match their personality/choice and what is on the garden-wall already to decide on their Creature |
|                       | -   Grids + Mirror locations                                      | -   Laser + Smoke to check the shape if it is a Kolam / Lu-Sona                                                   |
|                       | -   L Systems with random user-chosen seeds                       |                                                                                                                   |
|                       | -   Catalogue of shapes to choose from? In software? Poster also. |                                                                                                                   |
|                       | -   Not too much code                                             |                                                                                                                   |
+-----------------------+-------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------+
| Hardware              | -   Smoke and Mirrors                                             |                                                                                                                   |
|                       |                                                                   |                                                                                                                   |
|                       | -   Pointer Laser                                                 |                                                                                                                   |
+-----------------------+-------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------+
|                       |                                                                   |                                                                                                                   |
+-----------------------+-------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------+

## Project #3: Kagazi hai Pairhan

### Description

-   Dress design with paper

-   Participants will turn and pirouette in front of a camera

-   Measurements will be taken and modelled using non-Euclidean geometry

-   Paper cutout diagrams which can be fabricated to "dress up" the viewer in paper.

-   Paper can have their favourite theorem or piece of text!

    +------------------------------------------------------------------------+-------------------+-----------------------------------------------------------------+
    | Theory                                                                 | Tool              | Wait, but why?                                                  |
    +========================================================================+===================+=================================================================+
    | Measurements on Fixed Points from Camera Image                         | -                 | Clothing Design                                                 |
    +------------------------------------------------------------------------+-------------------+-----------------------------------------------------------------+
    | Math Model of connecting the Points with Hyperbolic Geometry Functions | -                 | -   Allow for fit and drape                                     |
    |                                                                        |                   |                                                                 |
    |                                                                        |                   | -   Should not be too tight                                     |
    |                                                                        |                   |                                                                 |
    |                                                                        |                   | -   Extra "cloth" to stitch with                                |
    |                                                                        |                   |                                                                 |
    |                                                                        |                   | -   All paper must be A4?                                       |
    |                                                                        |                   |                                                                 |
    |                                                                        |                   | -   Entire clothing item must be possible to carry in a file !! |
    |                                                                        |                   |                                                                 |
    |                                                                        |                   | -   Can be "Assembled" any time with tape                       |
    +------------------------------------------------------------------------+-------------------+-----------------------------------------------------------------+
    |                                                                        |                   |                                                                 |
    +------------------------------------------------------------------------+-------------------+-----------------------------------------------------------------+

    : : Project 3: Kagazi Hai Pairhan {.striped .hover}

### Pieces

## Project #4: Music by Hand-Waving

{{< video https://vimeo.com/74922458 >}}

## Other Project Ideas

-   Link IFTTT app to p5.js and make things happen over WiFi, from other classes or buildings
