---
title: Math Models in Design
date: 2022/Dec/31
listing: 
  type: grid
  sort: "order"
  sort-ui: false
  filter-ui: false
  contents: "Modules/*/*.qmd"
  fields: [image, title,reading-time]
  table-striped: true
  table-hover: true
  categories: numbered
---
## Introduction
We will study several Mathematical Models and apply them to Art and Design. The algorithms will be examined and then coded in R; however other open source tools may also be introduced as and when needed.

## Ideas

- 6 Equations that changed the world: Each Model is an Equation

- A mechanical engineer, a chemical engineer, and a computer scientist are driving down the street. The car breaks down and all three get out to see what’s wrong. The mechanical engineer says, “I know what’s wrong, it sounds like the the piston rods are misaligned, if we just fix that it’ll work again.” She takes out her tools, starts messing with the engine, and 30 minutes later the car still isn’t running. The chemical engineer says, “No, no, it sounds like we’re having a problem with the oxygen mixture, it’s too rich and we just need to tune that.” She pulls out the oxygen sensor and starts tweaking, but 30 minutes later the car still doesn’t go. The computer scientist says, “I don’t know what you two are talking about. Just turn the car off, slam the left passenger door three times, walk around the car twice, turn it back on and it will work again.” They do that, and lo and behold, the car starts.
[CS Command Line Bulshittery](https://medium.com/@eytanadar/on-the-value-of-command-line-bullshittery-94dc19ec8c61#.4qt0dd22r)


## References

1. Making Explanations (tools): <https://explorabl.es/tools/>

