---
title: "\U0001F409 Introduction to Radiant"
author: "Arvind Venkatadri"
date: 2022/Nov/11
date-modified: "`r Sys.Date()`"
subtitle: "An R/Shiny based point-and-click tool for Business Analytics"
order: 10
tags:
- Radiant
- Business Analytics
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(blogdown)
```

## Introduction to Radiant

**Radiant** is an open-source platform-independent browser-based
interface for business analytics in R.

Key features

-   Explore: Quickly and easily summarize, visualize, and analyze your
    data
-   Cross-platform: It runs in a browser on Windows, Mac, and Linux
-   Reproducible: Recreate results and share work with others as a state
    file or an Rmarkdown report
-   Programming: Integrate Radiant's analysis functions with your own
    R-code
-   Context: Data and examples focus on business applications

**Radiant** can be used for a variety of tasks

-   Probability and Stats
-   Data visualization
-   Machine Learning
-   Data mining
-   Report Generation.

Radiant Workflows can also be exported to R/RStudio easily.

## Installing Radiant

You can download and install Radiant from here:

<https://radiant-rstats.github.io/docs/install.html>

NOTE: - this automatically installs R, RStudio, and Radiant on your
machine. This is going to be convenient when we start working in R
too! - It also installs Latex, which allows us to create crisp PDF
reports of our analyses.

{{< "youtube", "16B5SvtW8Ks" >}}

## Basic Tutorials with Radiant

All the Tutorials are available on Youtube; the links to individual
videos are on the page below

<https://radiant-rstats.github.io/docs/radiant-tutorial-series.html>

------------------------------------------------------------------------
