---
title: "Working with Shape"
subtitle: ""
subject: "Shapes and Code"
abstract: ""
date: 2024-May-02
date-modified: "`r Sys.Date()`"
order: 90
categories:
- Iterated Functions
- Fractals
- L-Systems
- Mandelbrot
- Julia
- Algorithmic Patterns
- Symmetry
image: ""
lightbox: true
---

## Introduction
Topics that may be covered here:\
- Iterated Function Systems and Fractals\
- Symmetries in Space\
- L Systems, Mandalas and Kolams\
- Logistic Functions\
- Projections\

## {{< iconify icons8 idea >}} Inspiration

This equation will change how you see the world.  It's about the Logistic Map, bifurcation diagrams, the Mandelbrot set, animal populations, dripping faucets, neuron firing rates and more.

{{< video https://youtu.be/ovJcsL7vyrk >}}

So let us see how we can construct this algorithmically, the different parts of it. And of course why we should bother!

## What is an Iterated Function?

Well, we know what a `function` is don't we? A relationship between numbers. One varies as the others, and the relationship is specified by the function. E.g. $y = \sin(x)$.

So what is `iteration` then, and how do you do that to a function? It is applying the same function over and over again, by piping the results of the previous step i.e. iteration back into the function. 







## {{< iconify mingcute thought-line >}} Wait, But Why?


## {{< iconify ooui references-ltr >}} References


Working with Shadows. 
<https://www.wikiwand.com/en/Map_projection>

Working with Fourier Series and Epicyles
<http://www.jezzamon.com/fourier/index.html> and <https://alex.miller.im/posts/fourier-series-spinning-circles-visualization/>

https://twitter.com/i/status/962449509782495232
<https://codegolf.stackexchange.com/questions/36374/redraw-an-image-with-just-one-closed-curve>


## Generative Art

1. Art from Code: Danielle Navarro. <https://art-from-code.netlify.app>

2. <https://generative.substack.com/p/generative-art-and-r>

1. <https://github.com/cutterkom/generativeart>

1. <https://paulvanderlaken.com/2020/05/02/generative-art-computer-design-painting/>

1. <https://www.bigbookofr.com/art.html#thinking-outside-the-grid---a-bare-bones-intro-to-rtistry-concepts-in-r-using-ggplot>

1. <https://clauswilke.com/art/>

3. <https://generatecoll.medium.com/how-i-used-excel-to-create-abstract-album-artwork-fee740d4414f>

1. Random Digital Beauty. <https://anaselk.com/p/generative-r/>

4. https://nannou.cc

5. https://openframeworks.cc/

6. https://libcinder.org

7. <https://cgjennings.ca/articles/l-systems/>

8. <https://paulbourke.net/fractals/>


## Kolams, in R and other tools

1.   Reddy, Anu, and Alex McLean. 2024. “Drawing Kolam Patterns in Stitches and Code.” Algorithmic Pattern, March. https://doi.org/10.21428/108765d1.53f112a6.

1. Ezine for Kolam: ( Bad Link) <https://files.cargocollective.com/c989887/Kolam_zine--1-.png>

1. <https://www.ted.com/talks/ron_eglash_the_fractals_at_the_heart_of_african_designs>

1. <https://www.atlasobscura.com/articles/indian-rice-art-kolam>

1. <https://www.sciencedirect.com/science/article/abs/pii/0146664X74900112>

1. <https://www.sciencedirect.com/science/article/pii/S0166218X09000845#b26>

1. <http://interdigitation.embodimentlabs.org/>

1. <https://www.jeremykun.com/2014/09/29/hybrid-images/>
Using Fourier Series to morph images !!!

1. <https://nb.paulbutler.org/l-systems/>

1. <http://algorithmicbotany.org/papers/#abop>

1. <https://acko.net/blog/how-to-fold-a-julia-fractal/>

1. <https://algorithmicpattern.org>

1. Steven Witten. <https://acko.net/>

{{< youtube https://youtu.be/Zkx1aKv2z8o >}}


## Book References

1. Julien Sprott. <https://sprott.physics.wisc.edu/fractals/booktext/SABOOK.PDF>

1. Marcia Ascher, "Ethnomathematics"

1. Claudia Zaslavsky, "Africa Counts"

1. Ron Eglash, "Africa Fractals"

1. Paulus Gerdes, "Adventures in the World of Matrices"


