---
title: "Working with Sound"
date: ""
---

## Introduction

Topics that may be covered here:

-   Fourier Transforms\
-   Sound Analysis and Synthesis using FFT\

## What is the Fourier Series?

First let us watch this little video:

{{< video https://youtu.be/BUQzS5eVeck >}}

Now head off to <https://mathlets.org/mathlets/fourier-coefficients/> to
play an interactive Game on Fourier Analysis.

## Resources

1.  <https://mathlets.org/mathlets/fourier-coefficients/>
2.  Working with Audio in `p5.js`.
    <https://pdm.lsupathways.org/3_audio/>
3.  Violet Whitney. (Sep 28, 2023) *Sounds: Working with sounds and
    speech in P5.js*.
    <https://medium.spatialpixel.com/sounds-bd05429aba38>
4.  Mister Bomb. *p5.Sound project tutorials*.
    <https://www.youtube.com/playlist?list=PLIsdHp2z9wFl7A1wWb2VmQUUojEGsKELE>
5.  <https://musiclab.chromeexperiments.com/oscillators>
6.  <https://www.electronicbeats.net/the-feed/excel-drum-machine/>
7.  <https://junshern.github.io/algorithmic-music-tutorial/>
8.  <https://blackwhiskercult.com/visual-music-in-p5-js-i/>

### Other tools to explore

1.  Strudel REPL <https://strudel.cc>
2.  Introducing Jukebox, a neural net that generates music, including
    rudimentary singing, as raw audio in a variety of genres and artist
    styles. We're releasing a tool for everyone to explore the generated
    samples, as well as the model and code:
    <https://openai.com/index/jukebox/> (OpenAI (@OpenAI) April 30,
    2020,via Twitter https://twitter.com/OpenAI)
3.  <https://algorithmicpattern.org/2023/05/15/strudel-live-coding-patterns-on-the-web/>
4.  <https://betterexplained.com/articles/vector-calculus-understanding-the-dot-product/>
5.  Freesound: Find Any Sound you Like. <https://freesound.org>
6.  WebSpeech API.
    <https://developer.chrome.com/blog/voice-driven-web-apps-introduction-to-the-web-speech-api/>
7.  <https://dogbotic.com>
