---
title: "Using FlexDashboard in R"
date: "`r Sys.Date()`"
subtitle: "Making Business Presentations using Flexdashboards in R"
author: Arvind Venkatadri
order: 10
# image:
# image-height: 
# image-width: 
format: html
theme: united
code-fold: false
code-summary: Show the Code
code-tools: true
code-line-numbers: true
code-overflow: scroll
code-copy: true
fig-align: center
reference-location: margin
cap-location: margin
highlight-style: tango
df-print: paged
section-divs: true
number-sections: true
execute: 
  freeze: auto
tags:
  - flexdashboard
  - Dashboard Layouts
---

# {{< fa folder-open >}} Slides and Tutorials

| <a href="./files/flexdashboard.Rmd"><i class="fa-brands               
               fa-r-project"></i> R Tutorial</a>                        |     |     |     |
|------------------|-------------------|------------------|------------------|

# Introduction

Now that we have gotten a handle on Descriptive Analytics, Predictive
Analytics, Modelling, Statistical Analysis, and Optimization, it is time
to put all that work together in a convincing poster/presentation!

There are many ways of doing this, of course. We will be following a
very intuitive `package` in R, called `flexdashboard`. This package
allows us to make Posters that include code, analysis, description, and
of course pictures to weave a convincing story for upper management!

# FlexDashboard

We will use the `flexdashboard` package to create our reports.

> Highlights of the flexdashboard package include:
>
> -   Support for a wide variety of **components** including interactive
>     **htmlwidgets; base, lattice, and grid graphics; tabular data;
>     gauges; and value boxes**.
> -   Flexible and easy to specify **row and column-based layouts**.
>     Components are intelligently re-sized to fill the browser and
>     adapted for display on mobile devices.
> -   Extensive support for **text annotations** to include assumptions,
>     contextual narrative, and analysis within dashboards.
> -   **Storyboard layouts** for presenting sequences of visualizations
>     and related commentary.
> -   By default dashboards are standard HTML documents that can be
>     deployed on any web server or even attached to an email message.
>     You can optionally add Shiny components for additional
>     interactivity and then deploy on Shiny Server or shinyapps.io.

# An Example

Here is a good example of what we can create as a flexdashboard based
business report:

<https://testing-apps.shinyapps.io/flexdashboard-ggplotly-examples/>

Let us work through creating a `flexdashboard` based report.

## References

1.  Flexdashboard Basics
    <https://rstudio.github.io/flexdashboard/articles/flexdashboard.html>

2.  Flexdashboard Examples
    <https://rstudio.github.io/flexdashboard/articles/examples.html>

3.  Shannon Haymond,*Create laboratory business intelligence dashboards
    for free using R: A tutorial using the flexdashboard package*,
    Journal of Mass Spectrometry and Advances in the Clinical Lab,
    Volume 23, 2022,Pages 39-43, ISSN 2667-145X,
    <https://doi.org/10.1016/j.jmsacl.2021.12.002>.

4.  https://posit.co/blog/flexdashboard-easy-interactive-dashboards-for-r/
