---
title: "Projects"
author: "Arvind V"
date: 22/July/2024
date-modified: " `r Sys.Date()` "
order: 2024
---

## Introduction

Here are projects that we will contemplate creating at the end of the
course. All the techniques, software, packages, theory, hardware...will
be pieces aimed the realization of these projects. So we begin this
course with the end in mind.

## Project #1: King/Queen of the Mountain

#### Description

-   Each participant in the exhibit chooses whether they want to be on a
    mountain or in a valley, or in a grassland/meadow. More choices if
    you are up to it..volcano, anyone?

-   Their position within the space will be sensed. And they can move.

-   A terrain map will be projected, either on the ceiling, or the
    screen, or on the participants themselves, with each individual
    being located on a specific terrain feature type that they chose at
    the start.

#### Pieces

+----------------+------------------------+------------------------+
| Theory         | Tool                   | Wait, but why?         |
+================+========================+========================+
| Terrain        | -   p5.js/ Perlin      | -   Terrain!           |
| Generation     |     Noise              |                        |
+----------------+------------------------+------------------------+
| Location       | -   OSC protocol?      | -   Give seed          |
| Sensing        |                        |     locations to       |
|                | -   Arduino sensors?   |     Perlin Noise       |
|                |                        |     generator          |
|                | -   Link p5.js to      |                        |
|                |     Arduino, need      | -   Defines            |
|                |     libraries for      |     preferences of     |
|                |     interfacing and    |     terrain feature    |
|                |     data transfer      |     based in identity  |
+----------------+------------------------+------------------------+
| Projection     | -   Project terrain    | -   Watch participants |
|                |     map                |     move and terrain   |
|                |                        |     follows them       |
|                | -   Drive Projector    |                        |
|                |     using p5.js        |                        |
|                |                        |                        |
|                | -   Do we need         |                        |
|                |     projection mapping |                        |
|                |     libraries?         |                        |
+----------------+------------------------+------------------------+

: Project #1

## Project #2: Sound Relationships

#### Description

-   The floor is divided into footprint-sized areas. Each area is mapped
    to a particular note in a musical scale, that can be selected.
    Multi-octave.

-   Participants are told of the mapping and given a smartphone. And
    they can play hopscotch or dance or move, in sync with other
    participants to create a jam session.

-   Can they make music / rhythms?

-   They are given headphones?

#### Pieces

+----------------+----------------------+------------------------+
| Theory         | Tool                 | Wait, but why?         |
+================+======================+========================+
| Sound          | -   p5.js with       | -   Instruments        |
| Generation     |     Sound/Music      | -   Vocals?            |
|                |     Libraries        |                        |
|                | -   Do any of these  |                        |
|                |     SuperCollider?   |                        |
|                |     PureData?        |                        |
|                |     Strudel? JukeBox |                        |
|                |     AI? have a       |                        |
|                |     library for      |                        |
|                |     p5.js?           |                        |
+----------------+----------------------+------------------------+
| Location       | -   OSC protocol?    | -   Just location      |
| Sensing        |                      |     sensing            |
|                | -   Arduino sensors? |                        |
|                |                      |                        |
|                | -   Link p5.js to    |                        |
|                |     Arduino, need    |                        |
|                |     libraries for    |                        |
|                |     interfacing and  |                        |
|                |     data transfer    |                        |
+----------------+----------------------+------------------------+
| Projection     | -   Project Network  | -   Network links must |
|                |     and musical      |     decay when         |
|                |     Note?            |     participants are   |
|                |                      |     too far apart, or  |
|                | -   Drive Projector  |     are                |
|                |     using p5.js      |     silent...pauses in |
|                |                      |     music              |
|                | -   Do we need       |                        |
|                |     projection       |                        |
|                |     mapping          |                        |
|                |     libraries?       |                        |
+----------------+----------------------+------------------------+

: Project #2

## Project #3A and #3B: The 100-Acre Wood with Winnie the Pooh

### Description

-   Create natural shapes / images / illustrations / characters based on
    kolams/ lu-sona / fractals / L-Systems and graphs.

-   A: Use grids, smoke, and mirrors to create laser diagrams in a
    table-top maze.

    -   Pointer laser? Smoke? Agarbatti?
    -   Movable mirrors ( 0/90 degrees only so black paper clips should
        work.)
    -   Single Point of entry for laser.
    -   Look from above through the smoke.

-   B: Viewers can draw their illustration on a large paper canvas to
    create a Hundred Acre Wood

    -   Paper and Pencil / Colour / etc
    -   Check with Code and replicate by hand.
    -   Catalogue of Shapes is essential
    -   Grid, Kolam Choice for shape, changes, innovation are possible

#### Pieces

+----------------+----------------+--------------------------------+
| Theory         | Tool           | Wait, but why?                 |
+================+================+================================+
| Shape          | -   p5.js      | -   Viewers can match their    |
| Generation     | -   Grids +    |     personality/choice and     |
|                |     Mirror     |     what is on the garden-wall |
|                |     locations  |     already to decide on their |
|                | -   L Systems  |     Creature                   |
|                |     with       | -   Laser + Smoke to check the |
|                |     random     |     shape if it is a Kolam /   |
|                |                |     Lu-Sona                    |
|                |    user-chosen |                                |
|                |     seeds      |                                |
|                | -   Catalogue  |                                |
|                |     of shapes  |                                |
|                |     to choose  |                                |
|                |     from? In   |                                |
|                |     software?  |                                |
|                |     Poster     |                                |
|                |     also.      |                                |
|                | -   Not too    |                                |
|                |     much code  |                                |
+----------------+----------------+--------------------------------+
| Hardware       | -   Smoke and  |                                |
|                |     Mirrors    |                                |
|                |                |                                |
|                | -   Pointer    |                                |
|                |     Laser      |                                |
+----------------+----------------+--------------------------------+
|                |                |                                |
+----------------+----------------+--------------------------------+

## Project #4: Kagazi hai Pairhan

:::: pa4
::: {.athelas .ml0 .mt0 .pl4 .black-90 .bl .bw2 .b--blue}
["Naqsh fariyādī hai kis kī shoḳhi-e-tahrīr kā<br> Kāġhzī hai pairahan
har paikar-e-tasvīr kā"]{.f5 .f4-m .f3-l .lh-copy .measure .mt0}

[--- Ghalib]{.f6 .ttu .tracked .fs-normal}
:::
::::

### Description

-   Dress/Clothing design with paper

-   Participants will turn and pirouette/turn about in front of a camera

-   Measurements will be taken and modelled using non-Euclidean geometry

-   Paper cutout diagrams which can be fabricated to "dress up" the
    viewer in paper.

-   Paper can have their favourite theorem or piece of text printed upon
    it!

#### Pieces

+----------------+----------------+---------------------------------+
| Theory         | Tool           | Wait, but why?                  |
+================+================+=================================+
| Measurements   | -   ml5.js     | -   Clothing Design             |
| of Fixed       |     Pose       |                                 |
| Points on/from |     Detection? |                                 |
| Camera Image   |                |                                 |
|                | -   Must get   |                                 |
|                |     hold of    |                                 |
|                |     Pose       |                                 |
|                |     Detection  |                                 |
|                |     Data and   |                                 |
|                |     convert    |                                 |
|                |     into       |                                 |
|                |     "printed   |                                 |
|                |     dress"     |                                 |
|                |     pieces     |                                 |
|                |                |                                 |
|                | -   Choice of  |                                 |
|                |     Clothing?? |                                 |
+----------------+----------------+---------------------------------+
| Math Model of  | -   Other ways | -   Allow for fit and drape     |
| Connecting     |     than       | -   Should not be too tight     |
| Points with    |     ml5.js??   | -   "Extra" Cloth to stitch     |
| Hyperbolic     |                |     with                        |
| Geometry       | -   Image to   | -   All paper must be A4?       |
| Functions      |     Geometry   | -   Entire costume must be      |
|                |     libraries? |     possible to carry in a file |
|                |                | -   Can be "Assembled any time  |
|                |                |     with tape/ pins/clips       |
+----------------+----------------+---------------------------------+
|                |                |                                 |
+----------------+----------------+---------------------------------+

## Project #4: My Face is a Fourier Series

See this:

<https://gofigure.impara.ai/drawing/5711774133256192>

-   People stand in front of camera

-   Detailed picture is taken. Profile preferable!

-   The code will generate a Fourier Series of their profile and present
    an animated version on the screen.

-   Reset and Play should be possible

#### Pieces

+-----------------+-----------------+----------------------------------+
| Theory          | Tool            | Wait, but why?                   |
+=================+=================+==================================+
| Measurements of | -   ml5.js?     | -   Capturing Profile "waveform" |
| Fixed Points    |                 |                                  |
| on/from Camera  | -   Profile     |                                  |
| Image           |     Detection   |                                  |
|                 |     and         |                                  |
|                 |     conversion  |                                  |
|                 |     to waveform |                                  |
+-----------------+-----------------+----------------------------------+
| Generating      | -   Math        | -   Animation                    |
| Fourier Series  |     Library     |                                  |
| with Waveform + |                 |                                  |
| Animation       | -   Should be   |                                  |
|                 |     easily      |                                  |
|                 |     available   |                                  |
+-----------------+-----------------+----------------------------------+
|                 |                 |                                  |
+-----------------+-----------------+----------------------------------+

## Project #5: Music by Hand-Waving

{{< video https://vimeo.com/74922458 >}}

## Other Project Ideas

-   Link IFTTT app to p5.js and make things happen over WiFi, from other
    classes or buildings
