---
title: "Working With Chaos"
---
```{r}
#| label: setup
#| include: false

# devtools::install_github("seankross/p5")
library(p5)

```

{{< youtube https://youtu.be/ovJcsL7vyrk >}}

## References


### Websites

1. <https://openprocessing.org>

1. <https://timrodenbroeker.de/processing-or-p5/>


### Code References

1. Animations, coding, interactives in this video by Jonny Hyman 🙌
Try the code yourself: <https://github.com/jonnyhyman/Chaos>

### Papers

1. May, R. Simple mathematical models with very complicated dynamics. Nature 261, 459–467 (1976). <https://doi.org/10.1038/261459a0>

1. Robert Shaw, The Dripping Faucet as a Model Chaotic System
https://archive.org/details/ShawRober...

1. Crevier DW, Meister M. Synchronous period-doubling in flicker vision of salamander and man.
J Neurophysiol. 1998 Apr;79(4):1869-78.

1. Bing Jia, Huaguang Gu, Li Li, Xiaoyan Zhao. Dynamics of period-doubling bifurcation to chaos in the spontaneous neural firing patterns Cogn Neurodyn (2012) 6:89–106 DOI 10.1007/s11571-011-9184-7

1. A Garfinkel, ML Spano, WL Ditto, JN Weiss. Controlling cardiac chaos
Science  28 Aug 1992: Vol. 257, Issue 5074, pp. 1230-1235 DOI: 10.1126/science.1519060

1. R. M. May, D. M. G. Wishart, J. Bray and R. L. Smith Chaos and the Dynamics of Biological Populations
Source: Proceedings of the Royal Society of London. Series A, Mathematical and Physical Sciences, Vol. 413, No. 1844, Dynamical Chaos (Sep. 8, 1987), pp. 27-44

1. Chialvo, D., Gilmour Jr, R. & Jalife, J. Low dimensional chaos in cardiac tissue. Nature 343, 653–657 (1990). https://doi.org/10.1038/343653a0

1. Xujun Ye, Kenshi Sakai. A new modified resource budget model for nonlinear dynamics in citrus production. Chaos, Solitons and Fractals 87 (2016) 51–60

1. Libchaber, A. & Laroche, C. & Fauve, Stephan. (1982). Period doubling cascade in mercury, a quantitative measurement. http://dx.doi.org/10.1051/jphyslet:01.... 43. 10.1051/jphyslet:01982004307021100. 





