---
title: "Schelling Points"
author: "Arvind Venkatadri"
order: 30
date: 2023-08-24
date-modified: "`r Sys.Date()`"
abstract: "Dus Hazaar logon ko ek saath ek cheez karte hue dekha hai?"
---

## Introduction

In the module on [Game Theory](../10-InteratedGames/iteratedGames.qmd) we saw how we all are engaged in transactional *Games* with many other people, most of whom are strangers to us. [The Prisoner's Dilemma](../10-InteratedGames/iteratedGames.qmd#sec-nice-guys-finish-firsts)


As remarked before, the Human Species is perhaps unique in that we are able to [cooperate with strangers](https://fee.org/media/4316/547_42.pdf)!! How would we use these ideas in building businesses?

Today, we will study Coordination Games and Shcelling Focus Points, and see how these concepts can help better businesses.

### Coordination Games and Schelling Focus Points 

Watch these two videos on the topic of Focal Points as defined by Schelling.

{{< youtube CFOQquw6hig >}}


<br>

{{< youtube oDsePkuaL9Q >}}


<br>

Focal points can be used in Coordination Games: these are activities where people's actions tend to organize into Patterns based on specific default options. These actions could be 

a) Conversation

b) Dress

c) Travel / Meeting

d) Location

e) Attention

## How Does This Apply to Business?

Let us now look at a few uses of "cultural Schelling Points"!!

### Case Study #1: Tanishq Ad

{{< youtube UZhQVBcGQ-Y >}}

### Case Study #2: Havell's Ad

{{< youtube OlMlwUZ-LK0 >}}

And now shall we look at "Spatial Schelling Points"?


### Additional Readings on Schelling Points

a) https://mindyourdecisions.com/blog/2008/04/01/focal-points-or-schelling-points-how-we-naturally-organize-in-games-of-coordination/

b) https://medium.com/@richlitt/using-schelling-points-to-perform-better-973243efd989
