---
title: 'Lab-6: These Roses have been Painted !!'
subtitle: 'The Grammar of Graphics in R'
summary: "The Grammar of Graphics in R"
date: 21/Aug/2022
date-modified: "`r Sys.Date()`"
order: 60
---

## {{< fa folder-open >}} Slides and Tutorials

| <a href="../../../../labs/r-labs/graphics/index.qmd"><i class="fa-brandsfa-r-project"></i> R Tutorial</a>   | <a href="../../../../slides/r-slides/graphics/metaphors.qmd"> <iconify-icon icon="icon-park:ppt"></iconify-icon> Slides </a> | <a href="../../../../labs/r-labs/graphics/colors.qmd"> <iconify-icon icon="cil:color-palette"></iconify-icon> Colour in R</a>  | <a href="../../../../labs/r-labs/graphics/wizardy.qmd"><iconify-icon icon="fa6-solid:hat-wizard"></iconify-icon>Advanced Graphics</a> |
|------------------|------------------|------------------|-------------------|

## {{< iconify openmoji japanese-symbol-for-beginner >}} Introduction

Ah...`ggplot` ! All those wonderful pictures and graphs, that Alice
might have relished!

Metaphors, aesthetics, geometries...and pictures !! `ggplot` seems to
equate ravens to writing desks in its syntax...and out come graphs!!

And colours: Wes Anderson! Tim Burton! The Economist... and many
others!!

## {{< fa asterisk >}} References

1.  George Lakoff and Mark Johnson, *Metaphors We Live By*,
    <https://www.youtube.com/watch?v=lYcQcwUfo8c>

2.  Wickham and Grolemund, R for Data Science, `ggplot` chapter:
    <https://r4ds.had.co.nz/data-visualisation.html>

3.  CMDLineTips, *10 Tips to Customize Text Color, Font, Size in
    `ggplot2` with `element_text()`*,
    <https://cmdlinetips.com/2021/05/tips-to-customize-text-color-font-size-in-ggplot2-with-element_text/>

4.  CMDLineTips, *How to write a simple custom ggplot theme from
    scratch*,
    <https://cmdlinetips.com/2022/05/how-to-write-a-simple-custom-ggplot-theme-from-scratch/>

5.  Asha Hill \@ mode.com, *12 Extensions to ggplot2 for More Powerful R
    Visualizations*,
    <https://mode.com/blog/r-ggplot-extension-packages/>

6.  Emil Hvitfeldt, *ggplot Trial and Error*,
    <https://www.emilhvitfeldt.com/post/2018-06-12-ggplot2-trial-and-error-us-trade-data/>

## {{< fa icons >}} Fun Stuff

1.  Yihan Wu, *Mapping ggplot geoms and aesthetic parameters*, ( An
    interactive view of which aesthetic parameters work with which
    ggplot geom!! )
    <https://www.yihanwu.ca/post/geoms-and-aesthetic-parameters/>

2.  <https://www.theartstory.org/artist/kandinsky-wassily/>
