---
title: "Projects"
author: "Arvind V"
date: 22/July/2024
subject: ""
summary: ""
abstract: ""
order: 2025
---

## Introduction

Here are projects that we will contemplate creating at the end of the
course. All the techniques, software, packages, theory, hardware...will
be pieces aimed the realization of these projects. So we begin this
course with the end in mind.

The projects below have been grouped into two groups, one for the junior students and the other senior students, who are both paradoxically in the same class. But there is an opinion that [prerequisites are irrelevant](LINK TO BE WRITTEN IN). 

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Do not start with fundamentals. This is an awful approach to learning. <br><br>Start with so-called &quot;advanced&quot; topics and ask questions until every term/concept is understood. <br><br>This is the correct, rigorous, scientific way to learn, because the advanced topics are embedded in larger,…</p>&mdash; Sean McClure (@sean_a_mcclure) <a href="https://twitter.com/sean_a_mcclure/status/1895213068197450169?ref_src=twsrc%5Etfw">February 27, 2025</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

## Project #J0: Make an ad for a wellknown logo

## Project #J1: 


## Project #1: King/Queen of the Mountain

#### Description

-   Each participant in the exhibit chooses whether they want to be on a
    mountain or in a valley, or in a grassland/meadow. More choices if
    you are up to it...volcano, anyone?
-   Their position within the space will be sensed. And they can move.
-   A terrain map will be projected, either on the ceiling, or the
    screen, or on the participants themselves, with each individual
    being located on a specific terrain feature type that they chose at
    the start.

#### Pieces

+----------------+-----------------------+-----------------------+
| Theory         | Tool                  | Wait, but why?        |
+================+=======================+=======================+
| Terrain        | -   p5.js/ Perlin     | -   Terrain!          |
| Generation     |     Noise             |                       |
+----------------+-----------------------+-----------------------+
| Location       | -   OSC protocol?     | -   Give seed         |
| Sensing        | -   Arduino sensors?  |     locations to      |
|                | -   Link p5.js to     |     Perlin Noise      |
|                |     Arduino, need     |     generator         |
|                |     libraries for     | -   Defines           |
|                |     interfacing and   |     preferences of    |
|                |     data transfer     |     terrain feature   |
|                |                       |     based in identity |
+----------------+-----------------------+-----------------------+
| Projection     | -   Project terrain   | -   Watch             |
|                |     map               |     participants move |
|                | -   Drive Projector   |     and terrain       |
|                |     using p5.js       |     follows them      |
|                | -   Do we need        |                       |
|                |     projection        |                       |
|                |     mapping           |                       |
|                |     libraries?        |                       |
+----------------+-----------------------+-----------------------+

: Project #1

## Project #2: Sound Relationships

#### Description

-   The floor is divided into footprint-sized areas. Each area is mapped
    to a particular note in a musical scale, that can be selected.
    Multi-octave.
-   Participants are told of the mapping and given a smartphone. And
    they can play hopscotch or dance or move, in sync with other
    participants to create a jam session.
-   Can they make music / rhythms?
-   They are given headphones?

#### Pieces

+----------------+---------------------+-----------------------+
| Theory         | Tool                | Wait, but why?        |
+================+=====================+=======================+
| Sound          | -   p5.js with      | -   Instruments       |
| Generation     |     Sound/Music     | -   Vocals?           |
|                |     Libraries       |                       |
|                | -   Do any of these |                       |
|                |     SuperCollider?  |                       |
|                |     PureData?       |                       |
|                |     Strudel?        |                       |
|                |     JukeBox AI?     |                       |
|                |     have a library  |                       |
|                |     for p5.js?      |                       |
+----------------+---------------------+-----------------------+
| Location       | -   OSC protocol?   | -   Just location     |
| Sensing        | -   Arduino         |     sensing           |
|                |     sensors?        |                       |
|                | -   Link p5.js to   |                       |
|                |     Arduino, need   |                       |
|                |     libraries for   |                       |
|                |     interfacing and |                       |
|                |     data transfer   |                       |
+----------------+---------------------+-----------------------+
| Projection     | -   Project Network | -   Network links     |
|                |     and musical     |     must decay when   |
|                |     Note?           |     participants are  |
|                | -   Drive Projector |     too far apart, or |
|                |     using p5.js     |     are               |
|                | -   Do we need      |     silent...pauses   |
|                |     projection      |     in music          |
|                |     mapping         |                       |
|                |     libraries?      |                       |
+----------------+---------------------+-----------------------+

: Project #2

## Project #3A and #3B: The 100-Acre Wood with Winnie the Pooh

### Description

-   Create natural shapes / images / illustrations / characters based on
    kolams/ lu-sona / fractals / L-Systems and graphs.
-   A: Use grids, smoke, and mirrors to create laser diagrams in a
    table-top maze.
    -   Pointer laser? Smoke? Agarbatti?
    -   Movable mirrors ( 0/90 degrees only so black paper clips should
        work.)
    -   Single Point of entry for laser.
    -   Look from above through the smoke.
-   B: Viewers can draw their illustration on a large paper canvas to
    create a Hundred Acre Wood
    -   Paper and Pencil / Colour / etc
    -   Check with Code and replicate by hand.
    -   Catalogue of Shapes is essential
    -   Grid, Kolam Choice for shape, changes, innovation are possible

#### Pieces

+----------------+------------------------------+-------------------------------+
| Theory         | Tool                         | Wait, but why?                |
+================+==============================+===============================+
| Shape          | -   p5.js                    | -   Viewers can match their   |
| Generation     | -   Grids + Mirror locations |     personality/choice and    |
|                | -   L Systems with random    |     what is on the            |
|                |     user-chosen seeds -      |     garden-wall already to    |
|                |     Catalogue of shapes to   |     decide on their Creature  |
|                |     choose from? In          | -   Laser + Smoke to check    |
|                |     software? Poster also.   |     the shape if it is a      |
|                | -   Not too much code        |     Kolam / Lu-Sona           |
+----------------+------------------------------+-------------------------------+
| Hardware       | -   Smoke and Mirrors        |                               |
|                | -   Pointer Laser            |                               |
+----------------+------------------------------+-------------------------------+
|                |                              |                               |
+----------------+------------------------------+-------------------------------+

## Project #4: Kagazi hai Pairhan

:::: pa4
::: {.athelas .ml0 .mt0 .pl4 .black-90 .bl .bw2 .b--blue}
["Naqsh fariyādī hai kis kī shoḳhi-e-tahrīr kā<br> Kāġhzī hai pairahan
har paikar-e-tasvīr kā"]{.f5 .f4-m .f3-l .lh-copy .measure .mt0}

[--- Ghalib]{.f6 .ttu .tracked .fs-normal}
:::
::::

### Description

-   Dress/Clothing design with paper
-   Participants will turn and pirouette/turn about in front of a camera
-   Measurements will be taken and modelled using non-Euclidean geometry
-   Paper cutout diagrams which can be fabricated to "dress up" the
    viewer in paper.
-   Paper can have their favourite theorem or piece of text printed upon
    it!

#### Pieces

+----------------+----------------+--------------------------------+
| Theory         | Tool           | Wait, but why?                 |
+================+================+================================+
| Measurements   | -   ml5.js     | -   Clothing Design            |
| of Fixed       |     Pose       |                                |
| Points on/from |     Detection? |                                |
| Camera Image   | -   Must get   |                                |
|                |     hold of    |                                |
|                |     Pose       |                                |
|                |     Detection  |                                |
|                |     Data and   |                                |
|                |     convert    |                                |
|                |     into       |                                |
|                |     "printed   |                                |
|                |     dress"     |                                |
|                |     pieces     |                                |
|                | -   Choice of  |                                |
|                |     Clothing?? |                                |
+----------------+----------------+--------------------------------+
| Math Model of  | -   Other ways | -   Allow for fit and drape    |
| Connecting     |     than       | -   Should not be too tight    |
| Points with    |     ml5.js??   | -   "Extra" Cloth to stitch    |
| Hyperbolic     | -   Image to   |     with                       |
| Geometry       |     Geometry   | -   All paper must be A4?      |
| Functions      |     libraries? | -   Entire costume must be     |
|                |                |     possible to carry in a     |
|                |                |     file                       |
|                |                | -   Can be "Assembled any time |
|                |                |     with tape/ pins/clips      |
+----------------+----------------+--------------------------------+
|                |                |                                |
+----------------+----------------+--------------------------------+

## Project #4: My Face is a Fourier Series

See this:

<https://gofigure.impara.ai/drawing/5711774133256192>

-   People stand in front of camera
-   Detailed picture is taken. Profile preferable!
-   The code will generate a Fourier Series of their profile and present
    an animated version on the screen.
-   Reset and Play should be possible

#### Pieces

+----------------+----------------+---------------------------------+
| Theory         | Tool           | Wait, but why?                  |
+================+================+=================================+
| Measurements   | -   ml5.js?    | -   Capturing Profile           |
| of Fixed       | -   Profile    |     "waveform"                  |
| Points on/from |     Detection  |                                 |
| Camera Image   |     and        |                                 |
|                |     conversion |                                 |
|                |     to         |                                 |
|                |     waveform   |                                 |
+----------------+----------------+---------------------------------+
| Generating     | -   Math       | -   Animation                   |
| Fourier Series |     Library    |                                 |
| with           | -   Should be  |                                 |
| Waveform +     |     easily     |                                 |
| Animation      |     available  |                                 |
+----------------+----------------+---------------------------------+
|                |                |                                 |
+----------------+----------------+---------------------------------+

## Project #5: Music by Hand-Waving

{{< video https://vimeo.com/74922458 >}}

## Other Project Ideas

-   Link IFTTT app to p5.js and make things happen over WiFi, from other
    classes or buildings
