---
title: "\U0001F5FA Maps"
subtitle: "Maps"
abstract: "Geospatial Data and how to use it with intent"
author: "Arvind Venkatadri"
date: 15/Aug/2022
date-modified: "`r Sys.Date()`"
order: 70
format: html
#fig-format: retina
code-fold: false
code-summary: Show the Code
code-block-border-left: true
code-overflow: scroll
code-block-bg: "beige"
code-tools: true
code-line-numbers: true
code-copy: true
fig-align: center
reference-location: margin
cap-location: margin
highlight-style: tango
df-print: paged
section-divs: true
number-sections: true
execute: 
  freeze: auto
  cache: true
tags:
- Spatial Data Maps
- Static and Interactive
- Choropleth Maps
- Bubble Plots on Maps
- Cartograms
---

# {{< fa folder-open >}} Slides and Tutorials

|                                                                                                                              |                                                                                                                          |                                                                                                                                                         |                                                                                                                                                        |
|------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------|
| <a href="https://r-for-artists.netlify.app/slides/06-spatial/06-Spatial-Data-in-R.html"><i class="fa-solid                   
                   fa-file-powerpoint"></i> R Tutorial</a>                                                                     | <a href="./files/distributions.ows"> <iconify-icon icon="fluent-emoji:orange-circle"></iconify-icon> Orange Tutorial</a> | <a href="https://r-for-artists.netlify.app/slides/06-spatial/06-Spatial-Data-in-R.html"><i class="fa-solid                fa-map"></i> Static Maps</a>  | <a href="https://r-for-artists.netlify.app/labs/06-spatial/PlayingwithLeaflet.html"> <i class="fa-solid fa-map-location-dot"></i> Interactive Maps</a> |

# Introduction

First; let us watch a short, noisy video on maps:

{{< video https://youtu.be/YH2sAbXv7p4 >}}

## What kind of maps will we make?

We will first understand the structure of spatial data and where to find
it. For now, we will deal with **vector** spatial data; the discussion
on **raster** data will be dealt with in another future module.

We will get hands-on with making maps, both static and interactive.

### Choropleth Map

What does choropleth[^1] mean? And what kind of information could this
map represent?

<iframe width="100%" height="536" frameborder="0" src="https://observablehq.com/embed/2930afc559123cab?cells=chart">

</iframe>

### Bubble Map

What information could this map below represent?

<iframe width="100%" height="665" frameborder="0" src="https://observablehq.com/embed/9e3c148cb813bfbc?cells=chart">

</iframe>

Let us now look at the slides. Then we will understand how the R
packages `sf`, `tmap` work to create maps, using data downloadable into
R using `osmdata`, `osmplotr` and `osmar`. We will also make interactive
maps with `leaflet` and `mapview`; `tmap` is also capable of creating
interactive maps.

## Your Turn

### Animal and Bird Migration

-   Head off to
    [movebank.org](https://www.movebank.org/cms/movebank-main). Look at
    a few species of interest and choose one.
-   Download the data ( **ESRI Shapefile**). Note: You will get a .zip
    file with a good many files in it. Save **all** of them, but read
    only the `.shp` file into R and Orange.
-   Import that into R using `sf_read()`
-   See how you can plot locations, tracks and colour by
    species....based on the data you download.
-   For tutorial info: <https://movebankworkshopraleighnc.netlify.app/>

### UFO Sightings

Here is a UFO Sighting dataset, containing location and text
descriptions.
<https://github.com/planetsig/ufo-reports/blob/master/csv-data/ufo-scrubbed-geocoded-time-standardized.csv>

### Sales Data from kaggle

Head off to [Kaggle](https://www.kaggle.com/) and search for
`Geographical Sales` related data. Make both static and interactive maps
with this data. Justify your decisions for type of map.

# References

1.  [Hadley Wickham](http://hadley.nz/), [Danielle
    Navarro](https://djnavarro.net/), and [Thomas Lin
    Pedersen](https://www.data-imaginist.com/), *ggplot2: Elegant
    Graphics for Data Analysis* <https://ggplot2-book.org/maps.html>

2.  Emine Fidan, [Guide to Creating Interactive Maps in
    R](https://bookdown.org/eneminef/DRR_Bookdown/)

3.  Nikita Voevodin, [R, Not the Best
    Practices](https://bookdown.org/voevodin_nv/R_Not_the_Best_Practices/maps.html)

[^1]: Etymology. **From Ancient Greek χώρα (khṓra, "location") + πλῆθος
    (plêthos, "a great number") + English map**. First proposed in 1938
    by American geographer John Kirtland Wright to mean "quantity in
    area," although maps of the type have been used since the early 19th
    century.
