---
title: A Design of Experiments Class
date: "2022-01-31"
author: Arvind Venkatadri
abstract: A Design of Experiments Class
tags:
 - Design of Experiments
 - Randomness
 - Permutation Tests
 - Hypothesis Testing
---

## Slides and Code Links

<a href="/content/labs/doe/index.qmd"> {{< li ifuevrlc scale=25 >}}Code
Lab </a>

## {{< fa envelope >}} Introduction

This is a brief description and analysis of a Design of Experiments
module conducted as a part of the Order and Chaos course, in the
Foundation Studies Program (FSP 2021-2022) at SMI, MAHE, Bangalore.

## Context

A Short Term Memory(STM) Test was the investigative tool used to verify
several Hypotheses that were documented on the subject of STM.

This article describes the statistical analysis that was done with the
readings. In particular, Permutations Tests were used to verify the
effect size for each of *three* parameters that were hypothesized.

For more information, please click on the icon above to look at the Lab
document.

## References

1.  Lawrance, A. J. 1996. "A Design of Experiments Workshop as an
    Introduction to Statistics." American Statistician 50 (2): 156--58.
    doi:10.1080/00031305.1996.10474364.

2.  Ernst, Michael D. 2004. "Permutation Methods: A Basis for Exact
    Inference." Statistical Science 19 (4): 676--85.
    doi:10.1214/088342304000000396.

3.  Pruim R, Kaplan DT, Horton NJ (2017). "The mosaic Package: Helping
    Students to 'Think with Data' Using R." The R Journal, 9(1),
    77--102.
    https://journal.r-project.org/archive/2017/RJ-2017-024/index.html.
