{
  "hash": "c25016cb68739f061703da61584d3590",
  "result": {
    "markdown": "---\ntitle: \"\\U0001F0CF Permutation Test for Two Proportions\"\nauthor: \"Arvind Venkatadri\"\ndate: 10/Nov/2022\ndate-modified: \"2023-01-25\"\nabstract: \"Using Permutation Tests to check the equivalene of two proportions\"\norder: 50\nformat: html\n#fig-format: retina\ncode-fold: true\ncode-summary: Show the Code\ncode-block-border-left: true\ncode-overflow: scroll\ncode-block-bg: \"beige\"\ncode-tools: true\ncode-line-numbers: true\ncode-copy: true\nfig-align: center\nreference-location: margin\ncap-location: margin\nhighlight-style: tango\ndf-print: paged\nsection-divs: true\nnumber-sections: true\nexecute: \n  freeze: auto\ntags:\n- Permutation\n- Monte Carlo Simulation\n- Random Number Generation\n- Distributions\n- Generating Parallel Worlds\nlinks:\n- icon: circle\n  icon_pack: fas\n  name: Orange Tutorial\n  url: \"labs/Data-Analytics/proportions.ows\"\n- icon: sun\n  icon_pack: fas\n  name: Radiant\n  url: \"labs/Data-Analytics/proportions.rda\"\n- icon: r-project\n  icon_pack: fab\n  name: R Tutorial\n  url: \"labs/Data-Analytics/proportions.html\"\n- icon: database\n  icon_pack: fas\n  name: Sample Datasets\n  url: \"labs/Data-Analytics/data/sim-data.zip\"\nslides: \"\"\nurl_code: \"\"\nurl_pdf: \"\"\nurl_slides: \"\"\nurl_video: \"\"\n---\n\n\n\n\n# {{< fa folder-open >}} Slides and Tutorials\n\n| <a href=\"./files/two-props.qmd\"><i class=\"fa-brands      \n      fa-r-project\"></i> R Tutorial</a>                    | <a href=\"./files/two-props.ows\"> <iconify-icon icon=\"fluent-emoji:orange-circle\"></iconify-icon> Orange Tutorial</a> | <a href=\"./files/two-props.rda\"> <i class=\"fa-solid fa-person-rays\"></i> Radiant Tutorial</a>  | <a href=\"./files/data/sim-data.zip\"> <i class=\"fa-solid fa-database\"></i> Datasets</a> |\n|------------------|-------------------|------------------|------------------|\n\n\n\n# Introduction\n\nWe saw from the diagram created by Allen Downey that *there is only one\ntest*! We will now use this philosophy to develop a technique that\nallows us to mechanize several *Statistical Models* in that way, with\nnearly identical code.\n\nWe will use two packages in R, `mosaic` to develop our intuition for what are called **permutation** based statistical tests. (There is also a more recent package called `infer` in R which can do pretty much all of this, including visualization. In my opinion, the code is a little too high-level and does not offer quite the detailed insight that the `mosaic` package does).\n\n\n\n\n# Testing for Two or More Proportions\n\nLet us try a dataset with Qualitative / Categorical data. This is the\nGeneral Social Survey GSS dataset, and we have people with different\nlevels of `Education` stating their opinion on the `Death Penalty`. We\nwant to know if these two Categorical variables have a correlation, i.e.\ncan the opinions in favour of the `Death Penalty` be explained by the\n`Education` level?\n\nSince data is Categorical ( both variables ), we need to take `counts`\nin a table, and then implement a `chi-square test`. In the test, we will\npermute the `Education` variable to see if we can see how significant\nits *effect size* is.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndata(GSS2002)\ninspect(GSS2002)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\ncategorical variables:  \n            name  class levels    n missing\n1         Region factor      7 2765       0\n2         Gender factor      2 2765       0\n3           Race factor      3 2765       0\n4      Education factor      5 2760       5\n5        Marital factor      5 2765       0\n6       Religion factor     13 2746      19\n7          Happy factor      3 1369    1396\n8         Income factor     24 1875     890\n9       PolParty factor      8 2729      36\n10      Politics factor      7 1331    1434\n11     Marijuana factor      2  851    1914\n12  DeathPenalty factor      2 1308    1457\n13        OwnGun factor      3  924    1841\n14        GunLaw factor      2  916    1849\n15 SpendMilitary factor      3 1324    1441\n16     SpendEduc factor      3 1343    1422\n17      SpendEnv factor      3 1322    1443\n18      SpendSci factor      3 1266    1499\n19        Pres00 factor      5 1749    1016\n20      Postlife factor      2 1211    1554\n                                    distribution\n1  North Central (24.7%) ...                    \n2  Female (55.6%), Male (44.4%)                 \n3  White (79.1%), Black (14.8%) ...             \n4  HS (53.8%), Bachelors (16.1%) ...            \n5  Married (45.9%), Never Married (25.6%) ...   \n6  Protestant (53.2%), Catholic (24.5%) ...     \n7  Pretty happy (57.3%) ...                     \n8  40000-49999 (9.1%) ...                       \n9  Ind (19.3%), Not Str Dem (18.9%) ...         \n10 Moderate (39.2%), Conservative (15.8%) ...   \n11 Not legal (64%), Legal (36%)                 \n12 Favor (68.7%), Oppose (31.3%)                \n13 No (65.5%), Yes (33.5%) ...                  \n14 Favor (80.5%), Oppose (19.5%)                \n15 About right (46.5%) ...                      \n16 Too little (73.9%) ...                       \n17 Too little (60%) ...                         \n18 About right (49.7%) ...                      \n19 Bush (50.6%), Gore (44.7%) ...               \n20 Yes (80.5%), No (19.5%)                      \n\nquantitative variables:  \n  name   class min  Q1 median   Q3  max mean  sd    n missing\n1   ID integer   1 692   1383 2074 2765 1383 798 2765       0\n```\n:::\n:::\n\n\nNote how *all* variables are Categorical !! `Education` has five `levels`, and of course `DeathPenalty` has three:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nGSS2002 %>% count(Education)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Education\"],\"name\":[1],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"n\"],\"name\":[2],\"type\":[\"int\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"Left HS\",\"2\":\"400\"},{\"1\":\"HS\",\"2\":\"1485\"},{\"1\":\"Jr Col\",\"2\":\"202\"},{\"1\":\"Bachelors\",\"2\":\"443\"},{\"1\":\"Graduate\",\"2\":\"230\"},{\"1\":\"NA\",\"2\":\"5\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\nGSS2002 %>% count(DeathPenalty)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"DeathPenalty\"],\"name\":[1],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"n\"],\"name\":[2],\"type\":[\"int\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"Favor\",\"2\":\"899\"},{\"1\":\"Oppose\",\"2\":\"409\"},{\"1\":\"NA\",\"2\":\"1457\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nLet us drop NA entries in `Education` and `Death Penalty` and set up a\n**Contingency Table**.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ngss2002 <- GSS2002 %>% \n  dplyr::select(Education, DeathPenalty) %>% \n  tidyr::drop_na(., c(Education, DeathPenalty))\n\n\n\ngss_table <- tally(DeathPenalty ~ Education, data = gss2002)\ngss_table %>% \n  addmargins()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n            Education\nDeathPenalty Left HS   HS Jr Col Bachelors Graduate  Sum\n      Favor      117  511     71       135       64  898\n      Oppose      72  200     16        71       50  409\n      Sum        189  711     87       206      114 1307\n```\n:::\n:::\n\n\n\n\n\n## Contingency Table Plots\n\nThe Contingency Table can be plotted, as we have seen, using a `mosaic` plot using several packages:\n\n::: panel-tabset\n\n### Using `vcd`\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nvcd::mosaic(gss_table, gp = shading_hsv)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-4-1.png){fig-align='center' width=672}\n:::\n:::\n\n\n### Using `ggplot`\n\nNeed a little more work, to convert the Contigency Table into a tibble:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# https://stackoverflow.com/questions/19233365/how-to-create-a-marimekko-mosaic-plot-in-ggplot2\n\ngss_summary <- gss2002 %>%\n  mutate(\n    Education = factor(\n      Education,\n      levels = c(\"Bachelors\", \"Graduate\", \"Jr Col\", \"HS\", \"Left HS\"),\n      labels = c(\"Bachelors\", \"Graduate\", \"Jr Col\", \"HS\", \"Left HS\")\n    ),\n    DeathPenalty = as.factor(DeathPenalty)\n  ) %>%\n  group_by(Education, DeathPenalty) %>%\n  summarise(count = n()) %>% # This is good for a chisq test\n  \n  # Add two more columns to facilitate mosaic/Marrimekko Plot\n  # \n  mutate(edu_count = sum(count), \n         edu_prop = count / sum(count)) %>%\n  ungroup() \n\n###################################\n\n\nggplot(data = gss_summary, aes( x = Education, y = edu_prop)) +\n  \n  geom_bar(aes(width = edu_count, fill = DeathPenalty), \n           stat = \"identity\", \n           position = \"fill\", \n           colour = \"black\") +\n  \n  geom_text(aes(label = scales::percent(edu_prop)), \n            position = position_stack(vjust = 0.5)) +\n\n\n# if labels are desired\n facet_grid(~ Education, scales = \"free_x\", space = \"free_x\") + \n  theme(scale_fill_brewer(palette = \"RdYlGn\")) + \n  # theme(panel.spacing.x = unit(0, \"npc\")) + # if no spacing preferred between bars\n  theme_void() \n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-5-1.png){fig-align='center' width=672}\n:::\n:::\n\n\n### Using `ggmosaic`\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n#library(ggmosaic)\n\nggplot(data = gss2002) +\n  geom_mosaic(aes(x = product(DeathPenalty, Education), fill = DeathPenalty))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/mosaic-plot-1.png){fig-align='center' width=672}\n:::\n:::\n\n\n\n:::\n\n### Observed Statistic: the $X^2$ metric\n\nWhen there are multiple proportions involved, the $X^2$ test is what is\nused.\n\n::: panel-tabset\n\n#### Code\n\nLet us now perform the base `chisq test`: We need a `table` and then the\n`chisq` test: We see that our observed $X^2 = 23.45$:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# gss_table <- tally(DeathPenalty ~ Education, data = gss2002)\n# gss_table\n\n# Get the observed chi-square statistic\nobservedChi2 <- mosaic::chisq(tally(DeathPenalty ~ Education, data = gss2002))\nobservedChi2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nX.squared \n       23 \n```\n:::\n\n```{.r .cell-code}\n# Actual chi-square test\nstats::chisq.test(tally(DeathPenalty ~ Education, data = gss2002))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's Chi-squared test\n\ndata:  tally(DeathPenalty ~ Education, data = gss2002)\nX-squared = 23, df = 4, p-value = 0.0001\n```\n:::\n:::\n\n\n#### Intuitive Explanation\n\nLet us look at the Contingency Table that we have:\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n```\n            Education\nDeathPenalty Left HS   HS Jr Col Bachelors Graduate  Sum\n      Favor      117  511     71       135       64  898\n      Oppose      72  200     16        71       50  409\n      Sum        189  711     87       206      114 1307\n```\n:::\n:::\n\n\n\nIn the chi-square test, we check whether the two ( or more ) categorical\nvariables are independent. To do this we perform a simple check on the\nContingency Table. We first *re-compute* the totals in each row and\ncolumn, based on what we could **expect** if there was independence (NULL Hypothesis). If the two variables were independent, then there should be **no difference** between real and expected scores.\\\nHow do we know what scores to expect?\\\nConsider the entry in location (1,1): 117.\\\nThe number of **expected** entries there is probability of an entry\nlanding in that square times the total number of entries:\n\n\n$$\n\n\\begin{align}\n\\text{Expected Value at [1,1]} &=\\\\\n&= prob_{row_1} * prob_{col_1} * \\text{Overall Total}\\\\\n&= \\frac{\\text{row_1 total}}{\\text{Overall Total}} *\\frac{\\text{col_1 total}}{\\text{Overall Total}} * \\text{Overall Total}\\\\\n&= \\frac{898}{1307} * \\frac{189}{1307} * 1307\\\\\n&= 129.65\n\\end{align}\n\n$$ \n\n\n\n\nProceeding in this way for all the 15 entries in the Contingency\nTable, we get the \"Expected\" Contingency Table:\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n```\n            Education\nDeathPenalty Left HS   HS Jr Col Bachelors Graduate  Sum\n      Favor      117  511     71       135       64  898\n      Oppose      72  200     16        71       50  409\n      Sum        189  711     87       206      114 1307\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n            Education\nDeathPenalty Left HS   HS Jr Col Bachelors Graduate  Sum\n      Favor      130  489     60       142       78  898\n      Oppose      59  222     27        64       36  409\n      Sum        189  711     87       206      114 1307\n```\n:::\n:::\n\n\n\nThe $X^2$ statistic is sum of squared differences between `Observed` and `Expected` scores, scaled by the `Expected Scores`. For location [1,1] this would be: $(117-130)^2/189$. Do try to compute all of these and the $X^2$ statistic by hand !!\n\n\n:::\n\n### Hypotheses Definition\n\nWhat would our Hypotheses be?\n\n$$ \n\nH_0: \\text{Education does not affect Votes on Death Penalty}\\\\\n\nH_a: \\text{Education affects votes on Death Penalty}\\\\\n\n\n$$ \n\n\n### Permutation Test for `Education`\n\nWe should now repeat the test with permutations on `Education`:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nnull_chisq <- do(10000) * chisq.test(tally(DeathPenalty ~ shuffle(Education), data = gss2002))\n\nhead(null_chisq)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"X.squared\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"df\"],\"name\":[2],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"p.value\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"method\"],\"name\":[4],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"alternative\"],\"name\":[5],\"type\":[\"lgl\"],\"align\":[\"right\"]},{\"label\":[\"data\"],\"name\":[6],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\".row\"],\"name\":[7],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\".index\"],\"name\":[8],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"3.1\",\"2\":\"4\",\"3\":\"0.547\",\"4\":\"Pearson's Chi-squared test\",\"5\":\"NA\",\"6\":\"tally(DeathPenalty ~ shuffle(Education), data = gss2002)\",\"7\":\"1\",\"8\":\"1\",\"_rn_\":\"X-squared...1\"},{\"1\":\"12.8\",\"2\":\"4\",\"3\":\"0.012\",\"4\":\"Pearson's Chi-squared test\",\"5\":\"NA\",\"6\":\"tally(DeathPenalty ~ shuffle(Education), data = gss2002)\",\"7\":\"1\",\"8\":\"2\",\"_rn_\":\"X-squared...2\"},{\"1\":\"1.5\",\"2\":\"4\",\"3\":\"0.822\",\"4\":\"Pearson's Chi-squared test\",\"5\":\"NA\",\"6\":\"tally(DeathPenalty ~ shuffle(Education), data = gss2002)\",\"7\":\"1\",\"8\":\"3\",\"_rn_\":\"X-squared...3\"},{\"1\":\"4.1\",\"2\":\"4\",\"3\":\"0.392\",\"4\":\"Pearson's Chi-squared test\",\"5\":\"NA\",\"6\":\"tally(DeathPenalty ~ shuffle(Education), data = gss2002)\",\"7\":\"1\",\"8\":\"4\",\"_rn_\":\"X-squared...4\"},{\"1\":\"1.7\",\"2\":\"4\",\"3\":\"0.789\",\"4\":\"Pearson's Chi-squared test\",\"5\":\"NA\",\"6\":\"tally(DeathPenalty ~ shuffle(Education), data = gss2002)\",\"7\":\"1\",\"8\":\"5\",\"_rn_\":\"X-squared...5\"},{\"1\":\"5.9\",\"2\":\"4\",\"3\":\"0.206\",\"4\":\"Pearson's Chi-squared test\",\"5\":\"NA\",\"6\":\"tally(DeathPenalty ~ shuffle(Education), data = gss2002)\",\"7\":\"1\",\"8\":\"6\",\"_rn_\":\"X-squared...6\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\ngf_histogram( ~ X.squared, data = null_chisq) %>% \n  gf_vline(xintercept = observedChi2, color = \"red\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-9-1.png){fig-align='center' width=672}\n:::\n\n```{.r .cell-code}\nprop1(~ X.squared >= observedChi2, data = null_chisq)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nprop_TRUE \n   0.0003 \n```\n:::\n:::\n\n\nThe `p-value` is well below our threshold of $0.05\\%$, so we would\nconclude that `Education` has a significant effect on `DeathPenalty`\nopinion! \n\n## Conclusion\n\nWhy would a permutation test be a good idea here? \n\nIn our basic X^2 test, we calculate the test statistic of X^2 and look up a *theoretical* null distribution for that statistic, and see how unlikely our observed value is. \n\nWith a permutation test, there are *no assumptions* of the null distribution: this is computed based on real data. We note in passing that, in this case, since the number of `cases` in each cell of the Contingency Table are fairly high ( >= 5) the resulting NULL distribution is of the $X^2$ variety. \n\n## References\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../../../../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\r\n<script src=\"../../../../../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}