{
  "hash": "59c90a03d33d53f71abe1bcbe8176100",
  "result": {
    "markdown": "---\ntitle: \"Linear Models: Comparing Proportions\"\nauthor: \"Arvind Venkatadri\"\ndate: 25/Nov/2022\ndate-modified: \"2023-01-15\"\norder: 30\nformat: html\n#fig-format: retina\ncode-fold: true\ncode-summary: Show the Code\ncode-tools: true\ncode-line-numbers: true\ncode-overflow: wrap\ncode-copy: true\nfig-align: center\nreference-location: margin\ncap-location: margin\nhighlight-style: dracula\ndf-print: paged\nsection-divs: true\nnumber-sections: true\nexecute: \n  freeze: auto\nkeywords: Statistics ; Tests; p-value; Feynman Technique\nabstract:  This module is intended to assist with making statistically significant insights that drive business decisions. This document deals with the basics of stats. The method followed is that of Jonas Lindoloev, wherein every stat test is treated as a linear model y = mx + c.\n---\n\n\n\n\n## A Workflow in Orange\n\n## A Workflow in Radiant\n\n## A Workflow in R\n\n# References\n\n1.  *Common statistical tests are linear models (or: how to teach\n    stats)* by [Jonas Kristoffer\n    Lindeløv](https://lindeloev.github.io/tests-as-linear/)\n2.  [CheatSheet](https://lindeloev.github.io/tests-as-linear/linear_tests_cheat_sheet.pdf)\n3.  *Common statistical tests are linear models: a work through* by\n    [Steve Doogue](https://steverxd.github.io/Stat_tests/)\n4.  [Jeffrey Walker \"Elements of Statistical Modeling for Experimental\n    Biology\"](https://www.middleprofessor.com/files/applied-biostatistics_bookdown/_book/)\n5.  Text: Diez, David M & Barr, Christopher D & Çetinkaya-Rundel, Mine:\n    [OpenIntro Statistics](https://www.openintro.org/book/os/)\n6.  Modern Statistics with R: From wrangling and exploring data to\n    inference and predictive modelling by [Måns\n    Thulin](http://www.modernstatisticswithr.com/)\n\n# Structure of this document\n\nWe will follow the following structure: Each kind of Test is described\nin a separate Chapter. The Test *Model* is laid out in formula\n$y = mx + c$ and in *Code*.\n\nThe Structure looks like this:\n\n## Test {.tabset}\n\n### Model\n\nExplanation, formula etc.\n\n### Code\n\nWith Toy Data; Graphs\n\n### Example\n\nWith another \"real world\" data set; Graphs\n\n# Data\n\n## Sample Values\n\nMost examples in this exposition are based on three \"imaginary\" samples,\n$x, y, y2$. Each is normally distributed and made up of 50 observations.\n\nWe start by creating a function that will allow us to produce samples of\na given size (N) with a specified mean (mu) and standard deviation (sd):\nNote: this gives a *matrix* of numbers, as opposed to a vector using\n`rnorm` by itself. The data are created both in vector form and tibble\nform for flexibility of use in diverse packages and formulae in what\nfollows.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrnorm_fixed  <- function(N, mu = 0, sd = 1) {\n  scale(rnorm(N))* sd + mu\n}\n```\n:::\n\n\nWe create three variables: x ( explanatory) and y, y2 ( dependent ).\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(40) # for replication\n\n# Data as vectors ( for t.tests etc)\nx <- rnorm_fixed(50, mu = 0.0, sd = 1) #explanatory\ny <- rnorm_fixed(50, mu = 0.3, sd = 2) # dependent #1\ny2 <- rnorm_fixed(50, mu = 0.5, sd = 1.5) # dependent #2\n\n# Make a tibble with all variables\nmydata_wide <- tibble(x = x, y = y, y2 = y2)\n\n# Long form data\nmydata_long <- \n  mydata_wide %>%\n  pivot_longer(., cols = c(x,y,y2), \n               names_to = \"group\", \n               values_to = \"value\")\n\n# Long form data with only dependent variables\nmydata_long_y <- \n  mydata_wide %>% \n  select(-x) %>% \n  pivot_longer(., cols = c(y,y2), \n               names_to = \"group\", \n               values_to = \"value\")\nmydata_wide\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"x\"],\"name\":[1],\"type\":[\"dbl[,1]\"],\"align\":[\"right\"]},{\"label\":[\"y\"],\"name\":[2],\"type\":[\"dbl[,1]\"],\"align\":[\"right\"]},{\"label\":[\"y2\"],\"name\":[3],\"type\":[\"dbl[,1]\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"0.42678011\",\"2\":\"1.98488355\",\"3\":\"0.10303468\"},{\"1\":\"0.44408399\",\"2\":\"1.27130904\",\"3\":\"-0.28089065\"},{\"1\":\"-0.82789086\",\"2\":\"-0.94427745\",\"3\":\"0.62388864\"},{\"1\":\"-0.79925305\",\"2\":\"0.10328425\",\"3\":\"5.42679005\"},{\"1\":\"-0.32313106\",\"2\":\"2.19041969\",\"3\":\"0.16807478\"},{\"1\":\"-1.24462433\",\"2\":\"0.19192798\",\"3\":\"-0.54936141\"},{\"1\":\"-1.35506516\",\"2\":\"4.81186172\",\"3\":\"0.30919557\"},{\"1\":\"1.61563907\",\"2\":\"1.55169550\",\"3\":\"-0.99039138\"},{\"1\":\"-0.29189503\",\"2\":\"3.35737558\",\"3\":\"-0.17200537\"},{\"1\":\"-1.24940474\",\"2\":\"1.92492196\",\"3\":\"-0.15832838\"},{\"1\":\"-0.08659233\",\"2\":\"-2.88047669\",\"3\":\"0.85387666\"},{\"1\":\"-1.17065349\",\"2\":\"1.75053169\",\"3\":\"3.33911133\"},{\"1\":\"0.73756421\",\"2\":\"-1.08428013\",\"3\":\"-1.88393968\"},{\"1\":\"-0.48316590\",\"2\":\"0.96031018\",\"3\":\"2.48425274\"},{\"1\":\"0.40328291\",\"2\":\"-1.54016895\",\"3\":\"-0.04867594\"},{\"1\":\"0.91641886\",\"2\":\"-1.24357666\",\"3\":\"-0.61515773\"},{\"1\":\"0.41673257\",\"2\":\"0.03193645\",\"3\":\"-0.28681098\"},{\"1\":\"0.33137777\",\"2\":\"-1.30918647\",\"3\":\"-0.12350146\"},{\"1\":\"1.57677526\",\"2\":\"-0.99658718\",\"3\":\"0.29936602\"},{\"1\":\"-0.99289810\",\"2\":\"1.42150401\",\"3\":\"-1.06763475\"},{\"1\":\"1.22460582\",\"2\":\"-0.90365732\",\"3\":\"0.12124860\"},{\"1\":\"-0.57899018\",\"2\":\"2.94554205\",\"3\":\"-0.40094019\"},{\"1\":\"1.49026764\",\"2\":\"2.57375451\",\"3\":\"-1.55553594\"},{\"1\":\"-1.06533835\",\"2\":\"-1.21795541\",\"3\":\"-0.51902218\"},{\"1\":\"-1.39136994\",\"2\":\"-2.10136309\",\"3\":\"-0.24857353\"},{\"1\":\"0.66547299\",\"2\":\"0.90556693\",\"3\":\"1.35671958\"},{\"1\":\"-1.53224607\",\"2\":\"0.53146356\",\"3\":\"0.14529688\"},{\"1\":\"0.29011158\",\"2\":\"0.90084614\",\"3\":\"0.83560170\"},{\"1\":\"0.69239937\",\"2\":\"0.12687786\",\"3\":\"2.29182497\"},{\"1\":\"-1.76053733\",\"2\":\"2.64999575\",\"3\":\"2.73673094\"},{\"1\":\"0.72082239\",\"2\":\"0.13435947\",\"3\":\"0.27574827\"},{\"1\":\"-1.22395587\",\"2\":\"-2.78065291\",\"3\":\"3.14550409\"},{\"1\":\"-0.75311013\",\"2\":\"1.96202837\",\"3\":\"0.59938464\"},{\"1\":\"1.32801392\",\"2\":\"-4.25541004\",\"3\":\"1.04460392\"},{\"1\":\"-0.24174865\",\"2\":\"0.51517469\",\"3\":\"-0.68821620\"},{\"1\":\"0.55292812\",\"2\":\"0.32962526\",\"3\":\"1.15201767\"},{\"1\":\"-1.38976342\",\"2\":\"0.18227394\",\"3\":\"-1.86691141\"},{\"1\":\"0.20633230\",\"2\":\"0.76029377\",\"3\":\"4.27233650\"},{\"1\":\"-0.31920849\",\"2\":\"3.55063527\",\"3\":\"0.45077005\"},{\"1\":\"0.78482776\",\"2\":\"-0.56564635\",\"3\":\"-1.70953625\"},{\"1\":\"1.23964789\",\"2\":\"-2.88080049\",\"3\":\"0.84694745\"},{\"1\":\"0.27462181\",\"2\":\"3.04164950\",\"3\":\"-0.03903472\"},{\"1\":\"1.89759493\",\"2\":\"-1.29407455\",\"3\":\"1.11956044\"},{\"1\":\"-0.19262565\",\"2\":\"-3.42396604\",\"3\":\"1.05156905\"},{\"1\":\"-1.41365701\",\"2\":\"-1.75335473\",\"3\":\"1.49593530\"},{\"1\":\"0.35118649\",\"2\":\"1.82462838\",\"3\":\"1.86447305\"},{\"1\":\"1.45121334\",\"2\":\"-2.37113604\",\"3\":\"1.33013723\"},{\"1\":\"1.17029448\",\"2\":\"2.34340037\",\"3\":\"-0.14230534\"},{\"1\":\"-0.83901696\",\"2\":\"1.86633352\",\"3\":\"-0.39773459\"},{\"1\":\"0.31714653\",\"2\":\"-0.14984045\",\"3\":\"-0.99949269\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\nmydata_long\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"group\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"value\"],\"name\":[2],\"type\":[\"dbl[,1]\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"x\",\"2\":\"0.42678011\"},{\"1\":\"y\",\"2\":\"1.98488355\"},{\"1\":\"y2\",\"2\":\"0.10303468\"},{\"1\":\"x\",\"2\":\"0.44408399\"},{\"1\":\"y\",\"2\":\"1.27130904\"},{\"1\":\"y2\",\"2\":\"-0.28089065\"},{\"1\":\"x\",\"2\":\"-0.82789086\"},{\"1\":\"y\",\"2\":\"-0.94427745\"},{\"1\":\"y2\",\"2\":\"0.62388864\"},{\"1\":\"x\",\"2\":\"-0.79925305\"},{\"1\":\"y\",\"2\":\"0.10328425\"},{\"1\":\"y2\",\"2\":\"5.42679005\"},{\"1\":\"x\",\"2\":\"-0.32313106\"},{\"1\":\"y\",\"2\":\"2.19041969\"},{\"1\":\"y2\",\"2\":\"0.16807478\"},{\"1\":\"x\",\"2\":\"-1.24462433\"},{\"1\":\"y\",\"2\":\"0.19192798\"},{\"1\":\"y2\",\"2\":\"-0.54936141\"},{\"1\":\"x\",\"2\":\"-1.35506516\"},{\"1\":\"y\",\"2\":\"4.81186172\"},{\"1\":\"y2\",\"2\":\"0.30919557\"},{\"1\":\"x\",\"2\":\"1.61563907\"},{\"1\":\"y\",\"2\":\"1.55169550\"},{\"1\":\"y2\",\"2\":\"-0.99039138\"},{\"1\":\"x\",\"2\":\"-0.29189503\"},{\"1\":\"y\",\"2\":\"3.35737558\"},{\"1\":\"y2\",\"2\":\"-0.17200537\"},{\"1\":\"x\",\"2\":\"-1.24940474\"},{\"1\":\"y\",\"2\":\"1.92492196\"},{\"1\":\"y2\",\"2\":\"-0.15832838\"},{\"1\":\"x\",\"2\":\"-0.08659233\"},{\"1\":\"y\",\"2\":\"-2.88047669\"},{\"1\":\"y2\",\"2\":\"0.85387666\"},{\"1\":\"x\",\"2\":\"-1.17065349\"},{\"1\":\"y\",\"2\":\"1.75053169\"},{\"1\":\"y2\",\"2\":\"3.33911133\"},{\"1\":\"x\",\"2\":\"0.73756421\"},{\"1\":\"y\",\"2\":\"-1.08428013\"},{\"1\":\"y2\",\"2\":\"-1.88393968\"},{\"1\":\"x\",\"2\":\"-0.48316590\"},{\"1\":\"y\",\"2\":\"0.96031018\"},{\"1\":\"y2\",\"2\":\"2.48425274\"},{\"1\":\"x\",\"2\":\"0.40328291\"},{\"1\":\"y\",\"2\":\"-1.54016895\"},{\"1\":\"y2\",\"2\":\"-0.04867594\"},{\"1\":\"x\",\"2\":\"0.91641886\"},{\"1\":\"y\",\"2\":\"-1.24357666\"},{\"1\":\"y2\",\"2\":\"-0.61515773\"},{\"1\":\"x\",\"2\":\"0.41673257\"},{\"1\":\"y\",\"2\":\"0.03193645\"},{\"1\":\"y2\",\"2\":\"-0.28681098\"},{\"1\":\"x\",\"2\":\"0.33137777\"},{\"1\":\"y\",\"2\":\"-1.30918647\"},{\"1\":\"y2\",\"2\":\"-0.12350146\"},{\"1\":\"x\",\"2\":\"1.57677526\"},{\"1\":\"y\",\"2\":\"-0.99658718\"},{\"1\":\"y2\",\"2\":\"0.29936602\"},{\"1\":\"x\",\"2\":\"-0.99289810\"},{\"1\":\"y\",\"2\":\"1.42150401\"},{\"1\":\"y2\",\"2\":\"-1.06763475\"},{\"1\":\"x\",\"2\":\"1.22460582\"},{\"1\":\"y\",\"2\":\"-0.90365732\"},{\"1\":\"y2\",\"2\":\"0.12124860\"},{\"1\":\"x\",\"2\":\"-0.57899018\"},{\"1\":\"y\",\"2\":\"2.94554205\"},{\"1\":\"y2\",\"2\":\"-0.40094019\"},{\"1\":\"x\",\"2\":\"1.49026764\"},{\"1\":\"y\",\"2\":\"2.57375451\"},{\"1\":\"y2\",\"2\":\"-1.55553594\"},{\"1\":\"x\",\"2\":\"-1.06533835\"},{\"1\":\"y\",\"2\":\"-1.21795541\"},{\"1\":\"y2\",\"2\":\"-0.51902218\"},{\"1\":\"x\",\"2\":\"-1.39136994\"},{\"1\":\"y\",\"2\":\"-2.10136309\"},{\"1\":\"y2\",\"2\":\"-0.24857353\"},{\"1\":\"x\",\"2\":\"0.66547299\"},{\"1\":\"y\",\"2\":\"0.90556693\"},{\"1\":\"y2\",\"2\":\"1.35671958\"},{\"1\":\"x\",\"2\":\"-1.53224607\"},{\"1\":\"y\",\"2\":\"0.53146356\"},{\"1\":\"y2\",\"2\":\"0.14529688\"},{\"1\":\"x\",\"2\":\"0.29011158\"},{\"1\":\"y\",\"2\":\"0.90084614\"},{\"1\":\"y2\",\"2\":\"0.83560170\"},{\"1\":\"x\",\"2\":\"0.69239937\"},{\"1\":\"y\",\"2\":\"0.12687786\"},{\"1\":\"y2\",\"2\":\"2.29182497\"},{\"1\":\"x\",\"2\":\"-1.76053733\"},{\"1\":\"y\",\"2\":\"2.64999575\"},{\"1\":\"y2\",\"2\":\"2.73673094\"},{\"1\":\"x\",\"2\":\"0.72082239\"},{\"1\":\"y\",\"2\":\"0.13435947\"},{\"1\":\"y2\",\"2\":\"0.27574827\"},{\"1\":\"x\",\"2\":\"-1.22395587\"},{\"1\":\"y\",\"2\":\"-2.78065291\"},{\"1\":\"y2\",\"2\":\"3.14550409\"},{\"1\":\"x\",\"2\":\"-0.75311013\"},{\"1\":\"y\",\"2\":\"1.96202837\"},{\"1\":\"y2\",\"2\":\"0.59938464\"},{\"1\":\"x\",\"2\":\"1.32801392\"},{\"1\":\"y\",\"2\":\"-4.25541004\"},{\"1\":\"y2\",\"2\":\"1.04460392\"},{\"1\":\"x\",\"2\":\"-0.24174865\"},{\"1\":\"y\",\"2\":\"0.51517469\"},{\"1\":\"y2\",\"2\":\"-0.68821620\"},{\"1\":\"x\",\"2\":\"0.55292812\"},{\"1\":\"y\",\"2\":\"0.32962526\"},{\"1\":\"y2\",\"2\":\"1.15201767\"},{\"1\":\"x\",\"2\":\"-1.38976342\"},{\"1\":\"y\",\"2\":\"0.18227394\"},{\"1\":\"y2\",\"2\":\"-1.86691141\"},{\"1\":\"x\",\"2\":\"0.20633230\"},{\"1\":\"y\",\"2\":\"0.76029377\"},{\"1\":\"y2\",\"2\":\"4.27233650\"},{\"1\":\"x\",\"2\":\"-0.31920849\"},{\"1\":\"y\",\"2\":\"3.55063527\"},{\"1\":\"y2\",\"2\":\"0.45077005\"},{\"1\":\"x\",\"2\":\"0.78482776\"},{\"1\":\"y\",\"2\":\"-0.56564635\"},{\"1\":\"y2\",\"2\":\"-1.70953625\"},{\"1\":\"x\",\"2\":\"1.23964789\"},{\"1\":\"y\",\"2\":\"-2.88080049\"},{\"1\":\"y2\",\"2\":\"0.84694745\"},{\"1\":\"x\",\"2\":\"0.27462181\"},{\"1\":\"y\",\"2\":\"3.04164950\"},{\"1\":\"y2\",\"2\":\"-0.03903472\"},{\"1\":\"x\",\"2\":\"1.89759493\"},{\"1\":\"y\",\"2\":\"-1.29407455\"},{\"1\":\"y2\",\"2\":\"1.11956044\"},{\"1\":\"x\",\"2\":\"-0.19262565\"},{\"1\":\"y\",\"2\":\"-3.42396604\"},{\"1\":\"y2\",\"2\":\"1.05156905\"},{\"1\":\"x\",\"2\":\"-1.41365701\"},{\"1\":\"y\",\"2\":\"-1.75335473\"},{\"1\":\"y2\",\"2\":\"1.49593530\"},{\"1\":\"x\",\"2\":\"0.35118649\"},{\"1\":\"y\",\"2\":\"1.82462838\"},{\"1\":\"y2\",\"2\":\"1.86447305\"},{\"1\":\"x\",\"2\":\"1.45121334\"},{\"1\":\"y\",\"2\":\"-2.37113604\"},{\"1\":\"y2\",\"2\":\"1.33013723\"},{\"1\":\"x\",\"2\":\"1.17029448\"},{\"1\":\"y\",\"2\":\"2.34340037\"},{\"1\":\"y2\",\"2\":\"-0.14230534\"},{\"1\":\"x\",\"2\":\"-0.83901696\"},{\"1\":\"y\",\"2\":\"1.86633352\"},{\"1\":\"y2\",\"2\":\"-0.39773459\"},{\"1\":\"x\",\"2\":\"0.31714653\"},{\"1\":\"y\",\"2\":\"-0.14984045\"},{\"1\":\"y2\",\"2\":\"-0.99949269\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\nmydata_long_y\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"group\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"value\"],\"name\":[2],\"type\":[\"dbl[,1]\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"y\",\"2\":\"1.98488355\"},{\"1\":\"y2\",\"2\":\"0.10303468\"},{\"1\":\"y\",\"2\":\"1.27130904\"},{\"1\":\"y2\",\"2\":\"-0.28089065\"},{\"1\":\"y\",\"2\":\"-0.94427745\"},{\"1\":\"y2\",\"2\":\"0.62388864\"},{\"1\":\"y\",\"2\":\"0.10328425\"},{\"1\":\"y2\",\"2\":\"5.42679005\"},{\"1\":\"y\",\"2\":\"2.19041969\"},{\"1\":\"y2\",\"2\":\"0.16807478\"},{\"1\":\"y\",\"2\":\"0.19192798\"},{\"1\":\"y2\",\"2\":\"-0.54936141\"},{\"1\":\"y\",\"2\":\"4.81186172\"},{\"1\":\"y2\",\"2\":\"0.30919557\"},{\"1\":\"y\",\"2\":\"1.55169550\"},{\"1\":\"y2\",\"2\":\"-0.99039138\"},{\"1\":\"y\",\"2\":\"3.35737558\"},{\"1\":\"y2\",\"2\":\"-0.17200537\"},{\"1\":\"y\",\"2\":\"1.92492196\"},{\"1\":\"y2\",\"2\":\"-0.15832838\"},{\"1\":\"y\",\"2\":\"-2.88047669\"},{\"1\":\"y2\",\"2\":\"0.85387666\"},{\"1\":\"y\",\"2\":\"1.75053169\"},{\"1\":\"y2\",\"2\":\"3.33911133\"},{\"1\":\"y\",\"2\":\"-1.08428013\"},{\"1\":\"y2\",\"2\":\"-1.88393968\"},{\"1\":\"y\",\"2\":\"0.96031018\"},{\"1\":\"y2\",\"2\":\"2.48425274\"},{\"1\":\"y\",\"2\":\"-1.54016895\"},{\"1\":\"y2\",\"2\":\"-0.04867594\"},{\"1\":\"y\",\"2\":\"-1.24357666\"},{\"1\":\"y2\",\"2\":\"-0.61515773\"},{\"1\":\"y\",\"2\":\"0.03193645\"},{\"1\":\"y2\",\"2\":\"-0.28681098\"},{\"1\":\"y\",\"2\":\"-1.30918647\"},{\"1\":\"y2\",\"2\":\"-0.12350146\"},{\"1\":\"y\",\"2\":\"-0.99658718\"},{\"1\":\"y2\",\"2\":\"0.29936602\"},{\"1\":\"y\",\"2\":\"1.42150401\"},{\"1\":\"y2\",\"2\":\"-1.06763475\"},{\"1\":\"y\",\"2\":\"-0.90365732\"},{\"1\":\"y2\",\"2\":\"0.12124860\"},{\"1\":\"y\",\"2\":\"2.94554205\"},{\"1\":\"y2\",\"2\":\"-0.40094019\"},{\"1\":\"y\",\"2\":\"2.57375451\"},{\"1\":\"y2\",\"2\":\"-1.55553594\"},{\"1\":\"y\",\"2\":\"-1.21795541\"},{\"1\":\"y2\",\"2\":\"-0.51902218\"},{\"1\":\"y\",\"2\":\"-2.10136309\"},{\"1\":\"y2\",\"2\":\"-0.24857353\"},{\"1\":\"y\",\"2\":\"0.90556693\"},{\"1\":\"y2\",\"2\":\"1.35671958\"},{\"1\":\"y\",\"2\":\"0.53146356\"},{\"1\":\"y2\",\"2\":\"0.14529688\"},{\"1\":\"y\",\"2\":\"0.90084614\"},{\"1\":\"y2\",\"2\":\"0.83560170\"},{\"1\":\"y\",\"2\":\"0.12687786\"},{\"1\":\"y2\",\"2\":\"2.29182497\"},{\"1\":\"y\",\"2\":\"2.64999575\"},{\"1\":\"y2\",\"2\":\"2.73673094\"},{\"1\":\"y\",\"2\":\"0.13435947\"},{\"1\":\"y2\",\"2\":\"0.27574827\"},{\"1\":\"y\",\"2\":\"-2.78065291\"},{\"1\":\"y2\",\"2\":\"3.14550409\"},{\"1\":\"y\",\"2\":\"1.96202837\"},{\"1\":\"y2\",\"2\":\"0.59938464\"},{\"1\":\"y\",\"2\":\"-4.25541004\"},{\"1\":\"y2\",\"2\":\"1.04460392\"},{\"1\":\"y\",\"2\":\"0.51517469\"},{\"1\":\"y2\",\"2\":\"-0.68821620\"},{\"1\":\"y\",\"2\":\"0.32962526\"},{\"1\":\"y2\",\"2\":\"1.15201767\"},{\"1\":\"y\",\"2\":\"0.18227394\"},{\"1\":\"y2\",\"2\":\"-1.86691141\"},{\"1\":\"y\",\"2\":\"0.76029377\"},{\"1\":\"y2\",\"2\":\"4.27233650\"},{\"1\":\"y\",\"2\":\"3.55063527\"},{\"1\":\"y2\",\"2\":\"0.45077005\"},{\"1\":\"y\",\"2\":\"-0.56564635\"},{\"1\":\"y2\",\"2\":\"-1.70953625\"},{\"1\":\"y\",\"2\":\"-2.88080049\"},{\"1\":\"y2\",\"2\":\"0.84694745\"},{\"1\":\"y\",\"2\":\"3.04164950\"},{\"1\":\"y2\",\"2\":\"-0.03903472\"},{\"1\":\"y\",\"2\":\"-1.29407455\"},{\"1\":\"y2\",\"2\":\"1.11956044\"},{\"1\":\"y\",\"2\":\"-3.42396604\"},{\"1\":\"y2\",\"2\":\"1.05156905\"},{\"1\":\"y\",\"2\":\"-1.75335473\"},{\"1\":\"y2\",\"2\":\"1.49593530\"},{\"1\":\"y\",\"2\":\"1.82462838\"},{\"1\":\"y2\",\"2\":\"1.86447305\"},{\"1\":\"y\",\"2\":\"-2.37113604\"},{\"1\":\"y2\",\"2\":\"1.33013723\"},{\"1\":\"y\",\"2\":\"2.34340037\"},{\"1\":\"y2\",\"2\":\"-0.14230534\"},{\"1\":\"y\",\"2\":\"1.86633352\"},{\"1\":\"y2\",\"2\":\"-0.39773459\"},{\"1\":\"y\",\"2\":\"-0.14984045\"},{\"1\":\"y2\",\"2\":\"-0.99949269\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n## \"Signed Rank\" Values\n\nMost statistical tests use the **actual values** of the data variables.\nHowever, in some *non-parametric* statistical tests, the data are used\nin **rank-transformed** sense/order. In some cases the **signed-rank**\nof the data values is used instead of the data itself.\n\nSigned Rank is calculated as follows:\\\n1. Take the absolute value of each observation in a sample\\\n2. Place the <u>*ranks*</u> in order of (absolute magnitude). The\nsmallest number has *rank = 1* and so on.\\\n3. Give each of the ranks the sign of the original observation ( + or -\n)\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsigned_rank <- function(x) {sign(x) * rank(abs(x))}\n```\n:::\n\n\n## Plotting Original and Signed Rank Data\n\nA quick plot:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\np1 <- ggplot(mydata_long,aes(x = group, y = value)) +\n  geom_jitter(width = 0.02, height = 0,aes(colour = group), size = 4) +\n  geom_segment(data = mydata_wide, aes(y = 0, yend = 0, \n                                       x = .75, \n                                       xend = 1.25 )) + \n  geom_text(aes(x = 1, y = 0.5, label = \"0\")) +\n  geom_segment(data = mydata_wide, aes(y = 0.3, yend = 0.3, \n                                       x = 1.75 , \n                                       xend = 2.25 )) + \n  geom_text(aes(x = 2, y = 0.6, label = \"0.3\")) +\n  geom_segment(data = mydata_wide, aes(y = 0.5, yend = 0.5, \n                                       x = 2.75, \n                                       xend = 3.25 )) + \n  geom_text(aes(x = 3, y = 0.8, label = \"0.5\")) +\n  labs(title = \"Original Data\") +\n  ylab(\"Response Variable\")\n\np2 <- mydata_long %>% \n  group_by(group) %>% \n  mutate( s_value = signed_rank(value)) %>% \n  ggplot(., aes(x = group, y = s_value)) + \n  geom_jitter(width = 0.02, height = 0,aes(colour = group), size = 4) + \n  stat_summary(fun = \"mean\", geom = \"point\", colour = \"red\", \n               size = 8) + \n  labs(title = \"Signed Rank of Data\") +\n  ylab(\"Signed Rank of Response Variable\")\n\npatchwork::wrap_plots(p1,p2, nrow = 1, guides = \"collect\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/data_plots-1.png){fig-align='center' width=672}\n:::\n:::\n\n\n## How does Sign-Rank data work?\n\nTBD: need to add some explanation here.\n\n# The Linear ( Regression ) Model {.tabset}\n\nThe premise here is that many common statistical tests are special cases\nof the linear model.\n\nA linear model estimates the relationship between one *continuous* or\n*ordinal* variable (dependent variable or \"response\" ) and one or more\nother variables ( explanatory variable or \"predictors\" ). It is assumed\nthat the relationship is linear:\n\n$$\ny = \\beta_0 + \\beta_1 *x\n$$ $\\beta_0$ is the *intercept* and $\\beta_1$ is the slope of the linear\nfit, that **predicts** the value of y based the value of x. Each\nprediction leaves a small \"residual\" error between the actual and\npredicted values. $\\beta_0$ and $\\beta_1$ are calculated based on\nminimizing the *sum of square*s of these residuals, and hence this\nmethod is called \"ordinary least squares\" regression.\n\n![Least Squares](OLS.png)\n\nThe net *area* of all the shaded squares is minimized in the calculation\nof $\\beta_0$ and $\\beta_1$. It is also possible that there is more than\none explanatory variable: this is **multiple regression.**\n\n$$\ny = \\beta_0 + \\beta_1*x_1 + \\beta_2*x_2 ...+ \\beta_n*x_n\n$$\n\nwhere each of the $\\beta_i$ are slopes defining the relationship between\ny and $x_i$. Together, the RHS of that equation defines an n-dimensional\n*plane*.\n\nAs per Lindoloev, many statistical tests, going from one-sample t-tests\nto two-way ANOVA, are special cases of this system.\n\nAlso see [Jeffrey Walker \"A\nlinear-model-can-be-fit-to-data-with-continuous-discrete-or-categorical-x-variables\"](https://www.middleprofessor.com/files/applied-biostatistics_bookdown/_book/intro-linear-models.html#a-linear-model-can-be-fit-to-data-with-continuous-discrete-or-categorical-x-variables)\n\n## Linear Models as Hypothesis Tests\n\nUsing linear models is based on the idea of **Testing of Hypotheses**.\nThe Hypothesis Testing method typically defines a NULL Hypothesis where\nthe statements read as \"**there is no relationship**\" between the\nvariables at hand, explanatory and responses. The Alternative Hypothesis\ntypically states that there *is* a relationship between the variables.\n\nAccordingly, in fitting a linear model, we follow the process as\nfollows:\n\n1.  Make the following hypotheses: $$\n    y = \\beta_0 + \\beta_1 *x \\\\\n    NULL\\ Hypothesis\\ H_0 => x\\ and\\ y\\ are\\ unrelated.\\ (\\beta_1 = 0)\n    $$ $$\n    y = \\beta_0 + \\beta_1 *x \\\\\n    Alternate\\ Hypothesis\\ H_1 => x\\ and\\ y\\ are\\ linearly\\ related\\ (\\beta_1 \\ne 0)\n    $$\n2.  We \"assume\" that $H_0$ is true.\n3.  We calculate $\\beta_1$.\n4.  We then find probability **p** that \\[$\\beta_1 = Estimated\\ Value$\\]\n    **when the NULL Hypothesis** is **assumed** TRUE. This is the\n    **p-value**. If that probability is **p\\>=0.05**, we say we \"cannot\n    reject\" $H_0$ and there is unlikely to be significant linear\n    relationship.\n\nHowever, if **p\\<= 0.05** can we reject the NULL hypothesis, and say\nthat there could be a significant linear relationship,because\n$\\beta_1 = Estimated\\ Value$ by mere chance under $H_0$ is very small.\n\nPheeew !!\n\n## Linear Models in R\n\n`lm()` is the function to create linear models in R. In R we are lazy\nand write :\n\n$$\ny \\sim 1 + x\\\\\nwhich\\ reads\\ like\\\\\ny = 1*number + x* another\\ number\n$$\n\nNote: there are very many ways in which linear models can be coded in R.\nSee [Vito Ricci on\nCRAN.](https://cran.r-project.org/doc/contrib/Ricci-refcard-regression.pdf)\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# using lm()\nlm(y ~ 1 + x, data = mydata_wide) %>% \n  summary() %>%   \n  print(digits = 5)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = y ~ 1 + x, data = mydata_wide)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-3.93980 -1.09967  0.12548  1.27904  3.88372 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)\n(Intercept)  0.30000    0.27799  1.0792   0.2859\nx           -0.46355    0.28081 -1.6507   0.1053\n\nResidual standard error: 1.9657 on 48 degrees of freedom\nMultiple R-squared:  0.05372,\tAdjusted R-squared:  0.034006 \nF-statistic:  2.725 on 1 and 48 DF,  p-value: 0.10532\n```\n:::\n:::\n\n\nSince the *p-value* is \\>=0.05, we *fail to reject the NULL Hypothesis\nthat there is no relationship between x and y*.\n\n## Assumptions in Linear Models\n\n1.  **L**: $\\color{blue}{linear}$ relationship\n2.  **I**: Errors are **independent** (across observations)\n3.  **N**: y is $\\color{red}{normally}$ distributed at each \"level\" of\n    x.  \n4.  **E**: equal variance at all levels of x. No *heteroscedasticity*.\n    ![OLS Assumptions](ols_assumptions.png)\n\nLet us now see which standard statistical tests can be re-formulated as\nLinear Models.\n\n# Tests for Correlation {.tabset}\n\nCorrelation **r** is a measure of *strength* and *direction* of *linear\nassociation* between two variables. **r** is between \\[-1,+1\\], with 0\nimplying no association/correlation.\n\nFrom this definition, the *linear model* lends itself in a\nstraightforward way as a model to interpret *correlation*. Intuitively,\nthe slope of the linear model could be related to the correlation\nbetween y and x.\n\nNow we look at the numbers.\n\n## Pearson Correlation {.tabset}\n\n### Model\n\nThe model for Pearson Correlation tests is exactly the Linear Model:\n\n$$\ny = \\beta_0 + \\beta_1 * x \n\\\\\nH_0: \\beta_1 = 0\n$$\n\nSee the Code section for further insights into the relationship between\nthe Correlation Score and the Slope of the Linear Model.\n\n### Code\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Pearson (built-in test)\ncor <- cor.test(y,x,method = \"pearson\") %>% \n  broom::tidy() %>% select(estimate, p.value)\n\n# Linear Model\nlin <- lm(y ~ 1 + x, data = mydata_wide) %>% \n  broom::tidy() %>% select(estimate, p.value)\n\n# Scaled linear model\nlin_scl <- lm(scale(y) ~ 1 + scale(x), data = mydata_wide) %>% \n  broom::tidy() %>% select(estimate, p.value)\n\nprint(cor)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 2\n  estimate p.value\n     <dbl>   <dbl>\n1   -0.232   0.105\n```\n:::\n\n```{.r .cell-code}\nprint(lin)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 2\n  estimate p.value\n     <dbl>   <dbl>\n1    0.3     0.286\n2   -0.464   0.105\n```\n:::\n\n```{.r .cell-code}\nprint(lin_scl)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 2\n   estimate p.value\n      <dbl>   <dbl>\n1 -9.06e-17   1    \n2 -2.32e- 1   0.105\n```\n:::\n\n```{.r .cell-code}\n# All together\nrbind(cor, lin, lin_scl) %>% print()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 5 × 2\n   estimate p.value\n      <dbl>   <dbl>\n1 -2.32e- 1   0.105\n2  3   e- 1   0.286\n3 -4.64e- 1   0.105\n4 -9.06e-17   1    \n5 -2.32e- 1   0.105\n```\n:::\n:::\n\n\nNotes: 1. The *p-value* for Pearson Correlation and that for the *slope*\nin the linear model is the same ( 0.1053 ). Which means we cannot reject\nthe NULL hypothesis of \"no relationship\".\n\n2.  Here is the relationship between the slope and correlation:\n\n$$\nSlope\\ \\beta_1 = \\frac{sd_y}{sd_x} * r\n$$\n\nWhen both x and y have the same standard deviation, the slope and\ncorrelation are the same. Here, since x has twice the `sd` of y, the\nratio of **slope** = -0.4635533 to **r** = -0.2317767 is\n0.5. Hence a linear model using `scale()` for both variables will show\nslope = **r**.\n\nSlope_Scaled: -0.2317767 = Correlation: -0.2317767\n\n### Example\n\nWe choose to look at the `gpa_study_hours` dataset. It has two numeric\ncolumns `gpa` and `study_hours`:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nglimpse(gpa_study_hours)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 193\nColumns: 2\n$ gpa         <dbl> 4.000, 3.800, 3.930, 3.400, 3.200, 3.520, 3.680, 3.400, 3.…\n$ study_hours <dbl> 10, 25, 45, 10, 4, 10, 24, 40, 10, 10, 30, 7, 15, 60, 10, …\n```\n:::\n:::\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Checks for Normal/Symmetric distributions\np1 <- ggplot(gpa_study_hours) + geom_histogram(aes(gpa))\np2 <- ggplot(gpa_study_hours) + geom_histogram(aes(study_hours))\np3 <- ggplot(gpa_study_hours) + geom_point(aes(gpa, study_hours))\n(p1 + p2) / p3\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/Pearson_example_1-1.png){fig-align='center' width=672}\n:::\n:::\n\n\nHmm...not normally distributed, and the relationship is also not linear,\nand there is some evidence of heterscedasticity, so Pearson correlation\nwould not be the best idea here.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Pearson Correlation as Linear Model\nlm(gpa ~ study_hours, data = gpa_study_hours) %>% summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = gpa ~ study_hours, data = gpa_study_hours)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.95130 -0.19456  0.03879  0.21708  0.73872 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 3.527997   0.037424  94.272   <2e-16 ***\nstudy_hours 0.003328   0.001794   1.855   0.0652 .  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.2837 on 191 degrees of freedom\nMultiple R-squared:  0.01769,\tAdjusted R-squared:  0.01255 \nF-statistic:  3.44 on 1 and 191 DF,  p-value: 0.06517\n```\n:::\n\n```{.r .cell-code}\n# Other ways using other packages\nmosaic::cor_test(gpa ~ study_hours, data = gpa_study_hours)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's product-moment correlation\n\ndata:  gpa and study_hours\nt = 1.8548, df = 191, p-value = 0.06517\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n -0.008383868  0.269196552\nsample estimates:\n      cor \n0.1330138 \n```\n:::\n\n```{.r .cell-code}\nstatsExpressions::corr_test(data = gpa_study_hours, \n                            x = study_hours, \n                            y = gpa)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"parameter1\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"parameter2\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"effectsize\"],\"name\":[3],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"estimate\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"conf.level\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"conf.low\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"conf.high\"],\"name\":[7],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"statistic\"],\"name\":[8],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"df.error\"],\"name\":[9],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"p.value\"],\"name\":[10],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"method\"],\"name\":[11],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"n.obs\"],\"name\":[12],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"conf.method\"],\"name\":[13],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"expression\"],\"name\":[14],\"type\":[\"list\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"study_hours\",\"2\":\"gpa\",\"3\":\"Pearson correlation\",\"4\":\"0.1330138\",\"5\":\"0.95\",\"6\":\"-0.008383868\",\"7\":\"0.2691966\",\"8\":\"1.854768\",\"9\":\"191\",\"10\":\"0.06517072\",\"11\":\"Pearson correlation\",\"12\":\"193\",\"13\":\"normal\",\"14\":\"<language>\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nThe correlation estimate is $0.133$; the `p-value` is 0.065 and the\nconfidence interval includes 0. Hence we fail to reject the NULL\nhypothesis that `study_hours` and `gpa` have no relationship.\n\nWe can use a later package `ggstaplot` to plot this:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggstatsplot::ggscatterstats(data = gpa_study_hours, \n                            x = study_hours, \n                            y = gpa,\n                            type = \"robust\",\n                            marginal = TRUE,\n                            title = \"GPA vs Study Hours\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/Pearson_example_3-1.png){fig-align='center' width=672}\n:::\n:::\n\n\n## Spearman Correlation {.tabset}\n\n### Model\n\nIn some cases the **LINE** assumptions may not hold. Nonlinear\nrelationships, non-normally distributed data ( with large outliers ) and\nworking with *ordinal* rather than continuous data: these situations\nnecessitate the use of Spearman's *ranked* correlation scores.\n(**Ranked**, not **sign-ranked**.)\n\n$$\nrank(y) = \\beta_0 + \\beta_1 * rank(x) \\\\\nH_0: \\beta_1 = 0\n$$\n\nSpearman correlation = Pearson correlation using the rank of the data\nobservations. Let's check how this holds for a our x and y data:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Plot the data\np1 <- ggplot(mydata_wide, aes(x, y)) + \n  geom_point() +\n  geom_smooth(method = \"lm\") +\n  ggtitle(\" Pearson Correlation\\n and Linear Models\")\n\n# Plot ranked data\np2 <- mydata_wide %>% \n  mutate(x_rank = rank(x),\n         y_rank = rank(y)) %>%\n  ggplot(.,aes(x_rank, y_rank)) + \n  geom_point(shape = 15, size = 2) +\n  geom_smooth(method = \"lm\") + \n  ggtitle(\" Spearman Ranked Correlation\\n and Linear Models\")\n\npatchwork::wrap_plots(p1,p2, nrow = 1, guides = \"collect\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/Spearman_Plot-1.png){fig-align='center' width=672}\n:::\n:::\n\n\nSlopes are almost identical, \\~ 0.25.\n\n### Code\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Spearman\ncor1 <- cor.test(y,x, method = \"spearman\") %>% \n  broom::tidy() %>% select(estimate, p.value)\n\n# Pearson using ranks\ncor2 <- cor.test(rank(y), rank(x), method = \"pearson\") %>% \nbroom::tidy() %>% select(estimate, p.value)\n\n# Linear Models using rank\ncor3 <- lm(rank(y) ~ 1 + rank(x),data = mydata_wide) %>% \n  broom::tidy() %>% select(estimate, p.value)\n\nrbind(cor1, cor2, cor3) %>% print()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 4 × 2\n  estimate  p.value\n     <dbl>    <dbl>\n1   -0.227 1.13e- 1\n2   -0.227 1.14e- 1\n3   31.3   9.11e-10\n4   -0.227 1.14e- 1\n```\n:::\n:::\n\n\nNotes:\n\n1.  When ranks are used, the slope of the linear model ($\\beta_1$) has\n    the same value as the correlation coefficient ( $\\rho$ ).\n\n2.  Note that the slope from the linear model now has an intuitive\n    interpretation: **the number of ranks y changes for each change in\n    rank of x**. ( Ranks are \"independent\" of `sd` )\n\n### Example\n\nWe examine the `cars93` data, where the numeric variables of interest\nare `weight` and `price`.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncars93 %>% \n  ggplot(aes(weight, price)) + \n  geom_point() + geom_smooth(method = \"lm\", se = FALSE, lty = 2) + \n  labs(title = \"Car Weight and Car Price have a nonlinear relationship\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/Spearman_example_1-1.png){fig-align='center' width=672}\n:::\n:::\n\n\nLet us try a Spearman Correlation score for these variables, since the\ndata are not linearly related and the variance of `price` also is not\nconstant over `weight`\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncor.test(cars93$price, cars93$weight, method = \"spearman\") %>% broom::tidy()\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"estimate\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"statistic\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"p.value\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"method\"],\"name\":[4],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"alternative\"],\"name\":[5],\"type\":[\"chr\"],\"align\":[\"left\"]}],\"data\":[{\"1\":\"0.8828317\",\"2\":\"3073.91\",\"3\":\"1.066315e-18\",\"4\":\"Spearman's rank correlation rho\",\"5\":\"two.sided\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\n# Using linear Model\nlm(rank(price) ~ rank(weight), data = cars93) %>% summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = rank(price) ~ rank(weight), data = cars93)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-20.0676  -3.0135   0.7815   3.6926  20.4099 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   3.22074    2.05894   1.564    0.124    \nrank(weight)  0.88288    0.06514  13.554   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 7.46 on 52 degrees of freedom\nMultiple R-squared:  0.7794,\tAdjusted R-squared:  0.7751 \nF-statistic: 183.7 on 1 and 52 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\n# Stats Plot\nggstatsplot::ggscatterstats(data = cars93, x = weight, \n                            y = price,\n                            type = \"nonparametric\",\n                            title = \"Cars93: Weight vs Price\",\n                            subtitle = \"Spearman Correlation\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/Spearman_example_2-1.png){fig-align='center' width=672}\n:::\n:::\n\n\nWe see that using ranks of the `price` variable, we obtain a Spearman's\n$\\rho = 0.882$ with a `p-value` that is very small. Hence we are able to\nreject the NULL hypothesis and state that there is a relationship\nbetween these two variables. The **linear** relationship is evaluated as\na correlation of `0.882`.\n\n# Tests on One Mean {.tabset}\n\nA series of tests deal with one mean value of a sample. The idea is to\nevaluate whether that mean is representative of the mean of the\nunderlying population.\n\nThis uses the *Student's t-test* for parametric data and the *Wilcoxon\nsigned-rank test* for non-parametric data.\n\nTests can involve a *single sample* or *paired samples*.\n\n## The Student's t-test with one sample {.tabset}\n\n### Model\n\nA single number predicts y:\n\n$$ \ny = \\beta_0 + \\beta_1*x \\\\\n\\\\and\\ further \\ actually\\\\\ny = \\beta_0\n$$\n\nand the second term vanishes, since \"there is no x\": all the x-values\nare made equal to zero in the linear model !! The NULL Hypothesis\ntherefore is:\n\n$$\n\\ H_0: \\beta_0 = 0\n$$\n\nThis NULL Hypothesis makes sense, because in the accompanying linear\nmodel all values of the <u>explanatory</u> variable x are zero, and\ntherefore the NULL Hypothesis for the model should be that y also should\nbe zero mean. Note that if we **want** the NULL hypothesis to be that\nthe mean is other than zero, we can use the\n`lm(...., mu = some_number, ..)` parameter in the command.\n\n### Code\n\nIf we compare the `t.test` with the appropriate `lm` model:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# t-test\nt1 <- t.test(y, mu = 0, alternative = \"two.sided\")\nprint(t1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tOne Sample t-test\n\ndata:  y\nt = 1.0607, df = 49, p-value = 0.294\nalternative hypothesis: true mean is not equal to 0\n95 percent confidence interval:\n -0.2683937  0.8683937\nsample estimates:\nmean of x \n      0.3 \n```\n:::\n\n```{.r .cell-code}\n# linear model\nlm1 <- lm(y ~ 1, data = mydata_wide)\nlm1 %>% summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = y ~ 1, data = mydata_wide)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-4.5554 -1.4845 -0.0392  1.5559  4.5119 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)\n(Intercept)   0.3000     0.2828   1.061    0.294\n\nResidual standard error: 2 on 49 degrees of freedom\n```\n:::\n\n```{.r .cell-code}\nlm1 %>% confint()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                 2.5 %    97.5 %\n(Intercept) -0.2683937 0.8683937\n```\n:::\n:::\n\n\nThe confidence intervals for both the `t.test` and the `lm` model are\nidentical.\n\nt-test confidence intervals: -0.2683937, 0.8683937\\\nlinear model confidence intervals: -0.2683937, 0.8683937\n\nSo even though y has a mean of 0.3, the confidence intervals straddle\nzero, and hence we cannot reject the NULL hypothesis that the true\npopulation, of which y is a sample, could have mean=0.\n\n### Example\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nexam_grades\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"semester\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"sex\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"exam1\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"exam2\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"exam3\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"course_grade\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"2000-1\",\"2\":\"Man\",\"3\":\"84.5000\",\"4\":\"69.5\",\"5\":\"86.5000\",\"6\":\"76.2564\"},{\"1\":\"2000-1\",\"2\":\"Man\",\"3\":\"80.0000\",\"4\":\"74.0\",\"5\":\"67.0000\",\"6\":\"75.3882\"},{\"1\":\"2000-1\",\"2\":\"Man\",\"3\":\"56.0000\",\"4\":\"70.0\",\"5\":\"71.5000\",\"6\":\"67.0564\"},{\"1\":\"2000-1\",\"2\":\"Man\",\"3\":\"64.0000\",\"4\":\"61.0\",\"5\":\"67.5000\",\"6\":\"63.4538\"},{\"1\":\"2000-1\",\"2\":\"Man\",\"3\":\"90.5000\",\"4\":\"72.5\",\"5\":\"75.0000\",\"6\":\"72.3949\"},{\"1\":\"2000-1\",\"2\":\"Man\",\"3\":\"74.0000\",\"4\":\"78.5\",\"5\":\"84.5000\",\"6\":\"71.4128\"},{\"1\":\"2000-1\",\"2\":\"Man\",\"3\":\"60.5000\",\"4\":\"44.0\",\"5\":\"58.0000\",\"6\":\"56.0949\"},{\"1\":\"2000-1\",\"2\":\"Man\",\"3\":\"89.0000\",\"4\":\"82.0\",\"5\":\"88.0000\",\"6\":\"78.0103\"},{\"1\":\"2000-1\",\"2\":\"Woman\",\"3\":\"87.5000\",\"4\":\"86.5\",\"5\":\"95.0000\",\"6\":\"82.9026\"},{\"1\":\"2000-1\",\"2\":\"Man\",\"3\":\"91.0000\",\"4\":\"98.0\",\"5\":\"88.0000\",\"6\":\"89.0846\"},{\"1\":\"2000-1\",\"2\":\"Man\",\"3\":\"79.5000\",\"4\":\"88.0\",\"5\":\"56.0000\",\"6\":\"72.9769\"},{\"1\":\"2000-1\",\"2\":\"Man\",\"3\":\"96.0000\",\"4\":\"91.5\",\"5\":\"78.0000\",\"6\":\"82.5282\"},{\"1\":\"2000-1\",\"2\":\"Man\",\"3\":\"55.0000\",\"4\":\"79.5\",\"5\":\"72.0000\",\"6\":\"69.9872\"},{\"1\":\"2000-1\",\"2\":\"Man\",\"3\":\"80.0000\",\"4\":\"83.5\",\"5\":\"70.0000\",\"6\":\"67.7256\"},{\"1\":\"2000-1\",\"2\":\"Woman\",\"3\":\"64.5000\",\"4\":\"83.5\",\"5\":\"77.0000\",\"6\":\"80.3051\"},{\"1\":\"2000-1\",\"2\":\"Man\",\"3\":\"73.0000\",\"4\":\"90.0\",\"5\":\"96.0000\",\"6\":\"74.8744\"},{\"1\":\"2000-1\",\"2\":\"Man\",\"3\":\"83.0000\",\"4\":\"79.0\",\"5\":\"65.0000\",\"6\":\"71.1615\"},{\"1\":\"2000-1\",\"2\":\"Man\",\"3\":\"72.0000\",\"4\":\"91.0\",\"5\":\"90.0000\",\"6\":\"76.5615\"},{\"1\":\"2000-1\",\"2\":\"Woman\",\"3\":\"57.9000\",\"4\":\"53.0\",\"5\":\"47.0000\",\"6\":\"56.9903\"},{\"1\":\"2000-1\",\"2\":\"Man\",\"3\":\"89.0000\",\"4\":\"83.5\",\"5\":\"78.5000\",\"6\":\"80.8026\"},{\"1\":\"2000-1\",\"2\":\"Woman\",\"3\":\"69.0000\",\"4\":\"57.0\",\"5\":\"88.0000\",\"6\":\"69.4308\"},{\"1\":\"2000-1\",\"2\":\"Woman\",\"3\":\"91.0000\",\"4\":\"91.0\",\"5\":\"95.5000\",\"6\":\"92.0051\"},{\"1\":\"2000-1\",\"2\":\"Man\",\"3\":\"68.0000\",\"4\":\"84.5\",\"5\":\"64.0000\",\"6\":\"67.9051\"},{\"1\":\"2000-1\",\"2\":\"Man\",\"3\":\"83.0000\",\"4\":\"89.5\",\"5\":\"93.0000\",\"6\":\"79.7872\"},{\"1\":\"2000-1\",\"2\":\"Man\",\"3\":\"72.0000\",\"4\":\"77.5\",\"5\":\"67.0000\",\"6\":\"67.1256\"},{\"1\":\"2000-1\",\"2\":\"Woman\",\"3\":\"56.0000\",\"4\":\"45.0\",\"5\":\"61.0000\",\"6\":\"58.6308\"},{\"1\":\"2000-1\",\"2\":\"Man\",\"3\":\"55.0000\",\"4\":\"71.0\",\"5\":\"72.0000\",\"6\":\"67.8308\"},{\"1\":\"2000-1\",\"2\":\"Woman\",\"3\":\"68.5000\",\"4\":\"64.0\",\"5\":\"93.0000\",\"6\":\"77.6903\"},{\"1\":\"2000-1\",\"2\":\"Man\",\"3\":\"68.5000\",\"4\":\"79.5\",\"5\":\"50.5000\",\"6\":\"69.9308\"},{\"1\":\"2000-1\",\"2\":\"Man\",\"3\":\"70.0000\",\"4\":\"71.0\",\"5\":\"76.0000\",\"6\":\"69.6769\"},{\"1\":\"2000-1\",\"2\":\"Man\",\"3\":\"75.0000\",\"4\":\"81.0\",\"5\":\"81.5000\",\"6\":\"68.0923\"},{\"1\":\"2000-1\",\"2\":\"Man\",\"3\":\"68.5000\",\"4\":\"66.0\",\"5\":\"58.0000\",\"6\":\"60.3128\"},{\"1\":\"2000-1\",\"2\":\"Man\",\"3\":\"54.0000\",\"4\":\"84.0\",\"5\":\"88.0000\",\"6\":\"72.3821\"},{\"1\":\"2000-1\",\"2\":\"Man\",\"3\":\"79.6000\",\"4\":\"67.0\",\"5\":\"72.0000\",\"6\":\"67.4787\"},{\"1\":\"2000-1\",\"2\":\"Man\",\"3\":\"85.0000\",\"4\":\"61.0\",\"5\":\"44.5000\",\"6\":\"66.2364\"},{\"1\":\"2000-1\",\"2\":\"Man\",\"3\":\"82.0000\",\"4\":\"86.5\",\"5\":\"92.5000\",\"6\":\"83.3231\"},{\"1\":\"2000-1\",\"2\":\"Woman\",\"3\":\"65.0000\",\"4\":\"83.5\",\"5\":\"87.0000\",\"6\":\"77.6436\"},{\"1\":\"2000-1\",\"2\":\"Woman\",\"3\":\"76.0000\",\"4\":\"50.0\",\"5\":\"91.5000\",\"6\":\"70.9462\"},{\"1\":\"2000-1\",\"2\":\"Man\",\"3\":\"94.5000\",\"4\":\"67.0\",\"5\":\"96.0000\",\"6\":\"86.0133\"},{\"1\":\"2000-1\",\"2\":\"Man\",\"3\":\"72.0000\",\"4\":\"67.0\",\"5\":\"90.0000\",\"6\":\"72.0269\"},{\"1\":\"2000-1\",\"2\":\"Man\",\"3\":\"65.5000\",\"4\":\"82.5\",\"5\":\"79.0000\",\"6\":\"77.0282\"},{\"1\":\"2000-1\",\"2\":\"Man\",\"3\":\"61.5000\",\"4\":\"80.5\",\"5\":\"81.5000\",\"6\":\"68.2821\"},{\"1\":\"2000-1\",\"2\":\"Man\",\"3\":\"65.0000\",\"4\":\"50.0\",\"5\":\"43.5000\",\"6\":\"43.2733\"},{\"1\":\"2000-1\",\"2\":\"Man\",\"3\":\"63.0000\",\"4\":\"82.0\",\"5\":\"88.0000\",\"6\":\"70.1031\"},{\"1\":\"2000-1\",\"2\":\"Man\",\"3\":\"75.0000\",\"4\":\"66.5\",\"5\":\"76.0000\",\"6\":\"65.0846\"},{\"1\":\"2000-1\",\"2\":\"Man\",\"3\":\"69.5000\",\"4\":\"70.5\",\"5\":\"76.0000\",\"6\":\"68.6538\"},{\"1\":\"2000-1\",\"2\":\"Woman\",\"3\":\"60.0000\",\"4\":\"95.0\",\"5\":\"91.0000\",\"6\":\"83.0508\"},{\"1\":\"2000-1\",\"2\":\"Man\",\"3\":\"84.0000\",\"4\":\"88.0\",\"5\":\"67.0000\",\"6\":\"75.0856\"},{\"1\":\"2000-1\",\"2\":\"Man\",\"3\":\"90.0000\",\"4\":\"99.5\",\"5\":\"87.5000\",\"6\":\"74.4718\"},{\"1\":\"2000-1\",\"2\":\"Woman\",\"3\":\"62.5000\",\"4\":\"85.5\",\"5\":\"85.5000\",\"6\":\"74.4821\"},{\"1\":\"2000-1\",\"2\":\"Man\",\"3\":\"88.5000\",\"4\":\"86.5\",\"5\":\"70.0000\",\"6\":\"77.9526\"},{\"1\":\"2000-2\",\"2\":\"Man\",\"3\":\"74.5000\",\"4\":\"83.0\",\"5\":\"62.4000\",\"6\":\"78.7554\"},{\"1\":\"2000-2\",\"2\":\"Man\",\"3\":\"73.5000\",\"4\":\"69.5\",\"5\":\"74.5000\",\"6\":\"69.0228\"},{\"1\":\"2000-2\",\"2\":\"Man\",\"3\":\"75.0000\",\"4\":\"60.5\",\"5\":\"80.9000\",\"6\":\"68.6502\"},{\"1\":\"2000-2\",\"2\":\"Man\",\"3\":\"76.5000\",\"4\":\"76.0\",\"5\":\"61.0000\",\"6\":\"73.6702\"},{\"1\":\"2000-2\",\"2\":\"Woman\",\"3\":\"90.5000\",\"4\":\"68.0\",\"5\":\"59.0000\",\"6\":\"69.7842\"},{\"1\":\"2000-2\",\"2\":\"Man\",\"3\":\"88.0000\",\"4\":\"77.5\",\"5\":\"90.5000\",\"6\":\"84.1474\"},{\"1\":\"2000-2\",\"2\":\"Man\",\"3\":\"87.2727\",\"4\":\"58.0\",\"5\":\"28.0000\",\"6\":\"49.1931\"},{\"1\":\"2000-2\",\"2\":\"Man\",\"3\":\"81.9000\",\"4\":\"86.0\",\"5\":\"62.0000\",\"6\":\"73.9116\"},{\"1\":\"2000-2\",\"2\":\"Man\",\"3\":\"65.5000\",\"4\":\"90.0\",\"5\":\"61.8000\",\"6\":\"68.5425\"},{\"1\":\"2000-2\",\"2\":\"Woman\",\"3\":\"84.5000\",\"4\":\"80.5\",\"5\":\"72.5000\",\"6\":\"81.2088\"},{\"1\":\"2000-2\",\"2\":\"Man\",\"3\":\"88.9000\",\"4\":\"67.0\",\"5\":\"76.0000\",\"6\":\"80.5554\"},{\"1\":\"2000-2\",\"2\":\"Man\",\"3\":\"70.0000\",\"4\":\"56.0\",\"5\":\"81.5000\",\"6\":\"68.7839\"},{\"1\":\"2000-2\",\"2\":\"Man\",\"3\":\"73.0000\",\"4\":\"48.0\",\"5\":\"55.0000\",\"6\":\"65.3088\"},{\"1\":\"2000-2\",\"2\":\"Man\",\"3\":\"86.0000\",\"4\":\"77.0\",\"5\":\"82.0000\",\"6\":\"79.6035\"},{\"1\":\"2000-2\",\"2\":\"Man\",\"3\":\"68.0000\",\"4\":\"60.0\",\"5\":\"59.0000\",\"6\":\"58.4316\"},{\"1\":\"2000-2\",\"2\":\"Woman\",\"3\":\"82.0000\",\"4\":\"74.0\",\"5\":\"81.5000\",\"6\":\"76.6842\"},{\"1\":\"2000-2\",\"2\":\"Man\",\"3\":\"86.4000\",\"4\":\"72.0\",\"5\":\"69.5000\",\"6\":\"67.5625\"},{\"1\":\"2000-2\",\"2\":\"Man\",\"3\":\"74.0000\",\"4\":\"83.0\",\"5\":\"79.9000\",\"6\":\"74.5730\"},{\"1\":\"2000-2\",\"2\":\"Man\",\"3\":\"92.3000\",\"4\":\"76.0\",\"5\":\"97.0000\",\"6\":\"87.0288\"},{\"1\":\"2000-2\",\"2\":\"Man\",\"3\":\"57.0000\",\"4\":\"70.0\",\"5\":\"56.0000\",\"6\":\"65.3947\"},{\"1\":\"2000-2\",\"2\":\"Man\",\"3\":\"62.5000\",\"4\":\"41.0\",\"5\":\"77.8000\",\"6\":\"59.8863\"},{\"1\":\"2000-2\",\"2\":\"Man\",\"3\":\"75.5000\",\"4\":\"62.5\",\"5\":\"79.7000\",\"6\":\"73.5435\"},{\"1\":\"2000-2\",\"2\":\"Man\",\"3\":\"67.0000\",\"4\":\"58.0\",\"5\":\"45.8000\",\"6\":\"58.3828\"},{\"1\":\"2000-2\",\"2\":\"Man\",\"3\":\"73.0000\",\"4\":\"78.0\",\"5\":\"77.3000\",\"6\":\"79.2354\"},{\"1\":\"2000-2\",\"2\":\"Man\",\"3\":\"93.0000\",\"4\":\"75.0\",\"5\":\"96.0000\",\"6\":\"71.3228\"},{\"1\":\"2000-2\",\"2\":\"Man\",\"3\":\"81.5000\",\"4\":\"73.0\",\"5\":\"69.5000\",\"6\":\"65.5295\"},{\"1\":\"2000-2\",\"2\":\"Man\",\"3\":\"82.5000\",\"4\":\"83.5\",\"5\":\"82.5000\",\"6\":\"81.4474\"},{\"1\":\"2000-2\",\"2\":\"Woman\",\"3\":\"46.5000\",\"4\":\"77.0\",\"5\":\"47.0000\",\"6\":\"62.8842\"},{\"1\":\"2000-2\",\"2\":\"Man\",\"3\":\"62.0000\",\"4\":\"71.0\",\"5\":\"64.0000\",\"6\":\"69.4702\"},{\"1\":\"2000-2\",\"2\":\"Woman\",\"3\":\"68.5000\",\"4\":\"55.5\",\"5\":\"52.0000\",\"6\":\"61.8263\"},{\"1\":\"2000-2\",\"2\":\"Man\",\"3\":\"80.0000\",\"4\":\"84.0\",\"5\":\"48.5000\",\"6\":\"70.0947\"},{\"1\":\"2000-2\",\"2\":\"Man\",\"3\":\"77.0000\",\"4\":\"77.0\",\"5\":\"44.0000\",\"6\":\"68.0404\"},{\"1\":\"2000-2\",\"2\":\"Woman\",\"3\":\"55.0000\",\"4\":\"94.0\",\"5\":\"96.0000\",\"6\":\"83.5193\"},{\"1\":\"2000-2\",\"2\":\"Man\",\"3\":\"69.0000\",\"4\":\"74.5\",\"5\":\"41.5000\",\"6\":\"59.0386\"},{\"1\":\"2000-2\",\"2\":\"Woman\",\"3\":\"74.0000\",\"4\":\"56.0\",\"5\":\"69.9000\",\"6\":\"65.0204\"},{\"1\":\"2001-1\",\"2\":\"Man\",\"3\":\"93.0000\",\"4\":\"76.0\",\"5\":\"95.5000\",\"6\":\"85.5000\"},{\"1\":\"2001-1\",\"2\":\"Man\",\"3\":\"81.0000\",\"4\":\"78.0\",\"5\":\"79.5000\",\"6\":\"75.7333\"},{\"1\":\"2001-1\",\"2\":\"Man\",\"3\":\"98.0000\",\"4\":\"87.0\",\"5\":\"85.5000\",\"6\":\"86.5833\"},{\"1\":\"2001-1\",\"2\":\"Man\",\"3\":\"92.5000\",\"4\":\"81.0\",\"5\":\"74.5000\",\"6\":\"77.2833\"},{\"1\":\"2001-1\",\"2\":\"Man\",\"3\":\"83.5000\",\"4\":\"60.5\",\"5\":\"78.0000\",\"6\":\"73.6333\"},{\"1\":\"2001-1\",\"2\":\"Man\",\"3\":\"98.0000\",\"4\":\"92.0\",\"5\":\"90.5000\",\"6\":\"91.8585\"},{\"1\":\"2001-1\",\"2\":\"Man\",\"3\":\"80.5000\",\"4\":\"53.5\",\"5\":\"67.5000\",\"6\":\"62.9555\"},{\"1\":\"2001-1\",\"2\":\"Man\",\"3\":\"80.9000\",\"4\":\"68.0\",\"5\":\"67.0000\",\"6\":\"72.7600\"},{\"1\":\"2001-1\",\"2\":\"Man\",\"3\":\"84.5000\",\"4\":\"46.0\",\"5\":\"65.5000\",\"6\":\"60.6167\"},{\"1\":\"2001-1\",\"2\":\"Man\",\"3\":\"93.8000\",\"4\":\"59.5\",\"5\":\"73.3000\",\"6\":\"70.0067\"},{\"1\":\"2001-1\",\"2\":\"Man\",\"3\":\"98.0000\",\"4\":\"96.5\",\"5\":\"98.5000\",\"6\":\"97.5667\"},{\"1\":\"2001-1\",\"2\":\"Man\",\"3\":\"92.0000\",\"4\":\"78.5\",\"5\":\"72.0000\",\"6\":\"73.2833\"},{\"1\":\"2001-1\",\"2\":\"Man\",\"3\":\"91.0000\",\"4\":\"72.0\",\"5\":\"81.0000\",\"6\":\"75.1167\"},{\"1\":\"2001-1\",\"2\":\"Man\",\"3\":\"80.0000\",\"4\":\"72.0\",\"5\":\"59.5000\",\"6\":\"69.7000\"},{\"1\":\"2001-1\",\"2\":\"Man\",\"3\":\"94.0000\",\"4\":\"84.0\",\"5\":\"98.5000\",\"6\":\"88.8667\"},{\"1\":\"2001-1\",\"2\":\"Man\",\"3\":\"90.0000\",\"4\":\"73.0\",\"5\":\"63.5000\",\"6\":\"72.9000\"},{\"1\":\"2001-1\",\"2\":\"Man\",\"3\":\"94.0000\",\"4\":\"82.0\",\"5\":\"86.4000\",\"6\":\"80.3267\"},{\"1\":\"2001-1\",\"2\":\"Man\",\"3\":\"86.5000\",\"4\":\"76.0\",\"5\":\"85.5000\",\"6\":\"76.2000\"},{\"1\":\"2001-1\",\"2\":\"Man\",\"3\":\"87.0000\",\"4\":\"76.0\",\"5\":\"72.5000\",\"6\":\"70.7442\"},{\"1\":\"2001-1\",\"2\":\"Man\",\"3\":\"80.3000\",\"4\":\"88.5\",\"5\":\"83.5000\",\"6\":\"85.9700\"},{\"1\":\"2001-1\",\"2\":\"Man\",\"3\":\"89.5000\",\"4\":\"66.5\",\"5\":\"78.9000\",\"6\":\"72.5267\"},{\"1\":\"2001-1\",\"2\":\"Man\",\"3\":\"70.5000\",\"4\":\"70.5\",\"5\":\"58.0000\",\"6\":\"57.0000\"},{\"1\":\"2001-1\",\"2\":\"Man\",\"3\":\"89.4000\",\"4\":\"84.5\",\"5\":\"82.5000\",\"6\":\"83.8685\"},{\"1\":\"2001-1\",\"2\":\"Woman\",\"3\":\"79.5000\",\"4\":\"56.0\",\"5\":\"81.0000\",\"6\":\"68.2500\"},{\"1\":\"2001-1\",\"2\":\"Man\",\"3\":\"93.9000\",\"4\":\"88.0\",\"5\":\"71.0000\",\"6\":\"80.0600\"},{\"1\":\"2001-1\",\"2\":\"Man\",\"3\":\"73.5000\",\"4\":\"78.5\",\"5\":\"72.0000\",\"6\":\"77.0333\"},{\"1\":\"2001-1\",\"2\":\"Man\",\"3\":\"94.8000\",\"4\":\"84.5\",\"5\":\"77.5000\",\"6\":\"84.1700\"},{\"1\":\"2001-1\",\"2\":\"Woman\",\"3\":\"66.0000\",\"4\":\"62.0\",\"5\":\"80.5000\",\"6\":\"70.9333\"},{\"1\":\"2001-1\",\"2\":\"Man\",\"3\":\"96.3000\",\"4\":\"82.0\",\"5\":\"76.0000\",\"6\":\"79.9867\"},{\"1\":\"2001-1\",\"2\":\"Man\",\"3\":\"93.3000\",\"4\":\"93.0\",\"5\":\"92.5000\",\"6\":\"89.8033\"},{\"1\":\"2001-1\",\"2\":\"Man\",\"3\":\"87.3000\",\"4\":\"81.0\",\"5\":\"78.5000\",\"6\":\"85.7367\"},{\"1\":\"2001-1\",\"2\":\"Man\",\"3\":\"79.0000\",\"4\":\"81.0\",\"5\":\"91.0000\",\"6\":\"78.1222\"},{\"1\":\"2001-1\",\"2\":\"Man\",\"3\":\"84.0000\",\"4\":\"81.0\",\"5\":\"91.0000\",\"6\":\"75.0333\"},{\"1\":\"2001-1\",\"2\":\"Woman\",\"3\":\"81.0000\",\"4\":\"81.5\",\"5\":\"70.0000\",\"6\":\"74.2167\"},{\"1\":\"2001-1\",\"2\":\"Woman\",\"3\":\"84.5000\",\"4\":\"71.5\",\"5\":\"76.0000\",\"6\":\"73.9833\"},{\"1\":\"2001-1\",\"2\":\"Woman\",\"3\":\"90.6250\",\"4\":\"61.5\",\"5\":\"59.5000\",\"6\":\"66.6958\"},{\"1\":\"2001-1\",\"2\":\"Woman\",\"3\":\"91.5000\",\"4\":\"58.0\",\"5\":\"79.5000\",\"6\":\"74.9888\"},{\"1\":\"2001-1\",\"2\":\"Man\",\"3\":\"84.0000\",\"4\":\"72.5\",\"5\":\"76.0000\",\"6\":\"75.7000\"},{\"1\":\"2001-2\",\"2\":\"Man\",\"3\":\"73.2000\",\"4\":\"44.0\",\"5\":\"50.9000\",\"6\":\"47.9000\"},{\"1\":\"2001-2\",\"2\":\"Man\",\"3\":\"70.5000\",\"4\":\"42.8\",\"5\":\"36.4000\",\"6\":\"48.0500\"},{\"1\":\"2001-2\",\"2\":\"Woman\",\"3\":\"92.9000\",\"4\":\"88.5\",\"5\":\"79.0000\",\"6\":\"86.6500\"},{\"1\":\"2001-2\",\"2\":\"Man\",\"3\":\"68.8000\",\"4\":\"52.1\",\"5\":\"65.4000\",\"6\":\"55.9500\"},{\"1\":\"2001-2\",\"2\":\"Man\",\"3\":\"91.3000\",\"4\":\"71.0\",\"5\":\"79.5000\",\"6\":\"77.8250\"},{\"1\":\"2001-2\",\"2\":\"Man\",\"3\":\"78.3000\",\"4\":\"46.5\",\"5\":\"63.9000\",\"6\":\"56.7250\"},{\"1\":\"2001-2\",\"2\":\"Man\",\"3\":\"71.3000\",\"4\":\"43.0\",\"5\":\"67.4000\",\"6\":\"58.3750\"},{\"1\":\"2001-2\",\"2\":\"Man\",\"3\":\"74.9000\",\"4\":\"65.4\",\"5\":\"51.5000\",\"6\":\"56.0750\"},{\"1\":\"2001-2\",\"2\":\"Man\",\"3\":\"90.5000\",\"4\":\"71.5\",\"5\":\"69.5000\",\"6\":\"78.5000\"},{\"1\":\"2001-2\",\"2\":\"Man\",\"3\":\"80.3000\",\"4\":\"63.0\",\"5\":\"64.0000\",\"6\":\"64.7000\"},{\"1\":\"2001-2\",\"2\":\"Woman\",\"3\":\"79.0000\",\"4\":\"74.5\",\"5\":\"72.5000\",\"6\":\"68.3250\"},{\"1\":\"2001-2\",\"2\":\"Man\",\"3\":\"82.5000\",\"4\":\"62.5\",\"5\":\"77.5000\",\"6\":\"73.5000\"},{\"1\":\"2001-2\",\"2\":\"Man\",\"3\":\"79.7000\",\"4\":\"84.4\",\"5\":\"77.3000\",\"6\":\"75.5500\"},{\"1\":\"2001-2\",\"2\":\"Man\",\"3\":\"79.5000\",\"4\":\"77.9\",\"5\":\"62.0000\",\"6\":\"68.3500\"},{\"1\":\"2001-2\",\"2\":\"Man\",\"3\":\"79.5000\",\"4\":\"68.7\",\"5\":\"87.0000\",\"6\":\"81.7500\"},{\"1\":\"2001-2\",\"2\":\"Man\",\"3\":\"93.0000\",\"4\":\"70.9\",\"5\":\"67.5000\",\"6\":\"70.4250\"},{\"1\":\"2001-2\",\"2\":\"Man\",\"3\":\"88.5000\",\"4\":\"79.5\",\"5\":\"82.0000\",\"6\":\"80.5000\"},{\"1\":\"2001-2\",\"2\":\"Woman\",\"3\":\"86.0000\",\"4\":\"73.0\",\"5\":\"47.0000\",\"6\":\"66.0000\"},{\"1\":\"2001-2\",\"2\":\"Man\",\"3\":\"93.8000\",\"4\":\"68.5\",\"5\":\"66.4000\",\"6\":\"74.8750\"},{\"1\":\"2001-2\",\"2\":\"Woman\",\"3\":\"93.9000\",\"4\":\"84.0\",\"5\":\"83.5000\",\"6\":\"88.2250\"},{\"1\":\"2001-2\",\"2\":\"Man\",\"3\":\"83.3000\",\"4\":\"83.0\",\"5\":\"78.0000\",\"6\":\"82.5750\"},{\"1\":\"2001-2\",\"2\":\"Man\",\"3\":\"75.1000\",\"4\":\"70.0\",\"5\":\"61.0000\",\"6\":\"64.0250\"},{\"1\":\"2001-2\",\"2\":\"Man\",\"3\":\"92.9000\",\"4\":\"83.0\",\"5\":\"84.5000\",\"6\":\"84.1500\"},{\"1\":\"2001-2\",\"2\":\"Man\",\"3\":\"76.5000\",\"4\":\"41.5\",\"5\":\"48.0000\",\"6\":\"53.0750\"},{\"1\":\"2001-2\",\"2\":\"Woman\",\"3\":\"84.1000\",\"4\":\"88.8\",\"5\":\"75.5000\",\"6\":\"81.5500\"},{\"1\":\"2001-2\",\"2\":\"Man\",\"3\":\"87.9000\",\"4\":\"58.2\",\"5\":\"67.0000\",\"6\":\"63.5250\"},{\"1\":\"2001-2\",\"2\":\"Woman\",\"3\":\"79.5000\",\"4\":\"66.0\",\"5\":\"67.5000\",\"6\":\"69.1250\"},{\"1\":\"2001-2\",\"2\":\"Man\",\"3\":\"82.0000\",\"4\":\"53.5\",\"5\":\"52.0000\",\"6\":\"54.5000\"},{\"1\":\"2001-2\",\"2\":\"Woman\",\"3\":\"91.4000\",\"4\":\"77.0\",\"5\":\"76.0000\",\"6\":\"76.1000\"},{\"1\":\"2001-2\",\"2\":\"Man\",\"3\":\"84.9000\",\"4\":\"69.5\",\"5\":\"37.3000\",\"6\":\"60.3000\"},{\"1\":\"2001-2\",\"2\":\"Man\",\"3\":\"58.0000\",\"4\":\"61.0\",\"5\":\"47.4000\",\"6\":\"57.6000\"},{\"1\":\"2001-2\",\"2\":\"Man\",\"3\":\"81.5000\",\"4\":\"57.5\",\"5\":\"65.8000\",\"6\":\"60.3250\"},{\"1\":\"2001-2\",\"2\":\"Man\",\"3\":\"95.0000\",\"4\":\"68.0\",\"5\":\"82.5000\",\"6\":\"76.7500\"},{\"1\":\"2001-2\",\"2\":\"Man\",\"3\":\"95.5000\",\"4\":\"80.5\",\"5\":\"84.3000\",\"6\":\"75.7750\"},{\"1\":\"2001-2\",\"2\":\"Man\",\"3\":\"77.5000\",\"4\":\"80.9\",\"5\":\"75.0000\",\"6\":\"76.4250\"},{\"1\":\"2001-2\",\"2\":\"Man\",\"3\":\"82.0000\",\"4\":\"46.0\",\"5\":\"54.0000\",\"6\":\"53.0000\"},{\"1\":\"2001-2\",\"2\":\"Man\",\"3\":\"93.8000\",\"4\":\"82.5\",\"5\":\"80.5000\",\"6\":\"84.6500\"},{\"1\":\"2002-1\",\"2\":\"Man\",\"3\":\"89.0000\",\"4\":\"83.5\",\"5\":\"92.0000\",\"6\":\"77.1197\"},{\"1\":\"2002-1\",\"2\":\"Man\",\"3\":\"82.0000\",\"4\":\"78.5\",\"5\":\"82.0000\",\"6\":\"61.7972\"},{\"1\":\"2002-1\",\"2\":\"Man\",\"3\":\"73.5000\",\"4\":\"80.0\",\"5\":\"82.0000\",\"6\":\"73.5563\"},{\"1\":\"2002-1\",\"2\":\"Man\",\"3\":\"73.5000\",\"4\":\"82.8\",\"5\":\"79.5000\",\"6\":\"69.9459\"},{\"1\":\"2002-1\",\"2\":\"Woman\",\"3\":\"79.0000\",\"4\":\"86.5\",\"5\":\"97.0000\",\"6\":\"80.5324\"},{\"1\":\"2002-1\",\"2\":\"Man\",\"3\":\"71.5000\",\"4\":\"71.0\",\"5\":\"58.0000\",\"6\":\"62.4331\"},{\"1\":\"2002-1\",\"2\":\"Man\",\"3\":\"92.5000\",\"4\":\"92.0\",\"5\":\"93.5000\",\"6\":\"82.2000\"},{\"1\":\"2002-1\",\"2\":\"Woman\",\"3\":\"85.5000\",\"4\":\"90.5\",\"5\":\"85.0000\",\"6\":\"86.7901\"},{\"1\":\"2002-1\",\"2\":\"Man\",\"3\":\"93.0000\",\"4\":\"47.0\",\"5\":\"70.0000\",\"6\":\"59.8218\"},{\"1\":\"2002-1\",\"2\":\"Man\",\"3\":\"75.5000\",\"4\":\"66.0\",\"5\":\"94.0000\",\"6\":\"69.0648\"},{\"1\":\"2002-1\",\"2\":\"Man\",\"3\":\"88.5000\",\"4\":\"74.0\",\"5\":\"87.0000\",\"6\":\"78.2085\"},{\"1\":\"2002-1\",\"2\":\"Man\",\"3\":\"87.0000\",\"4\":\"96.0\",\"5\":\"98.5000\",\"6\":\"84.0577\"},{\"1\":\"2002-1\",\"2\":\"Woman\",\"3\":\"89.5000\",\"4\":\"77.5\",\"5\":\"88.9000\",\"6\":\"69.2110\"},{\"1\":\"2002-1\",\"2\":\"Man\",\"3\":\"97.5000\",\"4\":\"94.5\",\"5\":\"76.0000\",\"6\":\"78.9310\"},{\"1\":\"2002-1\",\"2\":\"Woman\",\"3\":\"59.0000\",\"4\":\"73.0\",\"5\":\"85.5000\",\"6\":\"58.2606\"},{\"1\":\"2002-1\",\"2\":\"Man\",\"3\":\"81.0000\",\"4\":\"87.0\",\"5\":\"86.5000\",\"6\":\"72.1352\"},{\"1\":\"2002-1\",\"2\":\"Man\",\"3\":\"73.5000\",\"4\":\"57.5\",\"5\":\"83.0000\",\"6\":\"61.7713\"},{\"1\":\"2002-1\",\"2\":\"Man\",\"3\":\"90.5000\",\"4\":\"53.0\",\"5\":\"78.5000\",\"6\":\"60.7915\"},{\"1\":\"2002-1\",\"2\":\"Man\",\"3\":\"70.0000\",\"4\":\"62.5\",\"5\":\"85.0000\",\"6\":\"64.5225\"},{\"1\":\"2002-1\",\"2\":\"Man\",\"3\":\"98.5000\",\"4\":\"98.0\",\"5\":\"90.0000\",\"6\":\"80.3761\"},{\"1\":\"2002-1\",\"2\":\"Man\",\"3\":\"85.5000\",\"4\":\"67.0\",\"5\":\"86.0000\",\"6\":\"67.6535\"},{\"1\":\"2002-1\",\"2\":\"Man\",\"3\":\"78.0000\",\"4\":\"58.0\",\"5\":\"92.5000\",\"6\":\"65.1831\"},{\"1\":\"2002-1\",\"2\":\"Man\",\"3\":\"86.5000\",\"4\":\"85.0\",\"5\":\"85.0000\",\"6\":\"73.5972\"},{\"1\":\"2002-1\",\"2\":\"Woman\",\"3\":\"99.3000\",\"4\":\"96.0\",\"5\":\"89.0000\",\"6\":\"91.4868\"},{\"1\":\"2002-1\",\"2\":\"Man\",\"3\":\"90.5000\",\"4\":\"78.5\",\"5\":\"79.5000\",\"6\":\"73.0634\"},{\"1\":\"2002-1\",\"2\":\"Man\",\"3\":\"86.5000\",\"4\":\"67.5\",\"5\":\"85.5000\",\"6\":\"70.0746\"},{\"1\":\"2002-1\",\"2\":\"Man\",\"3\":\"80.0000\",\"4\":\"94.0\",\"5\":\"90.5000\",\"6\":\"88.4310\"},{\"1\":\"2002-1\",\"2\":\"Man\",\"3\":\"72.0000\",\"4\":\"95.0\",\"5\":\"78.0000\",\"6\":\"77.3507\"},{\"1\":\"2002-1\",\"2\":\"Man\",\"3\":\"72.5000\",\"4\":\"69.5\",\"5\":\"92.0000\",\"6\":\"73.5648\"},{\"1\":\"2002-1\",\"2\":\"Man\",\"3\":\"77.5000\",\"4\":\"74.0\",\"5\":\"82.0000\",\"6\":\"73.1493\"},{\"1\":\"2002-1\",\"2\":\"Man\",\"3\":\"74.0000\",\"4\":\"49.5\",\"5\":\"82.0000\",\"6\":\"64.6690\"},{\"1\":\"2002-1\",\"2\":\"Man\",\"3\":\"79.0000\",\"4\":\"80.5\",\"5\":\"80.5000\",\"6\":\"71.9845\"},{\"1\":\"2002-1\",\"2\":\"Man\",\"3\":\"80.0000\",\"4\":\"82.0\",\"5\":\"77.0000\",\"6\":\"67.7986\"},{\"1\":\"2002-1\",\"2\":\"Man\",\"3\":\"97.4000\",\"4\":\"66.9\",\"5\":\"83.0000\",\"6\":\"74.9276\"},{\"1\":\"2002-1\",\"2\":\"Man\",\"3\":\"61.5000\",\"4\":\"64.5\",\"5\":\"86.0000\",\"6\":\"63.7651\"},{\"1\":\"2002-1\",\"2\":\"Man\",\"3\":\"86.0000\",\"4\":\"67.0\",\"5\":\"96.8000\",\"6\":\"73.7346\"},{\"1\":\"2003-1\",\"2\":\"Woman\",\"3\":\"75.7143\",\"4\":\"62.6\",\"5\":\"45.5556\",\"6\":\"59.5549\"},{\"1\":\"2003-1\",\"2\":\"Woman\",\"3\":\"80.7143\",\"4\":\"38.0\",\"5\":\"78.3333\",\"6\":\"65.2202\"},{\"1\":\"2003-1\",\"2\":\"Woman\",\"3\":\"88.2143\",\"4\":\"75.1\",\"5\":\"70.0000\",\"6\":\"72.3670\"},{\"1\":\"2003-1\",\"2\":\"Man\",\"3\":\"81.7857\",\"4\":\"76.0\",\"5\":\"68.3333\",\"6\":\"74.1120\"},{\"1\":\"2003-1\",\"2\":\"Man\",\"3\":\"96.0714\",\"4\":\"68.1\",\"5\":\"74.4444\",\"6\":\"70.4423\"},{\"1\":\"2003-1\",\"2\":\"Man\",\"3\":\"NA\",\"4\":\"58.0\",\"5\":\"78.3333\",\"6\":\"46.7231\"},{\"1\":\"2003-1\",\"2\":\"Man\",\"3\":\"73.5714\",\"4\":\"62.1\",\"5\":\"97.7778\",\"6\":\"69.1030\"},{\"1\":\"2003-1\",\"2\":\"Man\",\"3\":\"71.0714\",\"4\":\"41.5\",\"5\":\"55.5556\",\"6\":\"53.9348\"},{\"1\":\"2003-1\",\"2\":\"Man\",\"3\":\"66.4286\",\"4\":\"59.1\",\"5\":\"85.5556\",\"6\":\"68.5149\"},{\"1\":\"2003-1\",\"2\":\"Man\",\"3\":\"85.7143\",\"4\":\"77.1\",\"5\":\"83.3333\",\"6\":\"79.8810\"},{\"1\":\"2003-1\",\"2\":\"Woman\",\"3\":\"88.9286\",\"4\":\"72.0\",\"5\":\"93.3333\",\"6\":\"82.3626\"},{\"1\":\"2003-1\",\"2\":\"Man\",\"3\":\"65.7143\",\"4\":\"60.5\",\"5\":\"30.0000\",\"6\":\"48.5152\"},{\"1\":\"2003-1\",\"2\":\"Man\",\"3\":\"92.5000\",\"4\":\"63.5\",\"5\":\"92.7778\",\"6\":\"80.3655\"},{\"1\":\"2003-1\",\"2\":\"Woman\",\"3\":\"86.0714\",\"4\":\"77.5\",\"5\":\"96.6667\",\"6\":\"80.3527\"},{\"1\":\"2003-1\",\"2\":\"Man\",\"3\":\"75.0000\",\"4\":\"71.9\",\"5\":\"88.3333\",\"6\":\"70.3606\"},{\"1\":\"2003-1\",\"2\":\"Man\",\"3\":\"95.7143\",\"4\":\"90.1\",\"5\":\"98.8889\",\"6\":\"93.3003\"},{\"1\":\"2003-1\",\"2\":\"Man\",\"3\":\"88.9286\",\"4\":\"52.5\",\"5\":\"62.5000\",\"6\":\"61.1081\"},{\"1\":\"2003-1\",\"2\":\"Man\",\"3\":\"94.6429\",\"4\":\"90.0\",\"5\":\"90.0000\",\"6\":\"87.6431\"},{\"1\":\"2003-1\",\"2\":\"Man\",\"3\":\"92.5000\",\"4\":\"80.0\",\"5\":\"96.1111\",\"6\":\"87.9477\"},{\"1\":\"2003-1\",\"2\":\"Woman\",\"3\":\"91.0714\",\"4\":\"39.5\",\"5\":\"78.8889\",\"6\":\"67.9143\"},{\"1\":\"2003-1\",\"2\":\"Man\",\"3\":\"92.8571\",\"4\":\"73.5\",\"5\":\"92.1111\",\"6\":\"86.2788\"},{\"1\":\"2003-1\",\"2\":\"Woman\",\"3\":\"86.0714\",\"4\":\"45.5\",\"5\":\"55.5556\",\"6\":\"59.8701\"},{\"1\":\"2003-1\",\"2\":\"Man\",\"3\":\"87.1429\",\"4\":\"81.6\",\"5\":\"73.8889\",\"6\":\"76.4304\"},{\"1\":\"2003-1\",\"2\":\"Man\",\"3\":\"74.2857\",\"4\":\"52.6\",\"5\":\"47.2222\",\"6\":\"56.3211\"},{\"1\":\"2003-1\",\"2\":\"Man\",\"3\":\"95.7143\",\"4\":\"78.0\",\"5\":\"84.4444\",\"6\":\"83.2086\"},{\"1\":\"2003-1\",\"2\":\"Man\",\"3\":\"83.2143\",\"4\":\"64.6\",\"5\":\"58.8889\",\"6\":\"68.0731\"},{\"1\":\"2003-1\",\"2\":\"Man\",\"3\":\"85.0000\",\"4\":\"78.1\",\"5\":\"82.2222\",\"6\":\"70.5416\"},{\"1\":\"2003-1\",\"2\":\"Man\",\"3\":\"85.7143\",\"4\":\"68.1\",\"5\":\"72.0000\",\"6\":\"66.1202\"},{\"1\":\"2003-1\",\"2\":\"Woman\",\"3\":\"94.6429\",\"4\":\"94.5\",\"5\":\"96.1111\",\"6\":\"90.7190\"},{\"1\":\"2003-1\",\"2\":\"Man\",\"3\":\"90.7143\",\"4\":\"77.5\",\"5\":\"78.2222\",\"6\":\"77.5340\"},{\"1\":\"2003-1\",\"2\":\"Man\",\"3\":\"86.4286\",\"4\":\"70.1\",\"5\":\"88.3333\",\"6\":\"74.5553\"},{\"1\":\"2003-1\",\"2\":\"Man\",\"3\":\"98.2143\",\"4\":\"89.1\",\"5\":\"71.1111\",\"6\":\"85.5208\"},{\"1\":\"2003-1\",\"2\":\"Woman\",\"3\":\"95.0000\",\"4\":\"86.0\",\"5\":\"78.3333\",\"6\":\"83.6959\"},{\"1\":\"2003-1\",\"2\":\"Man\",\"3\":\"97.1429\",\"4\":\"53.5\",\"5\":\"67.2222\",\"6\":\"72.1189\"},{\"1\":\"2003-1\",\"2\":\"Man\",\"3\":\"85.0000\",\"4\":\"63.0\",\"5\":\"75.0000\",\"6\":\"67.1996\"},{\"1\":\"2003-1\",\"2\":\"Man\",\"3\":\"72.8571\",\"4\":\"48.5\",\"5\":\"90.5556\",\"6\":\"66.4035\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n## Wilcoxon's Signed-Rank Test {.tabset}\n\nSince we are dealing with the **mean**, the *sign* of the rank becomes\nimportant to use, in the case of a non-parametric single mean test.\n\n### Model\n\n$$\nsigned\\_rank(y) = \\beta_0 \\\\\nH_0: \\beta_0 = 0\n$$\n\n### Code\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Standard Wilcoxon Signed_Rank Test\nw1 <- wilcox.test(y)\nw1\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tWilcoxon signed rank test with continuity correction\n\ndata:  y\nV = 754, p-value = 0.2628\nalternative hypothesis: true location is not equal to 0\n```\n:::\n\n```{.r .cell-code}\n# Wilcoxon test with lm\nw2 <- lm(signed_rank(y) ~ 1 , data = mydata_wide)\nw2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = signed_rank(y) ~ 1, data = mydata_wide)\n\nCoefficients:\n(Intercept)  \n       4.66  \n```\n:::\n\n```{.r .cell-code}\n# t-test with signed_rank data\nw3 <- t.test(signed_rank(y))\nw3\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tOne Sample t-test\n\ndata:  signed_rank(y)\nt = 1.1277, df = 49, p-value = 0.265\nalternative hypothesis: true mean is not equal to 0\n95 percent confidence interval:\n -3.644491 12.964491\nsample estimates:\nmean of x \n     4.66 \n```\n:::\n:::\n\n\nWe can plot the y data both original and ranked to see where the mean\nlies in each case. The approximation to the true \\$\\beta\\_0 ( is good\nwhen the number of observations N is \\>=50. Lindoloev has a [simulation\non\nthis.](https://lindeloev.github.io/tests-as-linear/simulations/simulate_wilcoxon.html).\nWe can also plot the model using *lm* for both the original data and the\nsign-ranked data.\n\n### Example\n\n### Plots for both t-test and Wilcoxon test\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\np1 <- ggplot(mydata_wide, aes( x = 0, y = y)) +\n  geom_point(alpha = 0.4) +\n  geom_segment(aes(y = t1$estimate, \n                   yend = t1$estimate, \n                   x = -0.2, xend = 0.2)) + \n  labs(title = \"Student's\\n t-Test\")\n\n# t-test using linear model\np2 <- ggplot(mydata_wide, aes( x = 0, y = y)) +\n  geom_point(alpha = 0.4) +\n  geom_segment(aes(y = lm(y ~ 1)$coefficient, \n                   yend = lm(y ~ 1)$coefficient, \n                   x = -0.2, xend = 0.2)) + \n  labs(title = \"Student's\\n t-Test \\n using lm\")\n\n# Wilcoxon test, using signed-ranks of data\np3 <- ggplot(mydata_wide, aes( x = 0, y = signed_rank(y))) +\n  geom_point(alpha = 0.4) +\n  geom_segment(aes(y = mean(signed_rank(y)), yend = mean(signed_rank(y)), x = -0.2, xend = 0.2)) + \n  labs(title = \"Wilcoxon \\nSigned-Rank\\n Test\")\n\n# Wilcoxon test, using signed-ranks of data, and lm\np4 <- ggplot(mydata_wide, aes( x = 0, y = signed_rank(y))) +\n  geom_point(alpha = 0.4) +\n  geom_segment(aes(y = lm(signed_rank(y) ~1)$coefficient, \n                   yend = lm(signed_rank(y) ~1)$coefficient, \n                   x = -0.2, xend = 0.2)) + \n  labs(title = \"Wilcoxon \\n Signed-Rank \\n Test with lm\")\n\n\npatchwork::wrap_plots(p1,p2,p3,p4, nrow = 1, guides = \"collect\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/Mean_Related_Plots-1.png){fig-align='center' width=672}\n:::\n:::\n\n\n## Paired Sample t-test {.tabset}\n\nWe use this when we have two samples and the observations from one\nsample can be \"paired\" with observations in the other sample. Controlled\nstudies for interventions/measures, such as before/after kind of data,\ncomparisons between two interventions on the same set of subjects, and\ntwo measurements made on the same subjects using different methods etc.\n\n### Model\n\n$$\ny_2 - y_1 = \\beta_0 \\\\\nH_0 : \\beta_0 = 0\n$$\n\nThe NULL Hypothesis is that there is no difference, **either way**,\nbetween the two samples. Again, in the linear model, we assume as before\nthat \"the explanatory x variable has been equated to zero.\n\nWe therefore set `two.sided` and `mu = 0` in the `t.test`.\n\n### Code\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Using paired t-test\nt2 <- t.test(y2, y, paired = TRUE, mu = 0, \n             alternative = \"two.sided\")\nt2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPaired t-test\n\ndata:  y2 and y\nt = 0.54264, df = 49, p-value = 0.5898\nalternative hypothesis: true mean difference is not equal to 0\n95 percent confidence interval:\n -0.54067  0.94067\nsample estimates:\nmean difference \n            0.2 \n```\n:::\n\n```{.r .cell-code}\n# linear model\nlm2 <- lm(y2-y ~ 1, data = mydata_wide)\nlm2 %>% summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = y2 - y ~ 1, data = mydata_wide)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-4.7027 -2.1872 -0.1367  1.3835  5.7262 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)\n(Intercept)   0.2000     0.3686   0.543     0.59\n\nResidual standard error: 2.606 on 49 degrees of freedom\n```\n:::\n\n```{.r .cell-code}\nlm2 %>% confint()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n               2.5 %  97.5 %\n(Intercept) -0.54067 0.94067\n```\n:::\n:::\n\n\nBoth tests report the difference to be 0.2. However the p-value in both\ntests is about 0.6, so the result is not statistically significant.\n\n### Example\n\n## Wilcoxon Paired Test {.tabset}\n\nWhen the original data is not normally distributed or has outliers etc,.\nwe use a nonparametric Wilcoxon paired test. The difference between the\npaired and unpaired Wilcoxon test is that the test is run on the\nsigned-ranks of the **pairwise differences** y2- y.\n\n### Model\n\n\\$\\$ signed_rank(y2 - y1) = \\beta\\_0 \\\\\n\nH_0: \\beta\\_0 = 0\n\n\\$\\$\n\n### Code\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Paired Wilcoxon Test\nw4 <- wilcox.test(y, y2, paired = TRUE)\nw4\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tWilcoxon signed rank test with continuity correction\n\ndata:  y and y2\nV = 608, p-value = 0.7795\nalternative hypothesis: true location shift is not equal to 0\n```\n:::\n\n```{.r .cell-code}\n# Linear Model\nlm4 <- lm(signed_rank(y2-y) ~ 1 , data = mydata_wide)\nlm4 %>% summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = signed_rank(y2 - y) ~ 1, data = mydata_wide)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n-48.18 -27.93   0.82  22.57  48.82 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)\n(Intercept)    1.180      4.182   0.282    0.779\n\nResidual standard error: 29.57 on 49 degrees of freedom\n```\n:::\n\n```{.r .cell-code}\n# t-test with Signed Rank\nt4 <- t.test(signed_rank(y2-y), mu = 0 , alternative = \"two.sided\")\nt4\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tOne Sample t-test\n\ndata:  signed_rank(y2 - y)\nt = 0.28214, df = 49, p-value = 0.779\nalternative hypothesis: true mean is not equal to 0\n95 percent confidence interval:\n -7.224733  9.584733\nsample estimates:\nmean of x \n     1.18 \n```\n:::\n:::\n\n\nHere too, the p-values reported by the three tests are p = 0.779 so the\ndifference reported is not significant.\n\n### Example\n\n# Tests with Two Means {.tabset}\n\nWhen we have two independent samples and these are *not paired* as\nearlier. The intent is to test if there is a significant difference to\ntheir means. An example is identical measurements on two sets of\nsubjects.\n\nThere is considerable discussion on what test to use when: 1.If\nvariances are equal between samples, observations are normally\ndistributed within groups, no outliers, then `independent t-test` 2. If\nunequal variance, `t-test` with `Welch correction` ( Welch's t-test) 3.\nIf samples are not normal, then nonparametric test ( Wilcoxon with two\nsamples = `Mann-Whitney test`). Symmetry of the distribution is assumed\nhere.\n\n## Dummy Group Variable Concept\n\nAn important construct here is the **dummy variable**. When there is\nmore than one group in the data, a dummy *categorical variable* is set\nup, whose entries specify the group ID. The group IDs are **still\nnumerical** ( as with factors, remember ). The dummy variable is plotted\non the x-axis. The consecutive IDs in the dummy variable x are separated\nby *1*. Hence the *between-groups difference* in the stat measures\ncomputed on y are numerically equivalent to the **slope** in the linear\nmodel. Thus the *dummy variable* allows us to \\*\\*mathematically\\* use\nthe linear model, as presented in the equations above.\n\nDummy variables become even more useful when the explanatory variable (\n\"x-planatory\" ) is already categorical, as with ANOVA and friends.\n\nWe can visualize this as follows:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmydata_wide_new <- \n  tibble(y1 = rnorm(50, mean = 0, sd = 0.5),\n         y2 = rnorm(50, mean = 1.2, sd = 0.5)) %>%\n  pivot_longer(cols = c(y1, y2),\n               names_to = \"variable\",  \n               values_to = \"values\") %>% \n  cbind(group = rep(0:1, 50))\n\nmydata_wide_new %>% \n  ggplot(aes(x = group, y = values)) + \n  geom_point() + \n  stat_summary(fun = \"mean\", colour = \"red\", size = 4, geom =\"point\") +\n  stat_summary(fun = \"mean\", geom= \"line\", colour = \"blue\", lty = 2) +\n  xlab(\"Dummy Variable to show groups\") +\n  ylab(\"y1 and y2, on the same scale\") +\n  scale_x_discrete(name = \"Dummy Variable x_i  [0,1]\",\n                limits = c(0,1)) +\n  annotate(\"text\", x = 0, y = 1.5, label = \"Difference in means \\n equals slope in linear model\") \n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/Independent_Data_Plots-1.png){fig-align='center' width=672}\n:::\n\n```{.r .cell-code}\n# Need to use `glue` here to add more annotations\n# Math annotation on graphs\n```\n:::\n\n\n## Model\n\n$$\ny_i = \\beta_0 + \\beta_1 * x_i \\\\\nwhere\\\\\nx_i= \\left\\{\\begin{matrix}\n1\\ when\\ x\\ \\in\\ Group 1\\\\ \n0\\ when\\ x\\ \\in\\ Group2\n\\end{matrix}\\right.\n$$\n\n#  {.unnumbered}\n\nLet us now look at the tests.\n\n## Independent t-test {.tabset}\n\n### Model\n\nThe assumptions here are: - both data sets are normally distributed.\nSmall samples may be assumned to be `t-distributed` - variances are the\nsame - no outliers - observations across data sets are independent\n(obviously)\n\n$$\ny_i = \\beta_0 + \\beta_1 * x_i \\\\\nwhere \\\\\nx_i= \\left\\{\\begin{matrix}\n1\\ when\\ x\\ \\in\\ Group 1\\\\ \n0\\ when\\ x\\ \\in\\ Group2\n\\end{matrix}\\right.\n\\\\\nH_0 : \\beta_1 = 0\n$$\n\nThe t.test computes a statistic as follows:\n\n$$\nt \\ \\ = \\mod(\\bar{x_1}\\ - \\bar{x_2}) / std.error(\\bar{x_1}\\ - \\bar{x_2}) \\\\\n= \\mod(\\bar{x_1} - \\bar{x_2})\\ / \\sqrt{s_x^2 /n_x + s_y^2/n_y}  \\\\\nand\\\\\ndf = n_1 + n_2 - 2\\ \\ \\ \\ ( degrees\\ of\\ freedom)\n$$\n\nThe t-test uses an approximation to the sampling distribution of the\ndifference in sample means based on the Central Limit Theorem, which\nensures that for sufficiently large samples, the sampling distribution\nwill be very close to Normal. The mean of the sampling distribution will\nbe the difference in (underlying) population means, and the variance of\nthe sampling distribution will be the standard error of the difference\nin sample means.\n\nFor the `t-statistic`, note that the numerator of the formula is the\ndifference between means. The denominator is a measurement of\nexperimental error in the two groups combined. The wider the difference\nbetween means, the more confident you are in the data. The more\nexperimental error you have, the less confident you are in the data.\nThus the higher the value of t, the greater the confidence that there is\na difference.\n\nThe `t-statistic` has a t-distribution. It is compared to a *critical\nvalue* of t, for a given probability value ( 0.05 usually). If the\ncalculated t exceeds the critical value, we can assert that the NULL\nHypothesis can be rejected and there could be a significant difference\nin means. ![t-distribution curves](t-distribution.png)\n\n### Code\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Independent t-test\nt5 <- t.test(y2, y, var.equal = TRUE)\nt5 %>% tidy() \n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"estimate\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"estimate1\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"estimate2\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"statistic\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"p.value\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"parameter\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"conf.low\"],\"name\":[7],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"conf.high\"],\"name\":[8],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"method\"],\"name\":[9],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"alternative\"],\"name\":[10],\"type\":[\"chr\"],\"align\":[\"left\"]}],\"data\":[{\"1\":\"0.2\",\"2\":\"0.5\",\"3\":\"0.3\",\"4\":\"0.5656854\",\"5\":\"0.5729006\",\"6\":\"98\",\"7\":\"-0.5016152\",\"8\":\"0.9016152\",\"9\":\"Two Sample t-test\",\"10\":\"two.sided\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\n# Welch test when variances are not equal\nt6 <- t.test(y2,y, var.equal = FALSE)\nt6 %>% tidy()\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"estimate\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"estimate1\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"estimate2\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"statistic\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"p.value\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"parameter\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"conf.low\"],\"name\":[7],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"conf.high\"],\"name\":[8],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"method\"],\"name\":[9],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"alternative\"],\"name\":[10],\"type\":[\"chr\"],\"align\":[\"left\"]}],\"data\":[{\"1\":\"0.2\",\"2\":\"0.5\",\"3\":\"0.3\",\"4\":\"0.5656854\",\"5\":\"0.5730018\",\"6\":\"90.87537\",\"7\":\"-0.5023034\",\"8\":\"0.9023034\",\"9\":\"Welch Two Sample t-test\",\"10\":\"two.sided\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\n# Linear Model with Dummy variable\n# lm(value ~ 1 + group, data = mydata_long_y) # also works\nlm6 <- lm(value ~ 1 + I(group == \"y2\"), data = mydata_long_y)\nlm6 %>% tidy()\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"term\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"estimate\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"std.error\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"statistic\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"p.value\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"(Intercept)\",\"2\":\"0.3\",\"3\":\"0.2500000\",\"4\":\"1.2000000\",\"5\":\"0.2330323\"},{\"1\":\"I(group == \\\"y2\\\")TRUE\",\"2\":\"0.2\",\"3\":\"0.3535534\",\"4\":\"0.5656854\",\"5\":\"0.5729006\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nWe get the same estimates for means of y and y2 ( 0.3 and 0.5\nrespectively).\n\n### Example\n\n## Welch's t-test {.tabset}\n\n### Model\n\nWelch's test we have already explored as a variant of the t.test for two\nmeans, with variances unequal.\n\nWelch's test is also stated as a *Generalized* Linear Model using, not\n`lm` but the `gls` command from the `nlme` package. This is explained on\n[StackExchange](https://stats.stackexchange.com/questions/142685/equivalent-to-welchs-t-test-in-gls-framework)\nbut we need not digress now.\n\nWhen the variances are unequal, there is a difference in the t-statistic\nthat is computed *only* when the group \\*\\*sizes\\* are different (\nDenominator of t-statistic ).\n\nFrom StackExchange:\\\n$$\nt_w =\\ \\frac {\\bar{x_1}-\\bar{x_2}}{\\sqrt{{s_1^2/n_1}{s_2^2/n_2}}} \n\\\\\\\\\n=\\ \\frac{\\bar{x_1}-\\bar{x_2}} {{\\sqrt{\\frac{s_1^2 + s_2^2}{n}}}} \n\\\\\\\\\n=\\ \\frac{\\bar{x_1}-\\bar{x_2}} {{\\sqrt{\\frac{s_1^2 + s_2^2} {2} * (\\frac{2}{n})}}} \n\\\\\\\\\n=\\ t_s\n$$\n\nSo under these conditions the t-statistic for the Welch t-test is the\nsame as that for the standard t-test.\n\n### Code\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nt7 <- t.test(y, y2, var.equal = FALSE)\n```\n:::\n\n\n### Example\n\n## Mann-Whitney U Test {.tabset}\n\n(Wilcoxon Independent Sample test)\n\nAs before, when sample groups are not normally distributed, and when\nvariances are different, and they are outliers, a nonparametric rank-sum\ntest is preferred. This is the same as the Wilcoxon Test for independent\nvariables, and is called the Mann-Whitney Test.\n\n### Model\n\nAs before:\n\n$$\nrank(y_i) = \\beta_0 + \\beta_1 * rank(x_i) \\\\\nwhere \\\\\nx_i= \\left\\{\\begin{matrix}\n1\\ when\\ x\\ \\in\\ Group 1\\\\ \n0\\ when\\ x\\ \\in\\ Group2\n\\end{matrix}\\right.\n\\\\\nH_0 : \\beta_1 = 0\n$$\n\n### Code\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# As Wilcoxon Test\nw5 <- wilcox.test(y2,y, paired = FALSE)\nw5 %>% tidy()\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"statistic\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"p.value\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"method\"],\"name\":[3],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"alternative\"],\"name\":[4],\"type\":[\"chr\"],\"align\":[\"left\"]}],\"data\":[{\"1\":\"1264\",\"2\":\"0.9258507\",\"3\":\"Wilcoxon rank sum test with continuity correction\",\"4\":\"two.sided\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\n# As Linear model\nlm5 <- lm(rank(value) ~ 1 + I(group == \"y2\"), \n          data = mydata_long_y)\nlm5 %>% tidy()\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"term\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"estimate\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"std.error\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"statistic\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"p.value\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"(Intercept)\",\"2\":\"50.22\",\"3\":\"4.123530\",\"4\":\"12.17888471\",\"5\":\"2.504281e-21\"},{\"1\":\"I(group == \\\"y2\\\")TRUE\",\"2\":\"0.56\",\"3\":\"5.831552\",\"4\":\"0.09602932\",\"5\":\"9.236934e-01\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nNot clear how to explain this. Need to dig more into Mann-Whitney.\n\n### Example\n\n# Tests with Three or More Means {.tabset}\n\n## Model\n\nANOVAs are linear models with (only) categorical predictors so they\nsimply extend everything we did above, relying heavily on dummy coding.\n\n## One-way ANOVA {.tabset}\n\n### Model\n\nOne mean for each group predicts y.\n\n$$\ny=\\beta_0 + \\beta_1*x_1 + \\beta_2*x_2...+\\beta_n*x_n\\\\\nH0:y=β0\n$$\n\nwhere $x_i$ are indicators (x=0 or x=1) where at most one $x_i=1$ while\nall others are $x_i=0$.\n\nNotice how this is just \"more of the same\" of what we already did in\nother models above. When there are only two groups, this model is\n$y=β0+β1∗x$, i.e. the *independent t-test*. If there is only one group,\nit is $y=β0$, i.e. the *one-sample t-test*. This makes *one-way ANOVA* a\n**multiple regression** model.\n\nThis is easy to see in the visualization below - just cover up a few\ngroups and see that it matches the other visualizations above. Let's\nvisualize this using toy data:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nN = 15\nD_anova1 = data.frame(\n  y = c(\n    rnorm_fixed(N, 0.5, 0.3),\n    rnorm_fixed(N, 0, 0.3),\n    rnorm_fixed(N, 1, 0.3),\n    rnorm_fixed(N, 0.8, 0.3)\n  ),\n  x = rep(0:3, each = 15)\n)\nymeans = aggregate(y~x, D_anova1, mean)$y\nP_anova1 = ggplot(D_anova1, aes(x=x, y=y)) + \n  stat_summary(fun.y=mean, geom = \"errorbar\", aes(ymax = ..y.., ymin = ..y.., color='intercepts'), lwd=2) + \n  \n  geom_segment(x = -10, xend = 100, \n               y = 0.5, yend = 0.5, \n               lwd = 2, aes(color = 'beta_0')) +\n  geom_segment(x = 0, xend = 1, \n               y = ymeans[1], yend = ymeans[2], \n               lwd = 2, aes(color = 'betas')) +\n  geom_segment(x = 1, xend = 2, \n               y = ymeans[1], yend = ymeans[3], \n               lwd = 2, aes(color = 'betas')) +\n  geom_segment(x = 2, xend = 3, \n               y = ymeans[1], yend = ymeans[4], \n               lwd = 2, aes(color = 'betas')) +\n  \n  scale_color_manual(name = NULL, \n                     values = c(\"blue\", \"red\", \"darkblue\"),\n                     labels=c(bquote(beta[0]*\" (group 1 mean)\"),\n                              bquote(beta[1]*\", \"*beta[2]*\", \n                                     etc. (slopes/differences to \"*beta[0]*\")\"),\n      bquote(beta[0]*\"+\"*beta[1]*\", \"*beta[0]*\"+\"*beta[2]*\", etc. (group 2, 3, ... means)\")\n    )\n  )\nP_anova1\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/Visualizing_One_way_ANOVA-1.png){fig-align='center' width=672}\n:::\n:::\n\n\n### Code\n\n### Example\n\n## Two-way ANOVA {.tabset}\n\n### Model\n\n### Code\n\n### Example\n\n## ANCOVA {.tabset}\n\n### Model\n\n### Code\n\n### Example\n\n# Proportions {.tabset}\n\n## Model\n\n## Discrete Variables {.tabset}\n\n### Model\n\n### Code\n\n### Example\n\n## Continuous Variables {.tabset}\n\n### Model\n\n### Code\n\n### Example\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../../../../../../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\r\n<script src=\"../../../../../../../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}