---
title: <iconify-icon icon="streamline-emojis:canada"></iconify-icon> Canada - John Cheever
subtitle: "The Enormous Radio"
date: 2021-12-28
order: 140

---

```{r setup, include=FALSE}
library(blogdown)
```

## John Cheever




### Story
We will read Cheever's dystopian tech story, <u>[The Enormous Radio](Enormous_Radio_cheever.docx)</u>.

## Themes

- Communications Technology: Boon and Bane
- "Sweet Old Tech"
- Uses of Tech, and Used by Tech
- "We Wish to Be SomeWhere We are Not"
- "We Wish to Be Some~When~Time We are Not"
- "We Wish to Be SomeOne We are Not"
- "We Wish to Be SomeThing We are Not"
- Forbidden Knowledge
- Love Thy Neighbour
- 
## Additional Material
### Notes and References




 
## Song for the Story !!

Song: Somebody's Watching Me\
Group: Rockwell and Michael Jackson\
Release Date: Pongal / Makara Sankranthi, January 14, 1984\

>"Somebody's Watching Me" is a song recorded by American singer Rockwell (Kennedy Gordy), released by the Motown label in 1984, as the lead single from his debut studio album of the same name. Rockwell's debut single release, the song features guest vocals by brothers Michael Jackson (in the chorus) and Jermaine Jackson (additional backing vocals).

{{< youtube pHS4IUP8dDw >}}\
 
 Also listen to <u>[The Buggles - Video Killed the Radio Star](https://youtu.be/vRAn0ZM2TGM)</u> and <u>[Queen - Radio Gaga](https://youtu.be/pMYCOYjIKrE)</u>.
 
## Writing Prompts
1. On being Average, or being thought to be Average
1. Am I using [your favourite SM app] or is it using me?
1. On Human Dreams and Technology. Take inspiration from <u>[Robert Lucky *New Communications Services --What does Society want?*](Robert Lucky - Telecom-What does Society Want.pdf)</u>. Look especially on the Section VI. therein on *Fulfilling Ancient Dreams*.
1. On bugs in internet apps. Take inspiration from Vinton G. Cerf's famous Internet document in poetry form, RFC968 <u><https://datatracker.ietf.org/doc/html/rfc968></u>.

 

