{
  "hash": "1ee9efcd173eb2583add2e724e6fbc31",
  "result": {
    "markdown": "---\ntitle: \"\\U0001F0CF Inference for a Single Mean\"\nauthor: \"Arvind Venkatadri\"\ndate: 10/Nov/2022\ndate-modified: \"2023-12-31\"\nabstract: \"Inference Tests to check the significance of a single Mean\"\norder: 100\ncategories:\n- t.test\n- Linear Model\n- Inference\n- Bootstrap\n- Null Distributions\n- Generating Parallel Worlds\nbibliography: \n  - grateful-refs.bib\ncitation: true\n#suppress-bibliography: true\n---\n\n\n## {{< iconify noto-v1 package >}} Setting up R packages\n\n\n::: {.cell hash='single-mean_cache/html/setup_4b4e3216e477aa7b5c24834540cb4266'}\n\n```{.r .cell-code}\nknitr::opts_chunk$set(echo = TRUE,message = TRUE,warning = TRUE, fig.align = \"center\")\noptions(digits=2)\nlibrary(tidyverse)\nlibrary(mosaic)\nlibrary(infer)\n### Dataset from Chihara and Hesterberg's book (Second Edition)\nlibrary(resampledata)\nlibrary(openintro) # datasets\n```\n:::\n\n::: {.cell hash='single-mean_cache/html/Extra Pedagogical Packages_23e72fd1f81f63445140f5ca2d50ffe1'}\n\n:::\n\n\n## Introduction\n\nWe saw from the diagram created by Allen Downey that *there is only one\ntest* [^1]! We will now use this philosophy to develop a technique that\nallows us to mechanize several *Statistical Models* in that way, with\nnearly identical code.\n\nWe will use two packages in R, `mosaic` to develop our intuition for\nwhat are called **bootstrap randomization** based statistical tests.\n(There is also a more recent package called `infer` in R which can do\npretty much all of this, including visualization. In my opinion, the\ncode is a little too high-level and does not offer quite the detailed\ninsight that the `mosaic` package does).\n\n## {{< iconify pajamas issue-type-test-case >}} Case Study #1: Toy data\n\nFirst we will use a toy dataset with three \"imaginary\" samples,\n$x, y, y2$. Each is normally distributed and made up of 50 observations.\n\nWe start by creating a function that will allow us to produce samples of\na given size (N) with a specified mean (mu) and standard deviation (sd).\n\n\n::: {.cell hash='single-mean_cache/html/data_genr_51a0b3da0ac989808854d9ad9c552af0'}\n\n```{.r .cell-code}\nrnorm_fixed  <- function(N, mu = 0, sd = 1) {\n  scale(rnorm(N))* sd + mu\n}\n```\n:::\n\n\nWe create three variables: x ( explanatory) and y, y2 ( dependent ).\n\n\n::: {.cell .column-body-outset-right layout-ncol=\"3\" hash='single-mean_cache/html/toy_data_81078a45a12f96db6ca45e2d558493f0'}\n\n```{.r .cell-code}\nset.seed(40) # for replication\n\n# Data as vectors ( for t.tests etc)\nx <- rnorm_fixed(50, mu = 0.0, sd = 1) #explanatory\ny <- rnorm_fixed(50, mu = 0.3, sd = 2) # dependent #1\ny2 <- rnorm_fixed(50, mu = 0.5, sd = 1.5) # dependent #2\n\n# Make a tibble with all variables\nmydata_wide <- tibble(x = x, y = y, y2 = y2)\n\n# Long form data\nmydata_long <- \n  mydata_wide %>%\n  pivot_longer(., cols = c(x,y,y2), \n               names_to = \"group\", \n               values_to = \"value\")\n\n# Long form data with only dependent variables\nmydata_long_y <- \n  mydata_wide %>% \n  select(-x) %>% \n  pivot_longer(., cols = c(y,y2), \n               names_to = \"group\", \n               values_to = \"value\")\nmydata_wide\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"x\"],\"name\":[1],\"type\":[\"dbl[,1]\"],\"align\":[\"right\"]},{\"label\":[\"y\"],\"name\":[2],\"type\":[\"dbl[,1]\"],\"align\":[\"right\"]},{\"label\":[\"y2\"],\"name\":[3],\"type\":[\"dbl[,1]\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"0.42678011\",\"2\":\"1.98488355\",\"3\":\"0.10303468\"},{\"1\":\"0.44408399\",\"2\":\"1.27130904\",\"3\":\"-0.28089065\"},{\"1\":\"-0.82789086\",\"2\":\"-0.94427745\",\"3\":\"0.62388864\"},{\"1\":\"-0.79925305\",\"2\":\"0.10328425\",\"3\":\"5.42679005\"},{\"1\":\"-0.32313106\",\"2\":\"2.19041969\",\"3\":\"0.16807478\"},{\"1\":\"-1.24462433\",\"2\":\"0.19192798\",\"3\":\"-0.54936141\"},{\"1\":\"-1.35506516\",\"2\":\"4.81186172\",\"3\":\"0.30919557\"},{\"1\":\"1.61563907\",\"2\":\"1.55169550\",\"3\":\"-0.99039138\"},{\"1\":\"-0.29189503\",\"2\":\"3.35737558\",\"3\":\"-0.17200537\"},{\"1\":\"-1.24940474\",\"2\":\"1.92492196\",\"3\":\"-0.15832838\"},{\"1\":\"-0.08659233\",\"2\":\"-2.88047669\",\"3\":\"0.85387666\"},{\"1\":\"-1.17065349\",\"2\":\"1.75053169\",\"3\":\"3.33911133\"},{\"1\":\"0.73756421\",\"2\":\"-1.08428013\",\"3\":\"-1.88393968\"},{\"1\":\"-0.48316590\",\"2\":\"0.96031018\",\"3\":\"2.48425274\"},{\"1\":\"0.40328291\",\"2\":\"-1.54016895\",\"3\":\"-0.04867594\"},{\"1\":\"0.91641886\",\"2\":\"-1.24357666\",\"3\":\"-0.61515773\"},{\"1\":\"0.41673257\",\"2\":\"0.03193645\",\"3\":\"-0.28681098\"},{\"1\":\"0.33137777\",\"2\":\"-1.30918647\",\"3\":\"-0.12350146\"},{\"1\":\"1.57677526\",\"2\":\"-0.99658718\",\"3\":\"0.29936602\"},{\"1\":\"-0.99289810\",\"2\":\"1.42150401\",\"3\":\"-1.06763475\"},{\"1\":\"1.22460582\",\"2\":\"-0.90365732\",\"3\":\"0.12124860\"},{\"1\":\"-0.57899018\",\"2\":\"2.94554205\",\"3\":\"-0.40094019\"},{\"1\":\"1.49026764\",\"2\":\"2.57375451\",\"3\":\"-1.55553594\"},{\"1\":\"-1.06533835\",\"2\":\"-1.21795541\",\"3\":\"-0.51902218\"},{\"1\":\"-1.39136994\",\"2\":\"-2.10136309\",\"3\":\"-0.24857353\"},{\"1\":\"0.66547299\",\"2\":\"0.90556693\",\"3\":\"1.35671958\"},{\"1\":\"-1.53224607\",\"2\":\"0.53146356\",\"3\":\"0.14529688\"},{\"1\":\"0.29011158\",\"2\":\"0.90084614\",\"3\":\"0.83560170\"},{\"1\":\"0.69239937\",\"2\":\"0.12687786\",\"3\":\"2.29182497\"},{\"1\":\"-1.76053733\",\"2\":\"2.64999575\",\"3\":\"2.73673094\"},{\"1\":\"0.72082239\",\"2\":\"0.13435947\",\"3\":\"0.27574827\"},{\"1\":\"-1.22395587\",\"2\":\"-2.78065291\",\"3\":\"3.14550409\"},{\"1\":\"-0.75311013\",\"2\":\"1.96202837\",\"3\":\"0.59938464\"},{\"1\":\"1.32801392\",\"2\":\"-4.25541004\",\"3\":\"1.04460392\"},{\"1\":\"-0.24174865\",\"2\":\"0.51517469\",\"3\":\"-0.68821620\"},{\"1\":\"0.55292812\",\"2\":\"0.32962526\",\"3\":\"1.15201767\"},{\"1\":\"-1.38976342\",\"2\":\"0.18227394\",\"3\":\"-1.86691141\"},{\"1\":\"0.20633230\",\"2\":\"0.76029377\",\"3\":\"4.27233650\"},{\"1\":\"-0.31920849\",\"2\":\"3.55063527\",\"3\":\"0.45077005\"},{\"1\":\"0.78482776\",\"2\":\"-0.56564635\",\"3\":\"-1.70953625\"},{\"1\":\"1.23964789\",\"2\":\"-2.88080049\",\"3\":\"0.84694745\"},{\"1\":\"0.27462181\",\"2\":\"3.04164950\",\"3\":\"-0.03903472\"},{\"1\":\"1.89759493\",\"2\":\"-1.29407455\",\"3\":\"1.11956044\"},{\"1\":\"-0.19262565\",\"2\":\"-3.42396604\",\"3\":\"1.05156905\"},{\"1\":\"-1.41365701\",\"2\":\"-1.75335473\",\"3\":\"1.49593530\"},{\"1\":\"0.35118649\",\"2\":\"1.82462838\",\"3\":\"1.86447305\"},{\"1\":\"1.45121334\",\"2\":\"-2.37113604\",\"3\":\"1.33013723\"},{\"1\":\"1.17029448\",\"2\":\"2.34340037\",\"3\":\"-0.14230534\"},{\"1\":\"-0.83901696\",\"2\":\"1.86633352\",\"3\":\"-0.39773459\"},{\"1\":\"0.31714653\",\"2\":\"-0.14984045\",\"3\":\"-0.99949269\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\nmydata_long\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"group\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"value\"],\"name\":[2],\"type\":[\"dbl[,1]\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"x\",\"2\":\"0.42678011\"},{\"1\":\"y\",\"2\":\"1.98488355\"},{\"1\":\"y2\",\"2\":\"0.10303468\"},{\"1\":\"x\",\"2\":\"0.44408399\"},{\"1\":\"y\",\"2\":\"1.27130904\"},{\"1\":\"y2\",\"2\":\"-0.28089065\"},{\"1\":\"x\",\"2\":\"-0.82789086\"},{\"1\":\"y\",\"2\":\"-0.94427745\"},{\"1\":\"y2\",\"2\":\"0.62388864\"},{\"1\":\"x\",\"2\":\"-0.79925305\"},{\"1\":\"y\",\"2\":\"0.10328425\"},{\"1\":\"y2\",\"2\":\"5.42679005\"},{\"1\":\"x\",\"2\":\"-0.32313106\"},{\"1\":\"y\",\"2\":\"2.19041969\"},{\"1\":\"y2\",\"2\":\"0.16807478\"},{\"1\":\"x\",\"2\":\"-1.24462433\"},{\"1\":\"y\",\"2\":\"0.19192798\"},{\"1\":\"y2\",\"2\":\"-0.54936141\"},{\"1\":\"x\",\"2\":\"-1.35506516\"},{\"1\":\"y\",\"2\":\"4.81186172\"},{\"1\":\"y2\",\"2\":\"0.30919557\"},{\"1\":\"x\",\"2\":\"1.61563907\"},{\"1\":\"y\",\"2\":\"1.55169550\"},{\"1\":\"y2\",\"2\":\"-0.99039138\"},{\"1\":\"x\",\"2\":\"-0.29189503\"},{\"1\":\"y\",\"2\":\"3.35737558\"},{\"1\":\"y2\",\"2\":\"-0.17200537\"},{\"1\":\"x\",\"2\":\"-1.24940474\"},{\"1\":\"y\",\"2\":\"1.92492196\"},{\"1\":\"y2\",\"2\":\"-0.15832838\"},{\"1\":\"x\",\"2\":\"-0.08659233\"},{\"1\":\"y\",\"2\":\"-2.88047669\"},{\"1\":\"y2\",\"2\":\"0.85387666\"},{\"1\":\"x\",\"2\":\"-1.17065349\"},{\"1\":\"y\",\"2\":\"1.75053169\"},{\"1\":\"y2\",\"2\":\"3.33911133\"},{\"1\":\"x\",\"2\":\"0.73756421\"},{\"1\":\"y\",\"2\":\"-1.08428013\"},{\"1\":\"y2\",\"2\":\"-1.88393968\"},{\"1\":\"x\",\"2\":\"-0.48316590\"},{\"1\":\"y\",\"2\":\"0.96031018\"},{\"1\":\"y2\",\"2\":\"2.48425274\"},{\"1\":\"x\",\"2\":\"0.40328291\"},{\"1\":\"y\",\"2\":\"-1.54016895\"},{\"1\":\"y2\",\"2\":\"-0.04867594\"},{\"1\":\"x\",\"2\":\"0.91641886\"},{\"1\":\"y\",\"2\":\"-1.24357666\"},{\"1\":\"y2\",\"2\":\"-0.61515773\"},{\"1\":\"x\",\"2\":\"0.41673257\"},{\"1\":\"y\",\"2\":\"0.03193645\"},{\"1\":\"y2\",\"2\":\"-0.28681098\"},{\"1\":\"x\",\"2\":\"0.33137777\"},{\"1\":\"y\",\"2\":\"-1.30918647\"},{\"1\":\"y2\",\"2\":\"-0.12350146\"},{\"1\":\"x\",\"2\":\"1.57677526\"},{\"1\":\"y\",\"2\":\"-0.99658718\"},{\"1\":\"y2\",\"2\":\"0.29936602\"},{\"1\":\"x\",\"2\":\"-0.99289810\"},{\"1\":\"y\",\"2\":\"1.42150401\"},{\"1\":\"y2\",\"2\":\"-1.06763475\"},{\"1\":\"x\",\"2\":\"1.22460582\"},{\"1\":\"y\",\"2\":\"-0.90365732\"},{\"1\":\"y2\",\"2\":\"0.12124860\"},{\"1\":\"x\",\"2\":\"-0.57899018\"},{\"1\":\"y\",\"2\":\"2.94554205\"},{\"1\":\"y2\",\"2\":\"-0.40094019\"},{\"1\":\"x\",\"2\":\"1.49026764\"},{\"1\":\"y\",\"2\":\"2.57375451\"},{\"1\":\"y2\",\"2\":\"-1.55553594\"},{\"1\":\"x\",\"2\":\"-1.06533835\"},{\"1\":\"y\",\"2\":\"-1.21795541\"},{\"1\":\"y2\",\"2\":\"-0.51902218\"},{\"1\":\"x\",\"2\":\"-1.39136994\"},{\"1\":\"y\",\"2\":\"-2.10136309\"},{\"1\":\"y2\",\"2\":\"-0.24857353\"},{\"1\":\"x\",\"2\":\"0.66547299\"},{\"1\":\"y\",\"2\":\"0.90556693\"},{\"1\":\"y2\",\"2\":\"1.35671958\"},{\"1\":\"x\",\"2\":\"-1.53224607\"},{\"1\":\"y\",\"2\":\"0.53146356\"},{\"1\":\"y2\",\"2\":\"0.14529688\"},{\"1\":\"x\",\"2\":\"0.29011158\"},{\"1\":\"y\",\"2\":\"0.90084614\"},{\"1\":\"y2\",\"2\":\"0.83560170\"},{\"1\":\"x\",\"2\":\"0.69239937\"},{\"1\":\"y\",\"2\":\"0.12687786\"},{\"1\":\"y2\",\"2\":\"2.29182497\"},{\"1\":\"x\",\"2\":\"-1.76053733\"},{\"1\":\"y\",\"2\":\"2.64999575\"},{\"1\":\"y2\",\"2\":\"2.73673094\"},{\"1\":\"x\",\"2\":\"0.72082239\"},{\"1\":\"y\",\"2\":\"0.13435947\"},{\"1\":\"y2\",\"2\":\"0.27574827\"},{\"1\":\"x\",\"2\":\"-1.22395587\"},{\"1\":\"y\",\"2\":\"-2.78065291\"},{\"1\":\"y2\",\"2\":\"3.14550409\"},{\"1\":\"x\",\"2\":\"-0.75311013\"},{\"1\":\"y\",\"2\":\"1.96202837\"},{\"1\":\"y2\",\"2\":\"0.59938464\"},{\"1\":\"x\",\"2\":\"1.32801392\"},{\"1\":\"y\",\"2\":\"-4.25541004\"},{\"1\":\"y2\",\"2\":\"1.04460392\"},{\"1\":\"x\",\"2\":\"-0.24174865\"},{\"1\":\"y\",\"2\":\"0.51517469\"},{\"1\":\"y2\",\"2\":\"-0.68821620\"},{\"1\":\"x\",\"2\":\"0.55292812\"},{\"1\":\"y\",\"2\":\"0.32962526\"},{\"1\":\"y2\",\"2\":\"1.15201767\"},{\"1\":\"x\",\"2\":\"-1.38976342\"},{\"1\":\"y\",\"2\":\"0.18227394\"},{\"1\":\"y2\",\"2\":\"-1.86691141\"},{\"1\":\"x\",\"2\":\"0.20633230\"},{\"1\":\"y\",\"2\":\"0.76029377\"},{\"1\":\"y2\",\"2\":\"4.27233650\"},{\"1\":\"x\",\"2\":\"-0.31920849\"},{\"1\":\"y\",\"2\":\"3.55063527\"},{\"1\":\"y2\",\"2\":\"0.45077005\"},{\"1\":\"x\",\"2\":\"0.78482776\"},{\"1\":\"y\",\"2\":\"-0.56564635\"},{\"1\":\"y2\",\"2\":\"-1.70953625\"},{\"1\":\"x\",\"2\":\"1.23964789\"},{\"1\":\"y\",\"2\":\"-2.88080049\"},{\"1\":\"y2\",\"2\":\"0.84694745\"},{\"1\":\"x\",\"2\":\"0.27462181\"},{\"1\":\"y\",\"2\":\"3.04164950\"},{\"1\":\"y2\",\"2\":\"-0.03903472\"},{\"1\":\"x\",\"2\":\"1.89759493\"},{\"1\":\"y\",\"2\":\"-1.29407455\"},{\"1\":\"y2\",\"2\":\"1.11956044\"},{\"1\":\"x\",\"2\":\"-0.19262565\"},{\"1\":\"y\",\"2\":\"-3.42396604\"},{\"1\":\"y2\",\"2\":\"1.05156905\"},{\"1\":\"x\",\"2\":\"-1.41365701\"},{\"1\":\"y\",\"2\":\"-1.75335473\"},{\"1\":\"y2\",\"2\":\"1.49593530\"},{\"1\":\"x\",\"2\":\"0.35118649\"},{\"1\":\"y\",\"2\":\"1.82462838\"},{\"1\":\"y2\",\"2\":\"1.86447305\"},{\"1\":\"x\",\"2\":\"1.45121334\"},{\"1\":\"y\",\"2\":\"-2.37113604\"},{\"1\":\"y2\",\"2\":\"1.33013723\"},{\"1\":\"x\",\"2\":\"1.17029448\"},{\"1\":\"y\",\"2\":\"2.34340037\"},{\"1\":\"y2\",\"2\":\"-0.14230534\"},{\"1\":\"x\",\"2\":\"-0.83901696\"},{\"1\":\"y\",\"2\":\"1.86633352\"},{\"1\":\"y2\",\"2\":\"-0.39773459\"},{\"1\":\"x\",\"2\":\"0.31714653\"},{\"1\":\"y\",\"2\":\"-0.14984045\"},{\"1\":\"y2\",\"2\":\"-0.99949269\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\nmydata_long_y\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"group\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"value\"],\"name\":[2],\"type\":[\"dbl[,1]\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"y\",\"2\":\"1.98488355\"},{\"1\":\"y2\",\"2\":\"0.10303468\"},{\"1\":\"y\",\"2\":\"1.27130904\"},{\"1\":\"y2\",\"2\":\"-0.28089065\"},{\"1\":\"y\",\"2\":\"-0.94427745\"},{\"1\":\"y2\",\"2\":\"0.62388864\"},{\"1\":\"y\",\"2\":\"0.10328425\"},{\"1\":\"y2\",\"2\":\"5.42679005\"},{\"1\":\"y\",\"2\":\"2.19041969\"},{\"1\":\"y2\",\"2\":\"0.16807478\"},{\"1\":\"y\",\"2\":\"0.19192798\"},{\"1\":\"y2\",\"2\":\"-0.54936141\"},{\"1\":\"y\",\"2\":\"4.81186172\"},{\"1\":\"y2\",\"2\":\"0.30919557\"},{\"1\":\"y\",\"2\":\"1.55169550\"},{\"1\":\"y2\",\"2\":\"-0.99039138\"},{\"1\":\"y\",\"2\":\"3.35737558\"},{\"1\":\"y2\",\"2\":\"-0.17200537\"},{\"1\":\"y\",\"2\":\"1.92492196\"},{\"1\":\"y2\",\"2\":\"-0.15832838\"},{\"1\":\"y\",\"2\":\"-2.88047669\"},{\"1\":\"y2\",\"2\":\"0.85387666\"},{\"1\":\"y\",\"2\":\"1.75053169\"},{\"1\":\"y2\",\"2\":\"3.33911133\"},{\"1\":\"y\",\"2\":\"-1.08428013\"},{\"1\":\"y2\",\"2\":\"-1.88393968\"},{\"1\":\"y\",\"2\":\"0.96031018\"},{\"1\":\"y2\",\"2\":\"2.48425274\"},{\"1\":\"y\",\"2\":\"-1.54016895\"},{\"1\":\"y2\",\"2\":\"-0.04867594\"},{\"1\":\"y\",\"2\":\"-1.24357666\"},{\"1\":\"y2\",\"2\":\"-0.61515773\"},{\"1\":\"y\",\"2\":\"0.03193645\"},{\"1\":\"y2\",\"2\":\"-0.28681098\"},{\"1\":\"y\",\"2\":\"-1.30918647\"},{\"1\":\"y2\",\"2\":\"-0.12350146\"},{\"1\":\"y\",\"2\":\"-0.99658718\"},{\"1\":\"y2\",\"2\":\"0.29936602\"},{\"1\":\"y\",\"2\":\"1.42150401\"},{\"1\":\"y2\",\"2\":\"-1.06763475\"},{\"1\":\"y\",\"2\":\"-0.90365732\"},{\"1\":\"y2\",\"2\":\"0.12124860\"},{\"1\":\"y\",\"2\":\"2.94554205\"},{\"1\":\"y2\",\"2\":\"-0.40094019\"},{\"1\":\"y\",\"2\":\"2.57375451\"},{\"1\":\"y2\",\"2\":\"-1.55553594\"},{\"1\":\"y\",\"2\":\"-1.21795541\"},{\"1\":\"y2\",\"2\":\"-0.51902218\"},{\"1\":\"y\",\"2\":\"-2.10136309\"},{\"1\":\"y2\",\"2\":\"-0.24857353\"},{\"1\":\"y\",\"2\":\"0.90556693\"},{\"1\":\"y2\",\"2\":\"1.35671958\"},{\"1\":\"y\",\"2\":\"0.53146356\"},{\"1\":\"y2\",\"2\":\"0.14529688\"},{\"1\":\"y\",\"2\":\"0.90084614\"},{\"1\":\"y2\",\"2\":\"0.83560170\"},{\"1\":\"y\",\"2\":\"0.12687786\"},{\"1\":\"y2\",\"2\":\"2.29182497\"},{\"1\":\"y\",\"2\":\"2.64999575\"},{\"1\":\"y2\",\"2\":\"2.73673094\"},{\"1\":\"y\",\"2\":\"0.13435947\"},{\"1\":\"y2\",\"2\":\"0.27574827\"},{\"1\":\"y\",\"2\":\"-2.78065291\"},{\"1\":\"y2\",\"2\":\"3.14550409\"},{\"1\":\"y\",\"2\":\"1.96202837\"},{\"1\":\"y2\",\"2\":\"0.59938464\"},{\"1\":\"y\",\"2\":\"-4.25541004\"},{\"1\":\"y2\",\"2\":\"1.04460392\"},{\"1\":\"y\",\"2\":\"0.51517469\"},{\"1\":\"y2\",\"2\":\"-0.68821620\"},{\"1\":\"y\",\"2\":\"0.32962526\"},{\"1\":\"y2\",\"2\":\"1.15201767\"},{\"1\":\"y\",\"2\":\"0.18227394\"},{\"1\":\"y2\",\"2\":\"-1.86691141\"},{\"1\":\"y\",\"2\":\"0.76029377\"},{\"1\":\"y2\",\"2\":\"4.27233650\"},{\"1\":\"y\",\"2\":\"3.55063527\"},{\"1\":\"y2\",\"2\":\"0.45077005\"},{\"1\":\"y\",\"2\":\"-0.56564635\"},{\"1\":\"y2\",\"2\":\"-1.70953625\"},{\"1\":\"y\",\"2\":\"-2.88080049\"},{\"1\":\"y2\",\"2\":\"0.84694745\"},{\"1\":\"y\",\"2\":\"3.04164950\"},{\"1\":\"y2\",\"2\":\"-0.03903472\"},{\"1\":\"y\",\"2\":\"-1.29407455\"},{\"1\":\"y2\",\"2\":\"1.11956044\"},{\"1\":\"y\",\"2\":\"-3.42396604\"},{\"1\":\"y2\",\"2\":\"1.05156905\"},{\"1\":\"y\",\"2\":\"-1.75335473\"},{\"1\":\"y2\",\"2\":\"1.49593530\"},{\"1\":\"y\",\"2\":\"1.82462838\"},{\"1\":\"y2\",\"2\":\"1.86447305\"},{\"1\":\"y\",\"2\":\"-2.37113604\"},{\"1\":\"y2\",\"2\":\"1.33013723\"},{\"1\":\"y\",\"2\":\"2.34340037\"},{\"1\":\"y2\",\"2\":\"-0.14230534\"},{\"1\":\"y\",\"2\":\"1.86633352\"},{\"1\":\"y2\",\"2\":\"-0.39773459\"},{\"1\":\"y\",\"2\":\"-0.14984045\"},{\"1\":\"y2\",\"2\":\"-0.99949269\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n## \"Signed Rank\" Values\n\nMost statistical tests use the **actual values** of the data variables.\nHowever, in some *non-parametric* statistical tests, the data are used\nin **rank-transformed** sense/order. In some cases the **signed-rank**\nof the data values is used instead of the data itself.\n\nSigned Rank is calculated as follows:\\\n1. Take the absolute value of each observation in a sample\\\n2. Place the <u>*ranks*</u> in order of (absolute magnitude). The\nsmallest number has *rank = 1* and so on.\\\n3. Give each of the ranks the sign of the original observation ( + or -\n)\n\n\n::: {.cell hash='single-mean_cache/html/signed_rank_function_20bf682e9a8998592bab55ebe8af7cd4'}\n\n```{.r .cell-code}\nsigned_rank <- function(x) {sign(x) * rank(abs(x))}\n```\n:::\n\n\n## {{< iconify openmoji japanese-symbol-for-beginner >}} Introduction to Inference for a Single Mean\n\nA series of tests deal with one mean value of a sample. The idea is to\nevaluate whether that mean is representative of the mean of the\nunderlying population. Depending upon the nature of the (single)\nvariable, the test that can be used are as follows:\n\n\n```{mermaid}\nflowchart TD\n    A[Inference for Single Mean] -->|Check Assumptions| B[Normality: Shapiro-Wilk Test shapiro.test\\n]\n    B --> C{OK?}\n    C -->|Yes\\n Parametric| D[t.test]\n    D <-->F[Linear Model\\n with Data] \n    C -->|No\\n Non-Parametric| E[wilcox.test]\n    E <--> G[Linear Model\\n with\\n Signed-Ranks of Data]\n    C -->|No\\n Non-Parametric| P[Bootstrap]\n    P <--> Q[Linear Model\\n with Signed-Rank\\n with Bootstrap]\n \n```\n\n\n## {{< iconify carbon chart-3d >}} Inspecting and Charting Data\n\n### Testing Assumptions in the Data\n\n### Inference\n\n::: {.panel-tabset .nav-pills style=\"background: whitesmoke;\"}\n\n#### The Student's t-test with one sample {.tabset}\n\nA. Model\n\nA single number predicts y:\n\n$$ \ny = \\beta_0 + \\beta_1*x \\\\\n$$ $$\n\\\\and\\ further \\\\\n$$ $$\ny = \\beta_0\\\n$$\n\nand the second term vanishes, since \"there is no x\": all the x-values\nare made equal to zero in the linear model for a **single variable** !!\nThe NULL Hypothesis therefore is:\n\n$$\n\\ H_0: \\beta_0 = 0\n$$\n\nNote that if we **want** the NULL hypothesis to be that the mean is\nother than zero, we can use\n\n$$\nH_0:\\ \\beta_0 = \\mu \\ne 0\n$$ the `lm(...., mu = some_number, ..)` parameter in the command in the\ncode.\n\nB. Code\n\nIf we compare the `t.test` with the appropriate `lm` model:\n\n\n::: {.cell hash='single-mean_cache/html/t_test_one_mean_6e6b8f1c1ed65b012aa4f3287c5f1c20'}\n\n```{.r .cell-code}\n# t-test\nt1 <- t.test(y, mu = 0, alternative = \"two.sided\")\nprint(t1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tOne Sample t-test\n\ndata:  y\nt = 1.0607, df = 49, p-value = 0.294\nalternative hypothesis: true mean is not equal to 0\n95 percent confidence interval:\n -0.2683937  0.8683937\nsample estimates:\nmean of x \n      0.3 \n```\n:::\n:::\n\n\nSo even though y has a mean of 0.3, the confidence intervals straddle\nzero, and hence we cannot reject the NULL hypothesis that the true\npopulation, of which y is a sample, could have mean=0.\n\n#### Wilcoxon's Signed-Rank Test\n\nSince we are dealing with the **mean**, the *sign* of the rank becomes\nimportant to use, in the case of a non-parametric single mean test.\n\nA. Model\n\n$$\nsigned\\_rank(y) = \\beta_0 \\\\\nH_0: \\beta_0 = 0\n$$\n\nB. Code\n\n\n::: {.cell hash='single-mean_cache/html/Wilcoxon_Signed_Rank_test_One_Mean_1b05a4f6ead1b5c751ab3ee7927ebd5b'}\n\n```{.r .cell-code}\n# Standard Wilcoxon Signed_Rank Test\nw1 <- wilcox.test(y)\nw1\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tWilcoxon signed rank test with continuity correction\n\ndata:  y\nV = 754, p-value = 0.2628\nalternative hypothesis: true location is not equal to 0\n```\n:::\n\n```{.r .cell-code}\n# Wilcoxon test with lm\nw2 <- lm(signed_rank(y) ~ 1 , data = mydata_wide)\nw2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = signed_rank(y) ~ 1, data = mydata_wide)\n\nCoefficients:\n(Intercept)  \n       4.66  \n```\n:::\n\n```{.r .cell-code}\n# t-test with signed_rank data\nw3 <- t.test(signed_rank(y))\nw3\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tOne Sample t-test\n\ndata:  signed_rank(y)\nt = 1.1277, df = 49, p-value = 0.265\nalternative hypothesis: true mean is not equal to 0\n95 percent confidence interval:\n -3.644491 12.964491\nsample estimates:\nmean of x \n     4.66 \n```\n:::\n:::\n\n\n#### Linear Model\n\n\n::: {.cell hash='single-mean_cache/html/unnamed-chunk-4_2feba38cc1805d94148806a3cb759f29'}\n\n```{.r .cell-code}\n# linear model\nlm1 <- lm(y ~ 1, data = mydata_wide)\nlm1 %>% summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = y ~ 1, data = mydata_wide)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-4.5554 -1.4845 -0.0392  1.5559  4.5119 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)\n(Intercept)   0.3000     0.2828   1.061    0.294\n\nResidual standard error: 2 on 49 degrees of freedom\n```\n:::\n\n```{.r .cell-code}\nlm1 %>% confint()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                 2.5 %    97.5 %\n(Intercept) -0.2683937 0.8683937\n```\n:::\n:::\n\n\nThe confidence intervals for both the `t.test` and the `lm` model are\nidentical.\n\nt-test confidence intervals: -0.2683937, 0.8683937\\\nlinear model confidence intervals: -0.2683937, 0.8683937\n\n#### Using `bootstrap`\n\n#### Plots\n\nWe can plot the y data both original and ranked to see where the mean\nlies in each case. The approximation to the true $\\beta_0$ ( is good\nwhen the number of observations $n >=50$. Lindoloev has a [simulation on\nthis.](https://lindeloev.github.io/tests-as-linear/simulations/simulate_wilcoxon.html).\nWe can also plot the model using *lm* for both the original data and the\nsign-ranked data.\n\n\n::: {.cell hash='single-mean_cache/html/Mean_Related_Plots_4a2e2d52adc25c3a544728611acddf74'}\n\n```{.r .cell-code}\np1 <- ggplot(mydata_wide, aes( x = 0, y = y)) +\n  geom_point(alpha = 0.4) +\n  geom_segment(aes(y = t1$estimate, \n                   yend = t1$estimate, \n                   x = -0.2, xend = 0.2)) + \n  labs(title = \"Student's\\n t-Test\")\n\n# t-test using linear model\np2 <- ggplot(mydata_wide, aes( x = 0, y = y)) +\n  geom_point(alpha = 0.4) +\n  geom_segment(aes(y = lm(y ~ 1)$coefficient, \n                   yend = lm(y ~ 1)$coefficient, \n                   x = -0.2, xend = 0.2)) + \n  labs(title = \"Student's\\n t-Test \\n using lm\")\n\n# Wilcoxon test, using signed-ranks of data\np3 <- ggplot(mydata_wide, aes( x = 0, y = signed_rank(y))) +\n  geom_point(alpha = 0.4) +\n  geom_segment(aes(y = mean(signed_rank(y)), yend = mean(signed_rank(y)), x = -0.2, xend = 0.2)) + \n  labs(title = \"Wilcoxon \\nSigned-Rank\\n Test\")\n\n# Wilcoxon test, using signed-ranks of data, and lm\np4 <- ggplot(mydata_wide, aes( x = 0, y = signed_rank(y))) +\n  geom_point(alpha = 0.4) +\n  geom_segment(aes(y = lm(signed_rank(y) ~1)$coefficient, \n                   yend = lm(signed_rank(y) ~1)$coefficient, \n                   x = -0.2, xend = 0.2)) + \n  labs(title = \"Wilcoxon \\n Signed-Rank \\n Test with lm\")\n\n\npatchwork::wrap_plots(p1,p2,p3,p4, nrow = 1, guides = \"collect\")\n```\n\n::: {.cell-output-display}\n![](single-mean_files/figure-html/Mean_Related_Plots-1.png){width=2100}\n:::\n:::\n\n:::\n\n## {{< iconify pajamas issue-type-test-case >}} Case Study #2: Exam data\n\nLet us now choose a dataset from the `openintro` package:\n\n\n::: {.cell hash='single-mean_cache/html/unnamed-chunk-5_d725dcf18392dc1211fcc217fec15c7c'}\n\n```{.r .cell-code}\ndata(\"exam_grades\")\nexam_grades\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"semester\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"sex\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"exam1\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"exam2\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"exam3\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"course_grade\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"2000-1\",\"2\":\"Man\",\"3\":\"84.5000\",\"4\":\"69.5\",\"5\":\"86.5000\",\"6\":\"76.2564\"},{\"1\":\"2000-1\",\"2\":\"Man\",\"3\":\"80.0000\",\"4\":\"74.0\",\"5\":\"67.0000\",\"6\":\"75.3882\"},{\"1\":\"2000-1\",\"2\":\"Man\",\"3\":\"56.0000\",\"4\":\"70.0\",\"5\":\"71.5000\",\"6\":\"67.0564\"},{\"1\":\"2000-1\",\"2\":\"Man\",\"3\":\"64.0000\",\"4\":\"61.0\",\"5\":\"67.5000\",\"6\":\"63.4538\"},{\"1\":\"2000-1\",\"2\":\"Man\",\"3\":\"90.5000\",\"4\":\"72.5\",\"5\":\"75.0000\",\"6\":\"72.3949\"},{\"1\":\"2000-1\",\"2\":\"Man\",\"3\":\"74.0000\",\"4\":\"78.5\",\"5\":\"84.5000\",\"6\":\"71.4128\"},{\"1\":\"2000-1\",\"2\":\"Man\",\"3\":\"60.5000\",\"4\":\"44.0\",\"5\":\"58.0000\",\"6\":\"56.0949\"},{\"1\":\"2000-1\",\"2\":\"Man\",\"3\":\"89.0000\",\"4\":\"82.0\",\"5\":\"88.0000\",\"6\":\"78.0103\"},{\"1\":\"2000-1\",\"2\":\"Woman\",\"3\":\"87.5000\",\"4\":\"86.5\",\"5\":\"95.0000\",\"6\":\"82.9026\"},{\"1\":\"2000-1\",\"2\":\"Man\",\"3\":\"91.0000\",\"4\":\"98.0\",\"5\":\"88.0000\",\"6\":\"89.0846\"},{\"1\":\"2000-1\",\"2\":\"Man\",\"3\":\"79.5000\",\"4\":\"88.0\",\"5\":\"56.0000\",\"6\":\"72.9769\"},{\"1\":\"2000-1\",\"2\":\"Man\",\"3\":\"96.0000\",\"4\":\"91.5\",\"5\":\"78.0000\",\"6\":\"82.5282\"},{\"1\":\"2000-1\",\"2\":\"Man\",\"3\":\"55.0000\",\"4\":\"79.5\",\"5\":\"72.0000\",\"6\":\"69.9872\"},{\"1\":\"2000-1\",\"2\":\"Man\",\"3\":\"80.0000\",\"4\":\"83.5\",\"5\":\"70.0000\",\"6\":\"67.7256\"},{\"1\":\"2000-1\",\"2\":\"Woman\",\"3\":\"64.5000\",\"4\":\"83.5\",\"5\":\"77.0000\",\"6\":\"80.3051\"},{\"1\":\"2000-1\",\"2\":\"Man\",\"3\":\"73.0000\",\"4\":\"90.0\",\"5\":\"96.0000\",\"6\":\"74.8744\"},{\"1\":\"2000-1\",\"2\":\"Man\",\"3\":\"83.0000\",\"4\":\"79.0\",\"5\":\"65.0000\",\"6\":\"71.1615\"},{\"1\":\"2000-1\",\"2\":\"Man\",\"3\":\"72.0000\",\"4\":\"91.0\",\"5\":\"90.0000\",\"6\":\"76.5615\"},{\"1\":\"2000-1\",\"2\":\"Woman\",\"3\":\"57.9000\",\"4\":\"53.0\",\"5\":\"47.0000\",\"6\":\"56.9903\"},{\"1\":\"2000-1\",\"2\":\"Man\",\"3\":\"89.0000\",\"4\":\"83.5\",\"5\":\"78.5000\",\"6\":\"80.8026\"},{\"1\":\"2000-1\",\"2\":\"Woman\",\"3\":\"69.0000\",\"4\":\"57.0\",\"5\":\"88.0000\",\"6\":\"69.4308\"},{\"1\":\"2000-1\",\"2\":\"Woman\",\"3\":\"91.0000\",\"4\":\"91.0\",\"5\":\"95.5000\",\"6\":\"92.0051\"},{\"1\":\"2000-1\",\"2\":\"Man\",\"3\":\"68.0000\",\"4\":\"84.5\",\"5\":\"64.0000\",\"6\":\"67.9051\"},{\"1\":\"2000-1\",\"2\":\"Man\",\"3\":\"83.0000\",\"4\":\"89.5\",\"5\":\"93.0000\",\"6\":\"79.7872\"},{\"1\":\"2000-1\",\"2\":\"Man\",\"3\":\"72.0000\",\"4\":\"77.5\",\"5\":\"67.0000\",\"6\":\"67.1256\"},{\"1\":\"2000-1\",\"2\":\"Woman\",\"3\":\"56.0000\",\"4\":\"45.0\",\"5\":\"61.0000\",\"6\":\"58.6308\"},{\"1\":\"2000-1\",\"2\":\"Man\",\"3\":\"55.0000\",\"4\":\"71.0\",\"5\":\"72.0000\",\"6\":\"67.8308\"},{\"1\":\"2000-1\",\"2\":\"Woman\",\"3\":\"68.5000\",\"4\":\"64.0\",\"5\":\"93.0000\",\"6\":\"77.6903\"},{\"1\":\"2000-1\",\"2\":\"Man\",\"3\":\"68.5000\",\"4\":\"79.5\",\"5\":\"50.5000\",\"6\":\"69.9308\"},{\"1\":\"2000-1\",\"2\":\"Man\",\"3\":\"70.0000\",\"4\":\"71.0\",\"5\":\"76.0000\",\"6\":\"69.6769\"},{\"1\":\"2000-1\",\"2\":\"Man\",\"3\":\"75.0000\",\"4\":\"81.0\",\"5\":\"81.5000\",\"6\":\"68.0923\"},{\"1\":\"2000-1\",\"2\":\"Man\",\"3\":\"68.5000\",\"4\":\"66.0\",\"5\":\"58.0000\",\"6\":\"60.3128\"},{\"1\":\"2000-1\",\"2\":\"Man\",\"3\":\"54.0000\",\"4\":\"84.0\",\"5\":\"88.0000\",\"6\":\"72.3821\"},{\"1\":\"2000-1\",\"2\":\"Man\",\"3\":\"79.6000\",\"4\":\"67.0\",\"5\":\"72.0000\",\"6\":\"67.4787\"},{\"1\":\"2000-1\",\"2\":\"Man\",\"3\":\"85.0000\",\"4\":\"61.0\",\"5\":\"44.5000\",\"6\":\"66.2364\"},{\"1\":\"2000-1\",\"2\":\"Man\",\"3\":\"82.0000\",\"4\":\"86.5\",\"5\":\"92.5000\",\"6\":\"83.3231\"},{\"1\":\"2000-1\",\"2\":\"Woman\",\"3\":\"65.0000\",\"4\":\"83.5\",\"5\":\"87.0000\",\"6\":\"77.6436\"},{\"1\":\"2000-1\",\"2\":\"Woman\",\"3\":\"76.0000\",\"4\":\"50.0\",\"5\":\"91.5000\",\"6\":\"70.9462\"},{\"1\":\"2000-1\",\"2\":\"Man\",\"3\":\"94.5000\",\"4\":\"67.0\",\"5\":\"96.0000\",\"6\":\"86.0133\"},{\"1\":\"2000-1\",\"2\":\"Man\",\"3\":\"72.0000\",\"4\":\"67.0\",\"5\":\"90.0000\",\"6\":\"72.0269\"},{\"1\":\"2000-1\",\"2\":\"Man\",\"3\":\"65.5000\",\"4\":\"82.5\",\"5\":\"79.0000\",\"6\":\"77.0282\"},{\"1\":\"2000-1\",\"2\":\"Man\",\"3\":\"61.5000\",\"4\":\"80.5\",\"5\":\"81.5000\",\"6\":\"68.2821\"},{\"1\":\"2000-1\",\"2\":\"Man\",\"3\":\"65.0000\",\"4\":\"50.0\",\"5\":\"43.5000\",\"6\":\"43.2733\"},{\"1\":\"2000-1\",\"2\":\"Man\",\"3\":\"63.0000\",\"4\":\"82.0\",\"5\":\"88.0000\",\"6\":\"70.1031\"},{\"1\":\"2000-1\",\"2\":\"Man\",\"3\":\"75.0000\",\"4\":\"66.5\",\"5\":\"76.0000\",\"6\":\"65.0846\"},{\"1\":\"2000-1\",\"2\":\"Man\",\"3\":\"69.5000\",\"4\":\"70.5\",\"5\":\"76.0000\",\"6\":\"68.6538\"},{\"1\":\"2000-1\",\"2\":\"Woman\",\"3\":\"60.0000\",\"4\":\"95.0\",\"5\":\"91.0000\",\"6\":\"83.0508\"},{\"1\":\"2000-1\",\"2\":\"Man\",\"3\":\"84.0000\",\"4\":\"88.0\",\"5\":\"67.0000\",\"6\":\"75.0856\"},{\"1\":\"2000-1\",\"2\":\"Man\",\"3\":\"90.0000\",\"4\":\"99.5\",\"5\":\"87.5000\",\"6\":\"74.4718\"},{\"1\":\"2000-1\",\"2\":\"Woman\",\"3\":\"62.5000\",\"4\":\"85.5\",\"5\":\"85.5000\",\"6\":\"74.4821\"},{\"1\":\"2000-1\",\"2\":\"Man\",\"3\":\"88.5000\",\"4\":\"86.5\",\"5\":\"70.0000\",\"6\":\"77.9526\"},{\"1\":\"2000-2\",\"2\":\"Man\",\"3\":\"74.5000\",\"4\":\"83.0\",\"5\":\"62.4000\",\"6\":\"78.7554\"},{\"1\":\"2000-2\",\"2\":\"Man\",\"3\":\"73.5000\",\"4\":\"69.5\",\"5\":\"74.5000\",\"6\":\"69.0228\"},{\"1\":\"2000-2\",\"2\":\"Man\",\"3\":\"75.0000\",\"4\":\"60.5\",\"5\":\"80.9000\",\"6\":\"68.6502\"},{\"1\":\"2000-2\",\"2\":\"Man\",\"3\":\"76.5000\",\"4\":\"76.0\",\"5\":\"61.0000\",\"6\":\"73.6702\"},{\"1\":\"2000-2\",\"2\":\"Woman\",\"3\":\"90.5000\",\"4\":\"68.0\",\"5\":\"59.0000\",\"6\":\"69.7842\"},{\"1\":\"2000-2\",\"2\":\"Man\",\"3\":\"88.0000\",\"4\":\"77.5\",\"5\":\"90.5000\",\"6\":\"84.1474\"},{\"1\":\"2000-2\",\"2\":\"Man\",\"3\":\"87.2727\",\"4\":\"58.0\",\"5\":\"28.0000\",\"6\":\"49.1931\"},{\"1\":\"2000-2\",\"2\":\"Man\",\"3\":\"81.9000\",\"4\":\"86.0\",\"5\":\"62.0000\",\"6\":\"73.9116\"},{\"1\":\"2000-2\",\"2\":\"Man\",\"3\":\"65.5000\",\"4\":\"90.0\",\"5\":\"61.8000\",\"6\":\"68.5425\"},{\"1\":\"2000-2\",\"2\":\"Woman\",\"3\":\"84.5000\",\"4\":\"80.5\",\"5\":\"72.5000\",\"6\":\"81.2088\"},{\"1\":\"2000-2\",\"2\":\"Man\",\"3\":\"88.9000\",\"4\":\"67.0\",\"5\":\"76.0000\",\"6\":\"80.5554\"},{\"1\":\"2000-2\",\"2\":\"Man\",\"3\":\"70.0000\",\"4\":\"56.0\",\"5\":\"81.5000\",\"6\":\"68.7839\"},{\"1\":\"2000-2\",\"2\":\"Man\",\"3\":\"73.0000\",\"4\":\"48.0\",\"5\":\"55.0000\",\"6\":\"65.3088\"},{\"1\":\"2000-2\",\"2\":\"Man\",\"3\":\"86.0000\",\"4\":\"77.0\",\"5\":\"82.0000\",\"6\":\"79.6035\"},{\"1\":\"2000-2\",\"2\":\"Man\",\"3\":\"68.0000\",\"4\":\"60.0\",\"5\":\"59.0000\",\"6\":\"58.4316\"},{\"1\":\"2000-2\",\"2\":\"Woman\",\"3\":\"82.0000\",\"4\":\"74.0\",\"5\":\"81.5000\",\"6\":\"76.6842\"},{\"1\":\"2000-2\",\"2\":\"Man\",\"3\":\"86.4000\",\"4\":\"72.0\",\"5\":\"69.5000\",\"6\":\"67.5625\"},{\"1\":\"2000-2\",\"2\":\"Man\",\"3\":\"74.0000\",\"4\":\"83.0\",\"5\":\"79.9000\",\"6\":\"74.5730\"},{\"1\":\"2000-2\",\"2\":\"Man\",\"3\":\"92.3000\",\"4\":\"76.0\",\"5\":\"97.0000\",\"6\":\"87.0288\"},{\"1\":\"2000-2\",\"2\":\"Man\",\"3\":\"57.0000\",\"4\":\"70.0\",\"5\":\"56.0000\",\"6\":\"65.3947\"},{\"1\":\"2000-2\",\"2\":\"Man\",\"3\":\"62.5000\",\"4\":\"41.0\",\"5\":\"77.8000\",\"6\":\"59.8863\"},{\"1\":\"2000-2\",\"2\":\"Man\",\"3\":\"75.5000\",\"4\":\"62.5\",\"5\":\"79.7000\",\"6\":\"73.5435\"},{\"1\":\"2000-2\",\"2\":\"Man\",\"3\":\"67.0000\",\"4\":\"58.0\",\"5\":\"45.8000\",\"6\":\"58.3828\"},{\"1\":\"2000-2\",\"2\":\"Man\",\"3\":\"73.0000\",\"4\":\"78.0\",\"5\":\"77.3000\",\"6\":\"79.2354\"},{\"1\":\"2000-2\",\"2\":\"Man\",\"3\":\"93.0000\",\"4\":\"75.0\",\"5\":\"96.0000\",\"6\":\"71.3228\"},{\"1\":\"2000-2\",\"2\":\"Man\",\"3\":\"81.5000\",\"4\":\"73.0\",\"5\":\"69.5000\",\"6\":\"65.5295\"},{\"1\":\"2000-2\",\"2\":\"Man\",\"3\":\"82.5000\",\"4\":\"83.5\",\"5\":\"82.5000\",\"6\":\"81.4474\"},{\"1\":\"2000-2\",\"2\":\"Woman\",\"3\":\"46.5000\",\"4\":\"77.0\",\"5\":\"47.0000\",\"6\":\"62.8842\"},{\"1\":\"2000-2\",\"2\":\"Man\",\"3\":\"62.0000\",\"4\":\"71.0\",\"5\":\"64.0000\",\"6\":\"69.4702\"},{\"1\":\"2000-2\",\"2\":\"Woman\",\"3\":\"68.5000\",\"4\":\"55.5\",\"5\":\"52.0000\",\"6\":\"61.8263\"},{\"1\":\"2000-2\",\"2\":\"Man\",\"3\":\"80.0000\",\"4\":\"84.0\",\"5\":\"48.5000\",\"6\":\"70.0947\"},{\"1\":\"2000-2\",\"2\":\"Man\",\"3\":\"77.0000\",\"4\":\"77.0\",\"5\":\"44.0000\",\"6\":\"68.0404\"},{\"1\":\"2000-2\",\"2\":\"Woman\",\"3\":\"55.0000\",\"4\":\"94.0\",\"5\":\"96.0000\",\"6\":\"83.5193\"},{\"1\":\"2000-2\",\"2\":\"Man\",\"3\":\"69.0000\",\"4\":\"74.5\",\"5\":\"41.5000\",\"6\":\"59.0386\"},{\"1\":\"2000-2\",\"2\":\"Woman\",\"3\":\"74.0000\",\"4\":\"56.0\",\"5\":\"69.9000\",\"6\":\"65.0204\"},{\"1\":\"2001-1\",\"2\":\"Man\",\"3\":\"93.0000\",\"4\":\"76.0\",\"5\":\"95.5000\",\"6\":\"85.5000\"},{\"1\":\"2001-1\",\"2\":\"Man\",\"3\":\"81.0000\",\"4\":\"78.0\",\"5\":\"79.5000\",\"6\":\"75.7333\"},{\"1\":\"2001-1\",\"2\":\"Man\",\"3\":\"98.0000\",\"4\":\"87.0\",\"5\":\"85.5000\",\"6\":\"86.5833\"},{\"1\":\"2001-1\",\"2\":\"Man\",\"3\":\"92.5000\",\"4\":\"81.0\",\"5\":\"74.5000\",\"6\":\"77.2833\"},{\"1\":\"2001-1\",\"2\":\"Man\",\"3\":\"83.5000\",\"4\":\"60.5\",\"5\":\"78.0000\",\"6\":\"73.6333\"},{\"1\":\"2001-1\",\"2\":\"Man\",\"3\":\"98.0000\",\"4\":\"92.0\",\"5\":\"90.5000\",\"6\":\"91.8585\"},{\"1\":\"2001-1\",\"2\":\"Man\",\"3\":\"80.5000\",\"4\":\"53.5\",\"5\":\"67.5000\",\"6\":\"62.9555\"},{\"1\":\"2001-1\",\"2\":\"Man\",\"3\":\"80.9000\",\"4\":\"68.0\",\"5\":\"67.0000\",\"6\":\"72.7600\"},{\"1\":\"2001-1\",\"2\":\"Man\",\"3\":\"84.5000\",\"4\":\"46.0\",\"5\":\"65.5000\",\"6\":\"60.6167\"},{\"1\":\"2001-1\",\"2\":\"Man\",\"3\":\"93.8000\",\"4\":\"59.5\",\"5\":\"73.3000\",\"6\":\"70.0067\"},{\"1\":\"2001-1\",\"2\":\"Man\",\"3\":\"98.0000\",\"4\":\"96.5\",\"5\":\"98.5000\",\"6\":\"97.5667\"},{\"1\":\"2001-1\",\"2\":\"Man\",\"3\":\"92.0000\",\"4\":\"78.5\",\"5\":\"72.0000\",\"6\":\"73.2833\"},{\"1\":\"2001-1\",\"2\":\"Man\",\"3\":\"91.0000\",\"4\":\"72.0\",\"5\":\"81.0000\",\"6\":\"75.1167\"},{\"1\":\"2001-1\",\"2\":\"Man\",\"3\":\"80.0000\",\"4\":\"72.0\",\"5\":\"59.5000\",\"6\":\"69.7000\"},{\"1\":\"2001-1\",\"2\":\"Man\",\"3\":\"94.0000\",\"4\":\"84.0\",\"5\":\"98.5000\",\"6\":\"88.8667\"},{\"1\":\"2001-1\",\"2\":\"Man\",\"3\":\"90.0000\",\"4\":\"73.0\",\"5\":\"63.5000\",\"6\":\"72.9000\"},{\"1\":\"2001-1\",\"2\":\"Man\",\"3\":\"94.0000\",\"4\":\"82.0\",\"5\":\"86.4000\",\"6\":\"80.3267\"},{\"1\":\"2001-1\",\"2\":\"Man\",\"3\":\"86.5000\",\"4\":\"76.0\",\"5\":\"85.5000\",\"6\":\"76.2000\"},{\"1\":\"2001-1\",\"2\":\"Man\",\"3\":\"87.0000\",\"4\":\"76.0\",\"5\":\"72.5000\",\"6\":\"70.7442\"},{\"1\":\"2001-1\",\"2\":\"Man\",\"3\":\"80.3000\",\"4\":\"88.5\",\"5\":\"83.5000\",\"6\":\"85.9700\"},{\"1\":\"2001-1\",\"2\":\"Man\",\"3\":\"89.5000\",\"4\":\"66.5\",\"5\":\"78.9000\",\"6\":\"72.5267\"},{\"1\":\"2001-1\",\"2\":\"Man\",\"3\":\"70.5000\",\"4\":\"70.5\",\"5\":\"58.0000\",\"6\":\"57.0000\"},{\"1\":\"2001-1\",\"2\":\"Man\",\"3\":\"89.4000\",\"4\":\"84.5\",\"5\":\"82.5000\",\"6\":\"83.8685\"},{\"1\":\"2001-1\",\"2\":\"Woman\",\"3\":\"79.5000\",\"4\":\"56.0\",\"5\":\"81.0000\",\"6\":\"68.2500\"},{\"1\":\"2001-1\",\"2\":\"Man\",\"3\":\"93.9000\",\"4\":\"88.0\",\"5\":\"71.0000\",\"6\":\"80.0600\"},{\"1\":\"2001-1\",\"2\":\"Man\",\"3\":\"73.5000\",\"4\":\"78.5\",\"5\":\"72.0000\",\"6\":\"77.0333\"},{\"1\":\"2001-1\",\"2\":\"Man\",\"3\":\"94.8000\",\"4\":\"84.5\",\"5\":\"77.5000\",\"6\":\"84.1700\"},{\"1\":\"2001-1\",\"2\":\"Woman\",\"3\":\"66.0000\",\"4\":\"62.0\",\"5\":\"80.5000\",\"6\":\"70.9333\"},{\"1\":\"2001-1\",\"2\":\"Man\",\"3\":\"96.3000\",\"4\":\"82.0\",\"5\":\"76.0000\",\"6\":\"79.9867\"},{\"1\":\"2001-1\",\"2\":\"Man\",\"3\":\"93.3000\",\"4\":\"93.0\",\"5\":\"92.5000\",\"6\":\"89.8033\"},{\"1\":\"2001-1\",\"2\":\"Man\",\"3\":\"87.3000\",\"4\":\"81.0\",\"5\":\"78.5000\",\"6\":\"85.7367\"},{\"1\":\"2001-1\",\"2\":\"Man\",\"3\":\"79.0000\",\"4\":\"81.0\",\"5\":\"91.0000\",\"6\":\"78.1222\"},{\"1\":\"2001-1\",\"2\":\"Man\",\"3\":\"84.0000\",\"4\":\"81.0\",\"5\":\"91.0000\",\"6\":\"75.0333\"},{\"1\":\"2001-1\",\"2\":\"Woman\",\"3\":\"81.0000\",\"4\":\"81.5\",\"5\":\"70.0000\",\"6\":\"74.2167\"},{\"1\":\"2001-1\",\"2\":\"Woman\",\"3\":\"84.5000\",\"4\":\"71.5\",\"5\":\"76.0000\",\"6\":\"73.9833\"},{\"1\":\"2001-1\",\"2\":\"Woman\",\"3\":\"90.6250\",\"4\":\"61.5\",\"5\":\"59.5000\",\"6\":\"66.6958\"},{\"1\":\"2001-1\",\"2\":\"Woman\",\"3\":\"91.5000\",\"4\":\"58.0\",\"5\":\"79.5000\",\"6\":\"74.9888\"},{\"1\":\"2001-1\",\"2\":\"Man\",\"3\":\"84.0000\",\"4\":\"72.5\",\"5\":\"76.0000\",\"6\":\"75.7000\"},{\"1\":\"2001-2\",\"2\":\"Man\",\"3\":\"73.2000\",\"4\":\"44.0\",\"5\":\"50.9000\",\"6\":\"47.9000\"},{\"1\":\"2001-2\",\"2\":\"Man\",\"3\":\"70.5000\",\"4\":\"42.8\",\"5\":\"36.4000\",\"6\":\"48.0500\"},{\"1\":\"2001-2\",\"2\":\"Woman\",\"3\":\"92.9000\",\"4\":\"88.5\",\"5\":\"79.0000\",\"6\":\"86.6500\"},{\"1\":\"2001-2\",\"2\":\"Man\",\"3\":\"68.8000\",\"4\":\"52.1\",\"5\":\"65.4000\",\"6\":\"55.9500\"},{\"1\":\"2001-2\",\"2\":\"Man\",\"3\":\"91.3000\",\"4\":\"71.0\",\"5\":\"79.5000\",\"6\":\"77.8250\"},{\"1\":\"2001-2\",\"2\":\"Man\",\"3\":\"78.3000\",\"4\":\"46.5\",\"5\":\"63.9000\",\"6\":\"56.7250\"},{\"1\":\"2001-2\",\"2\":\"Man\",\"3\":\"71.3000\",\"4\":\"43.0\",\"5\":\"67.4000\",\"6\":\"58.3750\"},{\"1\":\"2001-2\",\"2\":\"Man\",\"3\":\"74.9000\",\"4\":\"65.4\",\"5\":\"51.5000\",\"6\":\"56.0750\"},{\"1\":\"2001-2\",\"2\":\"Man\",\"3\":\"90.5000\",\"4\":\"71.5\",\"5\":\"69.5000\",\"6\":\"78.5000\"},{\"1\":\"2001-2\",\"2\":\"Man\",\"3\":\"80.3000\",\"4\":\"63.0\",\"5\":\"64.0000\",\"6\":\"64.7000\"},{\"1\":\"2001-2\",\"2\":\"Woman\",\"3\":\"79.0000\",\"4\":\"74.5\",\"5\":\"72.5000\",\"6\":\"68.3250\"},{\"1\":\"2001-2\",\"2\":\"Man\",\"3\":\"82.5000\",\"4\":\"62.5\",\"5\":\"77.5000\",\"6\":\"73.5000\"},{\"1\":\"2001-2\",\"2\":\"Man\",\"3\":\"79.7000\",\"4\":\"84.4\",\"5\":\"77.3000\",\"6\":\"75.5500\"},{\"1\":\"2001-2\",\"2\":\"Man\",\"3\":\"79.5000\",\"4\":\"77.9\",\"5\":\"62.0000\",\"6\":\"68.3500\"},{\"1\":\"2001-2\",\"2\":\"Man\",\"3\":\"79.5000\",\"4\":\"68.7\",\"5\":\"87.0000\",\"6\":\"81.7500\"},{\"1\":\"2001-2\",\"2\":\"Man\",\"3\":\"93.0000\",\"4\":\"70.9\",\"5\":\"67.5000\",\"6\":\"70.4250\"},{\"1\":\"2001-2\",\"2\":\"Man\",\"3\":\"88.5000\",\"4\":\"79.5\",\"5\":\"82.0000\",\"6\":\"80.5000\"},{\"1\":\"2001-2\",\"2\":\"Woman\",\"3\":\"86.0000\",\"4\":\"73.0\",\"5\":\"47.0000\",\"6\":\"66.0000\"},{\"1\":\"2001-2\",\"2\":\"Man\",\"3\":\"93.8000\",\"4\":\"68.5\",\"5\":\"66.4000\",\"6\":\"74.8750\"},{\"1\":\"2001-2\",\"2\":\"Woman\",\"3\":\"93.9000\",\"4\":\"84.0\",\"5\":\"83.5000\",\"6\":\"88.2250\"},{\"1\":\"2001-2\",\"2\":\"Man\",\"3\":\"83.3000\",\"4\":\"83.0\",\"5\":\"78.0000\",\"6\":\"82.5750\"},{\"1\":\"2001-2\",\"2\":\"Man\",\"3\":\"75.1000\",\"4\":\"70.0\",\"5\":\"61.0000\",\"6\":\"64.0250\"},{\"1\":\"2001-2\",\"2\":\"Man\",\"3\":\"92.9000\",\"4\":\"83.0\",\"5\":\"84.5000\",\"6\":\"84.1500\"},{\"1\":\"2001-2\",\"2\":\"Man\",\"3\":\"76.5000\",\"4\":\"41.5\",\"5\":\"48.0000\",\"6\":\"53.0750\"},{\"1\":\"2001-2\",\"2\":\"Woman\",\"3\":\"84.1000\",\"4\":\"88.8\",\"5\":\"75.5000\",\"6\":\"81.5500\"},{\"1\":\"2001-2\",\"2\":\"Man\",\"3\":\"87.9000\",\"4\":\"58.2\",\"5\":\"67.0000\",\"6\":\"63.5250\"},{\"1\":\"2001-2\",\"2\":\"Woman\",\"3\":\"79.5000\",\"4\":\"66.0\",\"5\":\"67.5000\",\"6\":\"69.1250\"},{\"1\":\"2001-2\",\"2\":\"Man\",\"3\":\"82.0000\",\"4\":\"53.5\",\"5\":\"52.0000\",\"6\":\"54.5000\"},{\"1\":\"2001-2\",\"2\":\"Woman\",\"3\":\"91.4000\",\"4\":\"77.0\",\"5\":\"76.0000\",\"6\":\"76.1000\"},{\"1\":\"2001-2\",\"2\":\"Man\",\"3\":\"84.9000\",\"4\":\"69.5\",\"5\":\"37.3000\",\"6\":\"60.3000\"},{\"1\":\"2001-2\",\"2\":\"Man\",\"3\":\"58.0000\",\"4\":\"61.0\",\"5\":\"47.4000\",\"6\":\"57.6000\"},{\"1\":\"2001-2\",\"2\":\"Man\",\"3\":\"81.5000\",\"4\":\"57.5\",\"5\":\"65.8000\",\"6\":\"60.3250\"},{\"1\":\"2001-2\",\"2\":\"Man\",\"3\":\"95.0000\",\"4\":\"68.0\",\"5\":\"82.5000\",\"6\":\"76.7500\"},{\"1\":\"2001-2\",\"2\":\"Man\",\"3\":\"95.5000\",\"4\":\"80.5\",\"5\":\"84.3000\",\"6\":\"75.7750\"},{\"1\":\"2001-2\",\"2\":\"Man\",\"3\":\"77.5000\",\"4\":\"80.9\",\"5\":\"75.0000\",\"6\":\"76.4250\"},{\"1\":\"2001-2\",\"2\":\"Man\",\"3\":\"82.0000\",\"4\":\"46.0\",\"5\":\"54.0000\",\"6\":\"53.0000\"},{\"1\":\"2001-2\",\"2\":\"Man\",\"3\":\"93.8000\",\"4\":\"82.5\",\"5\":\"80.5000\",\"6\":\"84.6500\"},{\"1\":\"2002-1\",\"2\":\"Man\",\"3\":\"89.0000\",\"4\":\"83.5\",\"5\":\"92.0000\",\"6\":\"77.1197\"},{\"1\":\"2002-1\",\"2\":\"Man\",\"3\":\"82.0000\",\"4\":\"78.5\",\"5\":\"82.0000\",\"6\":\"61.7972\"},{\"1\":\"2002-1\",\"2\":\"Man\",\"3\":\"73.5000\",\"4\":\"80.0\",\"5\":\"82.0000\",\"6\":\"73.5563\"},{\"1\":\"2002-1\",\"2\":\"Man\",\"3\":\"73.5000\",\"4\":\"82.8\",\"5\":\"79.5000\",\"6\":\"69.9459\"},{\"1\":\"2002-1\",\"2\":\"Woman\",\"3\":\"79.0000\",\"4\":\"86.5\",\"5\":\"97.0000\",\"6\":\"80.5324\"},{\"1\":\"2002-1\",\"2\":\"Man\",\"3\":\"71.5000\",\"4\":\"71.0\",\"5\":\"58.0000\",\"6\":\"62.4331\"},{\"1\":\"2002-1\",\"2\":\"Man\",\"3\":\"92.5000\",\"4\":\"92.0\",\"5\":\"93.5000\",\"6\":\"82.2000\"},{\"1\":\"2002-1\",\"2\":\"Woman\",\"3\":\"85.5000\",\"4\":\"90.5\",\"5\":\"85.0000\",\"6\":\"86.7901\"},{\"1\":\"2002-1\",\"2\":\"Man\",\"3\":\"93.0000\",\"4\":\"47.0\",\"5\":\"70.0000\",\"6\":\"59.8218\"},{\"1\":\"2002-1\",\"2\":\"Man\",\"3\":\"75.5000\",\"4\":\"66.0\",\"5\":\"94.0000\",\"6\":\"69.0648\"},{\"1\":\"2002-1\",\"2\":\"Man\",\"3\":\"88.5000\",\"4\":\"74.0\",\"5\":\"87.0000\",\"6\":\"78.2085\"},{\"1\":\"2002-1\",\"2\":\"Man\",\"3\":\"87.0000\",\"4\":\"96.0\",\"5\":\"98.5000\",\"6\":\"84.0577\"},{\"1\":\"2002-1\",\"2\":\"Woman\",\"3\":\"89.5000\",\"4\":\"77.5\",\"5\":\"88.9000\",\"6\":\"69.2110\"},{\"1\":\"2002-1\",\"2\":\"Man\",\"3\":\"97.5000\",\"4\":\"94.5\",\"5\":\"76.0000\",\"6\":\"78.9310\"},{\"1\":\"2002-1\",\"2\":\"Woman\",\"3\":\"59.0000\",\"4\":\"73.0\",\"5\":\"85.5000\",\"6\":\"58.2606\"},{\"1\":\"2002-1\",\"2\":\"Man\",\"3\":\"81.0000\",\"4\":\"87.0\",\"5\":\"86.5000\",\"6\":\"72.1352\"},{\"1\":\"2002-1\",\"2\":\"Man\",\"3\":\"73.5000\",\"4\":\"57.5\",\"5\":\"83.0000\",\"6\":\"61.7713\"},{\"1\":\"2002-1\",\"2\":\"Man\",\"3\":\"90.5000\",\"4\":\"53.0\",\"5\":\"78.5000\",\"6\":\"60.7915\"},{\"1\":\"2002-1\",\"2\":\"Man\",\"3\":\"70.0000\",\"4\":\"62.5\",\"5\":\"85.0000\",\"6\":\"64.5225\"},{\"1\":\"2002-1\",\"2\":\"Man\",\"3\":\"98.5000\",\"4\":\"98.0\",\"5\":\"90.0000\",\"6\":\"80.3761\"},{\"1\":\"2002-1\",\"2\":\"Man\",\"3\":\"85.5000\",\"4\":\"67.0\",\"5\":\"86.0000\",\"6\":\"67.6535\"},{\"1\":\"2002-1\",\"2\":\"Man\",\"3\":\"78.0000\",\"4\":\"58.0\",\"5\":\"92.5000\",\"6\":\"65.1831\"},{\"1\":\"2002-1\",\"2\":\"Man\",\"3\":\"86.5000\",\"4\":\"85.0\",\"5\":\"85.0000\",\"6\":\"73.5972\"},{\"1\":\"2002-1\",\"2\":\"Woman\",\"3\":\"99.3000\",\"4\":\"96.0\",\"5\":\"89.0000\",\"6\":\"91.4868\"},{\"1\":\"2002-1\",\"2\":\"Man\",\"3\":\"90.5000\",\"4\":\"78.5\",\"5\":\"79.5000\",\"6\":\"73.0634\"},{\"1\":\"2002-1\",\"2\":\"Man\",\"3\":\"86.5000\",\"4\":\"67.5\",\"5\":\"85.5000\",\"6\":\"70.0746\"},{\"1\":\"2002-1\",\"2\":\"Man\",\"3\":\"80.0000\",\"4\":\"94.0\",\"5\":\"90.5000\",\"6\":\"88.4310\"},{\"1\":\"2002-1\",\"2\":\"Man\",\"3\":\"72.0000\",\"4\":\"95.0\",\"5\":\"78.0000\",\"6\":\"77.3507\"},{\"1\":\"2002-1\",\"2\":\"Man\",\"3\":\"72.5000\",\"4\":\"69.5\",\"5\":\"92.0000\",\"6\":\"73.5648\"},{\"1\":\"2002-1\",\"2\":\"Man\",\"3\":\"77.5000\",\"4\":\"74.0\",\"5\":\"82.0000\",\"6\":\"73.1493\"},{\"1\":\"2002-1\",\"2\":\"Man\",\"3\":\"74.0000\",\"4\":\"49.5\",\"5\":\"82.0000\",\"6\":\"64.6690\"},{\"1\":\"2002-1\",\"2\":\"Man\",\"3\":\"79.0000\",\"4\":\"80.5\",\"5\":\"80.5000\",\"6\":\"71.9845\"},{\"1\":\"2002-1\",\"2\":\"Man\",\"3\":\"80.0000\",\"4\":\"82.0\",\"5\":\"77.0000\",\"6\":\"67.7986\"},{\"1\":\"2002-1\",\"2\":\"Man\",\"3\":\"97.4000\",\"4\":\"66.9\",\"5\":\"83.0000\",\"6\":\"74.9276\"},{\"1\":\"2002-1\",\"2\":\"Man\",\"3\":\"61.5000\",\"4\":\"64.5\",\"5\":\"86.0000\",\"6\":\"63.7651\"},{\"1\":\"2002-1\",\"2\":\"Man\",\"3\":\"86.0000\",\"4\":\"67.0\",\"5\":\"96.8000\",\"6\":\"73.7346\"},{\"1\":\"2003-1\",\"2\":\"Woman\",\"3\":\"75.7143\",\"4\":\"62.6\",\"5\":\"45.5556\",\"6\":\"59.5549\"},{\"1\":\"2003-1\",\"2\":\"Woman\",\"3\":\"80.7143\",\"4\":\"38.0\",\"5\":\"78.3333\",\"6\":\"65.2202\"},{\"1\":\"2003-1\",\"2\":\"Woman\",\"3\":\"88.2143\",\"4\":\"75.1\",\"5\":\"70.0000\",\"6\":\"72.3670\"},{\"1\":\"2003-1\",\"2\":\"Man\",\"3\":\"81.7857\",\"4\":\"76.0\",\"5\":\"68.3333\",\"6\":\"74.1120\"},{\"1\":\"2003-1\",\"2\":\"Man\",\"3\":\"96.0714\",\"4\":\"68.1\",\"5\":\"74.4444\",\"6\":\"70.4423\"},{\"1\":\"2003-1\",\"2\":\"Man\",\"3\":\"NA\",\"4\":\"58.0\",\"5\":\"78.3333\",\"6\":\"46.7231\"},{\"1\":\"2003-1\",\"2\":\"Man\",\"3\":\"73.5714\",\"4\":\"62.1\",\"5\":\"97.7778\",\"6\":\"69.1030\"},{\"1\":\"2003-1\",\"2\":\"Man\",\"3\":\"71.0714\",\"4\":\"41.5\",\"5\":\"55.5556\",\"6\":\"53.9348\"},{\"1\":\"2003-1\",\"2\":\"Man\",\"3\":\"66.4286\",\"4\":\"59.1\",\"5\":\"85.5556\",\"6\":\"68.5149\"},{\"1\":\"2003-1\",\"2\":\"Man\",\"3\":\"85.7143\",\"4\":\"77.1\",\"5\":\"83.3333\",\"6\":\"79.8810\"},{\"1\":\"2003-1\",\"2\":\"Woman\",\"3\":\"88.9286\",\"4\":\"72.0\",\"5\":\"93.3333\",\"6\":\"82.3626\"},{\"1\":\"2003-1\",\"2\":\"Man\",\"3\":\"65.7143\",\"4\":\"60.5\",\"5\":\"30.0000\",\"6\":\"48.5152\"},{\"1\":\"2003-1\",\"2\":\"Man\",\"3\":\"92.5000\",\"4\":\"63.5\",\"5\":\"92.7778\",\"6\":\"80.3655\"},{\"1\":\"2003-1\",\"2\":\"Woman\",\"3\":\"86.0714\",\"4\":\"77.5\",\"5\":\"96.6667\",\"6\":\"80.3527\"},{\"1\":\"2003-1\",\"2\":\"Man\",\"3\":\"75.0000\",\"4\":\"71.9\",\"5\":\"88.3333\",\"6\":\"70.3606\"},{\"1\":\"2003-1\",\"2\":\"Man\",\"3\":\"95.7143\",\"4\":\"90.1\",\"5\":\"98.8889\",\"6\":\"93.3003\"},{\"1\":\"2003-1\",\"2\":\"Man\",\"3\":\"88.9286\",\"4\":\"52.5\",\"5\":\"62.5000\",\"6\":\"61.1081\"},{\"1\":\"2003-1\",\"2\":\"Man\",\"3\":\"94.6429\",\"4\":\"90.0\",\"5\":\"90.0000\",\"6\":\"87.6431\"},{\"1\":\"2003-1\",\"2\":\"Man\",\"3\":\"92.5000\",\"4\":\"80.0\",\"5\":\"96.1111\",\"6\":\"87.9477\"},{\"1\":\"2003-1\",\"2\":\"Woman\",\"3\":\"91.0714\",\"4\":\"39.5\",\"5\":\"78.8889\",\"6\":\"67.9143\"},{\"1\":\"2003-1\",\"2\":\"Man\",\"3\":\"92.8571\",\"4\":\"73.5\",\"5\":\"92.1111\",\"6\":\"86.2788\"},{\"1\":\"2003-1\",\"2\":\"Woman\",\"3\":\"86.0714\",\"4\":\"45.5\",\"5\":\"55.5556\",\"6\":\"59.8701\"},{\"1\":\"2003-1\",\"2\":\"Man\",\"3\":\"87.1429\",\"4\":\"81.6\",\"5\":\"73.8889\",\"6\":\"76.4304\"},{\"1\":\"2003-1\",\"2\":\"Man\",\"3\":\"74.2857\",\"4\":\"52.6\",\"5\":\"47.2222\",\"6\":\"56.3211\"},{\"1\":\"2003-1\",\"2\":\"Man\",\"3\":\"95.7143\",\"4\":\"78.0\",\"5\":\"84.4444\",\"6\":\"83.2086\"},{\"1\":\"2003-1\",\"2\":\"Man\",\"3\":\"83.2143\",\"4\":\"64.6\",\"5\":\"58.8889\",\"6\":\"68.0731\"},{\"1\":\"2003-1\",\"2\":\"Man\",\"3\":\"85.0000\",\"4\":\"78.1\",\"5\":\"82.2222\",\"6\":\"70.5416\"},{\"1\":\"2003-1\",\"2\":\"Man\",\"3\":\"85.7143\",\"4\":\"68.1\",\"5\":\"72.0000\",\"6\":\"66.1202\"},{\"1\":\"2003-1\",\"2\":\"Woman\",\"3\":\"94.6429\",\"4\":\"94.5\",\"5\":\"96.1111\",\"6\":\"90.7190\"},{\"1\":\"2003-1\",\"2\":\"Man\",\"3\":\"90.7143\",\"4\":\"77.5\",\"5\":\"78.2222\",\"6\":\"77.5340\"},{\"1\":\"2003-1\",\"2\":\"Man\",\"3\":\"86.4286\",\"4\":\"70.1\",\"5\":\"88.3333\",\"6\":\"74.5553\"},{\"1\":\"2003-1\",\"2\":\"Man\",\"3\":\"98.2143\",\"4\":\"89.1\",\"5\":\"71.1111\",\"6\":\"85.5208\"},{\"1\":\"2003-1\",\"2\":\"Woman\",\"3\":\"95.0000\",\"4\":\"86.0\",\"5\":\"78.3333\",\"6\":\"83.6959\"},{\"1\":\"2003-1\",\"2\":\"Man\",\"3\":\"97.1429\",\"4\":\"53.5\",\"5\":\"67.2222\",\"6\":\"72.1189\"},{\"1\":\"2003-1\",\"2\":\"Man\",\"3\":\"85.0000\",\"4\":\"63.0\",\"5\":\"75.0000\",\"6\":\"67.1996\"},{\"1\":\"2003-1\",\"2\":\"Man\",\"3\":\"72.8571\",\"4\":\"48.5\",\"5\":\"90.5556\",\"6\":\"66.4035\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n### {{< iconify carbon chart-3d >}} Inspecting and Charting Data\n\n### Testing Assumptions in the Data\n\n### Inference\n\n::: {.panel-tabset .nav-pills style=\"background: whitesmoke;\"}\n\n#### t.test\n\n#### Wilcoxon test\n\n#### Linear Model\n\n#### Using Bootstrap\n\n#### Plots\n\n:::\n\n## {{< iconify fluent-mdl2 decision-solid >}} Conclusion\nTBW\n\n## {{< iconify ooui references-ltr >}} References\n::: {#refs style=\"font-size: 60%;\"}\n\nOpenIntro Modern Statistics, [Chapter #17](https://openintro-ims.netlify.app/inference-one-prop.html)\n\n\n::: {.cell hash='single-mean_cache/html/unnamed-chunk-6_5276eb782e5e66ebd2a37398a26f1d6e'}\n::: {.cell-output-display}\nPackage         Version   Citation       \n--------------  --------  ---------------\ninfer           1.0.5     @infer         \nopenintro       2.4.0     @openintro     \nresampledata    0.3.1     @resampledata  \nTeachHist       0.2.1     @TeachHist     \nTeachingDemos   2.12      @TeachingDemos\n:::\n:::\n\n\n\n:::\n\n[^1]: <https://allendowney.blogspot.com/2016/06/there-is-still-only-one-test.html>\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../../../../../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"../../../../../../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}