---
title: Data Viz with No Code!
date: 2022/Dec/31
listing: 
  type: table
  contents: "Modules/*/*.qmd"
  sort: "order"
  
---

## Abstract

> **It is a truth universally acknowledged, that a Srishti Art and Design student, in possession of a good Mac, must be terrified of coding.**
>
> ::: {style="text-align: right"}
> \-[Code and Prejudice](https://www.gutenberg.org/ebooks/1342), Jane Austen, 1870
> :::

This Unit takes SMI ~~peasants~~ students on a journey of using data to tell stories and make decisions. Without ~~doing an iota of work~~ writing one byte of code. Bah. 

Datasets from various domains of *human enterprise and activity* are introduced. The datasets are motivated from the point of view of the *Types of Information* they contain: **Quantities**, **Attributes**, **Changes**, **Portions**, **Ranking**, **Relations**, and related to **Space**, and **Time**, for example.

The **human contexts** from these datasets are used to appreciate the specifics of **data formats**, and the **nature of variables** within the data. Student will relate the data variables to Data/Information Visualizations, making decisions on how geometric shapes and other aspects of different Data Types and Visualizations can be metaphorically matched to the contexts. These **information-to-geometry metaphors** will lead us to **Insights**, **Questions**, and eventually to **Stories** and good **Decisions**.

Students will then be prompted to work in groups, or as a whole, to conduct a complete data gathering experiment on campus, visualize the data and tell a Story that pertains to their immediate surroundings.

## What you will learn

-   Data Basics:
    -   Learn to find data and appreciate how it was gathered in the first place
    -   What does data look like and why should we care?
    -   How to Spot a good Variable
    -   What can we do with the data, visually? How do geometric attributes such as location, size, and colour, lend themselves to representing data?
-   Creating Graphs and Data Visualizations
    -   Rapidly make different kinds of graphs
    -   Use Graphs and Tables as a way of getting answers to your Questions
    -   Develop intuition that matches data and graph types
-   Tell stories with data and graphs
    -   Annotate Graphs with text and insights
    -   Export these to create crisp and readable documents that you can share

## Introduction

Take a look at the graph visualization below:

<iframe src="https://ourworldindata.org/grapher/share-of-teachers-who-are-female-in-primary-vs-tertiary-education" loading="lazy" style="width: 100%; height: 600px; border: 0px none;">

</iframe>

<br>

-   What information does the graph convey? How ?
-   What aspects of the Visual convey "human" information, such as Number and Relation?
-   What could the sloping dotted line in the picture depict?

We will form our intuition about shapes and data and learn to create some evocative information graphics that tell stories.

## References

1.  Jack Dougherty and Ilya Ilyankou, *Hands-On Data Visualization: Interactive Storytelling from Spreadsheets to Code*, <https://handsondataviz.org/>. Available free Online.

2.  Claus O. Wilke, *Fundamentals of Data Visualization*, <https://clauswilke.com/dataviz/>. Available free Online.

3.  Jonathan Schwabish, \*Better Data Visualizations: A Guide for Scholars, Researchers, and Wonks, Columbia University Press, 2021.

4.  Alberto Cairo, *The Functional Art:An introduction to information graphics and visualization*, New Riders. 2013. ISBN-9780133041361.

5.  Cole Nussbaumer Knaflic, *Storytelling With Data: A Data Visualization Guide for Business Professionals*, Wiley 2015. ISBN-9781119002253.

## Quick Lookup

### Charts and Data

1.  **Data Vis Project** <https://datavizproject.com/> Allows you to match data types and data-vis types!! Perfect!!

2.  **Data Viz Catalogue** <https://datavizcatalogue.com/> Another good place to look for graphs that match your data!

3.  **From Data-to-Viz** <https://www.data-to-viz.com/#explore>

4.  Financial Times **Visual Vocabulary Chart**. A great chart to match data to data-viz. [**PDF here**](/pdf/DataViz/FT4Schools_RGS.pdf) and Web version <https://ft-interactive.github.io/visual-vocabulary/>

5.  72 types of Visualization for Data Stories <https://blog.gramener.com/types-of-data-visualization-for-data-stories/>

### Charting in R

1.  **R Charts** <https://r-charts.com/>

2.  **R Graph Gallery** <https://r-graph-gallery.com/index.html>

## Dataset Resources

1.  A wide variety of graphics and datasets on global issues at **Our World in Data** <https://ourworldindata.org/>

2.  Datasets at **calmcode.io** <https://calmcode.io/datasets.html>. Simple datasets that you should begin with.

3.  **Data.World** <https://data.world>. A very well organized easily searchable database of datasets *and* visualizations!

4.  **The Harvard Dataverse** <https://dataverse.harvard.edu/>. A very large searchable database of datasets on a very wode set of topics.

5.  **IPUMS** <https://www.ipums.org/> Integrated Public Use Microdata Series (IPUMS) is the world's largest individual-level population database. IPUMS consists of microdata samples from United States (IPUMS-USA) and international (IPUMS-International) census records, as well as data from U.S. and international surveys. Data provided is integrated across time and space.*Health*, *Economics*, *Higher Education*, *Historical Data* and much more

6.  **Kaggle Datasets** <https://www.kaggle.com/datasets> E.g. [Netflix Shows](https://www.kaggle.com/datasets/shivamb/netflix-shows)

7.  **Data Is Plural** <https://www.data-is-plural.com/>. This a weekly newsletter of useful/curious datasets by Jeremy Singer-Vine.

8.  **Information is Beautiful** <https://informationisbeautiful.net/> David McCandless' terrific information visualization site. All datasets used here are also available for download.

9.  **India Data by Sector** <https://data.gov.in/sector>

10. The FBI's **Crime Data Explorer** (very US-centric) <https://crime-data-explorer.app.cloud.gov/pages/home>

11. Datasets at **538** ( *very* US-centric) <https://data.fivethirtyeight.com/>

12. **Open Data Network** ( again *very* US-centric) <https://www.opendatanetwork.com/>

13. **311-data.org** <https://www.311-data.org/>. Data about 311 calls in different parts of the US. (#311 is a complaints service that deals with non-crime / non-emergency related neighbourhood issues in the US)

14. **Google Dataset Search** <https://datasetsearch.research.google.com/>

15. **Github dataset search** <https://github.com/search?q=datasets>

16. **World Inequality Database**, <https://wid.world/>. Global data on income and wealth inequality. India specific data also available.

17. **World Bank Open Data** <https://data.worldbank.org/>. A global collection of economic development data .

18. Jonathan Schwabish's **PolicyViz DataViz Catalogue**. <https://policyviz.com/resources/policyviz-data-visualization-catalog/> This is a spreadsheet that has links to data *and* images of visualizations that have been achieved with each of the datasets. Over *800* entries...see table below! (US centric, but very inspirational visualizations!), See the emebedded version below:

<p align="center">

<iframe width="600" height="800" src="https://datastudio.google.com/embed/reporting/eb2fea55-8eeb-440f-9c56-e8278266a368/page/vZWQB" frameborder="0" style="border:0" allowfullscreen>

</iframe>

</p>

## Our Tools

### Chart Creation and Export

1.  **Orange Data Mining** <https://orangedatamining.com/> Free software. Very intuitive, point-and-click, goes all the way from simple data-viz to ML!

2.  **Datawrapper Academy** <https://academy.datawrapper.de/> A free browser-based tool, requires registration and login.

3.  **RAWGraphs** <https://app.rawgraphs.io/> Another Free browser-based tool, no registration, no login. Simple interface too.

### Story Telling with Charts

1.  **Flourish Studio** <https://flourish.studio/> Beautiful and easy data visualization and storytelling

2.  **Infogram** <https://infogram.com/> Create engaging infographics and reports in minutes

3.  **Visme** <https://www.visme.co/> Yet another...

## Modules

