<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.280">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="author" content="Arvind Venkatadri">
<meta name="dcterms.date" content="2023-01-12">
<title>The Foundation Series in Quarto - Permutation Tests</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<script src="../../../../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../../../../">
<script src="../../../../../../site_libs/quarto-html/quarto.js"></script>
<script src="../../../../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../../../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../../../../../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../../../../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../../../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../../../../../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark"><script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script><style>html{ scroll-behavior: smooth; }</style>
<script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>
<meta property="og:title" content="The Foundation Series in Quarto - Permutation Tests">
<meta property="og:site-name" content="The Foundation Series in Quarto">
<meta name="twitter:title" content="The Foundation Series in Quarto - Permutation Tests">
<meta name="twitter:creator" content="@arvind_v">
<meta name="twitter:card" content="summary_large_image">
</head>
<body class="nav-sidebar floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="navbar navbar-expand-lg navbar-dark "><div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../../../../../index.html">
    <span class="navbar-title">The Foundation Series in Quarto</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
<li class="nav-item">
    <a class="nav-link" href="../../../../../../index.html">
 <span class="menu-text">Home</span></a>
  </li>  
</ul>
<ul class="navbar-nav navbar-nav-scroll ms-auto">
<li class="nav-item compact">
    <a class="nav-link" href="https://github.com/arvindvenkatadri/my-quarto-website"><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com/arvind_v"><i class="bi bi-twitter" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="../../../../../../blog.xml"><i class="bi bi-rss" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
<div class="quarto-toggle-container">
                  <a href="" class="quarto-color-scheme-toggle nav-link" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
                  <a href="" class="quarto-reader-toggle nav-link" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
              </div>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav><nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }"><div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title">Permutation Tests</h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto"><div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../../../blog.html" class="sidebar-item-text sidebar-link">Home</a>
  </div>
</li>
        <li class="px-0"><hr class="sidebar-divider hi "></li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">Teaching</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="px-0"><hr class="sidebar-divider hi "></li>
          <li class="px-0"><hr class="sidebar-divider hi "></li>
          <li class="px-0"><hr class="sidebar-divider hi "></li>
          <li class="px-0"><hr class="sidebar-divider hi "></li>
          <li class="px-0"><hr class="sidebar-divider hi "></li>
          <li class="px-0"><hr class="sidebar-divider hi "></li>
      </ul>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../../../content/posts/posts.html" class="sidebar-item-text sidebar-link">Posts</a>
  </div>
</li>
        <li class="px-0"><hr class="sidebar-divider hi "></li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../../../../content/projects/projects.html" class="sidebar-item-text sidebar-link">Projects</a>
  </div>
</li>
    </ul>
</div>
</nav><!-- margin-sidebar --><div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">On this page</h2>
   
  <ul>
<li>
<a href="#permutation-tests" id="toc-permutation-tests" class="nav-link active" data-scroll-target="#permutation-tests">Permutation Tests</a>
  <ul class="collapse">
<li><a href="#case-study-1-hot-wings-orders-vs-gender" id="toc-case-study-1-hot-wings-orders-vs-gender" class="nav-link" data-scroll-target="#case-study-1-hot-wings-orders-vs-gender">Case Study-1: Hot Wings Orders vs Gender</a></li>
  <li><a href="#case-study-2-verizon" id="toc-case-study-2-verizon" class="nav-link" data-scroll-target="#case-study-2-verizon">Case Study-2: Verizon</a></li>
  <li><a href="#case-story-3-recidivism" id="toc-case-story-3-recidivism" class="nav-link" data-scroll-target="#case-story-3-recidivism">Case Story-3: Recidivism</a></li>
  <li><a href="#case-study-4-matched-pairs-results-from-a-diving-championship." id="toc-case-study-4-matched-pairs-results-from-a-diving-championship." class="nav-link" data-scroll-target="#case-study-4-matched-pairs-results-from-a-diving-championship.">Case Study-4: Matched Pairs: Results from a diving championship.</a></li>
  <li><a href="#case-study-5-flight-delays" id="toc-case-study-5-flight-delays" class="nav-link" data-scroll-target="#case-study-5-flight-delays">Case Study #5: Flight Delays</a></li>
  <li><a href="#case-study-6-walmart-vs-target" id="toc-case-study-6-walmart-vs-target" class="nav-link" data-scroll-target="#case-study-6-walmart-vs-target">Case Study #6: Walmart vs Target</a></li>
  <li><a href="#case-study-7-proportions-between-categorical-variables" id="toc-case-study-7-proportions-between-categorical-variables" class="nav-link" data-scroll-target="#case-study-7-proportions-between-categorical-variables">Case Study 7: Proportions between Categorical Variables</a></li>
  </ul>
</li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title d-none d-lg-block">Permutation Tests</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Arvind Venkatadri </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 12, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header><section id="permutation-tests" class="level2"><h2 class="anchored" data-anchor-id="permutation-tests">Permutation Tests</h2>
<section id="case-study-1-hot-wings-orders-vs-gender" class="level3"><h3 class="anchored" data-anchor-id="case-study-1-hot-wings-orders-vs-gender">Case Study-1: Hot Wings Orders vs Gender</h3>
<p>A student conducted a study of hot wings and beer consumption at a Bar. She asked patrons at the bar to record their consumption of hot wings and beer over the course of several hours. She wanted to know if people who ate more hot wings would then drink more beer. In addition, she investigated whether or not gender had an impact on hot wings or beer consumption.</p>
<div class="cell">
<details><summary>Show the Code</summary><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1"></a>Beerwings <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"../../../../../materials/data/resampling/Beerwings.csv"</span>)</span>
<span id="cb1-2"><a href="#cb1-2"></a><span class="fu">inspect</span>(Beerwings)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>
categorical variables:  
    name     class levels  n missing
1 Gender character      2 30       0
                                   distribution
1 F (50%), M (50%)                             

quantitative variables:  
      name   class min    Q1 median    Q3 max     mean        sd  n missing
1       ID integer   1  8.25   15.5 22.75  30 15.50000  8.803408 30       0
2 Hotwings integer   4  8.00   12.5 15.50  21 11.93333  4.784554 30       0
3     Beer integer   0 24.00   30.0 36.00  48 26.20000 11.842064 30       0</code></pre>
</div>
</div>
<p>Let us calculate the observed difference in <code>Hotwings</code> consumption between Males and Females ( <code>Gender</code>)</p>
<div class="cell">
<details><summary>Show the Code</summary><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1"></a><span class="fu">mean</span>(Hotwings <span class="sc">~</span> Gender, <span class="at">data =</span> Beerwings)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>        F         M 
 9.333333 14.533333 </code></pre>
</div>
<details><summary>Show the Code</summary><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1"></a>obs_diff_wings <span class="ot">&lt;-</span> mosaic<span class="sc">::</span><span class="fu">diffmean</span>(<span class="at">data =</span> Beerwings, Hotwings <span class="sc">~</span> Gender)</span>
<span id="cb5-2"><a href="#cb5-2"></a>obs_diff_wings </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>diffmean 
     5.2 </code></pre>
</div>
</div>
<div class="cell">
<details><summary>Show the Code</summary><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1"></a><span class="fu">gf_boxplot</span>(<span class="at">data =</span> Beerwings, Hotwings <span class="sc">~</span> Gender, <span class="at">title =</span> <span class="st">"Hotwings Consumption by Gender"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<p><img src="permutation_files/figure-html/unnamed-chunk-3-1.png" style="width:50.0%;height:50.0%"></p>
</div>
</div>
<p>The observed difference in mean consumption of Hotwings between Males and Females is 5.2. Could this have occurred by chance? Here is our formulation of the Hypotheses:</p>
<p><span class="math display">\[
NULL\ Hypothesis\ H_0 =&gt; No\&nbsp;difference\ between\ means\ across\ groups\\
Alternative\ Hypothesis\
H_a =&gt;Significant\ difference\ between\ the\ means\
\]</span></p>
<p>So we perform a Permutation Test to check:</p>
<div class="cell">
<details><summary>Show the Code</summary><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1"></a>null_dist_wings <span class="ot">&lt;-</span> <span class="fu">do</span>(<span class="dv">1000</span>) <span class="sc">*</span> <span class="fu">diffmean</span>(Hotwings <span class="sc">~</span> <span class="fu">shuffle</span>(Gender), <span class="at">data =</span> Beerwings)</span>
<span id="cb8-2"><a href="#cb8-2"></a>null_dist_wings <span class="sc">%&gt;%</span> <span class="fu">head</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>    diffmean
1 -0.2666667
2 -2.4000000
3  2.1333333
4 -3.2000000
5 -0.1333333
6  1.2000000</code></pre>
</div>
<details><summary>Show the Code</summary><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1"></a><span class="fu">gf_histogram</span>(<span class="at">data =</span> null_dist_wings, <span class="sc">~</span> diffmean) <span class="sc">%&gt;%</span> </span>
<span id="cb10-2"><a href="#cb10-2"></a>  <span class="fu">gf_vline</span>(<span class="at">xintercept =</span> obs_diff_wings, <span class="at">colour =</span> <span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<p><img src="permutation_files/figure-html/unnamed-chunk-4-1.png" style="width:50.0%;height:50.0%"></p>
</div>
<details><summary>Show the Code</summary><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1"></a><span class="fu">prop1</span>(<span class="sc">~</span> diffmean <span class="sc">&gt;=</span> obs_diff_wings, <span class="at">data =</span> null_dist_wings)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>  prop_TRUE 
0.000999001 </code></pre>
</div>
</div>
<p>The <span class="math inline">\(\color{red}{red\ line}\)</span> shows the actual measured mean difference in Hot Wings consumption. The probability that our Permutation distribution is able to equal or exceed that number is <span class="math inline">\(0.001998002\)</span> and we have to reject the Null Hypothesis that the means are identical.</p>
</section><section id="case-study-2-verizon" class="level3"><h3 class="anchored" data-anchor-id="case-study-2-verizon">Case Study-2: Verizon</h3>
<div class="cell">
<details><summary>Show the Code</summary><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1"></a>verizon <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"../../../../../materials/data/resampling/Verizon.csv"</span>)</span>
<span id="cb13-2"><a href="#cb13-2"></a><span class="fu">inspect</span>(verizon)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>
categorical variables:  
   name     class levels    n missing
1 Group character      2 1687       0
                                   distribution
1 ILEC (98.6%), CLEC (1.4%)                    

quantitative variables:  
  name   class min   Q1 median   Q3   max     mean       sd    n missing
1 Time numeric   0 0.75   3.63 7.35 191.6 8.522009 14.78848 1687       0</code></pre>
</div>
</div>
<div class="cell">
<details><summary>Show the Code</summary><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1"></a><span class="fu">mean</span>(Time <span class="sc">~</span> Group, <span class="at">data =</span> verizon)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>     CLEC      ILEC 
16.509130  8.411611 </code></pre>
</div>
<details><summary>Show the Code</summary><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1"></a>obs_diff_verizon <span class="ot">&lt;-</span> <span class="fu">diffmean</span>(Time <span class="sc">~</span> Group, <span class="at">data =</span> verizon)</span>
<span id="cb17-2"><a href="#cb17-2"></a>obs_diff_verizon</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>diffmean 
-8.09752 </code></pre>
</div>
</div>
<div class="cell">
<details><summary>Show the Code</summary><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1"></a>null_dist_verizon <span class="ot">&lt;-</span> <span class="fu">do</span>(<span class="dv">1000</span>) <span class="sc">*</span> <span class="fu">diffmean</span>(Time <span class="sc">~</span> <span class="fu">shuffle</span>(Group), <span class="at">data =</span> verizon)</span>
<span id="cb19-2"><a href="#cb19-2"></a><span class="fu">gf_histogram</span>(<span class="at">data =</span> null_dist_verizon, <span class="sc">~</span> diffmean) <span class="sc">%&gt;%</span> </span>
<span id="cb19-3"><a href="#cb19-3"></a>  <span class="fu">gf_vline</span>(<span class="at">xintercept =</span> obs_diff_wings, <span class="at">colour =</span> <span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<p><img src="permutation_files/figure-html/unnamed-chunk-7-1.png" style="width:50.0%;height:50.0%"></p>
</div>
<details><summary>Show the Code</summary><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1"></a><span class="fu">prop1</span>(<span class="sc">~</span> diffmean <span class="sc">&gt;=</span> obs_diff_wings, <span class="at">data =</span> null_dist_verizon)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>  prop_TRUE 
0.008991009 </code></pre>
</div>
</div>
</section><section id="case-story-3-recidivism" class="level3"><h3 class="anchored" data-anchor-id="case-story-3-recidivism">Case Story-3: Recidivism</h3>
<p>Do criminals released after a jail term commit crimes again?</p>
<div class="cell">
<details><summary>Show the Code</summary><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1"></a>recidivism <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"../../../../../materials/data/resampling/Recidivism.csv"</span>)</span>
<span id="cb22-2"><a href="#cb22-2"></a><span class="fu">inspect</span>(recidivism)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>
categorical variables:  
     name     class levels     n missing
1  Gender character      2 17019       3
2     Age character      5 17019       3
3   Age25 character      2 17019       3
4 Offense character      2 17022       0
5   Recid character      2 17022       0
6    Type character      3 17022       0
                                   distribution
1 M (87.7%), F (12.3%)                         
2 25-34 (36.6%), 35-44 (23.7%) ...             
3 Over 25 (81.9%), Under 25 (18.1%)            
4 Felony (80.6%), Misdemeanor (19.4%)          
5 No (68.4%), Yes (31.6%)                      
6 No Recidivism (68.4%), New (20.2%) ...       

quantitative variables:  
  name   class min  Q1 median  Q3  max     mean       sd    n missing
1 Days integer   0 241    418 687 1095 473.3275 283.1393 5386   11636</code></pre>
</div>
</div>
<p>There are some missing values in the variable <tt> <code>Age25</code></tt>. The <tt> <code>complete.cases</code></tt> command gives the row numbers where values are not missing. We create a new data frame omitting the rows where there is a missing value in the <tt> ‘Age25’ </tt> variable.</p>
<div class="cell">
<details><summary>Show the Code</summary><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1"></a>recidivism_na <span class="ot">&lt;-</span> recidivism <span class="sc">%&gt;%</span> tidyr<span class="sc">::</span><span class="fu">drop_na</span>(Age25)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Also, the variable <tt><code>Recid</code></tt> is a factor variable coded “Yes” or “No”. We convert it to a numeric variable of 1’s and 0’s.</p>
<div class="cell">
<details><summary>Show the Code</summary><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1"></a>recidivism_na <span class="ot">&lt;-</span> recidivism_na <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">Recid2 =</span> <span class="fu">ifelse</span>(Recid<span class="sc">==</span><span class="st">"Yes"</span>, <span class="dv">1</span>, <span class="dv">0</span>))</span>
<span id="cb25-2"><a href="#cb25-2"></a></span>
<span id="cb25-3"><a href="#cb25-3"></a>obs_diff_recid <span class="ot">&lt;-</span> <span class="fu">diffmean</span>( Recid2 <span class="sc">~</span> Age25, <span class="at">data =</span> recidivism_na)</span>
<span id="cb25-4"><a href="#cb25-4"></a>obs_diff_recid</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>  diffmean 
0.05919913 </code></pre>
</div>
<details><summary>Show the Code</summary><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1"></a>null_dist_recid <span class="ot">&lt;-</span> <span class="fu">do</span>(<span class="dv">1000</span>) <span class="sc">*</span> <span class="fu">diffmean</span>( Recid2 <span class="sc">~</span> <span class="fu">shuffle</span>(Age25), <span class="at">data =</span> recidivism_na)</span>
<span id="cb27-2"><a href="#cb27-2"></a></span>
<span id="cb27-3"><a href="#cb27-3"></a><span class="fu">gf_histogram</span>( <span class="sc">~</span> diffmean, <span class="at">data =</span> null_dist_recid) <span class="sc">%&gt;%</span> </span>
<span id="cb27-4"><a href="#cb27-4"></a>  <span class="fu">gf_vline</span>(<span class="at">xintercept =</span> obs_diff_recid, <span class="at">colour =</span> <span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<p><img src="permutation_files/figure-html/unnamed-chunk-10-1.png" style="width:50.0%;height:50.0%"></p>
</div>
</div>
</section><section id="case-study-4-matched-pairs-results-from-a-diving-championship." class="level3"><h3 class="anchored" data-anchor-id="case-study-4-matched-pairs-results-from-a-diving-championship.">Case Study-4: Matched Pairs: Results from a diving championship.</h3>
<div class="cell">
<details><summary>Show the Code</summary><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1"></a>Diving2017 <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"../../../../../materials/data/resampling/Diving2017.csv"</span>)</span>
<span id="cb28-2"><a href="#cb28-2"></a><span class="fu">head</span>(Diving2017)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>              Name     Country Semifinal  Final
1 CHEONG Jun Hoong    Malaysia    325.50 397.50
2         SI Yajie       China    382.80 396.00
3         REN Qian       China    367.50 391.95
4       KIM Mi Rae North Korea    346.00 385.55
5       WU Melissa   Australia    318.70 370.20
6    KIM Kuk Hyang North Korea    360.85 360.00</code></pre>
</div>
<details><summary>Show the Code</summary><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1"></a><span class="fu">inspect</span>(Diving2017)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>
categorical variables:  
     name     class levels  n missing
1    Name character     12 12       0
2 Country character      8 12       0
                                   distribution
1  SI Yajie (8.3%) ...                         
2 Canada (16.7%), China (16.7%) ...            

quantitative variables:  
       name   class    min       Q1  median      Q3   max    mean       sd  n
1 Semifinal numeric 313.70 322.2000 325.625 356.575 382.8 338.500 22.94946 12
2     Final numeric 283.35 318.5875 358.925 387.150 397.5 350.475 40.02204 12
  missing
1       0
2       0</code></pre>
</div>
</div>
<p>The data is made up of <strong>paired</strong> observations per swimmer. So we need to take the difference between the two swim records for <em>each</em> swimmer and then shuffle the differences to either polarity. Another way to look at this is to shuffle the records between <code>Semifinal</code> and <code>Final</code> on a per Swimmer basis.</p>
<div class="cell">
<details><summary>Show the Code</summary><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1"></a>Diving2017</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>                     Name     Country Semifinal  Final
1        CHEONG Jun Hoong    Malaysia    325.50 397.50
2                SI Yajie       China    382.80 396.00
3                REN Qian       China    367.50 391.95
4              KIM Mi Rae North Korea    346.00 385.55
5              WU Melissa   Australia    318.70 370.20
6           KIM Kuk Hyang North Korea    360.85 360.00
7         ITAHASHI Minami       Japan    313.70 357.85
8        BENFEITO Meaghan      Canada    355.15 331.40
9          PAMG Pandelela    Malaysia    322.75 322.40
10        CHAMANDY Olivia      Canada    320.55 307.15
11       PARRATTO Jessica         USA    322.75 302.35
12 MURILLO URREA Carolina    Colombia    325.75 283.35</code></pre>
</div>
<details><summary>Show the Code</summary><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1"></a>Diving2017 <span class="sc">%&gt;%</span> <span class="fu">diffmean</span>(<span class="at">data =</span> ., Final <span class="sc">~</span> Semifinal, <span class="at">only.2 =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>  318.7-313.7  320.55-318.7 322.75-320.55  325.5-322.75  325.75-325.5 
       12.350       -63.050         5.225        85.125      -114.150 
   346-325.75    355.15-346 360.85-355.15  367.5-360.85   382.8-367.5 
      102.200       -54.150        28.600        31.950         4.050 </code></pre>
</div>
<details><summary>Show the Code</summary><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1"></a>obs_diff_swim <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="sc">~</span> Final <span class="sc">-</span> Semifinal, <span class="at">data =</span> Diving2017)</span>
<span id="cb36-2"><a href="#cb36-2"></a>obs_diff_swim</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>[1] 11.975</code></pre>
</div>
</div>
<div class="cell">
<details><summary>Show the Code</summary><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1"></a>polarity <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="dv">1</span>, <span class="dv">6</span>), <span class="fu">rep</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">6</span>))</span>
<span id="cb38-2"><a href="#cb38-2"></a>polarity</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code> [1]  1  1  1  1  1  1 -1 -1 -1 -1 -1 -1</code></pre>
</div>
<details><summary>Show the Code</summary><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1"></a>null_dist_swim <span class="ot">&lt;-</span> <span class="fu">do</span>(<span class="dv">100000</span>) <span class="sc">*</span> <span class="fu">mean</span>(<span class="at">data =</span> Diving2017, </span>
<span id="cb40-2"><a href="#cb40-2"></a>                                    <span class="sc">~</span>(Final <span class="sc">-</span> Semifinal) <span class="sc">*</span> <span class="fu">resample</span>(polarity,</span>
<span id="cb40-3"><a href="#cb40-3"></a>                                                    <span class="at">replace =</span> <span class="cn">TRUE</span>))</span>
<span id="cb40-4"><a href="#cb40-4"></a>null_dist_swim <span class="sc">%&gt;%</span> <span class="fu">head</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>          mean
1   0.03333333
2  14.26666667
3  13.17500000
4 -17.60833333
5   1.85000000
6  18.78333333</code></pre>
</div>
<details><summary>Show the Code</summary><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1"></a><span class="fu">gf_histogram</span>(<span class="at">data =</span> null_dist_swim, <span class="sc">~</span>mean) <span class="sc">%&gt;%</span> </span>
<span id="cb42-2"><a href="#cb42-2"></a>  <span class="fu">gf_vline</span>(<span class="at">xintercept =</span> obs_diff_swim, <span class="at">colour =</span> <span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<p><img src="permutation_files/figure-html/unnamed-chunk-13-1.png" style="width:50.0%;height:50.0%"></p>
</div>
</div>
</section><section id="case-study-5-flight-delays" class="level3"><h3 class="anchored" data-anchor-id="case-study-5-flight-delays">Case Study #5: Flight Delays</h3>
<p>LaGuardia Airport (LGA) is one of three major airports that serves the New York City metropolitan area. In 2008, over 23 million passengers and over 375 000 planes flew in or out of LGA. United Airlines and America Airlines are two major airlines that schedule services at LGA. The data set <code>FlightDelays</code> contains information on all 4029 departures of these two airlines from LGA during May and June 2009.</p>
<div class="cell">
<details><summary>Show the Code</summary><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1"></a>flightDelays <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"../../../../../materials/data/resampling/FlightDelays.csv"</span>)</span>
<span id="cb43-2"><a href="#cb43-2"></a></span>
<span id="cb43-3"><a href="#cb43-3"></a><span class="fu">inspect</span>(flightDelays)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>
categorical variables:  
         name     class levels    n missing
1     Carrier character      2 4029       0
2 Destination character      7 4029       0
3  DepartTime character      5 4029       0
4         Day character      7 4029       0
5       Month character      2 4029       0
6   Delayed30 character      2 4029       0
                                   distribution
1 AA (72.1%), UA (27.9%)                       
2 ORD (44.3%), DFW (22.8%), MIA (15.1%) ...    
3 8-Noon (26.1%), Noon-4pm (26%) ...           
4 Fri (15.8%), Mon (15.6%), Tue (15.6%) ...    
5 June (50.4%), May (49.6%)                    
6 No (85.2%), Yes (14.8%)                      

quantitative variables:  
          name   class min   Q1 median   Q3  max      mean         sd    n
1           ID integer   1 1008   2015 3022 4029 2015.0000 1163.21645 4029
2     FlightNo integer  71  371    691  787 2255  827.1035  551.30939 4029
3 FlightLength integer  68  155    163  228  295  185.3011   41.78783 4029
4        Delay integer -19   -6     -3    5  693   11.7379   41.63050 4029
  missing
1       0
2       0
3       0
4       0</code></pre>
</div>
</div>
<p>The variables in the <code>flightDelays</code> dataset are:</p>
<table class="table">
<caption>flightDelay dataset variables</caption>
<colgroup>
<col style="width: 25%">
<col style="width: 75%">
</colgroup>
<thead><tr class="header">
<th>Variable</th>
<th>Description</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>Carrier</td>
<td>UA=United Airlines, AA=American Airlines</td>
</tr>
<tr class="even">
<td>FlightNo</td>
<td>Flight number</td>
</tr>
<tr class="odd">
<td>Destination</td>
<td>Airport code</td>
</tr>
<tr class="even">
<td>DepartTime</td>
<td>Scheduled departure time in 4 h intervals</td>
</tr>
<tr class="odd">
<td>Day</td>
<td>Day of the Week</td>
</tr>
<tr class="even">
<td>Month</td>
<td>May or June</td>
</tr>
<tr class="odd">
<td>Delay</td>
<td>Minutes flight delayed (negative indicates early departure)</td>
</tr>
<tr class="even">
<td>Delayed30</td>
<td>Departure delayed more than 30 min? Yes or No</td>
</tr>
<tr class="odd">
<td>FlightLength</td>
<td>Length of time of flight (minutes)</td>
</tr>
</tbody>
</table>
<ol type="a">
<li>Let us compute the proportion of times that each carrier’s flights was delayed more than 20 min. We will conduct a two-sided test to see if the difference in these proportions is statistically significant.</li>
</ol>
<div class="cell">
<details><summary>Show the Code</summary><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1"></a><span class="fu">prop</span>(<span class="at">data =</span> flightDelays, Delay <span class="sc">&gt;=</span> <span class="dv">20</span> <span class="sc">~</span> Carrier)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>prop_TRUE.AA prop_TRUE.UA 
   0.1713696    0.2226180 </code></pre>
</div>
<details><summary>Show the Code</summary><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1"></a>obs_diff_delay <span class="ot">&lt;-</span> <span class="fu">diffprop</span>(<span class="at">data =</span> flightDelays, Delay <span class="sc">&gt;=</span> <span class="dv">20</span> <span class="sc">~</span> Carrier)</span>
<span id="cb47-2"><a href="#cb47-2"></a>obs_diff_delay</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>  diffprop 
0.05124841 </code></pre>
</div>
</div>
<p>We see carrier AA has a 17.13% chance of delays&gt;= 20, while UA has 22.26% chance. The difference is 5.12%. Is this statistically significant? We take the Delays for both Carriers and perform a permutation test by <code>shuffle</code> on the <code>carrier</code> variable:</p>
<div class="cell">
<details><summary>Show the Code</summary><div class="sourceCode cell-code" id="cb49"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1"></a>null_dist_delay <span class="ot">&lt;-</span> <span class="fu">do</span>(<span class="dv">10000</span>) <span class="sc">*</span> <span class="fu">diffprop</span>(<span class="at">data =</span> flightDelays, Delay <span class="sc">&gt;=</span> <span class="dv">20</span> <span class="sc">~</span> <span class="fu">shuffle</span>(Carrier))</span>
<span id="cb49-2"><a href="#cb49-2"></a>null_dist_delay <span class="sc">%&gt;%</span> <span class="fu">head</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>      diffprop
1  0.001864904
2  0.009272430
3  0.008037842
4  0.027791243
5 -0.012950146
6  0.005568667</code></pre>
</div>
<details><summary>Show the Code</summary><div class="sourceCode cell-code" id="cb51"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1"></a><span class="fu">gf_histogram</span>(<span class="at">data =</span> null_dist_delay, <span class="sc">~</span> diffprop) <span class="sc">%&gt;%</span> <span class="fu">gf_vline</span>(<span class="at">xintercept =</span> obs_diff_delay, <span class="at">color =</span> <span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<p><img src="permutation_files/figure-html/unnamed-chunk-15-1.png" style="width:50.0%;height:50.0%"></p>
</div>
</div>
<p>It appears that the difference indelay times is significant. We can compute the <code>p-value</code> based on this test:</p>
<div class="cell">
<details><summary>Show the Code</summary><div class="sourceCode cell-code" id="cb52"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1"></a><span class="dv">2</span><span class="sc">*</span> <span class="fu">mean</span>(null_dist_delay <span class="sc">&gt;=</span> obs_diff_delay)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>[1] 4e-04</code></pre>
</div>
</div>
<p>which is very small. Hence we reject the null Hypothesis that there is no difference between <code>carrier</code>s on <code>delay times</code>.</p>
<ol start="2" type="a">
<li>Compute the variance in the flight delay lengths for each carrier. Conduct a test to see if the variance for United Airlines differs from that of American Airlines.</li>
</ol>
<div class="cell">
<details><summary>Show the Code</summary><div class="sourceCode cell-code" id="cb54"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1"></a><span class="fu">var</span>(<span class="at">data =</span> flightDelays, Delay <span class="sc">~</span> Carrier)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>      AA       UA 
1606.457 2037.525 </code></pre>
</div>
<details><summary>Show the Code</summary><div class="sourceCode cell-code" id="cb56"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1"></a><span class="co"># There is no readymade function in mosaic called `diffvar`...so...we construct one</span></span>
<span id="cb56-2"><a href="#cb56-2"></a>obs_diff_var <span class="ot">&lt;-</span> <span class="fu">diff</span>(<span class="fu">var</span>(<span class="at">data =</span> flightDelays, Delay <span class="sc">~</span> Carrier))</span>
<span id="cb56-3"><a href="#cb56-3"></a>obs_diff_var</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>      UA 
431.0677 </code></pre>
</div>
</div>
<p>The difference in variances in <code>Delay</code> between the two <code>carrier</code>s is <span class="math inline">\(-431.0677\)</span>. In our Permutation Test, we <code>shuffle</code> the <code>Carrier</code> variable:</p>
<div class="cell">
<details><summary>Show the Code</summary><div class="sourceCode cell-code" id="cb58"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1"></a>obs_diff_var <span class="ot">&lt;-</span> <span class="fu">diff</span>(<span class="fu">var</span>(<span class="at">data =</span> flightDelays, Delay <span class="sc">~</span> Carrier))</span>
<span id="cb58-2"><a href="#cb58-2"></a>null_dist_var <span class="ot">&lt;-</span></span>
<span id="cb58-3"><a href="#cb58-3"></a>  <span class="fu">do</span>(<span class="dv">10000</span>) <span class="sc">*</span> <span class="fu">diff</span>(<span class="fu">var</span>(<span class="at">data =</span> flightDelays, Delay <span class="sc">~</span> <span class="fu">shuffle</span>(Carrier)))</span>
<span id="cb58-4"><a href="#cb58-4"></a>null_dist_var <span class="sc">%&gt;%</span> <span class="fu">head</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>          UA
1   76.62204
2 -441.84771
3 -282.74600
4 -461.33198
5  217.88715
6  205.21916</code></pre>
</div>
<details><summary>Show the Code</summary><div class="sourceCode cell-code" id="cb60"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1"></a><span class="co"># The null distribution variable is called `UA`</span></span>
<span id="cb60-2"><a href="#cb60-2"></a><span class="fu">gf_histogram</span>(<span class="at">data =</span> null_dist_var, <span class="sc">~</span> UA) <span class="sc">%&gt;%</span> <span class="fu">gf_vline</span>(<span class="at">xintercept =</span> obs_diff_delay, <span class="at">color =</span> <span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<p><img src="permutation_files/figure-html/unnamed-chunk-18-1.png" style="width:50.0%;height:50.0%"></p>
</div>
<details><summary>Show the Code</summary><div class="sourceCode cell-code" id="cb61"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1"></a><span class="dv">2</span> <span class="sc">*</span> <span class="fu">mean</span>(null_dist_var <span class="sc">&gt;=</span> obs_diff_var)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2924</code></pre>
</div>
</div>
<p>Clearly there is no case for a significant difference in variances!</p>
</section><section id="case-study-6-walmart-vs-target" class="level3"><h3 class="anchored" data-anchor-id="case-study-6-walmart-vs-target">Case Study #6: Walmart vs Target</h3>
<p>Is there a difference in the price of groceries sold by the two retailers Target and Walmart? The data set <code>Groceries</code> contains a sample of grocery items and their prices advertised on their respective web sites on one specific day.</p>
<ol type="a">
<li>Inspect the data set, then explain why this is an example of matched pairs data.</li>
<li>Compute summary statistics of the prices for each store.</li>
<li>Conduct a permutation test to determine whether or not there is a difference in the mean prices.</li>
<li>Create a <del>histogram</del> bar-chart of the difference in prices. What is unusual about Quaker Oats Life cereal?</li>
<li>Redo the hypothesis test without this observation. Do you reach the same conclusion?</li>
</ol>
<div class="cell">
<details><summary>Show the Code</summary><div class="sourceCode cell-code" id="cb63"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1"></a>groceries <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"../../../../../materials/data/resampling/Groceries.csv"</span>) <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">Product =</span> stringr<span class="sc">::</span><span class="fu">str_squish</span>(Product))</span>
<span id="cb63-2"><a href="#cb63-2"></a><span class="fu">head</span>(groceries)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>                           Product    Size Target Walmart
1          Kellogg NutriGrain Bars  8 bars   2.50    2.78
2 Quaker Oats Life Cereal Original    18oz   3.19    6.01
3       General Mills Lucky Charms  11.50z   3.19    2.98
4        Quaker Oats Old Fashioned    18oz   2.82    2.68
5             Nabisco Oreo Cookies 14.3oz    2.99    2.98
6               Nabisco Chips Ahoy    13oz   2.64    1.98</code></pre>
</div>
<details><summary>Show the Code</summary><div class="sourceCode cell-code" id="cb65"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1"></a><span class="fu">inspect</span>(groceries)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>
categorical variables:  
     name     class levels  n missing
1 Product character     30 30       0
2    Size character     24 30       0
                                   distribution
1 Annie's Macaroni &amp; Cheese (3.3%) ...         
2 18oz (10%), 12oz (6.7%) ...                  

quantitative variables:  
     name   class  min     Q1 median    Q3  max     mean       sd  n missing
1  Target numeric 0.99 1.8275  2.545 3.140 7.99 2.762333 1.582128 30       0
2 Walmart numeric 1.00 1.7600  2.340 2.955 6.98 2.705667 1.560211 30       0</code></pre>
</div>
</div>
<p>We see that the comparison is to be made between two prices for the <em>same</em> product, and hence this is one more example of <code>paired data</code>, as in Case Study #4. Let us plot the prices for the products:</p>
<div class="cell">
<details><summary>Show the Code</summary><div class="sourceCode cell-code" id="cb67"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1"></a><span class="fu">gf_col</span>(<span class="at">data =</span> groceries,</span>
<span id="cb67-2"><a href="#cb67-2"></a>       Target <span class="sc">~</span> Product,</span>
<span id="cb67-3"><a href="#cb67-3"></a>       <span class="at">fill =</span> <span class="st">"#0073C299"</span>,</span>
<span id="cb67-4"><a href="#cb67-4"></a>       <span class="at">width =</span> <span class="fl">0.5</span> ) <span class="sc">%&gt;%</span> </span>
<span id="cb67-5"><a href="#cb67-5"></a>  <span class="fu">gf_col</span>(<span class="at">data =</span> groceries,</span>
<span id="cb67-6"><a href="#cb67-6"></a>         <span class="sc">-</span>Walmart <span class="sc">~</span> Product,</span>
<span id="cb67-7"><a href="#cb67-7"></a>         <span class="at">fill =</span> <span class="st">"#EFC00099"</span>,</span>
<span id="cb67-8"><a href="#cb67-8"></a>         <span class="at">ylab =</span> <span class="st">"Prices"</span>,</span>
<span id="cb67-9"><a href="#cb67-9"></a>         <span class="at">width =</span> <span class="fl">0.5</span></span>
<span id="cb67-10"><a href="#cb67-10"></a>       ) <span class="sc">%&gt;%</span> </span>
<span id="cb67-11"><a href="#cb67-11"></a>  <span class="fu">gf_col</span>(<span class="at">data =</span> groceries <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Product <span class="sc">==</span> <span class="st">"Quaker Oats Life Cereal Original"</span>), </span>
<span id="cb67-12"><a href="#cb67-12"></a>         <span class="sc">-</span>Walmart <span class="sc">~</span> Product,</span>
<span id="cb67-13"><a href="#cb67-13"></a>         <span class="at">fill =</span> <span class="st">"red"</span>, </span>
<span id="cb67-14"><a href="#cb67-14"></a>         <span class="at">width =</span> <span class="fl">0.5</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb67-15"><a href="#cb67-15"></a>  <span class="fu">gf_theme</span>(<span class="fu">theme_classic</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb67-16"><a href="#cb67-16"></a>  <span class="fu">gf_theme</span>(ggplot2<span class="sc">::</span><span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(</span>
<span id="cb67-17"><a href="#cb67-17"></a>    <span class="at">size =</span> <span class="dv">8</span>,</span>
<span id="cb67-18"><a href="#cb67-18"></a>    <span class="at">face =</span> <span class="st">"bold"</span>,</span>
<span id="cb67-19"><a href="#cb67-19"></a>    <span class="at">vjust =</span> <span class="dv">0</span>,</span>
<span id="cb67-20"><a href="#cb67-20"></a>    <span class="at">hjust =</span> <span class="dv">1</span></span>
<span id="cb67-21"><a href="#cb67-21"></a>  ))) <span class="sc">%&gt;%</span> <span class="fu">gf_theme</span>(ggplot2<span class="sc">::</span><span class="fu">coord_flip</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<p><img src="permutation_files/figure-html/unnamed-chunk-20-1.png" style="width:50.0%;height:50.0%"></p>
</div>
</div>
<p>We see that the price difference between Walmart and Target prices is highest for the <code>Product</code> named <code>Quaker Oats Life Cereal Original</code>. Let us check the mean difference in prices:</p>
<div class="cell">
<details><summary>Show the Code</summary><div class="sourceCode cell-code" id="cb68"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1"></a><span class="fu">diffmean</span>(<span class="at">data =</span> groceries, Walmart <span class="sc">~</span> Target, <span class="at">only.2 =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>   1-0.99    1.22-1 1.42-1.22 1.49-1.42 1.59-1.49 1.62-1.59 1.79-1.62 1.94-1.79 
-0.580000  0.170000  0.210000 -0.100000  0.190000  0.070000  0.180000  0.160000 
1.99-1.94 2.12-1.99 2.39-2.12  2.5-2.39  2.59-2.5 2.64-2.59 2.79-2.64 2.82-2.79 
 0.090000  0.010000  0.200000  0.600000 -0.200000 -0.600000  0.660000  0.040000 
2.99-2.82 3.19-2.99 3.49-3.19 3.99-3.49 4.79-3.99 7.19-4.79 7.99-7.19 
 0.220000  1.263333 -1.183333 -0.480000  2.290000  2.190000  0.000000 </code></pre>
</div>
<details><summary>Show the Code</summary><div class="sourceCode cell-code" id="cb70"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1"></a>obs_diff_price <span class="ot">=</span> <span class="fu">mean</span>( <span class="sc">~</span> Walmart <span class="sc">-</span> Target, <span class="at">data =</span> groceries)</span>
<span id="cb70-2"><a href="#cb70-2"></a>obs_diff_price</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>[1] -0.05666667</code></pre>
</div>
</div>
<p>Let us perform the pair-wise permutation test on prices, by shuffling the two store names:</p>
<div class="cell">
<details><summary>Show the Code</summary><div class="sourceCode cell-code" id="cb72"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1"></a>polarity <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="dv">1</span>, <span class="dv">15</span>), <span class="fu">rep</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">15</span>))</span>
<span id="cb72-2"><a href="#cb72-2"></a>polarity</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code> [1]  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
[26] -1 -1 -1 -1 -1</code></pre>
</div>
<details><summary>Show the Code</summary><div class="sourceCode cell-code" id="cb74"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1"></a>null_dist_price <span class="ot">&lt;-</span> <span class="fu">do</span>(<span class="dv">100000</span>) <span class="sc">*</span> <span class="fu">mean</span>(<span class="at">data =</span> groceries, </span>
<span id="cb74-2"><a href="#cb74-2"></a>                                    <span class="sc">~</span>(Walmart<span class="sc">-</span>Target) <span class="sc">*</span> <span class="fu">resample</span>(polarity,</span>
<span id="cb74-3"><a href="#cb74-3"></a>                                                    <span class="at">replace =</span> <span class="cn">TRUE</span>))</span>
<span id="cb74-4"><a href="#cb74-4"></a>null_dist_price <span class="sc">%&gt;%</span> <span class="fu">head</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>         mean
1  0.07800000
2 -0.07466667
3 -0.18133333
4 -0.17400000
5 -0.24066667
6  0.10000000</code></pre>
</div>
<details><summary>Show the Code</summary><div class="sourceCode cell-code" id="cb76"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1"></a><span class="fu">gf_histogram</span>(<span class="at">data =</span> null_dist_price, <span class="sc">~</span>mean) <span class="sc">%&gt;%</span> </span>
<span id="cb76-2"><a href="#cb76-2"></a>  <span class="fu">gf_vline</span>(<span class="at">xintercept =</span> obs_diff_price, <span class="at">colour =</span> <span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<p><img src="permutation_files/figure-html/unnamed-chunk-22-1.png" style="width:50.0%;height:50.0%"></p>
</div>
<details><summary>Show the Code</summary><div class="sourceCode cell-code" id="cb77"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1"></a><span class="dv">2</span><span class="sc">*</span>(<span class="fu">sum</span>(null_dist_price <span class="sc">&gt;=</span> obs_diff_price <span class="sc">+</span> <span class="dv">1</span>)<span class="sc">/</span>(<span class="dv">100000</span><span class="sc">+</span><span class="dv">1</span>)) <span class="co">#P-value</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
<p>Does not seem to be aby significant difference in prices…</p>
<p>Suppose we knock off the Quaker Cereal data item…</p>
<div class="cell">
<details><summary>Show the Code</summary><div class="sourceCode cell-code" id="cb79"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1"></a><span class="fu">which</span>(groceries<span class="sc">$</span>Product <span class="sc">==</span> <span class="st">"Quaker Oats Life Cereal Original"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>[1] 2</code></pre>
</div>
<details><summary>Show the Code</summary><div class="sourceCode cell-code" id="cb81"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1"></a>groceries_less <span class="ot">&lt;-</span> groceries[<span class="sc">-</span><span class="dv">2</span>,]</span>
<span id="cb81-2"><a href="#cb81-2"></a>groceries_less</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>                                                    Product     Size Target
1                                   Kellogg NutriGrain Bars   8 bars   2.50
3                                General Mills Lucky Charms   11.50z   3.19
4                                 Quaker Oats Old Fashioned     18oz   2.82
5                                      Nabisco Oreo Cookies  14.3oz    2.99
6                                        Nabisco Chips Ahoy     13oz   2.64
7                                Doritos Nacho Cheese Chips     10oz   3.99
8                                   Cheez-it Original Baked     21oz   4.79
9                                  Swiss Miss Hot Chocolate 10 count   1.49
10                        Tazo Chai Classic Latte Black Tea   32 oz    3.49
11                                Annie's Macaroni &amp; Cheese      6oz   1.79
12                                      Rice A Roni Chicken    6.9oz   1.00
13                            Zatarain's Jambalaya Rice Mix      8oz   1.62
14                                 SPAM Original Lunch Meat     12oz   2.79
15                           Campbell's Chicken Noodle Soup  10.75oz   0.99
16                       Dinty Moore Hearty Meals Beef Stew     15oz   1.99
17                                  Hormel Chili with Beans     15oz   1.94
18                                    Dole Pineapple Chunks    20 oz   1.59
19                              Skippy Creamy Peanut Butter   16.3oz   2.59
20                            Smucker's Strawberry Preserve     18oz   2.99
21                                     Heinz Tomato Ketchup     32oz   2.99
22                 Near East Couscous Toasted Pine Nuts mix    5.6oz   2.12
23                                 Barilla Angel Hair Pasta     16oz   1.42
24       Betty Crocker Super Moist Chocolate Fudge Cake Mix  15.25oz   1.22
25                             Kraft Jet-Puffed Marshmllows     16oz   1.99
26 Dunkin' Donuts Original Blend Medium Roast Ground Coffee     12oz   7.19
27                             Dove Promises Milk Chocolate   8.87oz   3.19
28                                                 Skittles     41oz   7.99
29                         Vlasic Kosher Dill Pickle Spears     24oz   2.39
30                          Vlasic Old Fashioned Sauerkraut     32oz   1.99
   Walmart
1     2.78
3     2.98
4     2.68
5     2.98
6     1.98
7     2.50
8     4.79
9     1.28
10    2.98
11    1.72
12    1.00
13    1.54
14    2.64
15    1.58
16    1.98
17    1.88
18    1.47
19    2.58
20    2.84
21    2.88
22    1.98
23    1.38
24    1.17
25    1.96
26    6.98
27    3.50
28    6.98
29    2.18
30    1.97</code></pre>
</div>
<details><summary>Show the Code</summary><div class="sourceCode cell-code" id="cb83"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1"></a>obs_diff_price_less <span class="ot">=</span> <span class="fu">mean</span>( <span class="sc">~</span> Walmart <span class="sc">-</span> Target, <span class="at">data =</span> groceries_less)</span>
<span id="cb83-2"><a href="#cb83-2"></a>obs_diff_price_less</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>[1] -0.1558621</code></pre>
</div>
<details><summary>Show the Code</summary><div class="sourceCode cell-code" id="cb85"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1"></a>polarity_less <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="dv">1</span>, <span class="dv">15</span>), <span class="fu">rep</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">14</span>)) <span class="co"># Due to resampling this small bias makes no difference</span></span>
<span id="cb85-2"><a href="#cb85-2"></a>null_dist_price_less <span class="ot">&lt;-</span> <span class="fu">do</span>(<span class="dv">100000</span>) <span class="sc">*</span> <span class="fu">mean</span>(<span class="at">data =</span> groceries_less, </span>
<span id="cb85-3"><a href="#cb85-3"></a>                                    <span class="sc">~</span>(Walmart<span class="sc">-</span>Target) <span class="sc">*</span> <span class="fu">resample</span>(polarity_less,</span>
<span id="cb85-4"><a href="#cb85-4"></a>                                                    <span class="at">replace =</span> <span class="cn">TRUE</span>))</span>
<span id="cb85-5"><a href="#cb85-5"></a>null_dist_price_less <span class="sc">%&gt;%</span> <span class="fu">head</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>          mean
1  0.068275862
2 -0.033103448
3  0.129655172
4  0.020000000
5 -0.004827586
6 -0.046896552</code></pre>
</div>
<details><summary>Show the Code</summary><div class="sourceCode cell-code" id="cb87"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1"></a><span class="fu">gf_histogram</span>(<span class="at">data =</span> null_dist_price_less, <span class="sc">~</span>mean) <span class="sc">%&gt;%</span> </span>
<span id="cb87-2"><a href="#cb87-2"></a>  <span class="fu">gf_vline</span>(<span class="at">xintercept =</span> obs_diff_price_less, <span class="at">colour =</span> <span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<p><img src="permutation_files/figure-html/unnamed-chunk-23-1.png" style="width:50.0%;height:50.0%"></p>
</div>
<details><summary>Show the Code</summary><div class="sourceCode cell-code" id="cb88"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1"></a><span class="dv">1</span><span class="sc">-</span> <span class="fu">mean</span>(null_dist_price_less <span class="sc">&gt;=</span> obs_diff_price_less) <span class="co">#P-value</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>[1] 0.01557</code></pre>
</div>
</div>
</section><section id="case-study-7-proportions-between-categorical-variables" class="level3"><h3 class="anchored" data-anchor-id="case-study-7-proportions-between-categorical-variables">Case Study 7: Proportions between Categorical Variables</h3>
<p>Let us try a dataset with Qualitative / Categorical data. This is a General Social Survey dataset, and we have people with different levels of <code>Education</code> stating their opinion on the <code>Death Penalty</code>. We want to know if these two Categorical variables have a correlation, i.e.&nbsp;can the opinions in favour of the Death Penalty be explained by the Education level?</p>
<p>Since data is Categorical, we need to take <code>counts</code> in a table, and then implement a <code>chi-square test</code>. In the test, we will permute the <code>Education</code> variable to see if we can see how significant its <em>effect size</em> is.</p>
<div class="cell">
<details><summary>Show the Code</summary><div class="sourceCode cell-code" id="cb90"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1"></a>GSS2002 <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"../../../../../materials/data/resampling/GSS2002.csv"</span>)</span>
<span id="cb90-2"><a href="#cb90-2"></a><span class="fu">inspect</span>(GSS2002)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>
categorical variables:  
            name     class levels    n missing
1         Region character      7 2765       0
2         Gender character      2 2765       0
3           Race character      3 2765       0
4      Education character      5 2760       5
5        Marital character      5 2765       0
6       Religion character     13 2746      19
7          Happy character      3 1369    1396
8         Income character     24 1875     890
9       PolParty character      8 2729      36
10      Politics character      7 1331    1434
11     Marijuana character      2  851    1914
12  DeathPenalty character      2 1308    1457
13        OwnGun character      3  924    1841
14        GunLaw character      2  916    1849
15 SpendMilitary character      3 1324    1441
16     SpendEduc character      3 1343    1422
17      SpendEnv character      3 1322    1443
18      SpendSci character      3 1266    1499
19        Pres00 character      5 1749    1016
20      Postlife character      2 1211    1554
                                    distribution
1  North Central (24.7%) ...                    
2  Female (55.6%), Male (44.4%)                 
3  White (79.1%), Black (14.8%) ...             
4  HS (53.8%), Bachelors (16.1%) ...            
5  Married (45.9%), Never Married (25.6%) ...   
6  Protestant (53.2%), Catholic (24.5%) ...     
7  Pretty happy (57.3%) ...                     
8  40000-49999 (9.1%) ...                       
9  Ind (19.3%), Not Str Dem (18.9%) ...         
10 Moderate (39.2%), Conservative (15.8%) ...   
11 Not legal (64%), Legal (36%)                 
12 Favor (68.7%), Oppose (31.3%)                
13 No (65.5%), Yes (33.5%) ...                  
14 Favor (80.5%), Oppose (19.5%)                
15 About right (46.5%) ...                      
16 Too little (73.9%) ...                       
17 Too little (60%) ...                         
18 About right (49.7%) ...                      
19 Bush (50.6%), Gore (44.7%) ...               
20 Yes (80.5%), No (19.5%)                      

quantitative variables:  
  name   class min  Q1 median   Q3  max mean       sd    n missing
1   ID integer   1 692   1383 2074 2765 1383 798.3311 2765       0</code></pre>
</div>
</div>
<p>Note how <em>all</em> variables are Categorical !! <code>Education</code> has five <code>levels</code>:</p>
<div class="cell">
<details><summary>Show the Code</summary><div class="sourceCode cell-code" id="cb92"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1"></a>GSS2002 <span class="sc">%&gt;%</span> <span class="fu">count</span>(Education)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>  Education    n
1 Bachelors  443
2  Graduate  230
3        HS 1485
4    Jr Col  202
5   Left HS  400
6      &lt;NA&gt;    5</code></pre>
</div>
<details><summary>Show the Code</summary><div class="sourceCode cell-code" id="cb94"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1"></a>GSS2002 <span class="sc">%&gt;%</span> <span class="fu">count</span>(DeathPenalty)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>  DeathPenalty    n
1        Favor  899
2       Oppose  409
3         &lt;NA&gt; 1457</code></pre>
</div>
</div>
<p>Let us drop NA entries in Education and Death Penalty. And set up a table for the chi-square test.</p>
<div class="cell">
<details><summary>Show the Code</summary><div class="sourceCode cell-code" id="cb96"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1"></a>gss2002 <span class="ot">&lt;-</span> GSS2002 <span class="sc">%&gt;%</span> </span>
<span id="cb96-2"><a href="#cb96-2"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(Education, DeathPenalty) <span class="sc">%&gt;%</span> </span>
<span id="cb96-3"><a href="#cb96-3"></a>  tidyr<span class="sc">::</span><span class="fu">drop_na</span>(., <span class="fu">c</span>(Education, DeathPenalty))</span>
<span id="cb96-4"><a href="#cb96-4"></a><span class="fu">dim</span>(gss2002)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>[1] 1307    2</code></pre>
</div>
<details><summary>Show the Code</summary><div class="sourceCode cell-code" id="cb98"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1"></a>gss_summary <span class="ot">&lt;-</span> gss2002 <span class="sc">%&gt;%</span></span>
<span id="cb98-2"><a href="#cb98-2"></a>  <span class="fu">mutate</span>(</span>
<span id="cb98-3"><a href="#cb98-3"></a>    <span class="at">Education =</span> <span class="fu">factor</span>(</span>
<span id="cb98-4"><a href="#cb98-4"></a>      Education,</span>
<span id="cb98-5"><a href="#cb98-5"></a>      <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Bachelors"</span>, <span class="st">"Graduate"</span>, <span class="st">"Jr Col"</span>, <span class="st">"HS"</span>, <span class="st">"Left HS"</span>),</span>
<span id="cb98-6"><a href="#cb98-6"></a>      <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Bachelors"</span>, <span class="st">"Graduate"</span>, <span class="st">"Jr Col"</span>, <span class="st">"HS"</span>, <span class="st">"Left HS"</span>)</span>
<span id="cb98-7"><a href="#cb98-7"></a>    ),</span>
<span id="cb98-8"><a href="#cb98-8"></a>    <span class="at">DeathPenalty =</span> <span class="fu">as.factor</span>(DeathPenalty)</span>
<span id="cb98-9"><a href="#cb98-9"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb98-10"><a href="#cb98-10"></a>  <span class="fu">group_by</span>(Education, DeathPenalty) <span class="sc">%&gt;%</span></span>
<span id="cb98-11"><a href="#cb98-11"></a>  <span class="fu">summarise</span>(<span class="at">count =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span> <span class="co"># This is good for a chisq test</span></span>
<span id="cb98-12"><a href="#cb98-12"></a>  </span>
<span id="cb98-13"><a href="#cb98-13"></a>  <span class="co"># Add two more columns to faciltate mosaic/Marrimekko Plot</span></span>
<span id="cb98-14"><a href="#cb98-14"></a>  <span class="co"># </span></span>
<span id="cb98-15"><a href="#cb98-15"></a>  <span class="fu">mutate</span>(<span class="at">edu_count =</span> <span class="fu">sum</span>(count), </span>
<span id="cb98-16"><a href="#cb98-16"></a>         <span class="at">edu_prop =</span> count <span class="sc">/</span> <span class="fu">sum</span>(count)) <span class="sc">%&gt;%</span></span>
<span id="cb98-17"><a href="#cb98-17"></a>  <span class="fu">ungroup</span>() </span>
<span id="cb98-18"><a href="#cb98-18"></a></span>
<span id="cb98-19"><a href="#cb98-19"></a>gss_summary</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 5
   Education DeathPenalty count edu_count edu_prop
   &lt;fct&gt;     &lt;fct&gt;        &lt;int&gt;     &lt;int&gt;    &lt;dbl&gt;
 1 Bachelors Favor          135       206    0.655
 2 Bachelors Oppose          71       206    0.345
 3 Graduate  Favor           64       114    0.561
 4 Graduate  Oppose          50       114    0.439
 5 Jr Col    Favor           71        87    0.816
 6 Jr Col    Oppose          16        87    0.184
 7 HS        Favor          511       711    0.719
 8 HS        Oppose         200       711    0.281
 9 Left HS   Favor          117       189    0.619
10 Left HS   Oppose          72       189    0.381</code></pre>
</div>
<details><summary>Show the Code</summary><div class="sourceCode cell-code" id="cb100"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1"></a><span class="co"># We can plot a heatmap-like `mosaic chart` for this table, using `ggplot`:</span></span>
<span id="cb100-2"><a href="#cb100-2"></a><span class="co"># https://stackoverflow.com/questions/19233365/how-to-create-a-marimekko-mosaic-plot-in-ggplot2</span></span>
<span id="cb100-3"><a href="#cb100-3"></a></span>
<span id="cb100-4"><a href="#cb100-4"></a><span class="fu">ggplot</span>(<span class="at">data =</span> gss_summary, <span class="fu">aes</span>( <span class="at">x =</span> Education, <span class="at">y =</span> edu_prop)) <span class="sc">+</span></span>
<span id="cb100-5"><a href="#cb100-5"></a>  <span class="fu">geom_bar</span>(<span class="fu">aes</span>(<span class="at">width =</span> edu_count, <span class="at">fill =</span> DeathPenalty), <span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">position =</span> <span class="st">"fill"</span>, <span class="at">colour =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb100-6"><a href="#cb100-6"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> scales<span class="sc">::</span><span class="fu">percent</span>(edu_prop)), <span class="at">position =</span> <span class="fu">position_stack</span>(<span class="at">vjust =</span> <span class="fl">0.5</span>)) <span class="sc">+</span></span>
<span id="cb100-7"><a href="#cb100-7"></a></span>
<span id="cb100-8"><a href="#cb100-8"></a></span>
<span id="cb100-9"><a href="#cb100-9"></a><span class="co"># if labels are desired</span></span>
<span id="cb100-10"><a href="#cb100-10"></a> <span class="fu">facet_grid</span>(<span class="sc">~</span> Education, <span class="at">scales =</span> <span class="st">"free_x"</span>, <span class="at">space =</span> <span class="st">"free_x"</span>) <span class="sc">+</span> </span>
<span id="cb100-11"><a href="#cb100-11"></a>  <span class="fu">theme</span>(<span class="fu">scale_fill_brewer</span>(<span class="at">palette =</span> <span class="st">"RdYlGn"</span>)) <span class="sc">+</span> </span>
<span id="cb100-12"><a href="#cb100-12"></a>  <span class="co"># theme(panel.spacing.x = unit(0, "npc")) + # if no spacing preferred between bars</span></span>
<span id="cb100-13"><a href="#cb100-13"></a>  <span class="fu">theme_void</span>() </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<p><img src="permutation_files/figure-html/unnamed-chunk-26-1.png" style="width:50.0%;height:50.0%"></p>
</div>
</div>
<p>Let us now perform the base <code>chisq test</code>: We need a <code>table</code> and then the <code>chisq</code> test:</p>
<div class="cell">
<details><summary>Show the Code</summary><div class="sourceCode cell-code" id="cb101"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb101-1"><a href="#cb101-1"></a>gss_table <span class="ot">&lt;-</span> <span class="fu">tally</span>(DeathPenalty <span class="sc">~</span> Education, <span class="at">data =</span> gss2002)</span>
<span id="cb101-2"><a href="#cb101-2"></a>gss_table</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>            Education
DeathPenalty Bachelors Graduate  HS Jr Col Left HS
      Favor        135       64 511     71     117
      Oppose        71       50 200     16      72</code></pre>
</div>
<details><summary>Show the Code</summary><div class="sourceCode cell-code" id="cb103"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb103-1"><a href="#cb103-1"></a><span class="co"># Get the observed chi-square statistic</span></span>
<span id="cb103-2"><a href="#cb103-2"></a>observedChi2 <span class="ot">&lt;-</span> mosaic<span class="sc">::</span><span class="fu">chisq</span>(<span class="fu">tally</span>(DeathPenalty <span class="sc">~</span> Education, <span class="at">data =</span> gss2002))</span>
<span id="cb103-3"><a href="#cb103-3"></a>observedChi2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>X.squared 
 23.45093 </code></pre>
</div>
<details><summary>Show the Code</summary><div class="sourceCode cell-code" id="cb105"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb105-1"><a href="#cb105-1"></a><span class="co"># Actual chi-square test</span></span>
<span id="cb105-2"><a href="#cb105-2"></a>stats<span class="sc">::</span><span class="fu">chisq.test</span>(<span class="fu">tally</span>(DeathPenalty <span class="sc">~</span> Education, <span class="at">data =</span> gss2002))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  tally(DeathPenalty ~ Education, data = gss2002)
X-squared = 23.451, df = 4, p-value = 0.0001029</code></pre>
</div>
</div>
<p>We should now repeat the test with permutations on <code>Education</code>:</p>
<div class="cell">
<details><summary>Show the Code</summary><div class="sourceCode cell-code" id="cb107"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb107-1"><a href="#cb107-1"></a>null_chisq <span class="ot">&lt;-</span> <span class="fu">do</span>(<span class="dv">10000</span>) <span class="sc">*</span> <span class="fu">chisq.test</span>(<span class="fu">tally</span>(DeathPenalty <span class="sc">~</span> <span class="fu">shuffle</span>(Education), <span class="at">data =</span> gss2002))</span>
<span id="cb107-2"><a href="#cb107-2"></a></span>
<span id="cb107-3"><a href="#cb107-3"></a><span class="fu">head</span>(null_chisq)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>              X.squared df    p.value                     method alternative
X-squared...1  1.839772  4 0.76519840 Pearson's Chi-squared test          NA
X-squared...2  3.039865  4 0.55117646 Pearson's Chi-squared test          NA
X-squared...3  9.339388  4 0.05315416 Pearson's Chi-squared test          NA
X-squared...4  8.379180  4 0.07863525 Pearson's Chi-squared test          NA
X-squared...5  2.121217  4 0.71347559 Pearson's Chi-squared test          NA
X-squared...6  1.911131  4 0.75209991 Pearson's Chi-squared test          NA
                                                                  data .row
X-squared...1 tally(DeathPenalty ~ shuffle(Education), data = gss2002)    1
X-squared...2 tally(DeathPenalty ~ shuffle(Education), data = gss2002)    1
X-squared...3 tally(DeathPenalty ~ shuffle(Education), data = gss2002)    1
X-squared...4 tally(DeathPenalty ~ shuffle(Education), data = gss2002)    1
X-squared...5 tally(DeathPenalty ~ shuffle(Education), data = gss2002)    1
X-squared...6 tally(DeathPenalty ~ shuffle(Education), data = gss2002)    1
              .index
X-squared...1      1
X-squared...2      2
X-squared...3      3
X-squared...4      4
X-squared...5      5
X-squared...6      6</code></pre>
</div>
<details><summary>Show the Code</summary><div class="sourceCode cell-code" id="cb109"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb109-1"><a href="#cb109-1"></a><span class="fu">gf_histogram</span>( <span class="sc">~</span> X.squared, <span class="at">data =</span> null_chisq) <span class="sc">%&gt;%</span> </span>
<span id="cb109-2"><a href="#cb109-2"></a>  <span class="fu">gf_vline</span>(<span class="at">xintercept =</span> observedChi2, <span class="at">color =</span> <span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<p><img src="permutation_files/figure-html/unnamed-chunk-28-1.png" style="width:50.0%;height:50.0%"></p>
</div>
<details><summary>Show the Code</summary><div class="sourceCode cell-code" id="cb110"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb110-1"><a href="#cb110-1"></a><span class="fu">gf_histogram</span>( <span class="sc">~</span> p.value, <span class="at">data =</span> null_chisq, <span class="at">binwidth =</span> <span class="fl">0.1</span>, <span class="at">center =</span> <span class="fl">0.05</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<p><img src="permutation_files/figure-html/unnamed-chunk-28-2.png" style="width:50.0%;height:50.0%"></p>
</div>
</div>
<p>So we would conclude that <code>Education</code> has a significant effect on <code>DeathPenalty</code> opinion!</p>


<!-- -->

</section></section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var filterRegex = new RegExp(/https:\/\/av-quarto\.netlify\.app/);
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
    var links = window.document.querySelectorAll('a:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
          // target, if specified
          link.setAttribute("target", "_blank");
      }
    }
});
</script><script src="https://utteranc.es/client.js" repo="arvindvenkatadri/my-quarto-website" issue-term="pathname" theme="github-light" crossorigin="anonymous" async="">
</script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb111" data-shortcodes="false"><pre class="sourceCode numberSource markdown number-lines code-with-copy"><code class="sourceCode markdown"><span id="cb111-1"><a href="#cb111-1"></a><span class="co">---</span></span>
<span id="cb111-2"><a href="#cb111-2"></a><span class="an">title:</span><span class="co"> "Permutation Tests"</span></span>
<span id="cb111-3"><a href="#cb111-3"></a><span class="an">author:</span><span class="co"> "Arvind Venkatadri"</span></span>
<span id="cb111-4"><a href="#cb111-4"></a><span class="an">date:</span><span class="co"> "`r Sys.Date()`"</span></span>
<span id="cb111-5"><a href="#cb111-5"></a><span class="an">code-fold:</span><span class="co"> true</span></span>
<span id="cb111-6"><a href="#cb111-6"></a><span class="an">code-tools:</span><span class="co"> true</span></span>
<span id="cb111-7"><a href="#cb111-7"></a><span class="an">code-line-numbers:</span><span class="co"> true</span></span>
<span id="cb111-8"><a href="#cb111-8"></a><span class="an">code-copy:</span><span class="co"> true</span></span>
<span id="cb111-9"><a href="#cb111-9"></a><span class="an">code-summary:</span><span class="co"> "Show the Code"</span></span>
<span id="cb111-10"><a href="#cb111-10"></a><span class="an">execute:</span><span class="co"> </span></span>
<span id="cb111-11"><a href="#cb111-11"></a><span class="co">  freeze: auto</span></span>
<span id="cb111-12"><a href="#cb111-12"></a><span class="co">---</span></span>
<span id="cb111-13"><a href="#cb111-13"></a></span>
<span id="cb111-14"><a href="#cb111-14"></a><span class="in">```{r setup, include=FALSE}</span></span>
<span id="cb111-15"><a href="#cb111-15"></a></span>
<span id="cb111-16"><a href="#cb111-16"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">echo =</span> <span class="cn">TRUE</span>, <span class="at">out.width=</span><span class="st">"50%"</span>, <span class="at">out.height =</span> <span class="st">"50%"</span>)</span>
<span id="cb111-17"><a href="#cb111-17"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb111-18"><a href="#cb111-18"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb111-19"><a href="#cb111-19"></a><span class="fu">library</span>(mosaic)</span>
<span id="cb111-20"><a href="#cb111-20"></a></span>
<span id="cb111-21"><a href="#cb111-21"></a><span class="in">```</span></span>
<span id="cb111-22"><a href="#cb111-22"></a></span>
<span id="cb111-23"><a href="#cb111-23"></a><span class="fu">## Permutation Tests</span></span>
<span id="cb111-24"><a href="#cb111-24"></a></span>
<span id="cb111-25"><a href="#cb111-25"></a><span class="fu">### Case Study-1: Hot Wings Orders vs Gender</span></span>
<span id="cb111-26"><a href="#cb111-26"></a></span>
<span id="cb111-27"><a href="#cb111-27"></a>A student conducted a study of hot wings and beer consumption at a Bar.</span>
<span id="cb111-28"><a href="#cb111-28"></a>She asked patrons at the bar to record their consumption of hot wings</span>
<span id="cb111-29"><a href="#cb111-29"></a>and beer over the course of several hours. She wanted to know if people</span>
<span id="cb111-30"><a href="#cb111-30"></a>who ate more hot wings would then drink more beer. In addition, she</span>
<span id="cb111-31"><a href="#cb111-31"></a>investigated whether or not gender had an impact on hot wings or beer</span>
<span id="cb111-32"><a href="#cb111-32"></a>consumption.</span>
<span id="cb111-33"><a href="#cb111-33"></a></span>
<span id="cb111-36"><a href="#cb111-36"></a><span class="in">```{r}</span></span>
<span id="cb111-37"><a href="#cb111-37"></a>Beerwings <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"../../../../../materials/data/resampling/Beerwings.csv"</span>)</span>
<span id="cb111-38"><a href="#cb111-38"></a><span class="fu">inspect</span>(Beerwings)</span>
<span id="cb111-39"><a href="#cb111-39"></a></span>
<span id="cb111-40"><a href="#cb111-40"></a><span class="in">```</span></span>
<span id="cb111-41"><a href="#cb111-41"></a></span>
<span id="cb111-42"><a href="#cb111-42"></a>Let us calculate the observed difference in <span class="in">`Hotwings`</span> consumption</span>
<span id="cb111-43"><a href="#cb111-43"></a>between Males and Females ( <span class="in">`Gender`</span>)</span>
<span id="cb111-44"><a href="#cb111-44"></a></span>
<span id="cb111-47"><a href="#cb111-47"></a><span class="in">```{r}</span></span>
<span id="cb111-48"><a href="#cb111-48"></a><span class="fu">mean</span>(Hotwings <span class="sc">~</span> Gender, <span class="at">data =</span> Beerwings)</span>
<span id="cb111-49"><a href="#cb111-49"></a>obs_diff_wings <span class="ot">&lt;-</span> mosaic<span class="sc">::</span><span class="fu">diffmean</span>(<span class="at">data =</span> Beerwings, Hotwings <span class="sc">~</span> Gender)</span>
<span id="cb111-50"><a href="#cb111-50"></a>obs_diff_wings </span>
<span id="cb111-51"><a href="#cb111-51"></a></span>
<span id="cb111-52"><a href="#cb111-52"></a><span class="in">```</span></span>
<span id="cb111-53"><a href="#cb111-53"></a></span>
<span id="cb111-56"><a href="#cb111-56"></a><span class="in">```{r}</span></span>
<span id="cb111-57"><a href="#cb111-57"></a><span class="fu">gf_boxplot</span>(<span class="at">data =</span> Beerwings, Hotwings <span class="sc">~</span> Gender, <span class="at">title =</span> <span class="st">"Hotwings Consumption by Gender"</span>)</span>
<span id="cb111-58"><a href="#cb111-58"></a></span>
<span id="cb111-59"><a href="#cb111-59"></a><span class="in">```</span></span>
<span id="cb111-60"><a href="#cb111-60"></a></span>
<span id="cb111-61"><a href="#cb111-61"></a>The observed difference in mean consumption of Hotwings between Males</span>
<span id="cb111-62"><a href="#cb111-62"></a>and Females is 5.2. Could this have occurred by chance? Here is our</span>
<span id="cb111-63"><a href="#cb111-63"></a>formulation of the Hypotheses:</span>
<span id="cb111-64"><a href="#cb111-64"></a></span>
<span id="cb111-65"><a href="#cb111-65"></a>$$</span>
<span id="cb111-66"><a href="#cb111-66"></a>NULL\ Hypothesis\ H_0 =&gt; No\&nbsp;difference\ between\ means\ across\ groups<span class="sc">\\</span></span>
<span id="cb111-67"><a href="#cb111-67"></a>Alternative\ Hypothesis\</span>
<span id="cb111-68"><a href="#cb111-68"></a>H_a =&gt;Significant\ difference\ between\ the\ means\</span>
<span id="cb111-69"><a href="#cb111-69"></a>$$</span>
<span id="cb111-70"><a href="#cb111-70"></a></span>
<span id="cb111-71"><a href="#cb111-71"></a>So we perform a Permutation Test to check:</span>
<span id="cb111-72"><a href="#cb111-72"></a></span>
<span id="cb111-75"><a href="#cb111-75"></a><span class="in">```{r}</span></span>
<span id="cb111-76"><a href="#cb111-76"></a>null_dist_wings <span class="ot">&lt;-</span> <span class="fu">do</span>(<span class="dv">1000</span>) <span class="sc">*</span> <span class="fu">diffmean</span>(Hotwings <span class="sc">~</span> <span class="fu">shuffle</span>(Gender), <span class="at">data =</span> Beerwings)</span>
<span id="cb111-77"><a href="#cb111-77"></a>null_dist_wings <span class="sc">%&gt;%</span> <span class="fu">head</span>()</span>
<span id="cb111-78"><a href="#cb111-78"></a></span>
<span id="cb111-79"><a href="#cb111-79"></a><span class="fu">gf_histogram</span>(<span class="at">data =</span> null_dist_wings, <span class="sc">~</span> diffmean) <span class="sc">%&gt;%</span> </span>
<span id="cb111-80"><a href="#cb111-80"></a>  <span class="fu">gf_vline</span>(<span class="at">xintercept =</span> obs_diff_wings, <span class="at">colour =</span> <span class="st">"red"</span>)</span>
<span id="cb111-81"><a href="#cb111-81"></a></span>
<span id="cb111-82"><a href="#cb111-82"></a><span class="fu">prop1</span>(<span class="sc">~</span> diffmean <span class="sc">&gt;=</span> obs_diff_wings, <span class="at">data =</span> null_dist_wings)</span>
<span id="cb111-83"><a href="#cb111-83"></a></span>
<span id="cb111-84"><a href="#cb111-84"></a><span class="in">```</span></span>
<span id="cb111-85"><a href="#cb111-85"></a></span>
<span id="cb111-86"><a href="#cb111-86"></a>The $\color{red}{red\ line}$ shows the actual measured mean difference</span>
<span id="cb111-87"><a href="#cb111-87"></a>in Hot Wings consumption. The probability that our Permutation</span>
<span id="cb111-88"><a href="#cb111-88"></a>distribution is able to equal or exceed that number is $0.001998002$ and</span>
<span id="cb111-89"><a href="#cb111-89"></a>we have to reject the Null Hypothesis that the means are identical.</span>
<span id="cb111-90"><a href="#cb111-90"></a></span>
<span id="cb111-91"><a href="#cb111-91"></a><span class="fu">### Case Study-2: Verizon</span></span>
<span id="cb111-92"><a href="#cb111-92"></a></span>
<span id="cb111-95"><a href="#cb111-95"></a><span class="in">```{r}</span></span>
<span id="cb111-96"><a href="#cb111-96"></a>verizon <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"../../../../../materials/data/resampling/Verizon.csv"</span>)</span>
<span id="cb111-97"><a href="#cb111-97"></a><span class="fu">inspect</span>(verizon)</span>
<span id="cb111-98"><a href="#cb111-98"></a></span>
<span id="cb111-99"><a href="#cb111-99"></a><span class="in">```</span></span>
<span id="cb111-100"><a href="#cb111-100"></a></span>
<span id="cb111-103"><a href="#cb111-103"></a><span class="in">```{r}</span></span>
<span id="cb111-104"><a href="#cb111-104"></a><span class="fu">mean</span>(Time <span class="sc">~</span> Group, <span class="at">data =</span> verizon)</span>
<span id="cb111-105"><a href="#cb111-105"></a>obs_diff_verizon <span class="ot">&lt;-</span> <span class="fu">diffmean</span>(Time <span class="sc">~</span> Group, <span class="at">data =</span> verizon)</span>
<span id="cb111-106"><a href="#cb111-106"></a>obs_diff_verizon</span>
<span id="cb111-107"><a href="#cb111-107"></a></span>
<span id="cb111-108"><a href="#cb111-108"></a><span class="in">```</span></span>
<span id="cb111-109"><a href="#cb111-109"></a></span>
<span id="cb111-112"><a href="#cb111-112"></a><span class="in">```{r}</span></span>
<span id="cb111-113"><a href="#cb111-113"></a>null_dist_verizon <span class="ot">&lt;-</span> <span class="fu">do</span>(<span class="dv">1000</span>) <span class="sc">*</span> <span class="fu">diffmean</span>(Time <span class="sc">~</span> <span class="fu">shuffle</span>(Group), <span class="at">data =</span> verizon)</span>
<span id="cb111-114"><a href="#cb111-114"></a><span class="fu">gf_histogram</span>(<span class="at">data =</span> null_dist_verizon, <span class="sc">~</span> diffmean) <span class="sc">%&gt;%</span> </span>
<span id="cb111-115"><a href="#cb111-115"></a>  <span class="fu">gf_vline</span>(<span class="at">xintercept =</span> obs_diff_wings, <span class="at">colour =</span> <span class="st">"red"</span>)</span>
<span id="cb111-116"><a href="#cb111-116"></a></span>
<span id="cb111-117"><a href="#cb111-117"></a><span class="fu">prop1</span>(<span class="sc">~</span> diffmean <span class="sc">&gt;=</span> obs_diff_wings, <span class="at">data =</span> null_dist_verizon)</span>
<span id="cb111-118"><a href="#cb111-118"></a></span>
<span id="cb111-119"><a href="#cb111-119"></a><span class="in">```</span></span>
<span id="cb111-120"><a href="#cb111-120"></a></span>
<span id="cb111-121"><a href="#cb111-121"></a><span class="fu">### Case Story-3: Recidivism</span></span>
<span id="cb111-122"><a href="#cb111-122"></a></span>
<span id="cb111-123"><a href="#cb111-123"></a>Do criminals released after a jail term commit crimes again?</span>
<span id="cb111-124"><a href="#cb111-124"></a></span>
<span id="cb111-127"><a href="#cb111-127"></a><span class="in">```{r}</span></span>
<span id="cb111-128"><a href="#cb111-128"></a>recidivism <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"../../../../../materials/data/resampling/Recidivism.csv"</span>)</span>
<span id="cb111-129"><a href="#cb111-129"></a><span class="fu">inspect</span>(recidivism)</span>
<span id="cb111-130"><a href="#cb111-130"></a></span>
<span id="cb111-131"><a href="#cb111-131"></a><span class="in">```</span></span>
<span id="cb111-132"><a href="#cb111-132"></a></span>
<span id="cb111-133"><a href="#cb111-133"></a>There are some missing values in the variable <span class="kw">&lt;tt&gt;</span> <span class="in">`Age25`</span><span class="kw">&lt;/tt&gt;</span>. The</span>
<span id="cb111-134"><a href="#cb111-134"></a><span class="kw">&lt;tt&gt;</span> <span class="in">`complete.cases`</span><span class="kw">&lt;/tt&gt;</span> command gives the row numbers where values</span>
<span id="cb111-135"><a href="#cb111-135"></a>are not missing. We create a new data frame omitting the rows where</span>
<span id="cb111-136"><a href="#cb111-136"></a>there is a missing value in the <span class="kw">&lt;tt&gt;</span> 'Age25' <span class="kw">&lt;/tt&gt;</span> variable.</span>
<span id="cb111-137"><a href="#cb111-137"></a></span>
<span id="cb111-140"><a href="#cb111-140"></a><span class="in">```{r}</span></span>
<span id="cb111-141"><a href="#cb111-141"></a>recidivism_na <span class="ot">&lt;-</span> recidivism <span class="sc">%&gt;%</span> tidyr<span class="sc">::</span><span class="fu">drop_na</span>(Age25)</span>
<span id="cb111-142"><a href="#cb111-142"></a></span>
<span id="cb111-143"><a href="#cb111-143"></a><span class="in">```</span></span>
<span id="cb111-144"><a href="#cb111-144"></a></span>
<span id="cb111-145"><a href="#cb111-145"></a>Also, the variable <span class="kw">&lt;tt&gt;</span><span class="in">`Recid`</span><span class="kw">&lt;/tt&gt;</span> is a factor variable coded "Yes" or</span>
<span id="cb111-146"><a href="#cb111-146"></a>"No". We convert it to a numeric variable of 1's and 0's.</span>
<span id="cb111-147"><a href="#cb111-147"></a></span>
<span id="cb111-150"><a href="#cb111-150"></a><span class="in">```{r}</span></span>
<span id="cb111-151"><a href="#cb111-151"></a>recidivism_na <span class="ot">&lt;-</span> recidivism_na <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">Recid2 =</span> <span class="fu">ifelse</span>(Recid<span class="sc">==</span><span class="st">"Yes"</span>, <span class="dv">1</span>, <span class="dv">0</span>))</span>
<span id="cb111-152"><a href="#cb111-152"></a></span>
<span id="cb111-153"><a href="#cb111-153"></a>obs_diff_recid <span class="ot">&lt;-</span> <span class="fu">diffmean</span>( Recid2 <span class="sc">~</span> Age25, <span class="at">data =</span> recidivism_na)</span>
<span id="cb111-154"><a href="#cb111-154"></a>obs_diff_recid</span>
<span id="cb111-155"><a href="#cb111-155"></a></span>
<span id="cb111-156"><a href="#cb111-156"></a>null_dist_recid <span class="ot">&lt;-</span> <span class="fu">do</span>(<span class="dv">1000</span>) <span class="sc">*</span> <span class="fu">diffmean</span>( Recid2 <span class="sc">~</span> <span class="fu">shuffle</span>(Age25), <span class="at">data =</span> recidivism_na)</span>
<span id="cb111-157"><a href="#cb111-157"></a></span>
<span id="cb111-158"><a href="#cb111-158"></a><span class="fu">gf_histogram</span>( <span class="sc">~</span> diffmean, <span class="at">data =</span> null_dist_recid) <span class="sc">%&gt;%</span> </span>
<span id="cb111-159"><a href="#cb111-159"></a>  <span class="fu">gf_vline</span>(<span class="at">xintercept =</span> obs_diff_recid, <span class="at">colour =</span> <span class="st">"red"</span>)</span>
<span id="cb111-160"><a href="#cb111-160"></a></span>
<span id="cb111-161"><a href="#cb111-161"></a><span class="in">```</span></span>
<span id="cb111-162"><a href="#cb111-162"></a></span>
<span id="cb111-163"><a href="#cb111-163"></a><span class="fu">### Case Study-4: Matched Pairs: Results from a diving championship.</span></span>
<span id="cb111-164"><a href="#cb111-164"></a></span>
<span id="cb111-167"><a href="#cb111-167"></a><span class="in">```{r}</span></span>
<span id="cb111-168"><a href="#cb111-168"></a>Diving2017 <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"../../../../../materials/data/resampling/Diving2017.csv"</span>)</span>
<span id="cb111-169"><a href="#cb111-169"></a><span class="fu">head</span>(Diving2017)</span>
<span id="cb111-170"><a href="#cb111-170"></a><span class="fu">inspect</span>(Diving2017)</span>
<span id="cb111-171"><a href="#cb111-171"></a></span>
<span id="cb111-172"><a href="#cb111-172"></a><span class="in">```</span></span>
<span id="cb111-173"><a href="#cb111-173"></a></span>
<span id="cb111-174"><a href="#cb111-174"></a>The data is made up of **paired** observations per swimmer. So we need</span>
<span id="cb111-175"><a href="#cb111-175"></a>to take the difference between the two swim records for *each* swimmer</span>
<span id="cb111-176"><a href="#cb111-176"></a>and then shuffle the differences to either polarity. Another way to look</span>
<span id="cb111-177"><a href="#cb111-177"></a>at this is to shuffle the records between <span class="in">`Semifinal`</span> and <span class="in">`Final`</span> on a</span>
<span id="cb111-178"><a href="#cb111-178"></a>per Swimmer basis.</span>
<span id="cb111-179"><a href="#cb111-179"></a></span>
<span id="cb111-182"><a href="#cb111-182"></a><span class="in">```{r}</span></span>
<span id="cb111-183"><a href="#cb111-183"></a>Diving2017</span>
<span id="cb111-184"><a href="#cb111-184"></a>Diving2017 <span class="sc">%&gt;%</span> <span class="fu">diffmean</span>(<span class="at">data =</span> ., Final <span class="sc">~</span> Semifinal, <span class="at">only.2 =</span> <span class="cn">FALSE</span>)</span>
<span id="cb111-185"><a href="#cb111-185"></a></span>
<span id="cb111-186"><a href="#cb111-186"></a>obs_diff_swim <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="sc">~</span> Final <span class="sc">-</span> Semifinal, <span class="at">data =</span> Diving2017)</span>
<span id="cb111-187"><a href="#cb111-187"></a>obs_diff_swim</span>
<span id="cb111-188"><a href="#cb111-188"></a></span>
<span id="cb111-189"><a href="#cb111-189"></a><span class="in">```</span></span>
<span id="cb111-190"><a href="#cb111-190"></a></span>
<span id="cb111-193"><a href="#cb111-193"></a><span class="in">```{r}</span></span>
<span id="cb111-194"><a href="#cb111-194"></a>polarity <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="dv">1</span>, <span class="dv">6</span>), <span class="fu">rep</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">6</span>))</span>
<span id="cb111-195"><a href="#cb111-195"></a>polarity</span>
<span id="cb111-196"><a href="#cb111-196"></a>null_dist_swim <span class="ot">&lt;-</span> <span class="fu">do</span>(<span class="dv">100000</span>) <span class="sc">*</span> <span class="fu">mean</span>(<span class="at">data =</span> Diving2017, </span>
<span id="cb111-197"><a href="#cb111-197"></a>                                    <span class="sc">~</span>(Final <span class="sc">-</span> Semifinal) <span class="sc">*</span> <span class="fu">resample</span>(polarity,</span>
<span id="cb111-198"><a href="#cb111-198"></a>                                                    <span class="at">replace =</span> <span class="cn">TRUE</span>))</span>
<span id="cb111-199"><a href="#cb111-199"></a>null_dist_swim <span class="sc">%&gt;%</span> <span class="fu">head</span>()</span>
<span id="cb111-200"><a href="#cb111-200"></a><span class="fu">gf_histogram</span>(<span class="at">data =</span> null_dist_swim, <span class="sc">~</span>mean) <span class="sc">%&gt;%</span> </span>
<span id="cb111-201"><a href="#cb111-201"></a>  <span class="fu">gf_vline</span>(<span class="at">xintercept =</span> obs_diff_swim, <span class="at">colour =</span> <span class="st">"red"</span>)</span>
<span id="cb111-202"><a href="#cb111-202"></a></span>
<span id="cb111-203"><a href="#cb111-203"></a><span class="in">```</span></span>
<span id="cb111-204"><a href="#cb111-204"></a></span>
<span id="cb111-205"><a href="#cb111-205"></a><span class="fu">### Case Study #5: Flight Delays</span></span>
<span id="cb111-206"><a href="#cb111-206"></a></span>
<span id="cb111-207"><a href="#cb111-207"></a>LaGuardia Airport (LGA) is one of three major airports that serves the</span>
<span id="cb111-208"><a href="#cb111-208"></a>New York City metropolitan area. In 2008, over 23 million passengers and</span>
<span id="cb111-209"><a href="#cb111-209"></a>over 375 000 planes flew in or out of LGA. United Airlines and America</span>
<span id="cb111-210"><a href="#cb111-210"></a>Airlines are two major airlines that schedule services at LGA. The data</span>
<span id="cb111-211"><a href="#cb111-211"></a>set <span class="in">`FlightDelays`</span> contains information on all 4029 departures of these</span>
<span id="cb111-212"><a href="#cb111-212"></a>two airlines from LGA during May and June 2009.</span>
<span id="cb111-213"><a href="#cb111-213"></a></span>
<span id="cb111-216"><a href="#cb111-216"></a><span class="in">```{r}</span></span>
<span id="cb111-217"><a href="#cb111-217"></a>flightDelays <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"../../../../../materials/data/resampling/FlightDelays.csv"</span>)</span>
<span id="cb111-218"><a href="#cb111-218"></a></span>
<span id="cb111-219"><a href="#cb111-219"></a><span class="fu">inspect</span>(flightDelays)</span>
<span id="cb111-220"><a href="#cb111-220"></a></span>
<span id="cb111-221"><a href="#cb111-221"></a><span class="in">```</span></span>
<span id="cb111-222"><a href="#cb111-222"></a></span>
<span id="cb111-223"><a href="#cb111-223"></a>The variables in the <span class="in">`flightDelays`</span> dataset are:</span>
<span id="cb111-224"><a href="#cb111-224"></a></span>
<span id="cb111-225"><a href="#cb111-225"></a>| Variable     | Description                                                 |</span>
<span id="cb111-226"><a href="#cb111-226"></a>|------------------|------------------------------------------------------|</span>
<span id="cb111-227"><a href="#cb111-227"></a>| Carrier      | UA=United Airlines, AA=American Airlines                    |</span>
<span id="cb111-228"><a href="#cb111-228"></a>| FlightNo     | Flight number                                               |</span>
<span id="cb111-229"><a href="#cb111-229"></a>| Destination  | Airport code                                                |</span>
<span id="cb111-230"><a href="#cb111-230"></a>| DepartTime   | Scheduled departure time in 4 h intervals                   |</span>
<span id="cb111-231"><a href="#cb111-231"></a>| Day          | Day of the Week                                             |</span>
<span id="cb111-232"><a href="#cb111-232"></a>| Month        | May or June                                                 |</span>
<span id="cb111-233"><a href="#cb111-233"></a>| Delay        | Minutes flight delayed (negative indicates early departure) |</span>
<span id="cb111-234"><a href="#cb111-234"></a>| Delayed30    | Departure delayed more than 30 min? Yes or No               |</span>
<span id="cb111-235"><a href="#cb111-235"></a>| FlightLength | Length of time of flight (minutes)                          |</span>
<span id="cb111-236"><a href="#cb111-236"></a></span>
<span id="cb111-237"><a href="#cb111-237"></a>: flightDelay dataset variables</span>
<span id="cb111-238"><a href="#cb111-238"></a></span>
<span id="cb111-239"><a href="#cb111-239"></a>a)  Let us compute the proportion of times that each carrier's flights</span>
<span id="cb111-240"><a href="#cb111-240"></a>    was delayed more than 20 min. We will conduct a two-sided test to</span>
<span id="cb111-241"><a href="#cb111-241"></a>    see if the difference in these proportions is statistically</span>
<span id="cb111-242"><a href="#cb111-242"></a>    significant.</span>
<span id="cb111-243"><a href="#cb111-243"></a></span>
<span id="cb111-244"><a href="#cb111-244"></a><span class="in">```{r flightDelays-a}</span></span>
<span id="cb111-245"><a href="#cb111-245"></a></span>
<span id="cb111-246"><a href="#cb111-246"></a><span class="fu">prop</span>(<span class="at">data =</span> flightDelays, Delay <span class="sc">&gt;=</span> <span class="dv">20</span> <span class="sc">~</span> Carrier)</span>
<span id="cb111-247"><a href="#cb111-247"></a>obs_diff_delay <span class="ot">&lt;-</span> <span class="fu">diffprop</span>(<span class="at">data =</span> flightDelays, Delay <span class="sc">&gt;=</span> <span class="dv">20</span> <span class="sc">~</span> Carrier)</span>
<span id="cb111-248"><a href="#cb111-248"></a>obs_diff_delay</span>
<span id="cb111-249"><a href="#cb111-249"></a></span>
<span id="cb111-250"><a href="#cb111-250"></a><span class="in">```</span></span>
<span id="cb111-251"><a href="#cb111-251"></a></span>
<span id="cb111-252"><a href="#cb111-252"></a>We see carrier AA has a 17.13% chance of delays<span class="sc">\&gt;</span>= 20, while UA has</span>
<span id="cb111-253"><a href="#cb111-253"></a>22.26% chance. The difference is 5.12%. Is this statistically</span>
<span id="cb111-254"><a href="#cb111-254"></a>significant? We take the Delays for both Carriers and perform a</span>
<span id="cb111-255"><a href="#cb111-255"></a>permutation test by <span class="in">`shuffle`</span> on the <span class="in">`carrier`</span> variable:</span>
<span id="cb111-256"><a href="#cb111-256"></a></span>
<span id="cb111-259"><a href="#cb111-259"></a><span class="in">```{r}</span></span>
<span id="cb111-260"><a href="#cb111-260"></a>null_dist_delay <span class="ot">&lt;-</span> <span class="fu">do</span>(<span class="dv">10000</span>) <span class="sc">*</span> <span class="fu">diffprop</span>(<span class="at">data =</span> flightDelays, Delay <span class="sc">&gt;=</span> <span class="dv">20</span> <span class="sc">~</span> <span class="fu">shuffle</span>(Carrier))</span>
<span id="cb111-261"><a href="#cb111-261"></a>null_dist_delay <span class="sc">%&gt;%</span> <span class="fu">head</span>()</span>
<span id="cb111-262"><a href="#cb111-262"></a><span class="fu">gf_histogram</span>(<span class="at">data =</span> null_dist_delay, <span class="sc">~</span> diffprop) <span class="sc">%&gt;%</span> <span class="fu">gf_vline</span>(<span class="at">xintercept =</span> obs_diff_delay, <span class="at">color =</span> <span class="st">"red"</span>)</span>
<span id="cb111-263"><a href="#cb111-263"></a></span>
<span id="cb111-264"><a href="#cb111-264"></a><span class="in">```</span></span>
<span id="cb111-265"><a href="#cb111-265"></a></span>
<span id="cb111-266"><a href="#cb111-266"></a>It appears that the difference indelay times is significant. We can</span>
<span id="cb111-267"><a href="#cb111-267"></a>compute the <span class="in">`p-value`</span> based on this test:</span>
<span id="cb111-268"><a href="#cb111-268"></a></span>
<span id="cb111-271"><a href="#cb111-271"></a><span class="in">```{r}</span></span>
<span id="cb111-272"><a href="#cb111-272"></a><span class="dv">2</span><span class="sc">*</span> <span class="fu">mean</span>(null_dist_delay <span class="sc">&gt;=</span> obs_diff_delay)</span>
<span id="cb111-273"><a href="#cb111-273"></a></span>
<span id="cb111-274"><a href="#cb111-274"></a><span class="in">```</span></span>
<span id="cb111-275"><a href="#cb111-275"></a></span>
<span id="cb111-276"><a href="#cb111-276"></a>which is very small. Hence we reject the null Hypothesis that there is</span>
<span id="cb111-277"><a href="#cb111-277"></a>no difference between <span class="in">`carrier`</span>s on <span class="in">`delay times`</span>.</span>
<span id="cb111-278"><a href="#cb111-278"></a></span>
<span id="cb111-279"><a href="#cb111-279"></a>b)  Compute the variance in the flight delay lengths for each carrier.</span>
<span id="cb111-280"><a href="#cb111-280"></a>    Conduct a test to see if the variance for United Airlines differs</span>
<span id="cb111-281"><a href="#cb111-281"></a>    from that of American Airlines.</span>
<span id="cb111-282"><a href="#cb111-282"></a></span>
<span id="cb111-285"><a href="#cb111-285"></a><span class="in">```{r}</span></span>
<span id="cb111-286"><a href="#cb111-286"></a><span class="fu">var</span>(<span class="at">data =</span> flightDelays, Delay <span class="sc">~</span> Carrier)</span>
<span id="cb111-287"><a href="#cb111-287"></a></span>
<span id="cb111-288"><a href="#cb111-288"></a><span class="co"># There is no readymade function in mosaic called `diffvar`...so...we construct one</span></span>
<span id="cb111-289"><a href="#cb111-289"></a>obs_diff_var <span class="ot">&lt;-</span> <span class="fu">diff</span>(<span class="fu">var</span>(<span class="at">data =</span> flightDelays, Delay <span class="sc">~</span> Carrier))</span>
<span id="cb111-290"><a href="#cb111-290"></a>obs_diff_var</span>
<span id="cb111-291"><a href="#cb111-291"></a></span>
<span id="cb111-292"><a href="#cb111-292"></a><span class="in">```</span></span>
<span id="cb111-293"><a href="#cb111-293"></a></span>
<span id="cb111-294"><a href="#cb111-294"></a>The difference in variances in <span class="in">`Delay`</span> between the two <span class="in">`carrier`</span>s is</span>
<span id="cb111-295"><a href="#cb111-295"></a>$-431.0677$. In our Permutation Test, we <span class="in">`shuffle`</span> the <span class="in">`Carrier`</span></span>
<span id="cb111-296"><a href="#cb111-296"></a>variable:</span>
<span id="cb111-297"><a href="#cb111-297"></a></span>
<span id="cb111-300"><a href="#cb111-300"></a><span class="in">```{r}</span></span>
<span id="cb111-301"><a href="#cb111-301"></a>obs_diff_var <span class="ot">&lt;-</span> <span class="fu">diff</span>(<span class="fu">var</span>(<span class="at">data =</span> flightDelays, Delay <span class="sc">~</span> Carrier))</span>
<span id="cb111-302"><a href="#cb111-302"></a>null_dist_var <span class="ot">&lt;-</span></span>
<span id="cb111-303"><a href="#cb111-303"></a>  <span class="fu">do</span>(<span class="dv">10000</span>) <span class="sc">*</span> <span class="fu">diff</span>(<span class="fu">var</span>(<span class="at">data =</span> flightDelays, Delay <span class="sc">~</span> <span class="fu">shuffle</span>(Carrier)))</span>
<span id="cb111-304"><a href="#cb111-304"></a>null_dist_var <span class="sc">%&gt;%</span> <span class="fu">head</span>()</span>
<span id="cb111-305"><a href="#cb111-305"></a></span>
<span id="cb111-306"><a href="#cb111-306"></a><span class="co"># The null distribution variable is called `UA`</span></span>
<span id="cb111-307"><a href="#cb111-307"></a><span class="fu">gf_histogram</span>(<span class="at">data =</span> null_dist_var, <span class="sc">~</span> UA) <span class="sc">%&gt;%</span> <span class="fu">gf_vline</span>(<span class="at">xintercept =</span> obs_diff_delay, <span class="at">color =</span> <span class="st">"red"</span>)</span>
<span id="cb111-308"><a href="#cb111-308"></a><span class="dv">2</span> <span class="sc">*</span> <span class="fu">mean</span>(null_dist_var <span class="sc">&gt;=</span> obs_diff_var)</span>
<span id="cb111-309"><a href="#cb111-309"></a></span>
<span id="cb111-310"><a href="#cb111-310"></a><span class="in">```</span></span>
<span id="cb111-311"><a href="#cb111-311"></a></span>
<span id="cb111-312"><a href="#cb111-312"></a>Clearly there is no case for a significant difference in variances!</span>
<span id="cb111-313"><a href="#cb111-313"></a></span>
<span id="cb111-314"><a href="#cb111-314"></a><span class="fu">### Case Study #6: Walmart vs Target</span></span>
<span id="cb111-315"><a href="#cb111-315"></a></span>
<span id="cb111-316"><a href="#cb111-316"></a>Is there a difference in the price of groceries sold by the two</span>
<span id="cb111-317"><a href="#cb111-317"></a>retailers Target and Walmart? The data set <span class="in">`Groceries`</span> contains a sample</span>
<span id="cb111-318"><a href="#cb111-318"></a>of grocery items and their prices advertised on their respective web</span>
<span id="cb111-319"><a href="#cb111-319"></a>sites on one specific day.</span>
<span id="cb111-320"><a href="#cb111-320"></a></span>
<span id="cb111-321"><a href="#cb111-321"></a>a)  Inspect the data set, then explain why this is an example of matched</span>
<span id="cb111-322"><a href="#cb111-322"></a>    pairs data.</span>
<span id="cb111-323"><a href="#cb111-323"></a>b)  Compute summary statistics of the prices for each store.</span>
<span id="cb111-324"><a href="#cb111-324"></a>c)  Conduct a permutation test to determine whether or not there is a</span>
<span id="cb111-325"><a href="#cb111-325"></a>    difference in the mean prices.</span>
<span id="cb111-326"><a href="#cb111-326"></a>d)  Create a ~~histogram~~ bar-chart of the difference in prices. What</span>
<span id="cb111-327"><a href="#cb111-327"></a>    is unusual about Quaker Oats Life cereal?</span>
<span id="cb111-328"><a href="#cb111-328"></a>e)  Redo the hypothesis test without this observation. Do you reach the</span>
<span id="cb111-329"><a href="#cb111-329"></a>    same conclusion?</span>
<span id="cb111-330"><a href="#cb111-330"></a></span>
<span id="cb111-333"><a href="#cb111-333"></a><span class="in">```{r}</span></span>
<span id="cb111-334"><a href="#cb111-334"></a>groceries <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"../../../../../materials/data/resampling/Groceries.csv"</span>) <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">Product =</span> stringr<span class="sc">::</span><span class="fu">str_squish</span>(Product))</span>
<span id="cb111-335"><a href="#cb111-335"></a><span class="fu">head</span>(groceries)</span>
<span id="cb111-336"><a href="#cb111-336"></a><span class="fu">inspect</span>(groceries)</span>
<span id="cb111-337"><a href="#cb111-337"></a></span>
<span id="cb111-338"><a href="#cb111-338"></a><span class="in">```</span></span>
<span id="cb111-339"><a href="#cb111-339"></a></span>
<span id="cb111-340"><a href="#cb111-340"></a>We see that the comparison is to be made between two prices for the</span>
<span id="cb111-341"><a href="#cb111-341"></a>*same* product, and hence this is one more example of <span class="in">`paired data`</span>, as</span>
<span id="cb111-342"><a href="#cb111-342"></a>in Case Study #4. Let us plot the prices for the products:</span>
<span id="cb111-343"><a href="#cb111-343"></a></span>
<span id="cb111-346"><a href="#cb111-346"></a><span class="in">```{r}</span></span>
<span id="cb111-347"><a href="#cb111-347"></a><span class="fu">gf_col</span>(<span class="at">data =</span> groceries,</span>
<span id="cb111-348"><a href="#cb111-348"></a>       Target <span class="sc">~</span> Product,</span>
<span id="cb111-349"><a href="#cb111-349"></a>       <span class="at">fill =</span> <span class="st">"#0073C299"</span>,</span>
<span id="cb111-350"><a href="#cb111-350"></a>       <span class="at">width =</span> <span class="fl">0.5</span> ) <span class="sc">%&gt;%</span> </span>
<span id="cb111-351"><a href="#cb111-351"></a>  <span class="fu">gf_col</span>(<span class="at">data =</span> groceries,</span>
<span id="cb111-352"><a href="#cb111-352"></a>         <span class="sc">-</span>Walmart <span class="sc">~</span> Product,</span>
<span id="cb111-353"><a href="#cb111-353"></a>         <span class="at">fill =</span> <span class="st">"#EFC00099"</span>,</span>
<span id="cb111-354"><a href="#cb111-354"></a>         <span class="at">ylab =</span> <span class="st">"Prices"</span>,</span>
<span id="cb111-355"><a href="#cb111-355"></a>         <span class="at">width =</span> <span class="fl">0.5</span></span>
<span id="cb111-356"><a href="#cb111-356"></a>       ) <span class="sc">%&gt;%</span> </span>
<span id="cb111-357"><a href="#cb111-357"></a>  <span class="fu">gf_col</span>(<span class="at">data =</span> groceries <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Product <span class="sc">==</span> <span class="st">"Quaker Oats Life Cereal Original"</span>), </span>
<span id="cb111-358"><a href="#cb111-358"></a>         <span class="sc">-</span>Walmart <span class="sc">~</span> Product,</span>
<span id="cb111-359"><a href="#cb111-359"></a>         <span class="at">fill =</span> <span class="st">"red"</span>, </span>
<span id="cb111-360"><a href="#cb111-360"></a>         <span class="at">width =</span> <span class="fl">0.5</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb111-361"><a href="#cb111-361"></a>  <span class="fu">gf_theme</span>(<span class="fu">theme_classic</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb111-362"><a href="#cb111-362"></a>  <span class="fu">gf_theme</span>(ggplot2<span class="sc">::</span><span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(</span>
<span id="cb111-363"><a href="#cb111-363"></a>    <span class="at">size =</span> <span class="dv">8</span>,</span>
<span id="cb111-364"><a href="#cb111-364"></a>    <span class="at">face =</span> <span class="st">"bold"</span>,</span>
<span id="cb111-365"><a href="#cb111-365"></a>    <span class="at">vjust =</span> <span class="dv">0</span>,</span>
<span id="cb111-366"><a href="#cb111-366"></a>    <span class="at">hjust =</span> <span class="dv">1</span></span>
<span id="cb111-367"><a href="#cb111-367"></a>  ))) <span class="sc">%&gt;%</span> <span class="fu">gf_theme</span>(ggplot2<span class="sc">::</span><span class="fu">coord_flip</span>())</span>
<span id="cb111-368"><a href="#cb111-368"></a></span>
<span id="cb111-369"><a href="#cb111-369"></a><span class="in">```</span></span>
<span id="cb111-370"><a href="#cb111-370"></a></span>
<span id="cb111-371"><a href="#cb111-371"></a>We see that the price difference between Walmart and Target prices is</span>
<span id="cb111-372"><a href="#cb111-372"></a>highest for the <span class="in">`Product`</span> named <span class="in">`Quaker Oats Life Cereal Original`</span>. Let</span>
<span id="cb111-373"><a href="#cb111-373"></a>us check the mean difference in prices:</span>
<span id="cb111-374"><a href="#cb111-374"></a></span>
<span id="cb111-377"><a href="#cb111-377"></a><span class="in">```{r}</span></span>
<span id="cb111-378"><a href="#cb111-378"></a><span class="fu">diffmean</span>(<span class="at">data =</span> groceries, Walmart <span class="sc">~</span> Target, <span class="at">only.2 =</span> <span class="cn">FALSE</span>)</span>
<span id="cb111-379"><a href="#cb111-379"></a>obs_diff_price <span class="ot">=</span> <span class="fu">mean</span>( <span class="sc">~</span> Walmart <span class="sc">-</span> Target, <span class="at">data =</span> groceries)</span>
<span id="cb111-380"><a href="#cb111-380"></a>obs_diff_price</span>
<span id="cb111-381"><a href="#cb111-381"></a></span>
<span id="cb111-382"><a href="#cb111-382"></a><span class="in">```</span></span>
<span id="cb111-383"><a href="#cb111-383"></a></span>
<span id="cb111-384"><a href="#cb111-384"></a>Let us perform the pair-wise permutation test on prices, by shuffling</span>
<span id="cb111-385"><a href="#cb111-385"></a>the two store names:</span>
<span id="cb111-386"><a href="#cb111-386"></a></span>
<span id="cb111-389"><a href="#cb111-389"></a><span class="in">```{r}</span></span>
<span id="cb111-390"><a href="#cb111-390"></a>polarity <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="dv">1</span>, <span class="dv">15</span>), <span class="fu">rep</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">15</span>))</span>
<span id="cb111-391"><a href="#cb111-391"></a>polarity</span>
<span id="cb111-392"><a href="#cb111-392"></a>null_dist_price <span class="ot">&lt;-</span> <span class="fu">do</span>(<span class="dv">100000</span>) <span class="sc">*</span> <span class="fu">mean</span>(<span class="at">data =</span> groceries, </span>
<span id="cb111-393"><a href="#cb111-393"></a>                                    <span class="sc">~</span>(Walmart<span class="sc">-</span>Target) <span class="sc">*</span> <span class="fu">resample</span>(polarity,</span>
<span id="cb111-394"><a href="#cb111-394"></a>                                                    <span class="at">replace =</span> <span class="cn">TRUE</span>))</span>
<span id="cb111-395"><a href="#cb111-395"></a>null_dist_price <span class="sc">%&gt;%</span> <span class="fu">head</span>()</span>
<span id="cb111-396"><a href="#cb111-396"></a><span class="fu">gf_histogram</span>(<span class="at">data =</span> null_dist_price, <span class="sc">~</span>mean) <span class="sc">%&gt;%</span> </span>
<span id="cb111-397"><a href="#cb111-397"></a>  <span class="fu">gf_vline</span>(<span class="at">xintercept =</span> obs_diff_price, <span class="at">colour =</span> <span class="st">"red"</span>)</span>
<span id="cb111-398"><a href="#cb111-398"></a></span>
<span id="cb111-399"><a href="#cb111-399"></a><span class="dv">2</span><span class="sc">*</span>(<span class="fu">sum</span>(null_dist_price <span class="sc">&gt;=</span> obs_diff_price <span class="sc">+</span> <span class="dv">1</span>)<span class="sc">/</span>(<span class="dv">100000</span><span class="sc">+</span><span class="dv">1</span>)) <span class="co">#P-value</span></span>
<span id="cb111-400"><a href="#cb111-400"></a></span>
<span id="cb111-401"><a href="#cb111-401"></a><span class="in">```</span></span>
<span id="cb111-402"><a href="#cb111-402"></a></span>
<span id="cb111-403"><a href="#cb111-403"></a>Does not seem to be aby significant difference in prices...</span>
<span id="cb111-404"><a href="#cb111-404"></a></span>
<span id="cb111-405"><a href="#cb111-405"></a>Suppose we knock off the Quaker Cereal data item...</span>
<span id="cb111-406"><a href="#cb111-406"></a></span>
<span id="cb111-409"><a href="#cb111-409"></a><span class="in">```{r}</span></span>
<span id="cb111-410"><a href="#cb111-410"></a><span class="fu">which</span>(groceries<span class="sc">$</span>Product <span class="sc">==</span> <span class="st">"Quaker Oats Life Cereal Original"</span>)</span>
<span id="cb111-411"><a href="#cb111-411"></a>groceries_less <span class="ot">&lt;-</span> groceries[<span class="sc">-</span><span class="dv">2</span>,]</span>
<span id="cb111-412"><a href="#cb111-412"></a>groceries_less</span>
<span id="cb111-413"><a href="#cb111-413"></a></span>
<span id="cb111-414"><a href="#cb111-414"></a></span>
<span id="cb111-415"><a href="#cb111-415"></a>obs_diff_price_less <span class="ot">=</span> <span class="fu">mean</span>( <span class="sc">~</span> Walmart <span class="sc">-</span> Target, <span class="at">data =</span> groceries_less)</span>
<span id="cb111-416"><a href="#cb111-416"></a>obs_diff_price_less</span>
<span id="cb111-417"><a href="#cb111-417"></a>polarity_less <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="dv">1</span>, <span class="dv">15</span>), <span class="fu">rep</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">14</span>)) <span class="co"># Due to resampling this small bias makes no difference</span></span>
<span id="cb111-418"><a href="#cb111-418"></a>null_dist_price_less <span class="ot">&lt;-</span> <span class="fu">do</span>(<span class="dv">100000</span>) <span class="sc">*</span> <span class="fu">mean</span>(<span class="at">data =</span> groceries_less, </span>
<span id="cb111-419"><a href="#cb111-419"></a>                                    <span class="sc">~</span>(Walmart<span class="sc">-</span>Target) <span class="sc">*</span> <span class="fu">resample</span>(polarity_less,</span>
<span id="cb111-420"><a href="#cb111-420"></a>                                                    <span class="at">replace =</span> <span class="cn">TRUE</span>))</span>
<span id="cb111-421"><a href="#cb111-421"></a>null_dist_price_less <span class="sc">%&gt;%</span> <span class="fu">head</span>()</span>
<span id="cb111-422"><a href="#cb111-422"></a><span class="fu">gf_histogram</span>(<span class="at">data =</span> null_dist_price_less, <span class="sc">~</span>mean) <span class="sc">%&gt;%</span> </span>
<span id="cb111-423"><a href="#cb111-423"></a>  <span class="fu">gf_vline</span>(<span class="at">xintercept =</span> obs_diff_price_less, <span class="at">colour =</span> <span class="st">"red"</span>)</span>
<span id="cb111-424"><a href="#cb111-424"></a></span>
<span id="cb111-425"><a href="#cb111-425"></a><span class="dv">1</span><span class="sc">-</span> <span class="fu">mean</span>(null_dist_price_less <span class="sc">&gt;=</span> obs_diff_price_less) <span class="co">#P-value</span></span>
<span id="cb111-426"><a href="#cb111-426"></a></span>
<span id="cb111-427"><a href="#cb111-427"></a><span class="in">```</span></span>
<span id="cb111-428"><a href="#cb111-428"></a></span>
<span id="cb111-429"><a href="#cb111-429"></a><span class="fu">### Case Study 7: Proportions between Categorical Variables</span></span>
<span id="cb111-430"><a href="#cb111-430"></a></span>
<span id="cb111-431"><a href="#cb111-431"></a>Let us try a dataset with Qualitative / Categorical data. This is a</span>
<span id="cb111-432"><a href="#cb111-432"></a>General Social Survey dataset, and we have people with different levels</span>
<span id="cb111-433"><a href="#cb111-433"></a>of <span class="in">`Education`</span> stating their opinion on the <span class="in">`Death Penalty`</span>. We want to</span>
<span id="cb111-434"><a href="#cb111-434"></a>know if these two Categorical variables have a correlation, i.e. can the</span>
<span id="cb111-435"><a href="#cb111-435"></a>opinions in favour of the Death Penalty be explained by the Education</span>
<span id="cb111-436"><a href="#cb111-436"></a>level?</span>
<span id="cb111-437"><a href="#cb111-437"></a></span>
<span id="cb111-438"><a href="#cb111-438"></a>Since data is Categorical, we need to take <span class="in">`counts`</span> in a table, and then</span>
<span id="cb111-439"><a href="#cb111-439"></a>implement a <span class="in">`chi-square test`</span>. In the test, we will permute the</span>
<span id="cb111-440"><a href="#cb111-440"></a><span class="in">`Education`</span> variable to see if we can see how significant its *effect</span>
<span id="cb111-441"><a href="#cb111-441"></a>size* is.</span>
<span id="cb111-442"><a href="#cb111-442"></a></span>
<span id="cb111-445"><a href="#cb111-445"></a><span class="in">```{r}</span></span>
<span id="cb111-446"><a href="#cb111-446"></a>GSS2002 <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"../../../../../materials/data/resampling/GSS2002.csv"</span>)</span>
<span id="cb111-447"><a href="#cb111-447"></a><span class="fu">inspect</span>(GSS2002)</span>
<span id="cb111-448"><a href="#cb111-448"></a></span>
<span id="cb111-449"><a href="#cb111-449"></a><span class="in">```</span></span>
<span id="cb111-450"><a href="#cb111-450"></a></span>
<span id="cb111-451"><a href="#cb111-451"></a>Note how *all* variables are Categorical !! <span class="in">`Education`</span> has five</span>
<span id="cb111-452"><a href="#cb111-452"></a><span class="in">`levels`</span>:</span>
<span id="cb111-453"><a href="#cb111-453"></a></span>
<span id="cb111-456"><a href="#cb111-456"></a><span class="in">```{r}</span></span>
<span id="cb111-457"><a href="#cb111-457"></a>GSS2002 <span class="sc">%&gt;%</span> <span class="fu">count</span>(Education)</span>
<span id="cb111-458"><a href="#cb111-458"></a>GSS2002 <span class="sc">%&gt;%</span> <span class="fu">count</span>(DeathPenalty)</span>
<span id="cb111-459"><a href="#cb111-459"></a></span>
<span id="cb111-460"><a href="#cb111-460"></a><span class="in">```</span></span>
<span id="cb111-461"><a href="#cb111-461"></a></span>
<span id="cb111-462"><a href="#cb111-462"></a>Let us drop NA entries in Education and Death Penalty. And set up a</span>
<span id="cb111-463"><a href="#cb111-463"></a>table for the chi-square test.</span>
<span id="cb111-464"><a href="#cb111-464"></a></span>
<span id="cb111-465"><a href="#cb111-465"></a><span class="in">```{r,warning=FALSE,message=FALSE}</span></span>
<span id="cb111-466"><a href="#cb111-466"></a></span>
<span id="cb111-467"><a href="#cb111-467"></a>gss2002 <span class="ot">&lt;-</span> GSS2002 <span class="sc">%&gt;%</span> </span>
<span id="cb111-468"><a href="#cb111-468"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(Education, DeathPenalty) <span class="sc">%&gt;%</span> </span>
<span id="cb111-469"><a href="#cb111-469"></a>  tidyr<span class="sc">::</span><span class="fu">drop_na</span>(., <span class="fu">c</span>(Education, DeathPenalty))</span>
<span id="cb111-470"><a href="#cb111-470"></a><span class="fu">dim</span>(gss2002)</span>
<span id="cb111-471"><a href="#cb111-471"></a></span>
<span id="cb111-472"><a href="#cb111-472"></a>gss_summary <span class="ot">&lt;-</span> gss2002 <span class="sc">%&gt;%</span></span>
<span id="cb111-473"><a href="#cb111-473"></a>  <span class="fu">mutate</span>(</span>
<span id="cb111-474"><a href="#cb111-474"></a>    <span class="at">Education =</span> <span class="fu">factor</span>(</span>
<span id="cb111-475"><a href="#cb111-475"></a>      Education,</span>
<span id="cb111-476"><a href="#cb111-476"></a>      <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Bachelors"</span>, <span class="st">"Graduate"</span>, <span class="st">"Jr Col"</span>, <span class="st">"HS"</span>, <span class="st">"Left HS"</span>),</span>
<span id="cb111-477"><a href="#cb111-477"></a>      <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Bachelors"</span>, <span class="st">"Graduate"</span>, <span class="st">"Jr Col"</span>, <span class="st">"HS"</span>, <span class="st">"Left HS"</span>)</span>
<span id="cb111-478"><a href="#cb111-478"></a>    ),</span>
<span id="cb111-479"><a href="#cb111-479"></a>    <span class="at">DeathPenalty =</span> <span class="fu">as.factor</span>(DeathPenalty)</span>
<span id="cb111-480"><a href="#cb111-480"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb111-481"><a href="#cb111-481"></a>  <span class="fu">group_by</span>(Education, DeathPenalty) <span class="sc">%&gt;%</span></span>
<span id="cb111-482"><a href="#cb111-482"></a>  <span class="fu">summarise</span>(<span class="at">count =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span> <span class="co"># This is good for a chisq test</span></span>
<span id="cb111-483"><a href="#cb111-483"></a>  </span>
<span id="cb111-484"><a href="#cb111-484"></a>  <span class="co"># Add two more columns to faciltate mosaic/Marrimekko Plot</span></span>
<span id="cb111-485"><a href="#cb111-485"></a>  <span class="co"># </span></span>
<span id="cb111-486"><a href="#cb111-486"></a>  <span class="fu">mutate</span>(<span class="at">edu_count =</span> <span class="fu">sum</span>(count), </span>
<span id="cb111-487"><a href="#cb111-487"></a>         <span class="at">edu_prop =</span> count <span class="sc">/</span> <span class="fu">sum</span>(count)) <span class="sc">%&gt;%</span></span>
<span id="cb111-488"><a href="#cb111-488"></a>  <span class="fu">ungroup</span>() </span>
<span id="cb111-489"><a href="#cb111-489"></a></span>
<span id="cb111-490"><a href="#cb111-490"></a>gss_summary</span>
<span id="cb111-491"><a href="#cb111-491"></a></span>
<span id="cb111-492"><a href="#cb111-492"></a><span class="co"># We can plot a heatmap-like `mosaic chart` for this table, using `ggplot`:</span></span>
<span id="cb111-493"><a href="#cb111-493"></a><span class="co"># https://stackoverflow.com/questions/19233365/how-to-create-a-marimekko-mosaic-plot-in-ggplot2</span></span>
<span id="cb111-494"><a href="#cb111-494"></a></span>
<span id="cb111-495"><a href="#cb111-495"></a><span class="fu">ggplot</span>(<span class="at">data =</span> gss_summary, <span class="fu">aes</span>( <span class="at">x =</span> Education, <span class="at">y =</span> edu_prop)) <span class="sc">+</span></span>
<span id="cb111-496"><a href="#cb111-496"></a>  <span class="fu">geom_bar</span>(<span class="fu">aes</span>(<span class="at">width =</span> edu_count, <span class="at">fill =</span> DeathPenalty), <span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">position =</span> <span class="st">"fill"</span>, <span class="at">colour =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb111-497"><a href="#cb111-497"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> scales<span class="sc">::</span><span class="fu">percent</span>(edu_prop)), <span class="at">position =</span> <span class="fu">position_stack</span>(<span class="at">vjust =</span> <span class="fl">0.5</span>)) <span class="sc">+</span></span>
<span id="cb111-498"><a href="#cb111-498"></a></span>
<span id="cb111-499"><a href="#cb111-499"></a></span>
<span id="cb111-500"><a href="#cb111-500"></a><span class="co"># if labels are desired</span></span>
<span id="cb111-501"><a href="#cb111-501"></a> <span class="fu">facet_grid</span>(<span class="sc">~</span> Education, <span class="at">scales =</span> <span class="st">"free_x"</span>, <span class="at">space =</span> <span class="st">"free_x"</span>) <span class="sc">+</span> </span>
<span id="cb111-502"><a href="#cb111-502"></a>  <span class="fu">theme</span>(<span class="fu">scale_fill_brewer</span>(<span class="at">palette =</span> <span class="st">"RdYlGn"</span>)) <span class="sc">+</span> </span>
<span id="cb111-503"><a href="#cb111-503"></a>  <span class="co"># theme(panel.spacing.x = unit(0, "npc")) + # if no spacing preferred between bars</span></span>
<span id="cb111-504"><a href="#cb111-504"></a>  <span class="fu">theme_void</span>() </span>
<span id="cb111-505"><a href="#cb111-505"></a></span>
<span id="cb111-506"><a href="#cb111-506"></a><span class="in">```</span></span>
<span id="cb111-507"><a href="#cb111-507"></a></span>
<span id="cb111-508"><a href="#cb111-508"></a>Let us now perform the base <span class="in">`chisq test`</span>: We need a <span class="in">`table`</span> and then the</span>
<span id="cb111-509"><a href="#cb111-509"></a><span class="in">`chisq`</span> test:</span>
<span id="cb111-510"><a href="#cb111-510"></a></span>
<span id="cb111-513"><a href="#cb111-513"></a><span class="in">```{r}</span></span>
<span id="cb111-514"><a href="#cb111-514"></a>gss_table <span class="ot">&lt;-</span> <span class="fu">tally</span>(DeathPenalty <span class="sc">~</span> Education, <span class="at">data =</span> gss2002)</span>
<span id="cb111-515"><a href="#cb111-515"></a>gss_table</span>
<span id="cb111-516"><a href="#cb111-516"></a></span>
<span id="cb111-517"><a href="#cb111-517"></a><span class="co"># Get the observed chi-square statistic</span></span>
<span id="cb111-518"><a href="#cb111-518"></a>observedChi2 <span class="ot">&lt;-</span> mosaic<span class="sc">::</span><span class="fu">chisq</span>(<span class="fu">tally</span>(DeathPenalty <span class="sc">~</span> Education, <span class="at">data =</span> gss2002))</span>
<span id="cb111-519"><a href="#cb111-519"></a>observedChi2</span>
<span id="cb111-520"><a href="#cb111-520"></a></span>
<span id="cb111-521"><a href="#cb111-521"></a><span class="co"># Actual chi-square test</span></span>
<span id="cb111-522"><a href="#cb111-522"></a>stats<span class="sc">::</span><span class="fu">chisq.test</span>(<span class="fu">tally</span>(DeathPenalty <span class="sc">~</span> Education, <span class="at">data =</span> gss2002))</span>
<span id="cb111-523"><a href="#cb111-523"></a></span>
<span id="cb111-524"><a href="#cb111-524"></a><span class="in">```</span></span>
<span id="cb111-525"><a href="#cb111-525"></a></span>
<span id="cb111-526"><a href="#cb111-526"></a>We should now repeat the test with permutations on <span class="in">`Education`</span>:</span>
<span id="cb111-527"><a href="#cb111-527"></a></span>
<span id="cb111-530"><a href="#cb111-530"></a><span class="in">```{r}</span></span>
<span id="cb111-531"><a href="#cb111-531"></a>null_chisq <span class="ot">&lt;-</span> <span class="fu">do</span>(<span class="dv">10000</span>) <span class="sc">*</span> <span class="fu">chisq.test</span>(<span class="fu">tally</span>(DeathPenalty <span class="sc">~</span> <span class="fu">shuffle</span>(Education), <span class="at">data =</span> gss2002))</span>
<span id="cb111-532"><a href="#cb111-532"></a></span>
<span id="cb111-533"><a href="#cb111-533"></a><span class="fu">head</span>(null_chisq)</span>
<span id="cb111-534"><a href="#cb111-534"></a></span>
<span id="cb111-535"><a href="#cb111-535"></a><span class="fu">gf_histogram</span>( <span class="sc">~</span> X.squared, <span class="at">data =</span> null_chisq) <span class="sc">%&gt;%</span> </span>
<span id="cb111-536"><a href="#cb111-536"></a>  <span class="fu">gf_vline</span>(<span class="at">xintercept =</span> observedChi2, <span class="at">color =</span> <span class="st">"red"</span>)</span>
<span id="cb111-537"><a href="#cb111-537"></a></span>
<span id="cb111-538"><a href="#cb111-538"></a><span class="fu">gf_histogram</span>( <span class="sc">~</span> p.value, <span class="at">data =</span> null_chisq, <span class="at">binwidth =</span> <span class="fl">0.1</span>, <span class="at">center =</span> <span class="fl">0.05</span>)</span>
<span id="cb111-539"><a href="#cb111-539"></a><span class="in">```</span></span>
<span id="cb111-540"><a href="#cb111-540"></a></span>
<span id="cb111-541"><a href="#cb111-541"></a>So we would conclude that <span class="in">`Education`</span> has a significant effect on</span>
<span id="cb111-542"><a href="#cb111-542"></a><span class="in">`DeathPenalty`</span> opinion!</span>
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->



<script src="../../../../../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>