---
title: "Working With Shape: Fractals"
subtitle: ""
subject: "Shapes and Code"
abstract: "A Geometric Jewellery Store"
date: 02/May/2024
date-modified: "`r Sys.Date()`"
order: 96
categories:
- Iterated Functions
- Fractals
- Mandelbrot
- Julia
image: ""
lightbox: true
---

:::: {.pa4}
::: {.athelas .ml0 .mt0 .pl4 .black-90 .bl .bw2 .b--blue}
"]{.f5 .f4-m .f3-l .lh-copy .measure .mt0}


[ --- ]{.f6 .ttu .tracked .fs-normal}
:::
::::


```{r, echo=FALSE,message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(blogdown)
library(emoji)
#devtools::install_github("mccarthy-m-g/embedr")
library(embedr) # Embed multimedia in HTML files
```

#### A Geometric Jewellery Store

![Photo by <a href="https://unsplash.com/@kolyakorzh?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Mykola/Kolya Korzh</a> on <a href="https://unsplash.com/photos/brown-wooden-bird-house-ornament-HFogW6fHv4E?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>
  ](featured.jpg)


## {{< iconify icons8 idea >}} Inspiration

## An Introduction to Fractals

Let us listen to the late great Benoit Mandelbrot, on the **Art of Roughness**.

{{< video https://youtu.be/wQTnVEXAtBY >}}

### Complex Planes: What am $i$?


Dude, what's the square root of -1?? `r emoji::emoji("scream_cat")` `r emoji::emoji("scream_cat")` `r emoji::emoji("scream_cat")`!! And, what can you do repeatedly to arrive at $[-1, 0]$?

Let us head off to <https://mathigon.org/course/fractals/mandelbrot> and play with some iterated functions in the Complex Plane. This will lead us into an intuitive understanding of Julia and Mandelbrot Fractals. 

{{< video https://youtu.be/DznD05F1DLI >}}


{{< video https://youtu.be/t75gXyWJNpA >}}

### Julia, and Julia, and still more Julia....

{{< video https://youtu.be/2AZYZ-L8m9Q >}}

### Jewellery Shopping with Mandelbrot

Ever gone shopping for jewellery? How is the place organized? That is a good metaphor for how Mandelbrot Set is generated!!

{{< video https://youtu.be/8ma6cV6fw24 >}}

<iframe width="100%" height="640" frameborder="0"
  src="https://observablehq.com/embed/@mcmcclur/julia-sets-and-the-mandelbrot-set?cells=topmatter%2Cwidget%2Cjulia_svg"></iframe>
  
### Using XaOS

Let us use the XaOS software to make different kinds of fractals. A sample screen to explore the Mandelbrot fractal is here:

<iframe width="100%" height="1048" frameborder="0"
src="https://xaos-project.github.io/XaoSjs/">
</iframe>



## {{< iconify mingcute thought-line >}} <u>[Wait, But Why?](https://waitbutwhy.com)</u>
To be Written Up. 


## {{< iconify ooui references-ltr >}} References

1. Batty, M. and Longley, P. A. (1994) “Fractal Cities: A Geometry of Form and Function”, London: Academic Press, 1994. 

1. Wang H, Luo S, Luo T. Fractal characteristics of urban surface transit and road networks: Case study of Strasbourg, France. Advances in Mechanical Engineering. 2017;9(2). <doi:10.1177/1687814017692289>

1. <https://www.reddit.com/r/CitiesSkylines/comments/9r0y4e/grid_idea_im_working_on_fractal_squares/>

1. Menger Sponge: <https://blogs.scientificamerican.com/roots-of-unity/a-few-of-my-favorite-spaces-the-menger-sponge/>

1. <http://fractalfoundation.org/resources/fractal-software/.

