---
title: "Maps"
---

```{r}
library(tidyverse)
library(sf)
library(tmap)
library(osmdata)
library(ggformula)

```

## Defining a bounding box

```{r}
bbox_2 <- osmdata::getbb("Jayanagar, Bangalore, India")
bbox_2
```


```{r}
locations <- 
  osmdata::opq(bbox = bbox_2) %>% 
  osmdata::add_osm_feature(key = "amenity", 
                           value = c("restaurant", "atm", "college")) %>% 
  osmdata_sf() %>%  # Convert to Simple Features format
  purrr::pluck("osm_points") # Pull out the data frame of interest
###
dat_buildings <-
  osmdata::opq(bbox = bbox_2) %>% 
  osmdata::add_osm_feature(key = "building") %>% 
  osmdata_sf() %>% 
  purrr::pluck("osm_polygons")

```


## Inspecting OSM data

```{r}
str(locations)
str(dat_buildings)

```

## Plotting Base Maps with ggplot/ggformula

```{r}
ggplot() +
  geom_sf(data = locations, fill = "gold", color = "grey", linewidth = 0.025) +
  geom_sf(data = dat_buildings, fill = "purple") +
  coord_sf()

gf_sf( geometry = ~ geometry, data = locations) %>% 
  gf_sf(geometry = ~ geometry,dat = dat_buildings)

```

## Plotting with tmap
```{r}
tm_shape(locations) +
  tm_dots(size = 0.5) +
  tm_shape(dat_buildings) + 
  tm_polygons() +
  tm_compass(position = c("right", "top"))

```



## Adding User Data to a Base Map
