---
title: "\U0001F355 Parts of a Whole"
subtitle: "Parts of a Whole"
author: "Arvind Venkatadri"
date: 25/Nov/2022
date-modified: "`r Sys.Date()`"
order: 50
abstract: "Slices, Portions, Counts, and Aggregates of Data"
number-sections: true
code-fold: true
code-summary: "Show the Code"
code-copy: true
code-tools: true
code-line-numbers: true
df-print: paged
cap-location: margin
execute: 
  freeze: auto
tags:
  - Pie Charts/Fan Charts/Donut Charts
  - Mosaic Charts
  - Venn Diagrams
  - Grouped/Stacked/Circular Bar Charts
  - Tree Maps/Dendrograms
  - Parliament/Waffle Charts
  - Circular Packing
---

{{< fa folder-open >}} Slides and Tutorials

<a href="./files/parts.qmd">
<i class="fa-solid fa-file-powerpoint fa-2x"></i></a> .nbsp;.nbsp;

<a href="./files/parts.ows">
<iconify-icon icon="icon-park-solid:orange"></iconify-icon></a>
.nbsp;.nbsp;

<a href="./files/parts.rda"> <i class="fa-solid fa-person-rays"></i></a>
.nbsp;.nbsp;

<a href="./data/data.zip"> <i class="fa-solid fa-database"></i></a>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(blogdown)
library(plotrix) # Fan, Parliament
```

## An Example

What influences love at first sight? (Or, at least, love in the first
four minutes?)

This dataset was compiled by Columbia Business School professors Ray
Fisman and Sheena Iyengar for their paper [**Gender Differences in Mate
Selection: Evidence From a Speed
DatingExperiment**](https://www0.gsb.columbia.edu/mygsb/faculty/research/pubfiles/866/racialPreferences.pdf).

Data was gathered from participants in experimental speed dating events
from 2002-2004. During the events, the attendees would have a four
minute "first date" with every other participant of the opposite sex. At
the end of their four minutes, participants were asked if they would
like to see their date again. They were also asked to rate their date on
six attributes: Attractiveness, Sincerity, Intelligence, Fun, Ambition,
and Shared Interests.

## What is the Story here?

1.  Do people prefer to date someone from their own *race*?
2.  Is that different for men and women?
3.  Does physical attractiveness help to overcome age differences?

## A Workflow in Orange

## A Workflow in Radiant

## A Workflow in R
