---
title: "Embedding p5.js Sketches in Quarto"
---

## Introduction

Trying embed `p5.js` sketches in Quarto.

### Setup Scripts
<script src="//toolness.github.io/p5.js-widget/p5-widget.js"></script>


## Sketches to Embed

### Okati

<script type="text/p5" data-autoplay>
function setup() {
  createCanvas(100, 100);
}

function draw() {
  background(255, 0, 200);
}
</script>


### Two-kati

<script type="text/p5" data-autoplay> 
let gridSize = 8;
let cellSize;
let dots = [];

function setup() {
  createCanvas(400, 400);
  cellSize = width / gridSize;
  background(255);
  frameRate(1);
  generateDots();
}

function draw() {
  background(255);
  drawDots();
  drawLines();
}

function generateDots() {
  dots = [];
  for (let i = 0; i < gridSize; i++) {
    for (let j = 0; j < gridSize; j++) {
      if ((i + j) % 2 === 0) {
        dots.push(new Dot(i, j));
      }
    }
  }
}

function drawDots() {
  for (let dot of dots) {
    dot.display();
  }
}

function drawLines() {
  for (let i = 0; i < dots.length; i++) {
    let dot = dots[i];
    if (i < dots.length - 1 && dot.isConnectedTo(dots[i + 1])) {
      line(dot.x * cellSize + cellSize / 2, dot.y * cellSize + cellSize / 2, dots[i + 1].x * cellSize + cellSize / 2, dots[i + 1].y * cellSize + cellSize / 2);
    }
    if (i < dots.length - gridSize && dot.isConnectedTo(dots[i + gridSize])) {
      line(dot.x * cellSize + cellSize / 2, dot.y * cellSize + cellSize / 2, dots[i + gridSize].x * cellSize + cellSize / 2, dots[i + gridSize].y * cellSize + cellSize / 2);
    }
  }
}

class Dot {
  constructor(x, y) {
    this.x = x;
    this.y = y;
  }

  display() {
    fill(0);
    noStroke();
    ellipse(this.x * cellSize + cellSize / 2, this.y * cellSize + cellSize / 2, cellSize / 2);
  }

  isConnectedTo(otherDot) {
    return (Math.abs(this.x - otherDot.x) === 1 && this.y === otherDot.y) || (Math.abs(this.y - otherDot.y) === 1 && this.x === otherDot.x);
  }
}
</script>


### vanilla kati

<iframe 
src="https://editor.p5js.org/arvindv/full/VpoBEeVZJ" width="800px" height="600px">
</iframe>







## References

1. Embedding `p5.js` sketches. <https://toolness.github.io/p5.js-widget/#src>
